// @generated by OntOS Codesmith Business Permission v1
// @ontos-permission-owner commerce.customer-context
// @ontos-permission-code counterparty.profile.read
import { defineBusinessPermission } from '@app/core-runtime';

export const counterpartyProfileReadPermission = defineBusinessPermission({
  allowedScopeKinds: ['counterparty', 'counterparty_storefront'],
  auditSensitivity: 'sensitive',
  authorityGroups: ['COUNTERPARTY_BUYER'],
  customerDelegable: true,
  internalGrantable: true,
  key: 'counterparty.profile.read',
  meaning: 'Read the permitted current Commerce Counterparty Purchasing Profile view.',
  owningCapability: 'commerce.customer-context.profile',
  protectedEntrypoints: [
    'commerce.customer-context.api.customer-profile-read',
    'commerce.customer-context.api.purchase-currency-resolution',
  ],
  schemaVersion: '1',
});
