// @generated by OntOS Codesmith Business Permission v1
// @ontos-permission-owner commerce.customer-context
// @ontos-permission-code counterparty.address_book.use
import { defineBusinessPermission } from '@app/core-runtime';

export const counterpartyAddressBookUsePermission = defineBusinessPermission({
  allowedScopeKinds: ['counterparty', 'counterparty_storefront'],
  auditSensitivity: 'standard',
  authorityGroups: ['COUNTERPARTY_BUYER'],
  customerDelegable: true,
  internalGrantable: true,
  key: 'counterparty.address_book.use',
  meaning: 'Use permitted Counterparty address-book candidates for a purchase.',
  owningCapability: 'commerce.customer-context.address-book',
  protectedEntrypoints: [
    'commerce.customer-context.api.saved-address-list',
    'commerce.customer-context.api.saved-address-detail',
    'commerce.customer-context.api.saved-address-defaults',
    'commerce.customer-context.api.delivery-destination-resolution',
    'commerce.customer-context.api.invoice-recipient-resolution',
  ],
  schemaVersion: '1',
});
