// @generated by OntOS Codesmith Action v1
// @ontos-action-owner privacy.core
// @ontos-action-slug record-notice-provision
/* eslint-disable effect-native/no-unbranded-identifier-schema -- Audit evidence preserves the owner-issued opaque Notice Provision identifier from the validated domain result. expires: 2027-03-31. */
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { DateTime, Effect, Schema } from 'effect';

import {
  RecordNoticeProvisionPayloadSchema,
  RecordNoticeProvisionResultSchema,
} from '../../shared/actions/record-notice-provision.ts';
import type { RecordNoticeProvisionPayload } from '../../shared/actions/record-notice-provision.ts';
import { materializePrivacyNoticeProvision } from '../../shared/domain/privacy-notice-provision.ts';
import { noticeProvisionRepositoryForScope } from '../persistence/notice-provision-postgres-repository.ts';
import { NoticeProvisionPersistenceError } from '../persistence/notice-provision-repository.ts';
import type { NoticeProvisionRepositoryService } from '../persistence/notice-provision-repository.ts';

class RecordNoticeProvisionError extends Schema.TaggedError<RecordNoticeProvisionError>()(
  'RecordNoticeProvisionError',
  {
    code: Schema.Literals(['privacy_notice_provision_invalid', 'privacy_notice_provision_scope_required']),
    reason: Schema.String,
  },
) {}

const domainEvents = {} as const;
const ErrorSchema = Schema.Union([RecordNoticeProvisionError, NoticeProvisionPersistenceError]);
const AuditEvidenceSchema = Schema.Struct({
  noticeVersionRef: Schema.String,
  outcome: Schema.String,
  providedLanguage: Schema.String,
  provisionId: Schema.String,
});
const MODULE_KEY = 'privacy.core' as const;
type Services = Pick<NoticeProvisionRepositoryService, 'record'>;

export const handleRecordNoticeProvision = Effect.fn('RecordNoticeProvisionAction.handle')(
  function* recordNoticeProvision(
    payload: RecordNoticeProvisionPayload,
    context: ActionHandlerContext<typeof domainEvents, Services>,
  ) {
    const { legalEntityId } = context.scope;
    if (legalEntityId === undefined) {
      return yield* new RecordNoticeProvisionError({
        code: 'privacy_notice_provision_scope_required',
        reason: 'Record Notice Provision requires a trusted Legal Entity scope',
      });
    }
    const { channelProof, ...draft } = payload;
    const provision = yield* materializePrivacyNoticeProvision(draft, {
      authoritativeProof: channelProof ?? null,
      recordedAt: DateTime.formatIso(yield* DateTime.now),
    }).pipe(
      Effect.mapError(
        ({ reason }) => new RecordNoticeProvisionError({ code: 'privacy_notice_provision_invalid', reason }),
      ),
    );
    const retained = yield* context.services.record(
      context.scope.tenantId,
      legalEntityId,
      context.actionInvocationId,
      provision,
    );
    yield* context.recordAuditEvidence({
      noticeVersionRef: retained.noticeVersionRef,
      outcome: retained.outcome,
      providedLanguage: retained.providedLanguage,
      provisionId: retained.provisionId,
    });
    return retained;
  },
);

export const recordNoticeProvisionAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'privacy.core.record-notice-provision.access.v1',
    },
    actionKey: 'privacy.core.record-notice-provision',
    auditEvidenceSchema: AuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: ErrorSchema,
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'privacy.core.record-notice-provision',
      moduleKey: MODULE_KEY,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'required',
    owningModuleKey: MODULE_KEY,
    payloadSchema: RecordNoticeProvisionPayloadSchema,
    policies: [],
    resultSchema: RecordNoticeProvisionResultSchema,
    schemaVersion: '1',
  },
  handleRecordNoticeProvision,
  (transaction, scope) =>
    noticeProvisionRepositoryForScope(transaction, scope).pipe(Effect.map(({ record }) => ({ record }))),
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
