// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.assortment
// @ontos-action-http-slug end-applicability-binding
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { HttpApi, HttpApiEndpoint, HttpApiGroup, Schema } from '@modern-js/bff-effect/effect-client';
import { HttpApiMiddleware } from 'effect/unstable/httpapi';
import {
  EndApplicabilityBindingPayloadSchema,
  EndApplicabilityBindingResultSchema,
} from '../actions/end-applicability-binding.ts';

export { EndApplicabilityBindingPayloadSchema } from '../actions/end-applicability-binding.ts';

const EndApplicabilityBindingActionHeadersSchema = Schema.Struct({
  'idempotency-key': Schema.optionalKey(Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(200))),
});

export const EndApplicabilityBindingActionInvalidProblemSchema = makeProblemDetailsSchema(
  'EndApplicabilityBindingActionInvalidProblem',
  400,
);
export const EndApplicabilityBindingActionAuthenticationProblemSchema = makeProblemDetailsSchema(
  'EndApplicabilityBindingActionAuthenticationProblem',
  401,
);
export const EndApplicabilityBindingActionForbiddenProblemSchema = makeProblemDetailsSchema(
  'EndApplicabilityBindingActionForbiddenProblem',
  403,
  {
    code: Schema.Literals([
      'action_permission_denied',
      'module_state_denied',
      'operation_context_denied',
      'operation_context_invalid',
    ]),
  },
);
export const EndApplicabilityBindingActionNotFoundProblemSchema = makeProblemDetailsSchema(
  'EndApplicabilityBindingActionNotFoundProblem',
  404,
  { code: Schema.Literals(['action_invocation_not_found', 'assortment_policy_not_found']) },
);
export const EndApplicabilityBindingActionConflictProblemSchema = makeProblemDetailsSchema(
  'EndApplicabilityBindingActionConflictProblem',
  409,
  {
    code: Schema.Literals([
      'action_request_hash_conflict',
      'action_invocation_state_invalid',
      'assortment_policy_conflict',
      'assortment_policy_lifecycle_conflict',
      'assortment_policy_stale_basis',
    ]),
  },
);
export const EndApplicabilityBindingActionIneligibleProblemSchema = makeProblemDetailsSchema(
  'EndApplicabilityBindingActionIneligibleProblem',
  422,
  { code: Schema.Literal('action_policy_denied') },
);
export const EndApplicabilityBindingActionPreconditionProblemSchema = makeProblemDetailsSchema(
  'EndApplicabilityBindingActionPreconditionProblem',
  428,
);
export const EndApplicabilityBindingActionUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'EndApplicabilityBindingActionUnavailableProblem',
  503,
  {
    code: Schema.Literals([
      'action_invocation_persistence_failed',
      'action_permission_check_failed',
      'action_policy_evaluation_failed',
      'action_transaction_failed',
      'module_state_check_unavailable',
      'operation_context_unavailable',
      'assortment_policy_persistence_unavailable',
    ]),
  },
);
export const EndApplicabilityBindingActionAlreadyCommittedProblemSchema = makeProblemDetailsSchema(
  'EndApplicabilityBindingActionAlreadyCommittedProblem',
  409,
  {
    code: Schema.Literal('action_already_committed'),
    invocationId: Schema.String,
    resolution: Schema.Literal('REFRESH_GOVERNED_READS'),
    retryCommand: Schema.Literal(false),
  },
);
export const EndApplicabilityBindingActionCommitIndeterminateProblemSchema = makeProblemDetailsSchema(
  'EndApplicabilityBindingActionCommitIndeterminateProblem',
  503,
  {
    invocationId: Schema.String,
    resolution: Schema.Literal('RESOLVE_COMMIT'),
    retryCommand: Schema.Literal(false),
  },
);
export const EndApplicabilityBindingActionInternalProblemSchema = makeProblemDetailsSchema(
  'EndApplicabilityBindingActionInternalProblem',
  500,
);

export type EndApplicabilityBindingActionProblem =
  | typeof EndApplicabilityBindingActionInvalidProblemSchema.Type
  | typeof EndApplicabilityBindingActionAuthenticationProblemSchema.Type
  | typeof EndApplicabilityBindingActionForbiddenProblemSchema.Type
  | typeof EndApplicabilityBindingActionNotFoundProblemSchema.Type
  | typeof EndApplicabilityBindingActionConflictProblemSchema.Type
  | typeof EndApplicabilityBindingActionIneligibleProblemSchema.Type
  | typeof EndApplicabilityBindingActionPreconditionProblemSchema.Type
  | typeof EndApplicabilityBindingActionUnavailableProblemSchema.Type
  | typeof EndApplicabilityBindingActionAlreadyCommittedProblemSchema.Type
  | typeof EndApplicabilityBindingActionCommitIndeterminateProblemSchema.Type
  | typeof EndApplicabilityBindingActionInternalProblemSchema.Type;

export class EndApplicabilityBindingActionSchemaErrorMiddleware extends HttpApiMiddleware.Service<EndApplicabilityBindingActionSchemaErrorMiddleware>()(
  'assortment/EndApplicabilityBindingActionSchemaErrorMiddleware',
  { error: EndApplicabilityBindingActionInvalidProblemSchema },
) {}

const actionErrors = [
  EndApplicabilityBindingActionInvalidProblemSchema,
  EndApplicabilityBindingActionAuthenticationProblemSchema,
  EndApplicabilityBindingActionForbiddenProblemSchema,
  EndApplicabilityBindingActionNotFoundProblemSchema,
  EndApplicabilityBindingActionConflictProblemSchema,
  EndApplicabilityBindingActionIneligibleProblemSchema,
  EndApplicabilityBindingActionPreconditionProblemSchema,
  EndApplicabilityBindingActionUnavailableProblemSchema,
  EndApplicabilityBindingActionAlreadyCommittedProblemSchema,
  EndApplicabilityBindingActionCommitIndeterminateProblemSchema,
  EndApplicabilityBindingActionInternalProblemSchema,
] as const;

export const EndApplicabilityBindingActionApi = HttpApi.make('EndApplicabilityBindingActionApi').add(
  HttpApiGroup.make('endApplicabilityBindingAction')
    .add(
      HttpApiEndpoint.post('execute', '/assortment/actions/end-applicability-binding', {
        error: actionErrors,
        headers: EndApplicabilityBindingActionHeadersSchema,
        payload: Schema.toEncoded(EndApplicabilityBindingPayloadSchema),
        success: EndApplicabilityBindingResultSchema,
      }),
    )
    .middleware(EndApplicabilityBindingActionSchemaErrorMiddleware),
);
