// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.customer-context
// @ontos-action-http-slug claim-portal-enrollment-transition
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  ClaimPortalEnrollmentTransitionActionApi,
  ClaimPortalEnrollmentTransitionPayloadSchema,
} from '../../shared/apis/claim-portal-enrollment-transition-action.ts';
import type { ClaimPortalEnrollmentTransitionPayload } from '../../shared/actions/claim-portal-enrollment-transition.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface ClaimPortalEnrollmentTransitionActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: ClaimPortalEnrollmentTransitionActionClientOptions,
];
type OperationInvocation = readonly [
  requestCorrelation: string,
  options: ClaimPortalEnrollmentTransitionActionClientOptions,
];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: ClaimPortalEnrollmentTransitionActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    {
      api: ClaimPortalEnrollmentTransitionActionApi,
      credential,
      defaultApiPrefix: '/commerce-customer-context-api',
      requestCorrelation,
    },
    options,
  );

export const executeClaimPortalEnrollmentTransitionWithAuthorization = (
  payload: ClaimPortalEnrollmentTransitionPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(ClaimPortalEnrollmentTransitionPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.claimPortalEnrollmentTransitionAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeClaimPortalEnrollmentTransition = (
  payload: ClaimPortalEnrollmentTransitionPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) =>
      executeClaimPortalEnrollmentTransitionWithAuthorization(payload, credential, requestCorrelation, options),
    options.gateway,
  );
