// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.customer-context
// @ontos-action-http-slug create-counterparty-purchasing-profile
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  CreateCounterpartyPurchasingProfileActionApi,
  CreateCounterpartyPurchasingProfilePayloadSchema,
} from '../../shared/apis/create-counterparty-purchasing-profile-action.ts';
import type { CreateCounterpartyPurchasingProfilePayload } from '../../shared/actions/create-counterparty-purchasing-profile.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface CreateCounterpartyPurchasingProfileActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: CreateCounterpartyPurchasingProfileActionClientOptions,
];
type OperationInvocation = readonly [
  requestCorrelation: string,
  options: CreateCounterpartyPurchasingProfileActionClientOptions,
];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: CreateCounterpartyPurchasingProfileActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    {
      api: CreateCounterpartyPurchasingProfileActionApi,
      credential,
      defaultApiPrefix: '/commerce-customer-context-api',
      requestCorrelation,
    },
    options,
  );

export const executeCreateCounterpartyPurchasingProfileWithAuthorization = (
  payload: CreateCounterpartyPurchasingProfilePayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(CreateCounterpartyPurchasingProfilePayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.createCounterpartyPurchasingProfileAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeCreateCounterpartyPurchasingProfile = (
  payload: CreateCounterpartyPurchasingProfilePayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) =>
      executeCreateCounterpartyPurchasingProfileWithAuthorization(
        payload,
        credential,
        requestCorrelation,
        options,
      ),
    options.gateway,
  );
