// @generated by OntOS Codesmith module-api v1
import { defineRead, defineReadResourcePermission, defineTenantModuleEntrypoint } from '@app/core-runtime';
import type { ReadHandlerContext } from '@app/core-runtime';
import { DateTime, Effect } from 'effect';
import { CustomerArchiveRequestSchema, CustomerArchiveResponseSchema } from '../../shared/apis/customer-archive.ts';
import type { CustomerArchiveRequest } from '../../shared/apis/customer-archive.ts';
import { composeCustomerArchive } from '../../shared/domain/history-composition.ts';
import type { CustomerHistoryPorts } from '../../shared/domain/history-ports.ts';
import { historyReadErrorMapper, loadCustomerHistoryReadServices } from './history-read-support.ts';
import { subjectHistoryTarget } from './history-read-authorization.ts';

const mapHistoryError = historyReadErrorMapper({
  denied: 'Customer Archive access is denied',
  notFound: 'The requested archived record is not available',
  unavailable: 'Customer Archive is temporarily unavailable',
});

const customerArchiveEntrypoint = defineTenantModuleEntrypoint({
  access: 'historical_read',
  authorization: { kind: 'authenticated_principal' },
  entrypointKey: 'commerce.customer-context.api.customer-archive',
  moduleKey: 'commerce.customer-context',
  role: 'api',
});

export const customerArchiveRead = defineRead(
  {
    accessKind: 'list',
    entrypoint: customerArchiveEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.customer-context.api.customer-archive.evidence.v1',
    },
    inputSchema: CustomerArchiveRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: 'commerce.customer-context',
    permissionTarget: 'business_permission',
    policies: [],
    readKey: 'commerce.customer-context.api.customer-archive',
    resourcePermission: defineReadResourcePermission<CustomerArchiveRequest>(({ subject }) => ({
      permission: 'read',
      resource: subject.profileRef,
    })),
    resultSchema: CustomerArchiveResponseSchema,
    schemaVersion: '1',
  },
  (input, context: ReadHandlerContext<{ readonly ports: CustomerHistoryPorts }>) =>
    DateTime.now.pipe(
      Effect.map(DateTime.formatIso),
      Effect.flatMap((now) =>
        composeCustomerArchive(context.services.ports, {
          ...input,
          now,
          principalId: context.scope.principalId,
        }),
      ),
      Effect.mapError(mapHistoryError),
      Effect.map((result) => ({ evidence: { resultCount: result.items.length }, result })),
    ),
  (transaction, scope) => loadCustomerHistoryReadServices(transaction, scope),
  subjectHistoryTarget,
);
