// @generated by OntOS Codesmith module-api v1
import {
  defineRead,
  defineTenantModuleEntrypoint,
  OperationContextUnavailable,
  ReadHandlerUnavailable,
} from '@app/core-runtime';
import type { ReadHandlerContext } from '@app/core-runtime';
import { Effect } from 'effect';
import {
  PurchaseLimitPolicyReadRequestSchema,
  PurchaseLimitPolicyReadResponseSchema,
} from '../../shared/apis/purchase-limit-policy-read.ts';
import type { PurchaseLimitPolicyReadRequest } from '../../shared/apis/purchase-limit-policy-read.ts';
import { PurchaseLimitPolicyServiceFactory } from '../../shared/domain/purchase-limit-policy.ts';
import type { PurchaseLimitPolicyService } from '../../shared/domain/purchase-limit-policy.ts';

const preserveFailureCause = <Failure extends object>(
  failure: Failure,
  cause: unknown,
): Failure => {
  Object.defineProperty(failure, 'cause', { configurable: true, value: cause });
  return failure;
};

export const purchaseLimitPolicyReadEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'counterparty.purchase_limit.manage' },
  entrypointKey: 'commerce.customer-context.api.purchase-limit-policy-read',
  moduleKey: 'commerce.customer-context',
  role: 'api',
});

export const purchaseLimitPolicyReadRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: purchaseLimitPolicyReadEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.customer-context.api.purchase-limit-policy-read.evidence.v1',
    },
    inputSchema: PurchaseLimitPolicyReadRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: 'commerce.customer-context',
    permissionTarget: 'business_permission',
    policies: [],
    readKey: 'commerce.customer-context.api.purchase-limit-policy-read',
    resultSchema: PurchaseLimitPolicyReadResponseSchema,
    schemaVersion: '1',
  },
  (
    input,
    context: ReadHandlerContext<{
      readonly policy: PurchaseLimitPolicyService;
    }>,
  ) =>
    context.services.policy
      .readCurrent({
        counterpartyRef: input.counterpartyRef,
        principalRef: input.principalRef,
      })
      .pipe(
        Effect.mapError((cause) =>
          preserveFailureCause(
            new ReadHandlerUnavailable({
              code: 'read_handler_unavailable',
              reason: 'Purchase Limit policy is temporarily unavailable',
            }),
            cause,
          ),
        ),
        Effect.map((result) => ({
          evidence: { resultCount: 1 },
          result,
        })),
      ),
  (transaction, scope) =>
    PurchaseLimitPolicyServiceFactory.pipe(
      Effect.flatMap((factory) => factory.make(transaction, scope)),
      Effect.mapError((cause) =>
        preserveFailureCause(
          new OperationContextUnavailable({
            code: 'operation_context_unavailable',
            reason: 'Purchase Limit policy persistence is temporarily unavailable',
          }),
          cause,
        ),
      ),
      Effect.map((policy) => ({ policy })),
    ),
  (input: PurchaseLimitPolicyReadRequest, scope) => ({
    businessPermission: {
      permission: 'counterparty.purchase_limit.manage',
      target: {
        counterpartyId: input.counterpartyRef.resourceId,
        kind: 'counterparty',
        legalEntityId: scope.legalEntityId ?? '',
        tenantId: scope.tenantId,
      },
    },
    kind: 'business_permission',
  }),
);
