// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.customer-context
// @ontos-action-http-slug reroute-purchase-approval-request
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  ReroutePurchaseApprovalRequestActionApi,
  ReroutePurchaseApprovalRequestPayloadSchema,
} from '../../shared/apis/reroute-purchase-approval-request-action.ts';
import type { ReroutePurchaseApprovalRequestPayload } from '../../shared/actions/reroute-purchase-approval-request.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface ReroutePurchaseApprovalRequestActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: ReroutePurchaseApprovalRequestActionClientOptions,
];
type OperationInvocation = readonly [
  requestCorrelation: string,
  options: ReroutePurchaseApprovalRequestActionClientOptions,
];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: ReroutePurchaseApprovalRequestActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    {
      api: ReroutePurchaseApprovalRequestActionApi,
      credential,
      defaultApiPrefix: '/commerce-customer-context-api',
      requestCorrelation,
    },
    options,
  );

export const executeReroutePurchaseApprovalRequestWithAuthorization = (
  payload: ReroutePurchaseApprovalRequestPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(ReroutePurchaseApprovalRequestPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.reroutePurchaseApprovalRequestAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeReroutePurchaseApprovalRequest = (
  payload: ReroutePurchaseApprovalRequestPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) =>
      executeReroutePurchaseApprovalRequestWithAuthorization(
        payload,
        credential,
        requestCorrelation,
        options,
      ),
    options.gateway,
  );
