// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.customer-context
// @ontos-action-http-slug revalidate-purchase-approval
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  RevalidatePurchaseApprovalActionApi,
  RevalidatePurchaseApprovalPayloadSchema,
} from '../../shared/apis/revalidate-purchase-approval-action.ts';
import type { RevalidatePurchaseApprovalPayload } from '../../shared/actions/revalidate-purchase-approval.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface RevalidatePurchaseApprovalActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: RevalidatePurchaseApprovalActionClientOptions,
];
type OperationInvocation = readonly [
  requestCorrelation: string,
  options: RevalidatePurchaseApprovalActionClientOptions,
];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: RevalidatePurchaseApprovalActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    {
      api: RevalidatePurchaseApprovalActionApi,
      credential,
      defaultApiPrefix: '/commerce-customer-context-api',
      requestCorrelation,
    },
    options,
  );

export const executeRevalidatePurchaseApprovalWithAuthorization = (
  payload: RevalidatePurchaseApprovalPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(RevalidatePurchaseApprovalPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.revalidatePurchaseApprovalAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeRevalidatePurchaseApproval = (
  payload: RevalidatePurchaseApprovalPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) =>
      executeRevalidatePurchaseApprovalWithAuthorization(
        payload,
        credential,
        requestCorrelation,
        options,
      ),
    options.gateway,
  );
