// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { VerifyEffectiveCustomerGroupMembershipSetV1Api } from '../../shared/apis/verify-effective-customer-group-membership-set-v1.ts';
import type { VerifyEffectiveCustomerGroupMembershipSetV1Request } from '../../shared/apis/verify-effective-customer-group-membership-set-v1.ts';
import { operationGateway } from './action-gateway.ts';

export interface VerifyEffectiveCustomerGroupMembershipSetV1ClientOptions {
  readonly baseUrl?: string | URL;
  readonly compositionRevision?: string;
}

type VerifyEffectiveCustomerGroupMembershipSetV1AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: VerifyEffectiveCustomerGroupMembershipSetV1ClientOptions,
];

type VerifyEffectiveCustomerGroupMembershipSetV1OperationInvocation = readonly [
  requestCorrelation: string,
  options?: VerifyEffectiveCustomerGroupMembershipSetV1ClientOptions,
];

const verifyEffectiveCustomerGroupMembershipSetV1Client = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: VerifyEffectiveCustomerGroupMembershipSetV1ClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: VerifyEffectiveCustomerGroupMembershipSetV1Api,
      credential,
      defaultApiPrefix: '/commerce-customer-context-api',
      requestCorrelation,
    },
    options,
  );

export const executeVerifyEffectiveCustomerGroupMembershipSetV1WithAuthorization = (
  payload: VerifyEffectiveCustomerGroupMembershipSetV1Request,
  ...[credential, requestCorrelation, options = {}]: VerifyEffectiveCustomerGroupMembershipSetV1AuthorizedInvocation
) =>
  verifyEffectiveCustomerGroupMembershipSetV1Client(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) => client.verifyEffectiveCustomerGroupMembershipSetV1.execute({ payload })),
  );

export const executeVerifyEffectiveCustomerGroupMembershipSetV1 = (
  payload: VerifyEffectiveCustomerGroupMembershipSetV1Request,
  ...[requestCorrelation, options = {}]: VerifyEffectiveCustomerGroupMembershipSetV1OperationInvocation
) =>
  operationGateway.invoke((credential, { apiBaseUrl, compositionRevision }) =>
    executeVerifyEffectiveCustomerGroupMembershipSetV1WithAuthorization(payload, credential, requestCorrelation, {
      ...options,
      baseUrl: apiBaseUrl,
      compositionRevision,
    }),
  );
