// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner commerce.catalog
// @ontos-resource-slug variant
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

/** Variant identity is allocated once and retained for the life of the tenant resource. */
const checkedUuid = Schema.String.check(Schema.isUUID(), Schema.isTrimmed());
const ResourceIdSchema = checkedUuid.pipe(Schema.brand('CatalogVariantResourceId'), Schema.decodeTo(checkedUuid));
const TenantIdSchema = checkedUuid.pipe(Schema.brand('CatalogTenantId'), Schema.decodeTo(checkedUuid));

export const VariantRefSchema = Schema.Struct({
  moduleId: Schema.Literal('commerce.catalog'),
  resourceId: ResourceIdSchema,
  resourceType: Schema.Literal('commerce.catalog.variant'),
  tenantId: TenantIdSchema,
});
export type VariantRef = typeof VariantRefSchema.Type;

export const variantResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Variant resource.',
  key: 'commerce.catalog.variant',
  label: 'Variant',
  owningModuleId: 'commerce.catalog',
} as const satisfies OntosResourceType;
