// @generated by OntOS Codesmith module-api v1
import type { ReadHandlerContext } from '@app/core-runtime';
import {
  ReadHandlerNotFound,
  ReadHandlerUnavailable,
  defineRead,
  defineTenantModuleEntrypoint,
} from '@app/core-runtime';
import { Effect, Match, Schema } from 'effect';
import {
  ActivatePackageOptionRecoveryRequestSchema,
  ActivatePackageOptionRecoveryResponseSchema,
} from '../../shared/apis/activate-package-option-recovery.ts';
import type { ActivatePackageOptionRecoveryRequest } from '../../shared/apis/activate-package-option-recovery.ts';
import { ActivatePackageOptionResultSchema } from '../../shared/actions/activate-package-option.ts';
import { recoverCatalogActionResult } from './catalog-action-result-recovery.ts';

interface RecoveryService {
  readonly recover: (invocationId: string) => ReturnType<typeof recoverResult>;
}

const notFound = () =>
  new ReadHandlerNotFound({
    code: 'read_handler_not_found',
    reason: 'No committed activate package option result exists in this principal scope',
  });
const unavailable = () =>
  new ReadHandlerUnavailable({
    code: 'read_handler_unavailable',
    reason: 'The original activate package option outcome cannot be verified yet',
  });

const recoverResult = (
  transaction: Parameters<typeof recoverCatalogActionResult>[0],
  scope: Parameters<typeof recoverCatalogActionResult>[1],
  invocationId: string,
) =>
  recoverCatalogActionResult(
    transaction,
    scope,
    { actionInvocationId: invocationId, actionKey: 'commerce.catalog.activate-package-option', schemaVersion: 1 },
    {
      decode: Schema.decodeUnknownEffect(ActivatePackageOptionResultSchema),
      encode: Schema.encodeEffect(ActivatePackageOptionResultSchema),
    },
  );

const recoverActivatePackageOption = Effect.fn('ActivatePackageOptionRecoveryRead.recover')(function* recover(
  input: ActivatePackageOptionRecoveryRequest,
  context: ReadHandlerContext<RecoveryService>,
) {
  const recovery = yield* context.services.recover(input.invocationId);
  return yield* Match.value(recovery).pipe(
    Match.discriminator('status')('committed', ({ result }) => Effect.succeed(result)),
    Match.discriminator('status')('absent', () => Effect.fail(notFound())),
    Match.discriminator('status')('rejected', () => Effect.fail(unavailable())),
    Match.discriminator('status')('open', () => Effect.fail(unavailable())),
    Match.discriminator('status')('indeterminate', () => Effect.fail(unavailable())),
    Match.discriminator('status')('unavailable', () => Effect.fail(unavailable())),
    Match.exhaustive,
  );
});

const activatePackageOptionRecoveryEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'commerce.catalog.read.activate-package-option-recovery' },
  entrypointKey: 'commerce.catalog.api.activate-package-option-recovery',
  moduleKey: 'commerce.catalog',
  role: 'api',
});

export const activatePackageOptionRecoveryRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: activatePackageOptionRecoveryEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.api.activate-package-option-recovery.evidence.v1',
    },
    inputSchema: ActivatePackageOptionRecoveryRequestSchema,
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    permissionTarget: 'tenant',
    policies: [],
    readKey: 'commerce.catalog.api.activate-package-option-recovery',
    resultSchema: ActivatePackageOptionRecoveryResponseSchema,
    schemaVersion: '1',
  },
  (input, context: ReadHandlerContext<RecoveryService>) =>
    recoverActivatePackageOption(input, context).pipe(
      Effect.map((result) => ({ evidence: { resultCount: 1 }, result })),
    ),
  (transaction, scope) =>
    Effect.succeed({ recover: (invocationId: string) => recoverResult(transaction, scope, invocationId) }),
  () => ({ kind: 'tenant', permission: 'access' }),
);
