// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { ChangeLocalOverrideRecoveryApi } from '../../shared/apis/change-local-override-recovery.ts';
import type { ChangeLocalOverrideRecoveryRequest } from '../../shared/apis/change-local-override-recovery.ts';
import { operationGateway } from './action-gateway.ts';

export interface ChangeLocalOverrideRecoveryClientOptions {
  readonly baseUrl?: string | URL;
}

type ChangeLocalOverrideRecoveryAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: ChangeLocalOverrideRecoveryClientOptions,
];

type ChangeLocalOverrideRecoveryOperationInvocation = readonly [
  requestCorrelation: string,
  options?: ChangeLocalOverrideRecoveryClientOptions,
];

const changeLocalOverrideRecoveryClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: ChangeLocalOverrideRecoveryClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: ChangeLocalOverrideRecoveryApi,
      credential,
      defaultApiPrefix: '/catalog-api',
      requestCorrelation,
    },
    options,
  );

export const executeChangeLocalOverrideRecoveryWithAuthorization = (
  payload: ChangeLocalOverrideRecoveryRequest,
  ...[credential, requestCorrelation, options = {}]: ChangeLocalOverrideRecoveryAuthorizedInvocation
) =>
  changeLocalOverrideRecoveryClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) =>
      client.changeLocalOverrideRecovery.execute({ headers: {}, params: {}, payload, query: {} }),
    ),
  );

export const executeChangeLocalOverrideRecovery = (
  payload: ChangeLocalOverrideRecoveryRequest,
  ...[requestCorrelation, options = {}]: ChangeLocalOverrideRecoveryOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeChangeLocalOverrideRecoveryWithAuthorization(payload, credential, requestCorrelation, options),
  );
