// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.catalog
// @ontos-action-http-slug confirm-variant-combination
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  ConfirmVariantCombinationActionApi,
  ConfirmVariantCombinationPayloadSchema,
} from '../../shared/apis/confirm-variant-combination-action.ts';
import type { ConfirmVariantCombinationPayload } from '../../shared/actions/confirm-variant-combination.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface ConfirmVariantCombinationActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly compositionRevision?: string;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: ConfirmVariantCombinationActionClientOptions,
];
type OperationInvocation = readonly [requestCorrelation: string, options: ConfirmVariantCombinationActionClientOptions];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: ConfirmVariantCombinationActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    {
      api: ConfirmVariantCombinationActionApi,
      credential,
      defaultApiPrefix: '/catalog-api',
      idempotencyKey: options.idempotencyKey,
      requestCorrelation,
    },
    options,
  );

export const executeConfirmVariantCombinationWithAuthorization = (
  payload: ConfirmVariantCombinationPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(ConfirmVariantCombinationPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) => client.confirmVariantCombinationAction.execute({ payload: encoded })),
      ),
    ),
  );

export const executeConfirmVariantCombination = (
  payload: ConfirmVariantCombinationPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential, { apiBaseUrl, compositionRevision }) =>
      executeConfirmVariantCombinationWithAuthorization(payload, credential, requestCorrelation, {
        ...options,
        baseUrl: apiBaseUrl,
        compositionRevision,
      }),
    options.gateway,
  );
