// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.catalog
// @ontos-action-http-slug create-product-type
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  CreateProductTypeActionApi,
  CreateProductTypePayloadSchema,
} from '../../shared/apis/create-product-type-action.ts';
import type { CreateProductTypePayload } from '../../shared/actions/create-product-type.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface CreateProductTypeActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: CreateProductTypeActionClientOptions,
];
type OperationInvocation = readonly [requestCorrelation: string, options: CreateProductTypeActionClientOptions];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: CreateProductTypeActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    { api: CreateProductTypeActionApi, credential, defaultApiPrefix: '/catalog-api', requestCorrelation },
    options,
  );

export const executeCreateProductTypeWithAuthorization = (
  payload: CreateProductTypePayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(CreateProductTypePayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.createProductTypeAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeCreateProductType = (
  payload: CreateProductTypePayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) => executeCreateProductTypeWithAuthorization(payload, credential, requestCorrelation, options),
    options.gateway,
  );
