// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { ReactivateProductRecoveryApi } from '../../shared/apis/reactivate-product-recovery.ts';
import type { ReactivateProductRecoveryRequest } from '../../shared/apis/reactivate-product-recovery.ts';
import { operationGateway } from './action-gateway.ts';

export interface ReactivateProductRecoveryClientOptions {
  readonly baseUrl?: string | URL;
}

type ReactivateProductRecoveryAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: ReactivateProductRecoveryClientOptions,
];

type ReactivateProductRecoveryOperationInvocation = readonly [
  requestCorrelation: string,
  options?: ReactivateProductRecoveryClientOptions,
];

const reactivateProductRecoveryClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: ReactivateProductRecoveryClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: ReactivateProductRecoveryApi,
      credential,
      defaultApiPrefix: '/catalog-api',
      requestCorrelation,
    },
    options,
  );

export const executeReactivateProductRecoveryWithAuthorization = (
  payload: ReactivateProductRecoveryRequest,
  ...[credential, requestCorrelation, options = {}]: ReactivateProductRecoveryAuthorizedInvocation
) =>
  reactivateProductRecoveryClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) =>
      client.reactivateProductRecovery.execute({ headers: {}, params: {}, payload, query: {} }),
    ),
  );

export const executeReactivateProductRecovery = (
  payload: ReactivateProductRecoveryRequest,
  ...[requestCorrelation, options = {}]: ReactivateProductRecoveryOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeReactivateProductRecoveryWithAuthorization(payload, credential, requestCorrelation, options),
  );
