// @generated by OntOS Codesmith module-api v1
import type { ReadHandlerContext } from '@app/core-runtime';
import {
  ReadHandlerNotFound,
  ReadHandlerUnavailable,
  defineRead,
  defineTenantModuleEntrypoint,
} from '@app/core-runtime';
import { Effect, Match, Schema } from 'effect';
import {
  RenameControlledAttributeValueRecoveryRequestSchema,
  RenameControlledAttributeValueRecoveryResponseSchema,
} from '../../shared/apis/rename-controlled-attribute-value-recovery.ts';
import type { RenameControlledAttributeValueRecoveryRequest } from '../../shared/apis/rename-controlled-attribute-value-recovery.ts';
import { RenameControlledAttributeValueResultSchema } from '../../shared/actions/rename-controlled-attribute-value.ts';
import { recoverCatalogActionResult } from './catalog-action-result-recovery.ts';

interface RecoveryService {
  readonly recover: (invocationId: string) => ReturnType<typeof recoverResult>;
}

const notFound = () =>
  new ReadHandlerNotFound({
    code: 'read_handler_not_found',
    reason: 'No committed original Action result exists in this principal scope',
  });
const unavailable = () =>
  new ReadHandlerUnavailable({
    code: 'read_handler_unavailable',
    reason: 'The original Action outcome cannot be verified yet',
  });

const recoverResult = (
  transaction: Parameters<typeof recoverCatalogActionResult>[0],
  scope: Parameters<typeof recoverCatalogActionResult>[1],
  invocationId: string,
) =>
  recoverCatalogActionResult(
    transaction,
    scope,
    {
      actionInvocationId: invocationId,
      actionKey: 'commerce.catalog.rename-controlled-attribute-value',
      schemaVersion: 1,
    },
    {
      decode: Schema.decodeUnknownEffect(RenameControlledAttributeValueResultSchema),
      encode: Schema.encodeEffect(RenameControlledAttributeValueResultSchema),
    },
  );

const recoverRenameControlledAttributeValue = Effect.fn('RenameControlledAttributeValueRecoveryRead.recover')(
  function* recover(
    input: RenameControlledAttributeValueRecoveryRequest,
    context: ReadHandlerContext<RecoveryService>,
  ) {
    const recovery = yield* context.services.recover(input.invocationId);
    return yield* Match.value(recovery).pipe(
      Match.discriminator('status')('committed', ({ result }) => Effect.succeed(result)),
      Match.discriminator('status')('absent', () => Effect.fail(notFound())),
      Match.discriminator('status')('rejected', () => Effect.fail(unavailable())),
      Match.discriminator('status')('open', () => Effect.fail(unavailable())),
      Match.discriminator('status')('indeterminate', () => Effect.fail(unavailable())),
      Match.discriminator('status')('unavailable', () => Effect.fail(unavailable())),
      Match.exhaustive,
    );
  },
);

const renameControlledAttributeValueRecoveryEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: {
    kind: 'context_permission',
    permission: 'commerce.catalog.read.rename-controlled-attribute-value-recovery',
  },
  entrypointKey: 'commerce.catalog.api.rename-controlled-attribute-value-recovery',
  moduleKey: 'commerce.catalog',
  role: 'api',
});

export const renameControlledAttributeValueRecoveryRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: renameControlledAttributeValueRecoveryEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.api.rename-controlled-attribute-value-recovery.evidence.v1',
    },
    inputSchema: RenameControlledAttributeValueRecoveryRequestSchema,
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    permissionTarget: 'tenant',
    policies: [],
    readKey: 'commerce.catalog.api.rename-controlled-attribute-value-recovery',
    resultSchema: RenameControlledAttributeValueRecoveryResponseSchema,
    schemaVersion: '1',
  },
  (input, context: ReadHandlerContext<RecoveryService>) =>
    recoverRenameControlledAttributeValue(input, context).pipe(
      Effect.map((result) => ({ evidence: { resultCount: 1 }, result })),
    ),
  (transaction, scope) =>
    Effect.succeed({ recover: (invocationId: string) => recoverResult(transaction, scope, invocationId) }),
  () => ({ kind: 'tenant', permission: 'access' }),
);
