// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { RenameControlledAttributeValueRecoveryApi } from '../../shared/apis/rename-controlled-attribute-value-recovery.ts';
import type { RenameControlledAttributeValueRecoveryRequest } from '../../shared/apis/rename-controlled-attribute-value-recovery.ts';
import { operationGateway } from './action-gateway.ts';

export interface RenameControlledAttributeValueRecoveryClientOptions {
  readonly baseUrl?: string | URL;
  readonly compositionRevision?: string;
}

type RenameControlledAttributeValueRecoveryAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: RenameControlledAttributeValueRecoveryClientOptions,
];

type RenameControlledAttributeValueRecoveryOperationInvocation = readonly [
  requestCorrelation: string,
  options?: RenameControlledAttributeValueRecoveryClientOptions,
];

const renameControlledAttributeValueRecoveryClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: RenameControlledAttributeValueRecoveryClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: RenameControlledAttributeValueRecoveryApi,
      credential,
      defaultApiPrefix: '/catalog-api',
      requestCorrelation,
    },
    options,
  );

export const executeRenameControlledAttributeValueRecoveryWithAuthorization = (
  payload: RenameControlledAttributeValueRecoveryRequest,
  ...[credential, requestCorrelation, options = {}]: RenameControlledAttributeValueRecoveryAuthorizedInvocation
) =>
  renameControlledAttributeValueRecoveryClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) => client.renameControlledAttributeValueRecovery.execute({ payload })),
  );

export const executeRenameControlledAttributeValueRecovery = (
  payload: RenameControlledAttributeValueRecoveryRequest,
  ...[requestCorrelation, options = {}]: RenameControlledAttributeValueRecoveryOperationInvocation
) =>
  operationGateway.invoke((credential, { apiBaseUrl, compositionRevision }) =>
    executeRenameControlledAttributeValueRecoveryWithAuthorization(payload, credential, requestCorrelation, {
      ...options,
      baseUrl: apiBaseUrl,
      compositionRevision,
    }),
  );
