// @generated by OntOS Codesmith module-api v1
import type { ReadHandlerContext } from '@app/core-runtime';
import {
  ReadHandlerNotFound,
  ReadHandlerUnavailable,
  defineRead,
  defineTenantModuleEntrypoint,
} from '@app/core-runtime';
import { Effect, Match, Schema } from 'effect';
import {
  RetireProductUnitRecoveryRequestSchema,
  RetireProductUnitRecoveryResponseSchema,
} from '../../shared/apis/retire-product-unit-recovery.ts';
import type { RetireProductUnitRecoveryRequest } from '../../shared/apis/retire-product-unit-recovery.ts';
import { RetireProductUnitResultSchema } from '../../shared/actions/retire-product-unit.ts';
import { recoverCatalogActionResult } from './catalog-action-result-recovery.ts';

interface RecoveryService {
  readonly recover: (invocationId: string) => ReturnType<typeof recoverResult>;
}

const notFound = () =>
  new ReadHandlerNotFound({
    code: 'read_handler_not_found',
    reason: 'No committed retire product unit result exists in this principal scope',
  });
const unavailable = () =>
  new ReadHandlerUnavailable({
    code: 'read_handler_unavailable',
    reason: 'The original retire product unit outcome cannot be verified yet',
  });

const recoverResult = (
  transaction: Parameters<typeof recoverCatalogActionResult>[0],
  scope: Parameters<typeof recoverCatalogActionResult>[1],
  invocationId: string,
) =>
  recoverCatalogActionResult(
    transaction,
    scope,
    { actionInvocationId: invocationId, actionKey: 'commerce.catalog.retire-product-unit', schemaVersion: 1 },
    {
      decode: Schema.decodeUnknownEffect(RetireProductUnitResultSchema),
      encode: Schema.encodeEffect(RetireProductUnitResultSchema),
    },
  );

const recoverRetireProductUnit = Effect.fn('RetireProductUnitRecoveryRead.recover')(function* recover(
  input: RetireProductUnitRecoveryRequest,
  context: ReadHandlerContext<RecoveryService>,
) {
  const recovery = yield* context.services.recover(input.invocationId);
  return yield* Match.value(recovery).pipe(
    Match.discriminator('status')('committed', ({ result }) => Effect.succeed(result)),
    Match.discriminator('status')('absent', () => Effect.fail(notFound())),
    Match.discriminator('status')('rejected', () => Effect.fail(unavailable())),
    Match.discriminator('status')('open', () => Effect.fail(unavailable())),
    Match.discriminator('status')('indeterminate', () => Effect.fail(unavailable())),
    Match.discriminator('status')('unavailable', () => Effect.fail(unavailable())),
    Match.exhaustive,
  );
});

const retireProductUnitRecoveryEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'commerce.catalog.read.retire-product-unit-recovery' },
  entrypointKey: 'commerce.catalog.api.retire-product-unit-recovery',
  moduleKey: 'commerce.catalog',
  role: 'api',
});

export const retireProductUnitRecoveryRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: retireProductUnitRecoveryEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.api.retire-product-unit-recovery.evidence.v1',
    },
    inputSchema: RetireProductUnitRecoveryRequestSchema,
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    permissionTarget: 'tenant',
    policies: [],
    readKey: 'commerce.catalog.api.retire-product-unit-recovery',
    resultSchema: RetireProductUnitRecoveryResponseSchema,
    schemaVersion: '1',
  },
  (input, context: ReadHandlerContext<RecoveryService>) =>
    recoverRetireProductUnit(input, context).pipe(Effect.map((result) => ({ evidence: { resultCount: 1 }, result }))),
  (transaction, scope) =>
    Effect.succeed({ recover: (invocationId: string) => recoverResult(transaction, scope, invocationId) }),
  () => ({ kind: 'tenant', permission: 'access' }),
);
