// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { ReviseAttributeDefinitionRecoveryApi } from '../../shared/apis/revise-attribute-definition-recovery.ts';
import type { ReviseAttributeDefinitionRecoveryRequest } from '../../shared/apis/revise-attribute-definition-recovery.ts';
import { operationGateway } from './action-gateway.ts';

export interface ReviseAttributeDefinitionRecoveryClientOptions {
  readonly baseUrl?: string | URL;
}

type ReviseAttributeDefinitionRecoveryAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: ReviseAttributeDefinitionRecoveryClientOptions,
];

type ReviseAttributeDefinitionRecoveryOperationInvocation = readonly [
  requestCorrelation: string,
  options?: ReviseAttributeDefinitionRecoveryClientOptions,
];

const reviseAttributeDefinitionRecoveryClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: ReviseAttributeDefinitionRecoveryClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: ReviseAttributeDefinitionRecoveryApi,
      credential,
      defaultApiPrefix: '/catalog-api',
      requestCorrelation,
    },
    options,
  );

export const executeReviseAttributeDefinitionRecoveryWithAuthorization = (
  payload: ReviseAttributeDefinitionRecoveryRequest,
  ...[credential, requestCorrelation, options = {}]: ReviseAttributeDefinitionRecoveryAuthorizedInvocation
) =>
  reviseAttributeDefinitionRecoveryClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) =>
      client.reviseAttributeDefinitionRecovery.execute({ headers: {}, params: {}, payload, query: {} }),
    ),
  );

export const executeReviseAttributeDefinitionRecovery = (
  payload: ReviseAttributeDefinitionRecoveryRequest,
  ...[requestCorrelation, options = {}]: ReviseAttributeDefinitionRecoveryOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeReviseAttributeDefinitionRecoveryWithAuthorization(payload, credential, requestCorrelation, options),
  );
