// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { SetCompositionCurrentApi } from '../../shared/apis/set-composition-current.ts';
import type { SetCompositionCurrentRequest } from '../../shared/apis/set-composition-current.ts';
import { operationGateway } from './action-gateway.ts';

export interface SetCompositionCurrentClientOptions {
  readonly baseUrl?: string | URL;
}

type SetCompositionCurrentAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: SetCompositionCurrentClientOptions,
];

type SetCompositionCurrentOperationInvocation = readonly [
  requestCorrelation: string,
  options?: SetCompositionCurrentClientOptions,
];

const setCompositionCurrentClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: SetCompositionCurrentClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: SetCompositionCurrentApi,
      credential,
      defaultApiPrefix: '/catalog-api',
      requestCorrelation,
    },
    options,
  );

export const executeSetCompositionCurrentWithAuthorization = (
  payload: SetCompositionCurrentRequest,
  ...[credential, requestCorrelation, options = {}]: SetCompositionCurrentAuthorizedInvocation
) =>
  setCompositionCurrentClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) => client.setCompositionCurrent.execute({ headers: {}, params: {}, payload, query: {} })),
  );

export const executeSetCompositionCurrent = (
  payload: SetCompositionCurrentRequest,
  ...[requestCorrelation, options = {}]: SetCompositionCurrentOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeSetCompositionCurrentWithAuthorization(payload, credential, requestCorrelation, options),
  );
