// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.catalog
// @ontos-action-http-slug set-product-unit-target-divisibility
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  SetProductUnitTargetDivisibilityActionApi,
  SetProductUnitTargetDivisibilityPayloadSchema,
} from '../../shared/apis/set-product-unit-target-divisibility-action.ts';
import type { SetProductUnitTargetDivisibilityPayload } from '../../shared/actions/set-product-unit-target-divisibility.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface SetProductUnitTargetDivisibilityActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: SetProductUnitTargetDivisibilityActionClientOptions,
];
type OperationInvocation = readonly [
  requestCorrelation: string,
  options: SetProductUnitTargetDivisibilityActionClientOptions,
];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: SetProductUnitTargetDivisibilityActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    {
      api: SetProductUnitTargetDivisibilityActionApi,
      credential,
      defaultApiPrefix: '/catalog-api',
      requestCorrelation,
    },
    options,
  );

export const executeSetProductUnitTargetDivisibilityWithAuthorization = (
  payload: SetProductUnitTargetDivisibilityPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(SetProductUnitTargetDivisibilityPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.setProductUnitTargetDivisibilityAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeSetProductUnitTargetDivisibility = (
  payload: SetProductUnitTargetDivisibilityPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) =>
      executeSetProductUnitTargetDivisibilityWithAuthorization(payload, credential, requestCorrelation, options),
    options.gateway,
  );
