// @generated by scaffold:outbox-worker worker-host
// @ontos-outbox-worker-host-owner party.registry
import { Layer } from 'effect';
import {
  CoreSearchIngestionLive,
  CoreSearchProjectionStoreLive,
  CoreSearchWorkerSnapshotLive,
} from '@app/core-runtime';
import { OutboxWorkerInfrastructureLive } from '@app/core-runtime/outbox/worker';
import type {
  CoreSearchIngestion,
  CoreSearchProjectionStoreService,
  CoreSearchWorkerSnapshot,
  OutboxRuntime,
} from '@app/core-runtime';
import { PartySearchProjectorLive } from '../services/party-search-projection.service.ts';
import type { PartySearchProjector } from '../services/party-search-projection.service.ts';
import { PartySearchProjectionSourceLive } from '../services/party-search-projection-source.service.ts';
import type { PartySearchProjectionSource } from '../services/party-search-projection-source.service.ts';

export {
  CorePersistenceLive as outboxWorkerCorePersistenceLive,
  DatabaseConfigLive as outboxWorkerDatabaseConfigLive,
  OutboxRepositoryLive as outboxWorkerRepositoryLive,
} from '@app/core-runtime/outbox/worker';

const outboxWorkerInfrastructureLayer: Layer.Layer<
  OutboxRuntime,
  never,
  Layer.Services<typeof OutboxWorkerInfrastructureLive>
> = OutboxWorkerInfrastructureLive;

type OutboxWorkerHandlerLayers = Readonly<{
  projector: Layer.Layer<
    PartySearchProjector,
    never,
    CoreSearchIngestion | CoreSearchProjectionStoreService | PartySearchProjectionSource
  >;
  projectionSource: Layer.Layer<PartySearchProjectionSource, never, CoreSearchWorkerSnapshot>;
  searchIngestion: Layer.Layer<CoreSearchIngestion, never, CoreSearchProjectionStoreService>;
  searchProjectionStore: Layer.Layer<
    CoreSearchProjectionStoreService,
    never,
    Layer.Services<typeof CoreSearchProjectionStoreLive>
  >;
  searchWorkerSnapshot: Layer.Layer<
    CoreSearchWorkerSnapshot,
    never,
    Layer.Services<typeof CoreSearchWorkerSnapshotLive>
  >;
}>;

/** Private canonical reads run post-commit; only sanitized projections cross into Core Search. */
export const outboxWorkerHandlerLayers: OutboxWorkerHandlerLayers = Object.freeze({
  projector: PartySearchProjectorLive,
  projectionSource: PartySearchProjectionSourceLive,
  searchIngestion: CoreSearchIngestionLive,
  searchProjectionStore: CoreSearchProjectionStoreLive,
  searchWorkerSnapshot: CoreSearchWorkerSnapshotLive,
});

export const outboxWorkerLayer: Layer.Layer<
  OutboxRuntime | PartySearchProjector,
  never,
  | Layer.Services<typeof OutboxWorkerInfrastructureLive>
  | CoreSearchIngestion
  | CoreSearchProjectionStoreService
  | PartySearchProjectionSource
> = Layer.merge(outboxWorkerInfrastructureLayer, outboxWorkerHandlerLayers.projector);
