import { Cause, Effect } from 'effect';
import { expect, it } from 'effect-rstest';

import { NodeServices } from '@effect/platform-node';

import { access, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { getHelpText, runScaffoldEffect } from '../cli.mts';
import type { JsonValue } from '../shared.mts';

const expectFailure = <A, E, R>(self: Effect.Effect<A, E, R>, check: (cause: unknown) => void) =>
  Effect.matchCauseEffect(self, {
    onFailure: (cause) => Effect.sync(() => check(Cause.squash(cause))),
    onSuccess: () =>
      Effect.sync(() => {
        throw new Error('Expected operation to fail');
      }),
  });

const json = (value: JsonValue): string => `${JSON.stringify(value, null, 2)}\n`;

const RETIRE_CONTRIBUTION_COMMAND = 'retire-contribution';
const ARCHIVE_ITEM = 'archive-item';
const ITEM_DETAIL = 'item-detail';
const ARCHIVE_ITEM_ACTION_PATH = 'verticals/inventory/src/actions/archive-item.action.ts';

const write = (root: string, relative: string, content: string): Effect.Effect<void, unknown> =>
  Effect.gen(function* scenario1() {
    const target = path.join(root, relative);
    yield* Effect.promise(() => mkdir(path.dirname(target), { recursive: true }));
    yield* Effect.promise(() => writeFile(target, content, 'utf-8'));
  });

const visitTree = (
  root: string,
  snapshot: Record<string, string>,
  directory: string,
): Effect.Effect<void, unknown> =>
  Effect.gen(function* scenario3() {
    const entries = yield* Effect.promise(() => readdir(directory, { withFileTypes: true }));
    yield* Effect.all(
      entries.map(
        Effect.fn(function* scenario4(entry) {
          const target = path.join(directory, entry.name);
          if (entry.isDirectory()) {
            yield* visitTree(root, snapshot, target);
          } else if (entry.isFile()) {
            snapshot[path.relative(root, target)] = yield* Effect.promise(() =>
              readFile(target, 'utf-8'),
            );
          }
        }),
      ),
      { concurrency: 'unbounded' },
    );
  });

const snapshotTree = Effect.fn(function* scenario2(root: string) {
  const snapshot: Record<string, string> = {};

  yield* visitTree(root, snapshot, root);
  return snapshot;
});

const manifest = `// @generated by OntOS Codesmith Module Contract v1
// @ontos-deployment-app-id inventory
// @ontos-module-id inventory.core
// <generated-module-manifest-imports>
import { archiveItemAction } from './src/actions/archive-item.action.ts';
import { ItemDetailApi } from './shared/apis/item-detail.ts';
import { ItemDetailPage } from './src/routes/[lang]/inventory/items/[id]/page.tsx';
// </generated-module-manifest-imports>
export const inventoryManifest = {
  publicSurface: {
    actions: [
      // <generated-module-manifest-actions>
      archiveItemAction,
      // </generated-module-manifest-actions>
    ],
    api: {
      // <generated-module-manifest-apis>
      'item-detail': ItemDetailApi,
      // </generated-module-manifest-apis>
    },
    components: {
      // <generated-module-manifest-components>
      'page-item-detail': ItemDetailPage,
      // </generated-module-manifest-components>
    },
    shellContributions: {
      navigation: [
        // <generated-module-shell-navigation>
        { contributionKey: 'inventory.core.navigation.item-detail', entrypoint: { entrypointKey: 'inventory.core.page.item-detail' }, pageKey: 'inventory.core.page.item-detail' },
        // </generated-module-shell-navigation>
      ],
      pages: [
        // <generated-module-shell-pages>
        { componentKey: 'inventory.core.page-item-detail', contributionKey: 'inventory.core.page.item-detail', entrypoint: { entrypointKey: 'inventory.core.page.item-detail' }, routePath: '/inventory/items/:id' },
        // </generated-module-shell-pages>
      ],
    },
  },
};
`;

const registration = `// @generated by OntOS Codesmith Module Contract v1
// @ontos-deployment-app-id inventory
// @ontos-module-id inventory.core
// <generated-module-registration-imports>
import { archiveItemAction } from './src/actions/archive-item.action.ts';
// </generated-module-registration-imports>
export const inventoryRegistration = {
  actions: [
    // <generated-module-registration-actions>
    archiveItemAction,
    // </generated-module-registration-actions>
  ],
  entrypoints: {
    api: {
      // <generated-module-registration-apis>
      'item-detail': () => import('./src/api/item-detail-client.ts'),
      // </generated-module-registration-apis>
    },
    pages: {
      // <generated-module-registration-pages>
      'page-item-detail': () => import('./src/routes/[lang]/inventory/items/[id]/page.tsx'),
      // </generated-module-registration-pages>
    },
  },
};
`;

const createFixture = (): Effect.Effect<string, unknown> =>
  Effect.gen(function* scenario5() {
    const root = yield* Effect.promise(() =>
      mkdtemp(path.join(tmpdir(), 'ontos-retire-contribution-')),
    );
    yield* write(
      root,
      'verticals/inventory/package.json',
      json({
        dependencies: { '@app/core-runtime': 'workspace:*' },
        exports: {},
        modernjs: {
          appId: 'inventory',
          ontosModule: {
            contractPath: '/.well-known/ontos-module-manifest.json',
            manifest: './vertical.manifest.ts',
            moduleId: 'inventory.core',
            registration: './vertical.registration.ts',
            schemaVersion: 2,
          },
          role: 'module-federation-remote',
          topology: '../../topology/reference-topology.json',
        },
        name: '@app/inventory',
        scripts: {},
      }),
    );
    yield* write(
      root,
      'topology/reference-topology.json',
      json({
        verticals: [
          {
            id: 'inventory',
            kind: 'vertical',
            moduleFederation: { name: 'verticalInventory', role: 'remote' },
            package: '@app/inventory',
            path: 'verticals/inventory',
          },
        ],
      }),
    );
    yield* write(root, 'verticals/inventory/vertical.manifest.ts', manifest);
    yield* write(root, 'verticals/inventory/vertical.registration.ts', registration);
    yield* write(
      root,
      ARCHIVE_ITEM_ACTION_PATH,
      `// @generated by OntOS Codesmith Action v1
// @ontos-action-owner inventory.core
// @ontos-action-slug archive-item
// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
export const archiveItemAction = {};
`,
    );
    const apiHeader = '// @generated by OntOS Codesmith module-api v1\n';
    yield* write(
      root,
      'verticals/inventory/shared/apis/item-detail.ts',
      `${apiHeader}export const ItemDetailApi = {};\n`,
    );
    yield* write(
      root,
      'verticals/inventory/src/api/item-detail.read.ts',
      `${apiHeader}export const itemDetailRead = {};\n`,
    );
    yield* write(
      root,
      'verticals/inventory/src/api/item-detail-client.ts',
      `${apiHeader}export const executeItemDetailWithAuthorization = () => {};\n`,
    );
    yield* write(
      root,
      'verticals/inventory/api/item-detail-read-server.ts',
      `${apiHeader}export const itemDetailReadApiLive = {};\n`,
    );
    yield* write(
      root,
      'verticals/inventory/src/routes/[lang]/inventory/items/[id]/page.tsx',
      'export const ItemDetailPage = () => null;\n',
    );
    return root;
  });

const withFixture = (
  run: (root: string) => Effect.Effect<void, unknown>,
): Effect.Effect<void, unknown> =>
  Effect.gen(function* scenario6() {
    const root = yield* createFixture();
    yield* run(root).pipe(
      Effect.ensuring(Effect.promise(() => rm(root, { force: true, recursive: true }))),
    );
  });

const retire = Effect.fn(function* scenario7(
  root: string,
  kind: 'action' | 'api' | 'page',
  name: string,
) {
  return yield* runScaffoldEffect(
    RETIRE_CONTRIBUTION_COMMAND,
    ['--vertical', 'inventory', '--kind', kind, '--name', name],
    { workspaceRoot: root },
  ).pipe(Effect.provide(NodeServices.layer));
});

it.live(
  'retire-contribution help is write-free and documents the narrow kinds',
  Effect.fn(function* scenario8() {
    const result = yield* runScaffoldEffect(RETIRE_CONTRIBUTION_COMMAND, ['--help'], {
      workspaceRoot: path.join(tmpdir(), 'retire-help-missing'),
    }).pipe(Effect.provide(NodeServices.layer));
    expect(result).toEqual({ help: getHelpText(RETIRE_CONTRIBUTION_COMMAND), kind: 'help' });
    if (result.kind !== 'help') {
      throw new Error('Expected help result');
    }
    expect(result.help).toMatch(/--kind <action\|api\|page>/u);
  }),
);

it.live(
  'retires generated Actions, APIs, and page exposure while preserving page source',
  Effect.fn(function* scenario9() {
    yield* withFixture(
      Effect.fn(function* scenario10(root) {
        yield* retire(root, 'action', ARCHIVE_ITEM);
        yield* expectFailure(
          Effect.promise(() => access(path.join(root, ARCHIVE_ITEM_ACTION_PATH))),
          (error) => expect(error).toBeDefined(),
        );

        yield* retire(root, 'api', ITEM_DETAIL);
        yield* Effect.all(
          [
            'shared/apis/item-detail.ts',
            'src/api/item-detail.read.ts',
            'src/api/item-detail-client.ts',
            'api/item-detail-read-server.ts',
          ].map(
            Effect.fn(function* scenario11(relative) {
              return yield* expectFailure(
                Effect.promise(() => access(path.join(root, 'verticals/inventory', relative))),
                (error) => expect(error).toBeDefined(),
              );
            }),
          ),
          { concurrency: 'unbounded' },
        );

        yield* retire(root, 'page', ITEM_DETAIL);
        yield* Effect.promise(() =>
          access(
            path.join(root, 'verticals/inventory/src/routes/[lang]/inventory/items/[id]/page.tsx'),
          ),
        );
        const [nextManifest, nextRegistration] = yield* Effect.all(
          [
            Effect.promise(() =>
              readFile(path.join(root, 'verticals/inventory/vertical.manifest.ts'), 'utf-8'),
            ),
            Effect.promise(() =>
              readFile(path.join(root, 'verticals/inventory/vertical.registration.ts'), 'utf-8'),
            ),
          ],
          { concurrency: 'unbounded' },
        );
        expect(nextManifest).not.toMatch(
          /archiveItemAction|ItemDetailApi|ItemDetailPage|item-detail/u,
        );
        expect(nextRegistration).not.toMatch(/archiveItemAction|item-detail/u);
      }),
    );
  }),
);

it.live(
  'refuses traversal, reruns, customized artifacts, and dependent Actions atomically',
  Effect.fn(function* scenario12() {
    yield* withFixture(
      Effect.fn(function* scenario13(root) {
        const beforeTraversal = yield* snapshotTree(root);
        yield* expectFailure(retire(root, 'action', '../archive-item'), (error) =>
          expect(String(error)).toMatch(/lower-kebab-case/u),
        );
        expect(yield* snapshotTree(root)).toEqual(beforeTraversal);

        const actionPath = path.join(root, ARCHIVE_ITEM_ACTION_PATH);
        yield* Effect.promise(() =>
          writeFile(actionPath, 'export const archiveItemAction = {};\n', 'utf-8'),
        );
        const beforeCustomized = yield* snapshotTree(root);
        yield* expectFailure(retire(root, 'action', ARCHIVE_ITEM), (error) =>
          expect(String(error)).toMatch(/matching generated Action/u),
        );
        expect(yield* snapshotTree(root)).toEqual(beforeCustomized);
      }),
    );

    yield* withFixture(
      Effect.fn(function* scenario14(root) {
        const actionPath = path.join(root, ARCHIVE_ITEM_ACTION_PATH);
        const action = yield* Effect.promise(() => readFile(actionPath, 'utf-8'));
        yield* Effect.promise(() =>
          writeFile(
            actionPath,
            action.replace(
              '// </generated-outbox-message-exports>',
              'export const createMessage = () => ({});\n// </generated-outbox-message-exports>',
            ),
            'utf-8',
          ),
        );
        const beforeDependent = yield* snapshotTree(root);
        yield* expectFailure(retire(root, 'action', ARCHIVE_ITEM), (error) =>
          expect(String(error)).toMatch(/published Outbox dependents/u),
        );
        expect(yield* snapshotTree(root)).toEqual(beforeDependent);
      }),
    );

    yield* withFixture(
      Effect.fn(function* scenario15(root) {
        yield* retire(root, 'page', ITEM_DETAIL);
        const retired = yield* snapshotTree(root);
        yield* expectFailure(retire(root, 'page', ITEM_DETAIL), (error) =>
          expect(String(error)).toMatch(/exactly one generated/u),
        );
        expect(yield* snapshotTree(root)).toEqual(retired);
      }),
    );
  }),
);
