// @generated by OntOS Codesmith module-api v1
import {
  makeProblemDetailsSchema,
  makeRetryableProblemDetailsSchema,
} from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import {
  CommerceCustomerProfileTargetSchema,
  CustomerPriceGroupAssignmentSchema,
  PriceGroupAuthorizationSubjectSchema,
  isPriceGroupAuthorizationSubjectCompatible,
} from '../domain/price-group-contracts.ts';

export const CustomerPriceGroupAssignmentReadRequestSchema = Schema.Struct({
  authorizationSubject: PriceGroupAuthorizationSubjectSchema,
  profile: CommerceCustomerProfileTargetSchema,
}).check(
  Schema.makeFilter(({ authorizationSubject, profile }) =>
    isPriceGroupAuthorizationSubjectCompatible(profile, authorizationSubject)
      ? undefined
      : 'The authorization subject must identify the exact kind and Tenant of the target profile',
  ),
);
export type CustomerPriceGroupAssignmentReadRequest =
  typeof CustomerPriceGroupAssignmentReadRequestSchema.Type;
export const CustomerPriceGroupAssignmentReadResponseSchema = Schema.Struct({
  assignments: Schema.Array(CustomerPriceGroupAssignmentSchema).check(Schema.isMaxLength(200)),
  profile: CommerceCustomerProfileTargetSchema,
});
export type CustomerPriceGroupAssignmentReadResponse =
  typeof CustomerPriceGroupAssignmentReadResponseSchema.Type;

export const CustomerPriceGroupAssignmentReadAuthenticationProblemSchema = makeProblemDetailsSchema(
  'CustomerPriceGroupAssignmentReadAuthenticationProblem',
  401,
);
export const CustomerPriceGroupAssignmentReadInvalidProblemSchema = makeProblemDetailsSchema(
  'CustomerPriceGroupAssignmentReadInvalidProblem',
  400,
);
export const CustomerPriceGroupAssignmentReadUnavailableProblemSchema =
  makeRetryableProblemDetailsSchema('CustomerPriceGroupAssignmentReadUnavailableProblem', 503);
export const CustomerPriceGroupAssignmentReadForbiddenProblemSchema = makeProblemDetailsSchema(
  'CustomerPriceGroupAssignmentReadForbiddenProblem',
  403,
);
export const CustomerPriceGroupAssignmentReadNotFoundProblemSchema = makeProblemDetailsSchema(
  'CustomerPriceGroupAssignmentReadNotFoundProblem',
  404,
);
export const CustomerPriceGroupAssignmentReadPolicyProblemSchema = makeProblemDetailsSchema(
  'CustomerPriceGroupAssignmentReadPolicyProblem',
  422,
);
export const CustomerPriceGroupAssignmentReadPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'CustomerPriceGroupAssignmentReadPolicyConflictProblem',
  409,
);
export const CustomerPriceGroupAssignmentReadInternalProblemSchema = makeProblemDetailsSchema(
  'CustomerPriceGroupAssignmentReadInternalProblem',
  500,
);

export const CustomerPriceGroupAssignmentReadApi = HttpApi.make(
  'CustomerPriceGroupAssignmentReadApi',
).add(
  HttpApiGroup.make('customerPriceGroupAssignmentRead').add(
    HttpApiEndpoint.post('execute', '/reads/customer-price-group-assignment-read', {
      error: [
        CustomerPriceGroupAssignmentReadInvalidProblemSchema,
        CustomerPriceGroupAssignmentReadAuthenticationProblemSchema,
        CustomerPriceGroupAssignmentReadForbiddenProblemSchema,
        CustomerPriceGroupAssignmentReadNotFoundProblemSchema,
        CustomerPriceGroupAssignmentReadPolicyConflictProblemSchema,
        CustomerPriceGroupAssignmentReadPolicyProblemSchema,
        CustomerPriceGroupAssignmentReadUnavailableProblemSchema,
        CustomerPriceGroupAssignmentReadInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: CustomerPriceGroupAssignmentReadRequestSchema,
      query: {},
      success: CustomerPriceGroupAssignmentReadResponseSchema,
    }),
  ),
);
