// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import {
  MarketBootstrapResolutionOutcomeSchema,
  MarketBootstrapResolutionRequestSchema as BootstrapResolutionRequestSchema,
} from '../domain/market-bootstrap-resolution.ts';

export const MarketBootstrapResolutionRequestSchema = BootstrapResolutionRequestSchema;
export type MarketBootstrapResolutionRequest = typeof MarketBootstrapResolutionRequestSchema.Type;
export const MarketBootstrapResolutionResponseSchema = MarketBootstrapResolutionOutcomeSchema;
export type MarketBootstrapResolutionResponse = typeof MarketBootstrapResolutionResponseSchema.Type;

export const MarketBootstrapResolutionAuthenticationProblemSchema = makeProblemDetailsSchema(
  'MarketBootstrapResolutionAuthenticationProblem',
  401,
);
export const MarketBootstrapResolutionInvalidProblemSchema = makeProblemDetailsSchema(
  'MarketBootstrapResolutionInvalidProblem',
  400,
);
export const MarketBootstrapResolutionUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'MarketBootstrapResolutionUnavailableProblem',
  503,
);
export const MarketBootstrapResolutionForbiddenProblemSchema = makeProblemDetailsSchema(
  'MarketBootstrapResolutionForbiddenProblem',
  403,
);
export const MarketBootstrapResolutionNotFoundProblemSchema = makeProblemDetailsSchema(
  'MarketBootstrapResolutionNotFoundProblem',
  404,
);
export const MarketBootstrapResolutionPolicyProblemSchema = makeProblemDetailsSchema(
  'MarketBootstrapResolutionPolicyProblem',
  422,
);
export const MarketBootstrapResolutionPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'MarketBootstrapResolutionPolicyConflictProblem',
  409,
);
export const MarketBootstrapResolutionInternalProblemSchema = makeProblemDetailsSchema(
  'MarketBootstrapResolutionInternalProblem',
  500,
);

export const MarketBootstrapResolutionApi = HttpApi.make('MarketBootstrapResolutionApi').add(
  HttpApiGroup.make('marketBootstrapResolution').add(
    HttpApiEndpoint.post('execute', '/reads/market-bootstrap-resolution', {
      error: [
        MarketBootstrapResolutionInvalidProblemSchema,
        MarketBootstrapResolutionAuthenticationProblemSchema,
        MarketBootstrapResolutionForbiddenProblemSchema,
        MarketBootstrapResolutionNotFoundProblemSchema,
        MarketBootstrapResolutionPolicyConflictProblemSchema,
        MarketBootstrapResolutionPolicyProblemSchema,
        MarketBootstrapResolutionUnavailableProblemSchema,
        MarketBootstrapResolutionInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: MarketBootstrapResolutionRequestSchema,
      query: {},
      success: MarketBootstrapResolutionResponseSchema,
    }),
  ),
);
