// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import { RepeatOrderPreparationResultSchema } from '../domain/history-contracts.ts';
import { CustomerHistorySubjectSchema, HistoricalRecordRefSchema } from '../domain/record-visibility-contracts.ts';

export const RepeatOrderPreparationRequestSchema = Schema.Struct({
  orderRef: HistoricalRecordRefSchema,
  subject: CustomerHistorySubjectSchema,
});
export type RepeatOrderPreparationRequest = typeof RepeatOrderPreparationRequestSchema.Type;
export const RepeatOrderPreparationResponseSchema = RepeatOrderPreparationResultSchema;

export const RepeatOrderPreparationAuthenticationProblemSchema = makeProblemDetailsSchema(
  'RepeatOrderPreparationAuthenticationProblem',
  401,
);
export const RepeatOrderPreparationInvalidProblemSchema = makeProblemDetailsSchema(
  'RepeatOrderPreparationInvalidProblem',
  400,
);
export const RepeatOrderPreparationUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'RepeatOrderPreparationUnavailableProblem',
  503,
);
export const RepeatOrderPreparationForbiddenProblemSchema = makeProblemDetailsSchema(
  'RepeatOrderPreparationForbiddenProblem',
  403,
);
export const RepeatOrderPreparationNotFoundProblemSchema = makeProblemDetailsSchema(
  'RepeatOrderPreparationNotFoundProblem',
  404,
);
export const RepeatOrderPreparationPolicyProblemSchema = makeProblemDetailsSchema(
  'RepeatOrderPreparationPolicyProblem',
  422,
);
export const RepeatOrderPreparationPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'RepeatOrderPreparationPolicyConflictProblem',
  409,
);
export const RepeatOrderPreparationInternalProblemSchema = makeProblemDetailsSchema(
  'RepeatOrderPreparationInternalProblem',
  500,
);

export const RepeatOrderPreparationApi = HttpApi.make('RepeatOrderPreparationApi').add(
  HttpApiGroup.make('repeatOrderPreparation').add(
    HttpApiEndpoint.post('execute', '/reads/repeat-order-preparation', {
      error: [
        RepeatOrderPreparationInvalidProblemSchema,
        RepeatOrderPreparationAuthenticationProblemSchema,
        RepeatOrderPreparationForbiddenProblemSchema,
        RepeatOrderPreparationNotFoundProblemSchema,
        RepeatOrderPreparationPolicyConflictProblemSchema,
        RepeatOrderPreparationPolicyProblemSchema,
        RepeatOrderPreparationUnavailableProblemSchema,
        RepeatOrderPreparationInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: RepeatOrderPreparationRequestSchema,
      query: {},
      success: RepeatOrderPreparationResponseSchema,
    }),
  ),
);
