// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.customer-context
// @ontos-action-http-slug revoke-retail-portal-profile-binding
import {
  makeProblemDetailsSchema,
  makeRetryableProblemDetailsSchema,
} from '@app/shared-contracts/problem-details';
import {
  HttpApi,
  HttpApiEndpoint,
  HttpApiGroup,
  Schema,
} from '@modern-js/plugin-bff/effect-client';
import { HttpApiMiddleware } from 'effect/unstable/httpapi';
import {
  RevokeRetailPortalProfileBindingPayloadSchema,
  RevokeRetailPortalProfileBindingResultSchema,
} from '../actions/revoke-retail-portal-profile-binding.ts';

export {
  RevokeRetailPortalProfileBindingPayloadSchema,
  RevokeRetailPortalProfileBindingResultSchema,
} from '../actions/revoke-retail-portal-profile-binding.ts';
export type {
  RevokeRetailPortalProfileBindingPayload,
  RevokeRetailPortalProfileBindingResult,
} from '../actions/revoke-retail-portal-profile-binding.ts';

export const RevokeRetailPortalProfileBindingActionHeadersSchema = Schema.Struct({
  'idempotency-key': Schema.optionalKey(
    Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(200)),
  ),
});

export const RevokeRetailPortalProfileBindingActionInvalidProblemSchema = makeProblemDetailsSchema(
  'RevokeRetailPortalProfileBindingActionInvalidProblem',
  400,
);
export const RevokeRetailPortalProfileBindingActionAuthenticationProblemSchema =
  makeProblemDetailsSchema('RevokeRetailPortalProfileBindingActionAuthenticationProblem', 401);
export const RevokeRetailPortalProfileBindingActionForbiddenProblemSchema =
  makeProblemDetailsSchema('RevokeRetailPortalProfileBindingActionForbiddenProblem', 403, {
    code: Schema.Literals([
      'action_permission_denied',
      'module_state_denied',
      'operation_context_denied',
      'operation_context_invalid',
    ]),
  });
export const RevokeRetailPortalProfileBindingActionNotFoundProblemSchema = makeProblemDetailsSchema(
  'RevokeRetailPortalProfileBindingActionNotFoundProblem',
  404,
  {
    code: Schema.Literals([
      'action_invocation_not_found',
      'BINDING_NOT_FOUND',
      'PROFILE_NOT_FOUND',
    ]),
  },
);
export const RevokeRetailPortalProfileBindingActionConflictProblemSchema = makeProblemDetailsSchema(
  'RevokeRetailPortalProfileBindingActionConflictProblem',
  409,
  {
    code: Schema.Literals([
      'action_request_hash_conflict',
      'action_invocation_state_invalid',
      'BINDING_CONFLICT',
      'CURRENT_STATE_CONFLICT',
    ]),
  },
);
export const RevokeRetailPortalProfileBindingActionIneligibleProblemSchema =
  makeProblemDetailsSchema('RevokeRetailPortalProfileBindingActionIneligibleProblem', 422, {
    code: Schema.Literals([
      'action_policy_denied',
      'BINDING_AMBIGUOUS',
      'ENROLLMENT_EVIDENCE_INSUFFICIENT',
      'PROFILE_NOT_ACTIVE',
    ]),
  });
export const RevokeRetailPortalProfileBindingActionPreconditionProblemSchema =
  makeProblemDetailsSchema('RevokeRetailPortalProfileBindingActionPreconditionProblem', 428);
export const RevokeRetailPortalProfileBindingActionUnavailableProblemSchema =
  makeRetryableProblemDetailsSchema(
    'RevokeRetailPortalProfileBindingActionUnavailableProblem',
    503,
    {
      code: Schema.Literals([
        'action_invocation_persistence_failed',
        'action_permission_check_failed',
        'action_policy_evaluation_failed',
        'action_transaction_failed',
        'module_state_check_unavailable',
        'operation_context_unavailable',
        'DEPENDENCY_UNAVAILABLE',
        'OUTCOME_INDETERMINATE',
        'PERSISTENCE_UNAVAILABLE',
      ]),
    },
  );
export const RevokeRetailPortalProfileBindingActionAlreadyCommittedProblemSchema =
  makeProblemDetailsSchema('RevokeRetailPortalProfileBindingActionAlreadyCommittedProblem', 409, {
    code: Schema.Literal('action_already_committed'),
    invocationId: Schema.String,
    resolution: Schema.Literal('REFRESH_GOVERNED_READS'),
    retryCommand: Schema.Literal(false),
  });
export const RevokeRetailPortalProfileBindingActionCommitIndeterminateProblemSchema =
  makeProblemDetailsSchema(
    'RevokeRetailPortalProfileBindingActionCommitIndeterminateProblem',
    503,
    {
      invocationId: Schema.String,
      resolution: Schema.Literal('RESOLVE_COMMIT'),
      retryCommand: Schema.Literal(false),
    },
  );
export const RevokeRetailPortalProfileBindingActionInternalProblemSchema = makeProblemDetailsSchema(
  'RevokeRetailPortalProfileBindingActionInternalProblem',
  500,
);

export type RevokeRetailPortalProfileBindingActionProblem =
  | typeof RevokeRetailPortalProfileBindingActionInvalidProblemSchema.Type
  | typeof RevokeRetailPortalProfileBindingActionAuthenticationProblemSchema.Type
  | typeof RevokeRetailPortalProfileBindingActionForbiddenProblemSchema.Type
  | typeof RevokeRetailPortalProfileBindingActionNotFoundProblemSchema.Type
  | typeof RevokeRetailPortalProfileBindingActionConflictProblemSchema.Type
  | typeof RevokeRetailPortalProfileBindingActionIneligibleProblemSchema.Type
  | typeof RevokeRetailPortalProfileBindingActionPreconditionProblemSchema.Type
  | typeof RevokeRetailPortalProfileBindingActionUnavailableProblemSchema.Type
  | typeof RevokeRetailPortalProfileBindingActionAlreadyCommittedProblemSchema.Type
  | typeof RevokeRetailPortalProfileBindingActionCommitIndeterminateProblemSchema.Type
  | typeof RevokeRetailPortalProfileBindingActionInternalProblemSchema.Type;

export class RevokeRetailPortalProfileBindingActionSchemaErrorMiddleware extends HttpApiMiddleware.Service<RevokeRetailPortalProfileBindingActionSchemaErrorMiddleware>()(
  'commerce-customer-context/RevokeRetailPortalProfileBindingActionSchemaErrorMiddleware',
  { error: RevokeRetailPortalProfileBindingActionInvalidProblemSchema },
) {}

const actionErrors = [
  RevokeRetailPortalProfileBindingActionInvalidProblemSchema,
  RevokeRetailPortalProfileBindingActionAuthenticationProblemSchema,
  RevokeRetailPortalProfileBindingActionForbiddenProblemSchema,
  RevokeRetailPortalProfileBindingActionNotFoundProblemSchema,
  RevokeRetailPortalProfileBindingActionConflictProblemSchema,
  RevokeRetailPortalProfileBindingActionIneligibleProblemSchema,
  RevokeRetailPortalProfileBindingActionPreconditionProblemSchema,
  RevokeRetailPortalProfileBindingActionUnavailableProblemSchema,
  RevokeRetailPortalProfileBindingActionAlreadyCommittedProblemSchema,
  RevokeRetailPortalProfileBindingActionCommitIndeterminateProblemSchema,
  RevokeRetailPortalProfileBindingActionInternalProblemSchema,
] as const;

export const RevokeRetailPortalProfileBindingActionApi = HttpApi.make(
  'RevokeRetailPortalProfileBindingActionApi',
).add(
  HttpApiGroup.make('revokeRetailPortalProfileBindingAction')
    .add(
      HttpApiEndpoint.post(
        'execute',
        '/commerce-customer-context/actions/revoke-retail-portal-profile-binding',
        {
          error: actionErrors,
          headers: RevokeRetailPortalProfileBindingActionHeadersSchema,
          payload: Schema.toEncoded(RevokeRetailPortalProfileBindingPayloadSchema),
          success: RevokeRetailPortalProfileBindingResultSchema,
        },
      ),
    )
    .middleware(RevokeRetailPortalProfileBindingActionSchemaErrorMiddleware),
);
