// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner privacy.core
// @ontos-action-http-slug record-retention-exception
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  RecordRetentionExceptionActionApi,
  RecordRetentionExceptionPayloadSchema,
} from '../../shared/apis/record-retention-exception-action.ts';
import type { RecordRetentionExceptionPayload } from '../../shared/actions/record-retention-exception.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface RecordRetentionExceptionActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: RecordRetentionExceptionActionClientOptions,
];
type OperationInvocation = readonly [requestCorrelation: string, options: RecordRetentionExceptionActionClientOptions];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: RecordRetentionExceptionActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    { api: RecordRetentionExceptionActionApi, credential, defaultApiPrefix: '/privacy-api', requestCorrelation },
    options,
  );

export const executeRecordRetentionExceptionWithAuthorization = (
  payload: RecordRetentionExceptionPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(RecordRetentionExceptionPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.recordRetentionExceptionAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeRecordRetentionException = (
  payload: RecordRetentionExceptionPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) => executeRecordRetentionExceptionWithAuthorization(payload, credential, requestCorrelation, options),
    options.gateway,
  );
