// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner privacy.core
// @ontos-action-http-slug transition-processing-activity
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  TransitionProcessingActivityActionApi,
  TransitionProcessingActivityPayloadSchema,
} from '../../shared/apis/transition-processing-activity-action.ts';
import type { TransitionProcessingActivityPayload } from '../../shared/actions/transition-processing-activity.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface TransitionProcessingActivityActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: TransitionProcessingActivityActionClientOptions,
];
type OperationInvocation = readonly [
  requestCorrelation: string,
  options: TransitionProcessingActivityActionClientOptions,
];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: TransitionProcessingActivityActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    { api: TransitionProcessingActivityActionApi, credential, defaultApiPrefix: '/privacy-api', requestCorrelation },
    options,
  );

export const executeTransitionProcessingActivityWithAuthorization = (
  payload: TransitionProcessingActivityPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(TransitionProcessingActivityPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.transitionProcessingActivityAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeTransitionProcessingActivity = (
  payload: TransitionProcessingActivityPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) =>
      executeTransitionProcessingActivityWithAuthorization(payload, credential, requestCorrelation, options),
    options.gateway,
  );
