// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner payment.term-catalog
// @ontos-action-http-slug retire-payment-term
import {
  makeProblemDetailsSchema,
  makeRetryableProblemDetailsSchema,
} from '@app/shared-contracts/problem-details';
import {
  HttpApi,
  HttpApiEndpoint,
  HttpApiGroup,
  Schema,
} from '@modern-js/plugin-bff/effect-client';
import { HttpApiMiddleware } from 'effect/unstable/httpapi';
import {
  RetirePaymentTermPayloadSchema,
  RetirePaymentTermResultSchema,
} from '../actions/retire-payment-term.ts';

export {
  RetirePaymentTermPayloadSchema,
  RetirePaymentTermResultSchema,
} from '../actions/retire-payment-term.ts';
export type {
  RetirePaymentTermPayload,
  RetirePaymentTermResult,
} from '../actions/retire-payment-term.ts';

export const RetirePaymentTermActionHeadersSchema = Schema.Struct({
  'idempotency-key': Schema.optionalKey(
    Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(200)),
  ),
});

export const RetirePaymentTermActionInvalidProblemSchema = makeProblemDetailsSchema(
  'RetirePaymentTermActionInvalidProblem',
  400,
);
export const RetirePaymentTermActionAuthenticationProblemSchema = makeProblemDetailsSchema(
  'RetirePaymentTermActionAuthenticationProblem',
  401,
);
export const RetirePaymentTermActionForbiddenProblemSchema = makeProblemDetailsSchema(
  'RetirePaymentTermActionForbiddenProblem',
  403,
  {
    code: Schema.Literals([
      'action_permission_denied',
      'module_state_denied',
      'operation_context_denied',
      'operation_context_invalid',
    ]),
  },
);
export const RetirePaymentTermActionNotFoundProblemSchema = makeProblemDetailsSchema(
  'RetirePaymentTermActionNotFoundProblem',
  404,
  { code: Schema.Literals(['action_invocation_not_found', 'payment_term_not_found']) },
);
export const RetirePaymentTermActionConflictProblemSchema = makeProblemDetailsSchema(
  'RetirePaymentTermActionConflictProblem',
  409,
  {
    code: Schema.Literals([
      'action_request_hash_conflict',
      'action_invocation_state_invalid',
      'payment_term_in_use',
      'payment_term_lifecycle_conflict',
      'payment_term_revision_conflict',
    ]),
  },
);
export const RetirePaymentTermActionIneligibleProblemSchema = makeProblemDetailsSchema(
  'RetirePaymentTermActionIneligibleProblem',
  422,
  {
    code: Schema.Literals([
      'action_policy_denied',
      'payment_term_affected_use_assessment_rejected',
      'payment_term_retirement_reservation_rejected',
    ]),
  },
);
export const RetirePaymentTermActionPreconditionProblemSchema = makeProblemDetailsSchema(
  'RetirePaymentTermActionPreconditionProblem',
  428,
);
export const RetirePaymentTermActionUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'RetirePaymentTermActionUnavailableProblem',
  503,
  {
    code: Schema.Literals([
      'action_invocation_persistence_failed',
      'action_permission_check_failed',
      'action_policy_evaluation_failed',
      'action_transaction_failed',
      'module_state_check_unavailable',
      'operation_context_unavailable',
      'payment_term_affected_use_assessment_unavailable',
      'payment_term_catalog_persistence_conflict',
      'payment_term_catalog_persistence_unavailable',
      'payment_term_retirement_reservation_unavailable',
    ]),
  },
);
export const RetirePaymentTermActionAlreadyCommittedProblemSchema = makeProblemDetailsSchema(
  'RetirePaymentTermActionAlreadyCommittedProblem',
  409,
  {
    code: Schema.Literal('action_already_committed'),
    invocationId: Schema.String,
    resolution: Schema.Literal('REFRESH_GOVERNED_READS'),
    retryCommand: Schema.Literal(false),
  },
);
export const RetirePaymentTermActionCommitIndeterminateProblemSchema = makeProblemDetailsSchema(
  'RetirePaymentTermActionCommitIndeterminateProblem',
  503,
  {
    invocationId: Schema.String,
    resolution: Schema.Literal('RESOLVE_COMMIT'),
    retryCommand: Schema.Literal(false),
  },
);
export const RetirePaymentTermActionInternalProblemSchema = makeProblemDetailsSchema(
  'RetirePaymentTermActionInternalProblem',
  500,
);

export type RetirePaymentTermActionProblem =
  | typeof RetirePaymentTermActionInvalidProblemSchema.Type
  | typeof RetirePaymentTermActionAuthenticationProblemSchema.Type
  | typeof RetirePaymentTermActionForbiddenProblemSchema.Type
  | typeof RetirePaymentTermActionNotFoundProblemSchema.Type
  | typeof RetirePaymentTermActionConflictProblemSchema.Type
  | typeof RetirePaymentTermActionIneligibleProblemSchema.Type
  | typeof RetirePaymentTermActionPreconditionProblemSchema.Type
  | typeof RetirePaymentTermActionUnavailableProblemSchema.Type
  | typeof RetirePaymentTermActionAlreadyCommittedProblemSchema.Type
  | typeof RetirePaymentTermActionCommitIndeterminateProblemSchema.Type
  | typeof RetirePaymentTermActionInternalProblemSchema.Type;

export class RetirePaymentTermActionSchemaErrorMiddleware extends HttpApiMiddleware.Service<RetirePaymentTermActionSchemaErrorMiddleware>()(
  'payment-term-catalog/RetirePaymentTermActionSchemaErrorMiddleware',
  { error: RetirePaymentTermActionInvalidProblemSchema },
) {}

const actionErrors = [
  RetirePaymentTermActionInvalidProblemSchema,
  RetirePaymentTermActionAuthenticationProblemSchema,
  RetirePaymentTermActionForbiddenProblemSchema,
  RetirePaymentTermActionNotFoundProblemSchema,
  RetirePaymentTermActionConflictProblemSchema,
  RetirePaymentTermActionIneligibleProblemSchema,
  RetirePaymentTermActionPreconditionProblemSchema,
  RetirePaymentTermActionUnavailableProblemSchema,
  RetirePaymentTermActionAlreadyCommittedProblemSchema,
  RetirePaymentTermActionCommitIndeterminateProblemSchema,
  RetirePaymentTermActionInternalProblemSchema,
] as const;

export const RetirePaymentTermActionApi = HttpApi.make('RetirePaymentTermActionApi').add(
  HttpApiGroup.make('retirePaymentTermAction')
    .add(
      HttpApiEndpoint.post('execute', '/payment-term-catalog/actions/retire-payment-term', {
        error: actionErrors,
        headers: RetirePaymentTermActionHeadersSchema,
        payload: Schema.toEncoded(RetirePaymentTermPayloadSchema),
        success: RetirePaymentTermResultSchema,
      }),
    )
    .middleware(RetirePaymentTermActionSchemaErrorMiddleware),
);
