// @generated by scaffold:outbox-worker worker-host
// @ontos-outbox-worker-host-owner commerce.inventory
import { DateTime, Effect, Layer } from 'effect';
import type { OutboxRuntime } from '@app/core-runtime';
import type { OutboxWorkerLegalEntityScope, OutboxWorkerLegalEntityScopeFanout } from '@app/core-runtime/outbox/worker';
import {
  OutboxWorkerInfrastructureLive,
  OutboxWorkerLegalEntityScopeFanoutLive,
} from '@app/core-runtime/outbox/worker';

import { InventoryReservationCreateUnavailable } from '../../shared/domain/inventory-reservation-create.ts';
import { ReservationConfirmationRejected } from '../../shared/domain/reservation-confirmation.ts';
import { finalizeCommitmentProtectionForWorker } from '../persistence/commitment-protection-repository.ts';
import { inventoryEffectLedgerPersistenceForWorkerScope } from '../persistence/inventory-effect-ledger-repository.ts';
import { physicalStockEffectPersistenceForWorkerScope } from '../persistence/physical-stock-effect-repository.ts';
import { reservationConfirmationPersistenceForWorkerScope } from '../persistence/reservation-confirmation-repository.ts';
import { reservationShortageImpactPersistenceForWorkerScope } from '../persistence/reservation-shortage-impact-repository.ts';
import { reservationCreateEffectPersistenceForWorkerScope } from '../persistence/reservation-create-effect-repository.ts';
import { reservationReleaseEffectPersistenceForWorkerScope } from '../persistence/reservation-release-effect-repository.ts';
import { InventoryBackendEffects } from '../services/inventory-backend-effects.service.ts';
/* oxlint-disable anti-slop-effect/no-service-constructor-imports -- This owner composition layer binds tested constructors to their Context services; expires: 2027-03-31. */
import { CommitmentProtectionAuthorityPort } from '../services/commitment-protection-authority.ts';
import { makeCommitmentProtectionEstablishmentExecutionService } from '../services/commitment-protection.service.ts';
import { makeInventoryEffectLedgerService } from '../services/inventory-effect-ledger.service.ts';
import { InventoryEffectRecoveryAuthorityPort } from '../services/inventory-effect-recovery-authority.ts';
import {
  InventoryReservationCreateBackendPort,
  InventoryReservationCreateBackendUnavailableLive,
  makeInventoryReservationCreateExecutionService,
} from '../services/inventory-reservation-create.service.ts';
import {
  InventoryReservationReleaseBackendPort,
  InventoryReservationReleaseBackendUnavailableLive,
  makeInventoryReservationReleaseExecutionService,
  ReservationReleaseOrderTruth,
  ReservationReleaseProtectionTruth,
  reservationReleaseUnavailable,
} from '../services/inventory-reservation-release.service.ts';
import { PhysicalStockEffects, makePhysicalStockEffectsService } from '../services/physical-stock-effects.service.ts';
import { makeReservationIssuerService } from '../services/reservation-issuer.service.ts';
import { makeReservationConfirmationService } from '../services/reservation-confirmation.service.ts';
import { makeReservationShortageImpactService } from '../services/reservation-shortage-impact.service.ts';
import { CommitmentProtectionEstablishmentExecution } from '../workers/execute-commitment-protection-establishment.worker.ts';
import { InventoryReservationCreateExecution } from '../workers/execute-inventory-reservation-create.worker.ts';
import { InventoryReservationReleaseExecution } from '../workers/execute-inventory-reservation-release.worker.ts';
import { ReservationConfirmationIssuanceExecution } from '../workers/execute-reservation-confirmation-issuance.worker.ts';
/* oxlint-enable anti-slop-effect/no-service-constructor-imports */

export { CorePersistenceLive as outboxWorkerCorePersistenceLive } from '@app/core-runtime/outbox/worker';
export { DatabaseConfigLive as outboxWorkerDatabaseConfigLive } from '@app/core-runtime/outbox/worker';
export { OutboxRepositoryLive as outboxWorkerRepositoryLive } from '@app/core-runtime/outbox/worker';

/** Add owner-local repositories and services required by worker handlers here. */
const physicalStockEffectsLive = Layer.effect(
  PhysicalStockEffects,
  Effect.gen(function* makePhysicalStockEffectsLive() {
    const backend = yield* InventoryBackendEffects;
    return {
      execute: (scope, request) =>
        makePhysicalStockEffectsService(
          physicalStockEffectPersistenceForWorkerScope(scope),
          backend,
          makeReservationShortageImpactService({
            persistence: reservationShortageImpactPersistenceForWorkerScope(scope),
          }),
          makeInventoryEffectLedgerService(
            inventoryEffectLedgerPersistenceForWorkerScope(scope),
            DateTime.now.pipe(Effect.map(DateTime.formatIso)),
          ),
        ).execute(scope, request),
    };
  }),
);

/* oxlint-disable effect-native/no-refinement-outside-schema -- The service contract intentionally exposes identity-only scope while this worker-only composition verifies its non-data capabilities before binding persistence; expires: 2027-03-31. */
const isLegalEntityWorkerScope = (scope: {
  readonly legalEntityId: string;
  readonly tenantId: string;
}): scope is OutboxWorkerLegalEntityScope => 'completionPublisher' in scope && 'routineInvoker' in scope;
/* oxlint-enable effect-native/no-refinement-outside-schema */

const inventoryReservationCreateExecutionLive = Layer.effect(
  InventoryReservationCreateExecution,
  Effect.gen(function* makeInventoryReservationCreateExecutionLive() {
    const backend = yield* InventoryReservationCreateBackendPort;
    return {
      execute: (scope, request) => {
        if (!isLegalEntityWorkerScope(scope)) {
          return Effect.fail(
            new InventoryReservationCreateUnavailable({
              code: 'inventory_reservation_create_unavailable',
              effectId: request.effectId,
              reason: 'Reservation create execution requires a verified Legal Entity worker scope',
              retryable: true,
            }),
          );
        }
        return makeInventoryReservationCreateExecutionService({
          backend,
          effects: reservationCreateEffectPersistenceForWorkerScope(scope),
          ledger: makeInventoryEffectLedgerService(
            inventoryEffectLedgerPersistenceForWorkerScope(scope),
            DateTime.now.pipe(Effect.map(DateTime.formatIso)),
          ),
        }).execute(scope, request);
      },
    };
  }),
).pipe(
  // oxlint-disable-next-line effect-native/no-layer-provide-in-library -- The owner worker host binds its fail-closed backend adapter; deployment adapters replace this layer composition; expires: 2027-03-31.
  Layer.provide(InventoryReservationCreateBackendUnavailableLive),
);

const inventoryReservationReleaseExecutionLive = Layer.effect(
  InventoryReservationReleaseExecution,
  Effect.gen(function* makeInventoryReservationReleaseExecutionLive() {
    const backend = yield* InventoryReservationReleaseBackendPort;
    const orderTruth = yield* ReservationReleaseOrderTruth;
    const protectionTruth = yield* ReservationReleaseProtectionTruth;
    return {
      execute: (scope, request) => {
        if (!isLegalEntityWorkerScope(scope)) {
          return Effect.fail(
            reservationReleaseUnavailable(
              request.effectId,
              'Reservation Release execution requires a verified Legal Entity worker scope',
            ),
          );
        }
        return makeInventoryReservationReleaseExecutionService({
          backend,
          effects: reservationReleaseEffectPersistenceForWorkerScope(scope),
          ledger: makeInventoryEffectLedgerService(
            inventoryEffectLedgerPersistenceForWorkerScope(scope),
            DateTime.now.pipe(Effect.map(DateTime.formatIso)),
          ),
          orderTruth,
          protectionTruth,
        }).execute(scope, request);
      },
    };
  }),
).pipe(
  // oxlint-disable-next-line effect-native/no-layer-provide-in-library -- Fail-closed owner defaults are replaced by deployment proof/backend adapters; expires: 2027-03-31.
  Layer.provide(InventoryReservationReleaseBackendUnavailableLive),
);

const reservationConfirmationIssuanceExecutionLive = Layer.effect(
  ReservationConfirmationIssuanceExecution,
  Effect.gen(function* makeReservationConfirmationIssuanceExecutionLive() {
    const authority = yield* CommitmentProtectionAuthorityPort;
    const issuer = makeReservationIssuerService({
      issue: (command) => authority.establish(command),
    });
    return {
      execute: (scope, input) => {
        if (!isLegalEntityWorkerScope(scope)) {
          return Effect.fail(
            new ReservationConfirmationRejected({
              code: 'reservation_confirmation_rejected',
              confirmationRef: input.confirmationRef,
              reason: 'TENANT_SCOPE_MISMATCH',
            }),
          );
        }
        return makeReservationConfirmationService({
          issuer,
          persistence: reservationConfirmationPersistenceForWorkerScope(scope),
        }).issue(input);
      },
    };
  }),
);

const commitmentProtectionEstablishmentExecutionLive = Layer.effect(
  CommitmentProtectionEstablishmentExecution,
  Effect.gen(function* makeCommitmentProtectionEstablishmentExecutionLive() {
    const authority = yield* CommitmentProtectionAuthorityPort;
    const recoveryAuthority = yield* InventoryEffectRecoveryAuthorityPort;
    return makeCommitmentProtectionEstablishmentExecutionService({
      authority,
      confirmations: reservationConfirmationPersistenceForWorkerScope,
      finalizer: finalizeCommitmentProtectionForWorker,
      ledger: (scope) =>
        makeInventoryEffectLedgerService(
          inventoryEffectLedgerPersistenceForWorkerScope(scope),
          DateTime.now.pipe(Effect.map(DateTime.formatIso)),
        ),
      recoveryAuthority,
    });
  }),
);

type InventoryOutboxWorkerServices =
  | CommitmentProtectionEstablishmentExecution
  | InventoryReservationCreateExecution
  | InventoryReservationReleaseExecution
  | OutboxRuntime
  | OutboxWorkerLegalEntityScopeFanout
  | PhysicalStockEffects
  | ReservationConfirmationIssuanceExecution;

export const outboxWorkerLayer: Layer.Layer<
  InventoryOutboxWorkerServices,
  Layer.Error<typeof OutboxWorkerInfrastructureLive>,
  | Layer.Services<typeof OutboxWorkerInfrastructureLive>
  | Layer.Services<typeof OutboxWorkerLegalEntityScopeFanoutLive>
  | InventoryBackendEffects
> = Layer.mergeAll(
  OutboxWorkerInfrastructureLive,
  OutboxWorkerLegalEntityScopeFanoutLive,
  commitmentProtectionEstablishmentExecutionLive,
  inventoryReservationCreateExecutionLive,
  inventoryReservationReleaseExecutionLive,
  physicalStockEffectsLive,
  reservationConfirmationIssuanceExecutionLive,
);
