// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.assortment
// @ontos-action-http-slug replace-applicability-binding
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  ReplaceApplicabilityBindingActionApi,
  ReplaceApplicabilityBindingPayloadSchema,
} from '../../shared/apis/replace-applicability-binding-action.ts';
import type { ReplaceApplicabilityBindingPayload } from '../../shared/actions/replace-applicability-binding.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface ReplaceApplicabilityBindingActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly compositionRevision?: string;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: ReplaceApplicabilityBindingActionClientOptions,
];
type OperationInvocation = readonly [
  requestCorrelation: string,
  options: ReplaceApplicabilityBindingActionClientOptions,
];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: ReplaceApplicabilityBindingActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    { api: ReplaceApplicabilityBindingActionApi, credential, defaultApiPrefix: '/assortment-api', requestCorrelation },
    options,
  );

export const executeReplaceApplicabilityBindingWithAuthorization = (
  payload: ReplaceApplicabilityBindingPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(ReplaceApplicabilityBindingPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.replaceApplicabilityBindingAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeReplaceApplicabilityBinding = (
  payload: ReplaceApplicabilityBindingPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential, { apiBaseUrl, compositionRevision }) =>
      executeReplaceApplicabilityBindingWithAuthorization(payload, credential, requestCorrelation, {
        ...options,
        baseUrl: apiBaseUrl,
        compositionRevision,
      }),
    options.gateway,
  );
