// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.assortment
// @ontos-action-http-slug retire-rule
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import { RetireRuleActionApi, RetireRulePayloadSchema } from '../../shared/apis/retire-rule-action.ts';
import type { RetireRulePayload } from '../../shared/actions/retire-rule.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface RetireRuleActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly compositionRevision?: string;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: RetireRuleActionClientOptions,
];
type OperationInvocation = readonly [requestCorrelation: string, options: RetireRuleActionClientOptions];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: RetireRuleActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    { api: RetireRuleActionApi, credential, defaultApiPrefix: '/assortment-api', requestCorrelation },
    options,
  );

export const executeRetireRuleWithAuthorization = (
  payload: RetireRulePayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(RetireRulePayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.retireRuleAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeRetireRule = (payload: RetireRulePayload, ...[requestCorrelation, options]: OperationInvocation) =>
  operationGateway.invoke(
    (credential, { apiBaseUrl, compositionRevision }) =>
      executeRetireRuleWithAuthorization(payload, credential, requestCorrelation, {
        ...options,
        baseUrl: apiBaseUrl,
        compositionRevision,
      }),
    options.gateway,
  );
