// @generated by OntOS Codesmith Governed Contribution v1
// @ontos-contribution-kind search-provider
import { DateTime, Effect } from 'effect';
import {
  OperationContextUnavailable,
  ReadHandlerUnavailable,
  defineRead,
  defineTenantModuleEntrypoint,
} from '@app/core-runtime';
import type { ReadHandlerContext } from '@app/core-runtime';
import {
  CounterpartiesProviderRequestSchema,
  CounterpartiesProviderResponseSchema,
} from '../../shared/apis/counterparties-search.ts';
import type {
  CounterpartiesProviderRequest,
  CounterpartiesProviderResponse,
} from '../../shared/apis/counterparties-search.ts';
import { PartySearchProjectionGateway } from '../../shared/domain/search-projection-gateway.ts';
import type { PartySearchProjectionGatewayService } from '../../shared/domain/search-projection-gateway.ts';
import { PartySearchProjectionUnavailable } from '../../shared/domain/search-projection-error.ts';
import { normalizeCounterpartySearchHits } from '../../shared/domain/search-semantics.ts';

export const counterpartiesEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  entrypointKey: 'party.registry.search.counterparties',
  moduleKey: 'party.registry',
  role: 'search',
});

interface CounterpartiesSearchServices {
  readonly load: (
    input: CounterpartiesProviderRequest,
  ) => Effect.Effect<CounterpartiesProviderResponse, PartySearchProjectionUnavailable>;
}

export const loadCounterpartySearch = (
  gateway: PartySearchProjectionGatewayService,
  scope: Readonly<{ readonly legalEntityId: string; readonly tenantId: string }>,
  input: CounterpartiesProviderRequest,
  effectiveAt: string,
) =>
  gateway
    .searchCounterparties(
      input.role === undefined
        ? {
            effectiveAt,
            includeArchived: input.includeArchived ?? false,
            legalEntityId: scope.legalEntityId,
            query: input.query,
            tenantId: scope.tenantId,
          }
        : {
            effectiveAt,
            includeArchived: input.includeArchived ?? false,
            legalEntityId: scope.legalEntityId,
            query: input.query,
            role: input.role,
            tenantId: scope.tenantId,
          },
    )
    .pipe(
      Effect.flatMap((hits) => {
        const normalized = normalizeCounterpartySearchHits(
          input.role === undefined
            ? {
                effectiveAt,
                includeArchived: input.includeArchived ?? false,
                legalEntityId: scope.legalEntityId,
                tenantId: scope.tenantId,
              }
            : {
                effectiveAt,
                includeArchived: input.includeArchived ?? false,
                legalEntityId: scope.legalEntityId,
                role: input.role,
                tenantId: scope.tenantId,
              },
          hits,
        );
        return normalized._tag === 'SearchResults'
          ? Effect.succeed(normalized.items satisfies CounterpartiesProviderResponse)
          : Effect.fail(
              new PartySearchProjectionUnavailable({
                code: 'party_search_projection_unavailable',
                reason: normalized.reason,
              }),
            );
      }),
    );

export const counterpartiesRead = defineRead(
  {
    accessKind: 'search',
    entrypoint: counterpartiesEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'party.registry.search.counterparties.evidence.v1',
    },
    inputSchema: CounterpartiesProviderRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: 'party.registry',
    permissionTarget: 'legal_entity',
    policies: [],
    readKey: 'party.registry.search.counterparties',
    resultSchema: CounterpartiesProviderResponseSchema,
    schemaVersion: '1',
  },
  (input, context: ReadHandlerContext<CounterpartiesSearchServices>) =>
    context.services.load(input).pipe(
      Effect.mapError(
        () =>
          new ReadHandlerUnavailable({
            code: 'read_handler_unavailable',
            reason: 'Counterparty Search projection is temporarily unavailable',
          }),
      ),
      Effect.map((result) => ({
        evidence: { resultCount: result.length },
        result,
      })),
    ),
  (_transaction, scope) =>
    Effect.gen(function* makeCounterpartySearchServices() {
      const gateway = yield* PartySearchProjectionGateway;
      const { legalEntityId } = scope;
      if (legalEntityId === undefined) {
        return yield* new OperationContextUnavailable({
          code: 'operation_context_unavailable',
          reason: 'Counterparty Search requires trusted Legal Entity context',
        });
      }
      return {
        load: (input: CounterpartiesProviderRequest) =>
          DateTime.now.pipe(
            Effect.map(DateTime.formatIso),
            Effect.flatMap((effectiveAt) =>
              loadCounterpartySearch(
                gateway,
                { legalEntityId, tenantId: scope.tenantId },
                input,
                effectiveAt,
              ),
            ),
          ),
      };
    }),
  () => ({ kind: 'legal_entity', permission: 'read_counterparty' }),
  (result) => result.map(({ ref }) => ref),
);
