// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner payment.term-catalog
// @ontos-action-http-slug reconcile-payment-term-reference
// oxlint-disable sonarjs/function-name -- Effect Match.tags requires owner-declared tag keys; remove-when: sonarjs accepts discriminant-map properties.
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  ReconcilePaymentTermReferenceActionAlreadyCommittedProblemSchema,
  ReconcilePaymentTermReferenceActionAuthenticationProblemSchema,
  ReconcilePaymentTermReferenceActionCommitIndeterminateProblemSchema,
  ReconcilePaymentTermReferenceActionConflictProblemSchema,
  ReconcilePaymentTermReferenceActionForbiddenProblemSchema,
  ReconcilePaymentTermReferenceActionIneligibleProblemSchema,
  ReconcilePaymentTermReferenceActionInternalProblemSchema,
  ReconcilePaymentTermReferenceActionInvalidProblemSchema,
  ReconcilePaymentTermReferenceActionNotFoundProblemSchema,
  ReconcilePaymentTermReferenceActionPreconditionProblemSchema,
  ReconcilePaymentTermReferenceActionSchemaErrorMiddleware,
  ReconcilePaymentTermReferenceActionUnavailableProblemSchema,
} from '../shared/apis/reconcile-payment-term-reference-action.ts';
import type { ReconcilePaymentTermReferenceActionProblem } from '../shared/apis/reconcile-payment-term-reference-action.ts';
import { reconcilePaymentTermReferenceAction } from '../src/actions/reconcile-payment-term-reference.action.ts';

type DomainError = typeof reconcilePaymentTermReferenceAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends ReconcilePaymentTermReferenceActionProblem['_tag']> = Extract<
  ReconcilePaymentTermReferenceActionProblem,
  { readonly _tag: Tag }
>;

const problemStatus = {
  authentication: 401,
  conflict: 409,
  forbidden: 403,
  ineligible: 422,
  internal: 500,
  invalid: 400,
  notFound: 404,
  precondition: 428,
  rateLimited: 429,
  timeout: 504,
  unavailable: 503,
} as const;

export const reconcilePaymentTermReferenceActionProblem = {
  authentication: (): ProblemOf<'ReconcilePaymentTermReferenceActionAuthenticationProblem'> =>
    ReconcilePaymentTermReferenceActionAuthenticationProblemSchema.make({
      detail: 'A valid audience-scoped Bearer assertion is required.',
      status: problemStatus.authentication,
      title: 'Authentication required',
      type: 'https://ontos.dev/problems/operation-authentication-required',
    }),
  conflict: (
    code: ProblemOf<'ReconcilePaymentTermReferenceActionConflictProblem'>['code'],
  ): ProblemOf<'ReconcilePaymentTermReferenceActionConflictProblem'> =>
    ReconcilePaymentTermReferenceActionConflictProblemSchema.make({
      code,
      detail: 'The Action conflicts with current state.',
      status: problemStatus.conflict,
      title: 'Action conflict',
      type: 'https://ontos.dev/problems/action-conflict',
    }),
  forbidden: (
    code: ProblemOf<'ReconcilePaymentTermReferenceActionForbiddenProblem'>['code'],
  ): ProblemOf<'ReconcilePaymentTermReferenceActionForbiddenProblem'> =>
    ReconcilePaymentTermReferenceActionForbiddenProblemSchema.make({
      code,
      detail: 'The principal is not permitted to perform this Action.',
      status: problemStatus.forbidden,
      title: 'Action forbidden',
      type: 'https://ontos.dev/problems/action-forbidden',
    }),
  ineligible: (
    code: ProblemOf<'ReconcilePaymentTermReferenceActionIneligibleProblem'>['code'],
  ): ProblemOf<'ReconcilePaymentTermReferenceActionIneligibleProblem'> =>
    ReconcilePaymentTermReferenceActionIneligibleProblemSchema.make({
      code,
      detail: 'The request is not eligible for this Action.',
      status: problemStatus.ineligible,
      title: 'Action ineligible',
      type: 'https://ontos.dev/problems/action-ineligible',
    }),
  internal: (): ProblemOf<'ReconcilePaymentTermReferenceActionInternalProblem'> =>
    ReconcilePaymentTermReferenceActionInternalProblemSchema.make({
      detail: 'The Action could not be completed.',
      status: problemStatus.internal,
      title: 'Action failed',
      type: 'https://ontos.dev/problems/action-failed',
    }),
  invalid: (): ProblemOf<'ReconcilePaymentTermReferenceActionInvalidProblem'> =>
    ReconcilePaymentTermReferenceActionInvalidProblemSchema.make({
      detail: 'The reconcile-payment-term-reference Action request is invalid.',
      status: problemStatus.invalid,
      title: 'Invalid Action request',
      type: 'https://ontos.dev/problems/action-invalid',
    }),
  notFound: (
    code: ProblemOf<'ReconcilePaymentTermReferenceActionNotFoundProblem'>['code'],
  ): ProblemOf<'ReconcilePaymentTermReferenceActionNotFoundProblem'> =>
    ReconcilePaymentTermReferenceActionNotFoundProblemSchema.make({
      code,
      detail: 'The requested resource was not found.',
      status: problemStatus.notFound,
      title: 'Resource not found',
      type: 'https://ontos.dev/problems/action-resource-not-found',
    }),
  precondition: (): ProblemOf<'ReconcilePaymentTermReferenceActionPreconditionProblem'> =>
    ReconcilePaymentTermReferenceActionPreconditionProblemSchema.make({
      detail: 'An Idempotency-Key header is required.',
      status: problemStatus.precondition,
      title: 'Idempotency key required',
      type: 'https://ontos.dev/problems/idempotency-key-required',
    }),
  unavailable: (
    code: ProblemOf<'ReconcilePaymentTermReferenceActionUnavailableProblem'>['code'],
  ): ProblemOf<'ReconcilePaymentTermReferenceActionUnavailableProblem'> =>
    ReconcilePaymentTermReferenceActionUnavailableProblemSchema.make({
      code,
      detail: 'The Action capability is temporarily unavailable.',
      retryable: true,
      status: problemStatus.unavailable,
      title: 'Action unavailable',
      type: 'https://ontos.dev/problems/action-unavailable',
    }),
} as const;

const mapDomainProblem = (error: DomainError): ReconcilePaymentTermReferenceActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      PaymentTermCatalogPersistenceConflict: () =>
        reconcilePaymentTermReferenceActionProblem.unavailable('payment_term_catalog_persistence_conflict'),
      PaymentTermCatalogPersistenceUnavailable: () =>
        reconcilePaymentTermReferenceActionProblem.unavailable('payment_term_catalog_persistence_unavailable'),
      PaymentTermNotFound: () => reconcilePaymentTermReferenceActionProblem.notFound('payment_term_not_found'),
      PaymentTermReconciliationConflict: () =>
        reconcilePaymentTermReferenceActionProblem.conflict('payment_term_reconciliation_conflict'),
      PaymentTermRevisionConflict: () =>
        reconcilePaymentTermReferenceActionProblem.conflict('payment_term_revision_conflict'),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): ReconcilePaymentTermReferenceActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        ReconcilePaymentTermReferenceActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: reconcilePaymentTermReferenceActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        ReconcilePaymentTermReferenceActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: reconcilePaymentTermReferenceActionProblem.internal,
      ActionIdempotencyKeyRequired: reconcilePaymentTermReferenceActionProblem.precondition,
      ActionInvocationNotFound: (failure) => reconcilePaymentTermReferenceActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) =>
        reconcilePaymentTermReferenceActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => reconcilePaymentTermReferenceActionProblem.conflict(failure.code),
      ActionPayloadValidationError: reconcilePaymentTermReferenceActionProblem.invalid,
      ActionPermissionCheckError: (failure) => reconcilePaymentTermReferenceActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => reconcilePaymentTermReferenceActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => reconcilePaymentTermReferenceActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => reconcilePaymentTermReferenceActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => reconcilePaymentTermReferenceActionProblem.conflict(failure.code),
      ActionResultValidationError: reconcilePaymentTermReferenceActionProblem.internal,
      ActionTransactionError: (failure) => reconcilePaymentTermReferenceActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: reconcilePaymentTermReferenceActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) =>
        reconcilePaymentTermReferenceActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => reconcilePaymentTermReferenceActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: reconcilePaymentTermReferenceActionProblem.authentication,
      OperationContextDenied: (failure) => reconcilePaymentTermReferenceActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => reconcilePaymentTermReferenceActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => reconcilePaymentTermReferenceActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(reconcilePaymentTermReferenceAction.descriptor.domainErrorSchema);
export const mapReconcilePaymentTermReferenceActionProblem = (
  error: ActionCoreError | DomainError,
): ReconcilePaymentTermReferenceActionProblem =>
  isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error);

export const reconcilePaymentTermReferenceActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  ReconcilePaymentTermReferenceActionSchemaErrorMiddleware,
  () => Effect.fail(reconcilePaymentTermReferenceActionProblem.invalid()),
);
