// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { CurrentStockEvidenceForAvailabilityApi } from '../../shared/apis/current-stock-evidence-for-availability.ts';
import type { CurrentStockEvidenceForAvailabilityRequest } from '../../shared/apis/current-stock-evidence-for-availability.ts';
import { operationGateway } from './action-gateway.ts';

export interface CurrentStockEvidenceForAvailabilityClientOptions {
  readonly baseUrl?: string | URL;
  readonly compositionRevision?: string;
}

type CurrentStockEvidenceForAvailabilityAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: CurrentStockEvidenceForAvailabilityClientOptions,
];

type CurrentStockEvidenceForAvailabilityOperationInvocation = readonly [
  requestCorrelation: string,
  options?: CurrentStockEvidenceForAvailabilityClientOptions,
];

const currentStockEvidenceForAvailabilityClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: CurrentStockEvidenceForAvailabilityClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: CurrentStockEvidenceForAvailabilityApi,
      credential,
      defaultApiPrefix: '/inventory-api',
      requestCorrelation,
    },
    options,
  );

export const executeCurrentStockEvidenceForAvailabilityWithAuthorization = (
  payload: CurrentStockEvidenceForAvailabilityRequest,
  ...[credential, requestCorrelation, options = {}]: CurrentStockEvidenceForAvailabilityAuthorizedInvocation
) =>
  currentStockEvidenceForAvailabilityClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) => client.currentStockEvidenceForAvailability.execute({ payload })),
  );

export const executeCurrentStockEvidenceForAvailability = (
  payload: CurrentStockEvidenceForAvailabilityRequest,
  ...[requestCorrelation, options = {}]: CurrentStockEvidenceForAvailabilityOperationInvocation
) =>
  operationGateway.invoke((credential, { apiBaseUrl, compositionRevision }) =>
    executeCurrentStockEvidenceForAvailabilityWithAuthorization(payload, credential, requestCorrelation, {
      ...options,
      baseUrl: apiBaseUrl,
      compositionRevision,
    }),
  );
