// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.customer-context
// @ontos-action-slug administer-market-bootstrap-policy
/* oxlint-disable effect-native/no-manual-tag-comparison, effect-native/no-unbranded-identifier-schema, eslint/prefer-destructuring -- Generated Action adapter mirrors domain-owned tagged payloads and identifiers; tracked in: #333; remove-when: Codesmith emits shared audit-subject projections. */
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { DateTime, Effect, Schema } from 'effect';
import {
  CustomerCommercePolicyAdministrationRejected,
  CustomerCommercePolicyMutationSummarySchema,
  MarketBootstrapPolicyAdministrationPayloadSchema,
  toTrustedMarketBootstrapPolicyAdministrationCommand,
} from '../../shared/domain/customer-commerce-policy-administration.ts';
import type { MarketBootstrapPolicyAdministrationPayload } from '../../shared/domain/customer-commerce-policy-administration.ts';
import {
  OutboxPayloadSchema as MarketBootstrapPolicyChangedEventSchema,
  outboxProducerModuleKey as MODULE_KEY,
  outboxTopic as EVENT_TYPE,
} from '../../shared/outbox/commerce-customer-context-market-bootstrap-policy-changed.ts';
import { customerCommercePolicyAdministrationServiceFactory } from '../services/customer-commerce-policy-administration.service.ts';
import type { CustomerCommercePolicyAdministrationService } from '../services/customer-commerce-policy-administration.service.ts';
import { createAdministerMarketBootstrapPolicyCommerceCustomerContextMarketBootstrapPolicyChangedOutboxMessage as createOutboxMessage } from './administer-market-bootstrap-policy-commerce-customer-context-market-bootstrap-policy-changed.outbox-message.ts';

const stableReference = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(300), Schema.isTrimmed());
const reason = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(1000), Schema.isTrimmed());
const AdministerMarketBootstrapPolicyPayloadSchema = MarketBootstrapPolicyAdministrationPayloadSchema;
export type AdministerMarketBootstrapPolicyPayload = MarketBootstrapPolicyAdministrationPayload;

const AdministerMarketBootstrapPolicyResultSchema = CustomerCommercePolicyMutationSummarySchema;

const auditEvidenceSchema = Schema.Struct({
  changed: Schema.Boolean,
  field: Schema.Literal('MARKET_BOOTSTRAP'),
  generation: Schema.Int,
  operation: Schema.Literals(['ACTIVATE_REVISION', 'CREATE_REVISION', 'REPLACE_REVISION', 'RETIRE_REVISION']),
  reason,
  revisionId: stableReference,
});
const domainEvents = { [EVENT_TYPE]: MarketBootstrapPolicyChangedEventSchema } as const;

const failScope = (reasonText: string) =>
  new CustomerCommercePolicyAdministrationRejected({
    code: 'SCOPE_MISMATCH',
    reason: reasonText,
    retryable: false,
  });

const observedAt = DateTime.now.pipe(Effect.map((instant) => DateTime.formatIso(instant)));

const handleAdministerMarketBootstrapPolicy = Effect.fn('AdministerMarketBootstrapPolicyAction.handle')(
  function* handle(
    payload: AdministerMarketBootstrapPolicyPayload,
    context: ActionHandlerContext<typeof domainEvents, CustomerCommercePolicyAdministrationService>,
  ) {
    const legalEntityId = context.scope.legalEntityId;
    if (legalEntityId === undefined) {
      return yield* failScope('Market Bootstrap policy administration requires trusted Legal Entity scope');
    }
    const recordedAt = yield* observedAt;
    const trusted = {
      actionInvocationId: context.actionInvocationId,
      actorPrincipalId: context.scope.principalId,
      sellingLegalEntityId: legalEntityId,
      tenantId: context.scope.tenantId,
    } as const;
    let reasonText: string;
    let revisionId: string;
    if (payload._tag === 'CREATE_REVISION' || payload._tag === 'REPLACE_REVISION') {
      const candidate = payload._tag === 'CREATE_REVISION' ? payload.revision : payload.replacement;
      if (candidate.scope.sellingLegalEntityId !== legalEntityId) {
        return yield* failScope('Market Bootstrap policy scope must match the trusted Legal Entity');
      }
      reasonText = candidate.reason;
      revisionId = candidate.revisionId;
    } else {
      reasonText = payload.reason;
      revisionId = payload.revisionId;
    }
    const command = toTrustedMarketBootstrapPolicyAdministrationCommand(payload, trusted, recordedAt);
    const result = yield* context.services.administerMarketBootstrapPolicy(command);
    yield* context.recordAuditEvidence({
      changed: result.changed,
      field: 'MARKET_BOOTSTRAP',
      generation: result.generation,
      operation: payload._tag,
      reason: reasonText,
      revisionId,
    });
    yield* context.recordDataAccess({
      accessKind: 'read',
      queryHash: `customer-commerce-policy:market-bootstrap:${revisionId}:${payload.expectedGeneration}`,
      resultCount: result.revisionIds.length,
      servingModuleKey: MODULE_KEY,
      targetModuleKey: MODULE_KEY,
      targetResourceId: revisionId,
      targetResourceType: `${MODULE_KEY}.market-bootstrap-policy`,
    });
    if (result.changed) {
      const eventPayload = {
        changed: result.changed,
        field: 'MARKET_BOOTSTRAP' as const,
        generation: result.generation,
        revisionIds: result.revisionIds,
      };
      const event = yield* context.addDomainEvent({
        eventType: EVENT_TYPE,
        payloadJson: eventPayload,
        producerModuleKey: MODULE_KEY,
        subjectModuleKey: MODULE_KEY,
        subjectResourceId: revisionId,
        subjectResourceType: `${MODULE_KEY}.market-bootstrap-policy`,
      });
      yield* context.addOutboxMessage(event, createOutboxMessage(eventPayload));
    }
    return result;
  },
);

export const administerMarketBootstrapPolicyAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.customer-context.administer-market-bootstrap-policy.access.v1',
    },
    actionKey: 'commerce.customer-context.administer-market-bootstrap-policy',
    auditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: CustomerCommercePolicyAdministrationRejected,
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.customer-context.administer-market-bootstrap-policy',
      moduleKey: 'commerce.customer-context',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'required',
    owningModuleKey: 'commerce.customer-context',
    payloadSchema: AdministerMarketBootstrapPolicyPayloadSchema,
    policies: [],
    resultSchema: AdministerMarketBootstrapPolicyResultSchema,
    schemaVersion: '1',
  },
  handleAdministerMarketBootstrapPolicy,
  customerCommercePolicyAdministrationServiceFactory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
