// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner privacy.core
// @ontos-action-http-slug consent-self-service
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { HttpApi, HttpApiEndpoint, HttpApiGroup, Schema } from '@modern-js/bff-effect/effect-client';
import { HttpApiMiddleware } from 'effect/unstable/httpapi';
import { ConsentSelfServicePayloadSchema, ConsentSelfServiceResultSchema } from '../actions/consent-self-service.ts';

export { ConsentSelfServicePayloadSchema } from '../actions/consent-self-service.ts';

const ConsentSelfServiceActionHeadersSchema = Schema.Struct({
  'idempotency-key': Schema.optionalKey(Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(200))),
});

export const ConsentSelfServiceActionInvalidProblemSchema = makeProblemDetailsSchema(
  'ConsentSelfServiceActionInvalidProblem',
  400,
);
export const ConsentSelfServiceActionAuthenticationProblemSchema = makeProblemDetailsSchema(
  'ConsentSelfServiceActionAuthenticationProblem',
  401,
);
export const ConsentSelfServiceActionForbiddenProblemSchema = makeProblemDetailsSchema(
  'ConsentSelfServiceActionForbiddenProblem',
  403,
  {
    code: Schema.Literals([
      'action_permission_denied',
      'module_state_denied',
      'operation_context_denied',
      'operation_context_invalid',
    ]),
  },
);
export const ConsentSelfServiceActionNotFoundProblemSchema = makeProblemDetailsSchema(
  'ConsentSelfServiceActionNotFoundProblem',
  404,
  { code: Schema.Literal('action_invocation_not_found') },
);
export const ConsentSelfServiceActionConflictProblemSchema = makeProblemDetailsSchema(
  'ConsentSelfServiceActionConflictProblem',
  409,
  { code: Schema.Literals(['action_request_hash_conflict', 'action_invocation_state_invalid']) },
);
export const ConsentSelfServiceActionIneligibleProblemSchema = makeProblemDetailsSchema(
  'ConsentSelfServiceActionIneligibleProblem',
  422,
  { code: Schema.Literals(['action_policy_denied', 'privacy_action_rejected', 'privacy_action_scope_required']) },
);
export const ConsentSelfServiceActionPreconditionProblemSchema = makeProblemDetailsSchema(
  'ConsentSelfServiceActionPreconditionProblem',
  428,
);
export const ConsentSelfServiceActionUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'ConsentSelfServiceActionUnavailableProblem',
  503,
  {
    code: Schema.Literals([
      'action_invocation_persistence_failed',
      'action_permission_check_failed',
      'action_policy_evaluation_failed',
      'action_transaction_failed',
      'module_state_check_unavailable',
      'operation_context_unavailable',
      'privacy_operation_conflict',
      'privacy_operation_not_found',
      'privacy_operation_persistence_unavailable',
      'privacy_operation_scope_mismatch',
    ]),
  },
);
export const ConsentSelfServiceActionAlreadyCommittedProblemSchema = makeProblemDetailsSchema(
  'ConsentSelfServiceActionAlreadyCommittedProblem',
  409,
  {
    code: Schema.Literal('action_already_committed'),
    invocationId: Schema.String,
    resolution: Schema.Literal('REFRESH_GOVERNED_READS'),
    retryCommand: Schema.Literal(false),
  },
);
export const ConsentSelfServiceActionCommitIndeterminateProblemSchema = makeProblemDetailsSchema(
  'ConsentSelfServiceActionCommitIndeterminateProblem',
  503,
  {
    invocationId: Schema.String,
    resolution: Schema.Literal('RESOLVE_COMMIT'),
    retryCommand: Schema.Literal(false),
  },
);
export const ConsentSelfServiceActionInternalProblemSchema = makeProblemDetailsSchema(
  'ConsentSelfServiceActionInternalProblem',
  500,
);

export type ConsentSelfServiceActionProblem =
  | typeof ConsentSelfServiceActionInvalidProblemSchema.Type
  | typeof ConsentSelfServiceActionAuthenticationProblemSchema.Type
  | typeof ConsentSelfServiceActionForbiddenProblemSchema.Type
  | typeof ConsentSelfServiceActionNotFoundProblemSchema.Type
  | typeof ConsentSelfServiceActionConflictProblemSchema.Type
  | typeof ConsentSelfServiceActionIneligibleProblemSchema.Type
  | typeof ConsentSelfServiceActionPreconditionProblemSchema.Type
  | typeof ConsentSelfServiceActionUnavailableProblemSchema.Type
  | typeof ConsentSelfServiceActionAlreadyCommittedProblemSchema.Type
  | typeof ConsentSelfServiceActionCommitIndeterminateProblemSchema.Type
  | typeof ConsentSelfServiceActionInternalProblemSchema.Type;

export class ConsentSelfServiceActionSchemaErrorMiddleware extends HttpApiMiddleware.Service<ConsentSelfServiceActionSchemaErrorMiddleware>()(
  'privacy/ConsentSelfServiceActionSchemaErrorMiddleware',
  { error: ConsentSelfServiceActionInvalidProblemSchema },
) {}

const actionErrors = [
  ConsentSelfServiceActionInvalidProblemSchema,
  ConsentSelfServiceActionAuthenticationProblemSchema,
  ConsentSelfServiceActionForbiddenProblemSchema,
  ConsentSelfServiceActionNotFoundProblemSchema,
  ConsentSelfServiceActionConflictProblemSchema,
  ConsentSelfServiceActionIneligibleProblemSchema,
  ConsentSelfServiceActionPreconditionProblemSchema,
  ConsentSelfServiceActionUnavailableProblemSchema,
  ConsentSelfServiceActionAlreadyCommittedProblemSchema,
  ConsentSelfServiceActionCommitIndeterminateProblemSchema,
  ConsentSelfServiceActionInternalProblemSchema,
] as const;

export const ConsentSelfServiceActionApi = HttpApi.make('ConsentSelfServiceActionApi').add(
  HttpApiGroup.make('consentSelfServiceAction')
    .add(
      HttpApiEndpoint.post('execute', '/privacy/actions/consent-self-service', {
        error: actionErrors,
        headers: ConsentSelfServiceActionHeadersSchema,
        payload: Schema.toEncoded(ConsentSelfServicePayloadSchema),
        success: ConsentSelfServiceResultSchema,
      }),
    )
    .middleware(ConsentSelfServiceActionSchemaErrorMiddleware),
);
