// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

import { OwnerInventoryRequestSchema, OwnerInventoryResponseSchema } from '../privacy-queries.ts';

export { OwnerInventoryRequestSchema } from '../privacy-queries.ts';
export { OwnerInventoryResponseSchema } from '../privacy-queries.ts';

export type OwnerInventoryRequest = typeof OwnerInventoryRequestSchema.Type;
export type OwnerInventoryResponse = typeof OwnerInventoryResponseSchema.Type;

export const OwnerInventoryAuthenticationProblemSchema = makeProblemDetailsSchema(
  'OwnerInventoryAuthenticationProblem',
  401,
);
export const OwnerInventoryInvalidProblemSchema = makeProblemDetailsSchema('OwnerInventoryInvalidProblem', 400);
export const OwnerInventoryUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'OwnerInventoryUnavailableProblem',
  503,
);
export const OwnerInventoryForbiddenProblemSchema = makeProblemDetailsSchema('OwnerInventoryForbiddenProblem', 403);
export const OwnerInventoryNotFoundProblemSchema = makeProblemDetailsSchema('OwnerInventoryNotFoundProblem', 404);
export const OwnerInventoryPolicyProblemSchema = makeProblemDetailsSchema('OwnerInventoryPolicyProblem', 422);
export const OwnerInventoryPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'OwnerInventoryPolicyConflictProblem',
  409,
);
export const OwnerInventoryInternalProblemSchema = makeProblemDetailsSchema('OwnerInventoryInternalProblem', 500);

export const OwnerInventoryApi = HttpApi.make('OwnerInventoryApi').add(
  HttpApiGroup.make('ownerInventory').add(
    HttpApiEndpoint.post('execute', '/reads/owner-inventory', {
      error: [
        OwnerInventoryInvalidProblemSchema,
        OwnerInventoryAuthenticationProblemSchema,
        OwnerInventoryForbiddenProblemSchema,
        OwnerInventoryNotFoundProblemSchema,
        OwnerInventoryPolicyConflictProblemSchema,
        OwnerInventoryPolicyProblemSchema,
        OwnerInventoryUnavailableProblemSchema,
        OwnerInventoryInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: OwnerInventoryRequestSchema,
      query: {},
      success: OwnerInventoryResponseSchema,
    }),
  ),
);
