import { Effect, FileSystem, Match, Option, Schema, Predicate } from 'effect';
import { createCodesmithGenerator } from '../generator-adapter.mts';
import {
  MODULE_REGISTRATION_IMPORT_SLOT_END,
  MODULE_REGISTRATION_IMPORT_SLOT_START,
  MODULE_REGISTRATION_WORKER_SLOT_END,
  MODULE_REGISTRATION_WORKER_SLOT_START,
  OUTBOX_CONTRACT_GENERATOR_HEADER,
  OUTBOX_WORKER_GENERATOR_HEADER,
  OUTBOX_WORKER_IMPORT_SLOT_END,
  OUTBOX_WORKER_IMPORT_SLOT_START,
  OUTBOX_WORKER_REGISTRY_SLOT_END,
  OUTBOX_WORKER_REGISTRY_SLOT_START,
  asJsonObject,
  createMutationEffect,
  discoverOntosModuleEffect,
  ensureUniqueMutationPaths,
  insertSortedSlot,
  patchJsonObjectProperty,
  requireCanonicalSlug,
  requireTopic,
  resolveContainedPath,
  toCamelCase,
  toPascalCase,
  topicToSlug,
  updateMutation,
} from '../shared.mts';
import type {
  MutableJsonObject,
  Mutation,
  OntosVerticalMetadata,
  OutboxWorkerScaffoldConfig,
  OutboxWorkerScaffoldResult,
  ScaffoldFailure,
  ScaffoldPlan,
} from '../shared.mts';

class OutboxWorkerScaffoldError extends Schema.TaggedError<OutboxWorkerScaffoldError>()(
  'OutboxWorkerScaffoldError',
  {
    cause: Schema.Unknown,
    message: Schema.String,
  },
) {}

const scaffoldError = (cause: unknown, message?: string): OutboxWorkerScaffoldError =>
  new OutboxWorkerScaffoldError({
    cause,
    message: message ?? (Predicate.isError(cause) ? cause.message : String(cause)),
  });

const trySync = <Value,>(operation: () => Value) =>
  Effect.try({
    catch: scaffoldError,
    try: operation,
  });

const readRequiredFile = (filePath: string, label: string) =>
  Effect.gen(function* readRequiredFileEffect() {
    const fileSystem = yield* FileSystem.FileSystem;
    return yield* fileSystem.readFileString(filePath).pipe(
      Effect.mapError((error) =>
        Match.value(error.reason).pipe(
          Match.tag('NotFound', () => scaffoldError(error, `${label} is missing at ${filePath}`)),
          Match.orElse(() => scaffoldError(error)),
        ),
      ),
    );
  });

const readOptionalFile = (filePath: string) =>
  Effect.gen(function* readOptionalFileEffect() {
    const fileSystem = yield* FileSystem.FileSystem;
    return yield* fileSystem.readFileString(filePath).pipe(
      Effect.map(Option.some),
      Effect.catch((error) =>
        Match.value(error.reason).pipe(
          Match.tag('NotFound', () => Effect.succeed(Option.none<string>())),
          Match.orElse(() => Effect.fail(scaffoldError(error))),
        ),
      ),
    );
  });

const OUTBOX_WORKER_HOST_HEADER = '// @generated by scaffold:outbox-worker worker-host';
const TsconfigReferenceSchema = Schema.StructWithRest(Schema.Struct({ path: Schema.String }), [
  Schema.Record(Schema.String, Schema.Json),
]);
const TsconfigReferencesSchema = Schema.Array(TsconfigReferenceSchema);

const renderWorker = (
  consumer: OntosVerticalMetadata,
  producer: OntosVerticalMetadata,
  worker: string,
  topic: string,
): string => {
  const workerType = toPascalCase(worker);
  const workerVariable = `${toCamelCase(worker)}Worker`;
  const contractPath = `${producer.packageName}/outbox/${topicToSlug(topic)}`;
  return `${OUTBOX_WORKER_GENERATOR_HEADER}
// @ontos-outbox-worker-key ${consumer.moduleId}.${worker}
// @ontos-outbox-worker-owner ${consumer.moduleId}
// @ontos-outbox-worker-producer ${producer.moduleId}
// @ontos-outbox-worker-topic ${topic}
import { Effect, Schema } from 'effect';
import { defineOutboxWorker, defineTenantModuleEntrypoint } from '@app/core-runtime';
import {
  OutboxPayloadSchema,
  outboxProducerModuleKey,
  outboxTopic,
} from '${contractPath}';

export class ${workerType}NotImplemented extends Schema.TaggedError<${workerType}NotImplemented>()(
  '${workerType}NotImplemented',
  {
    code: Schema.Literal('outbox_worker_not_implemented'),
    reason: Schema.String,
  },
) {}

const handle${workerType} = () =>
  Effect.fail(
    new ${workerType}NotImplemented({
      code: 'outbox_worker_not_implemented',
      reason: 'The ${workerType} Outbox Worker is not implemented',
    }),
  );

export const ${workerVariable} = defineOutboxWorker(
  {
    consumerModuleKey: '${consumer.moduleId}',
    entrypoint: defineTenantModuleEntrypoint({
      access: 'background',
      authorization: { kind: 'owner_local_background' },
      entrypointKey: '${consumer.moduleId}.${worker}',
      moduleKey: '${consumer.moduleId}',
      role: 'worker',
    }),
    leaseDurationMs: 30_000,
    payloadSchema: OutboxPayloadSchema,
    producerModuleKey: outboxProducerModuleKey,
    retryPolicy: {
      initialBackoffMs: 1000,
      maxAttempts: 5,
      maxBackoffMs: 60_000,
      multiplier: 2,
    },
    topic: outboxTopic,
    workerKey: '${consumer.moduleId}.${worker}',
  },
  handle${workerType},
);
`;
};

const renderRegistry =
  (): string => `import type { AnyOutboxWorkerRegistration } from '@app/core-runtime';

${OUTBOX_WORKER_IMPORT_SLOT_START}
${OUTBOX_WORKER_IMPORT_SLOT_END}

export const outboxWorkers = Object.freeze([
  ${OUTBOX_WORKER_REGISTRY_SLOT_START}
  ${OUTBOX_WORKER_REGISTRY_SLOT_END}
]) satisfies readonly AnyOutboxWorkerRegistration[];
`;

const renderWorkerHostLayer = (
  consumer: OntosVerticalMetadata,
): string => `${OUTBOX_WORKER_HOST_HEADER}
// @ontos-outbox-worker-host-owner ${consumer.moduleId}
import { Layer } from 'effect';
import { OutboxWorkerInfrastructureLive } from '@app/core-runtime/outbox/worker';

export { CorePersistenceLive as outboxWorkerCorePersistenceLive } from '@app/core-runtime/outbox/worker';
export { DatabaseConfigLive as outboxWorkerDatabaseConfigLive } from '@app/core-runtime/outbox/worker';
export { OutboxRepositoryLive as outboxWorkerRepositoryLive } from '@app/core-runtime/outbox/worker';

/** Add owner-local repositories and services required by worker handlers here. */
const outboxWorkerHandlerLayer = Layer.empty;

export const outboxWorkerLayer = Layer.merge(
  OutboxWorkerInfrastructureLive,
  outboxWorkerHandlerLayer,
);
`;

const renderWorkerHostMain = (
  consumer: OntosVerticalMetadata,
): string => `${OUTBOX_WORKER_HOST_HEADER}
// @ontos-outbox-worker-host-owner ${consumer.moduleId}
import { start${toPascalCase(consumer.slug)}OutboxWorker } from '../../scripts/outbox-worker.ts';

start${toPascalCase(consumer.slug)}OutboxWorker();
`;

const renderWorkerHostScript = (
  consumer: OntosVerticalMetadata,
): string => `${OUTBOX_WORKER_HOST_HEADER}
// @ontos-outbox-worker-host-owner ${consumer.moduleId}
import { Layer } from 'effect';
import {
  extractOutboxWorkerSubscriptions,
  startOutboxWorkerProcess,
} from '@app/core-runtime/outbox/worker';
import { outboxWorkers } from '../src/workers/index.ts';
import {
  outboxWorkerCorePersistenceLive,
  outboxWorkerDatabaseConfigLive,
  outboxWorkerLayer as outboxWorkerDefinitionLayer,
  outboxWorkerRepositoryLive,
} from '../src/worker-host/layer.ts';

const outboxSubscriptions = extractOutboxWorkerSubscriptions(outboxWorkers);
const outboxWorkerProcessLayer = outboxWorkerDefinitionLayer.pipe(
  Layer.provide(outboxWorkerRepositoryLive),
  Layer.provide(outboxWorkerCorePersistenceLive),
  Layer.provide(outboxWorkerDatabaseConfigLive),
);

export const start${toPascalCase(consumer.slug)}OutboxWorker = (): void =>
  startOutboxWorkerProcess({
    claimOwnerPrefix: '${consumer.moduleId}-outbox-worker',
    health: true,
    layer: outboxWorkerProcessLayer,
    registrations: outboxWorkers,
    subscriptions: outboxSubscriptions,
  });
`;

const planWorkerHostFile = (filePath: string, consumer: OntosVerticalMetadata, content: string) =>
  Effect.gen(function* planWorkerHostFileEffect() {
    const existing = yield* readOptionalFile(filePath);
    if (Option.isNone(existing)) {
      return Option.some(yield* createMutationEffect(filePath, content));
    }
    if (
      !existing.value.startsWith(`${OUTBOX_WORKER_HOST_HEADER}\n`) ||
      !existing.value.includes(`// @ontos-outbox-worker-host-owner ${consumer.moduleId}\n`)
    ) {
      return yield* new OutboxWorkerScaffoldError({
        cause: existing.value,
        message: `existing Outbox Worker host is not owned by ${consumer.moduleId}`,
      });
    }
    return Option.none<Mutation>();
  });

const patchConsumerPackage = (consumer: OntosVerticalMetadata, producer: OntosVerticalMetadata) =>
  Effect.gen(function* patchConsumerPackageEffect() {
    const dependenciesValue = consumer.packageJson['dependencies'];
    const dependencies: MutableJsonObject =
      dependenciesValue === undefined
        ? {}
        : {
            ...(yield* trySync(() =>
              asJsonObject(dependenciesValue, `vertical ${consumer.slug} dependencies`),
            )),
          };
    for (const [name, version] of [
      ['@app/core-runtime', 'workspace:*'],
      [producer.packageName, 'workspace:*'],
    ] as const) {
      if (name === consumer.packageName) {
        continue;
      }
      const current = dependencies[name];
      if (current !== undefined && current !== version) {
        return yield* new OutboxWorkerScaffoldError({
          cause: current,
          message: `vertical ${consumer.slug} has an incompatible ${name} dependency`,
        });
      }
      dependencies[name] = version;
    }
    const sortedDependencies = Object.fromEntries(
      Object.entries(dependencies).toSorted(([left], [right]) => left.localeCompare(right)),
    );
    const packageScripts = consumer.packageJson['scripts'];
    if (packageScripts === undefined) {
      return yield* new OutboxWorkerScaffoldError({
        cause: packageScripts,
        message: `vertical ${consumer.slug} package scripts must be a JSON object`,
      });
    }
    const scriptsValue = yield* trySync(() =>
      asJsonObject(packageScripts, `vertical ${consumer.slug} package scripts`),
    );
    const workerCommand = 'node --experimental-strip-types ./src/worker-host/main.ts';
    const scripts: MutableJsonObject = { ...scriptsValue };
    for (const scriptName of ['dev:worker', 'worker:start'] as const) {
      const current = scripts[scriptName];
      if (current !== undefined && current !== workerCommand) {
        return yield* new OutboxWorkerScaffoldError({
          cause: current,
          message: `vertical ${consumer.slug} has an incompatible ${scriptName} script`,
        });
      }
      scripts[scriptName] = workerCommand;
    }
    const sortedScripts = Object.fromEntries(
      Object.entries(scripts).toSorted(([left], [right]) => left.localeCompare(right)),
    );
    const withDependencies = yield* trySync(() =>
      patchJsonObjectProperty(consumer.packageContent, [], 'dependencies', sortedDependencies),
    );
    return yield* trySync(() =>
      patchJsonObjectProperty(withDependencies, [], 'scripts', sortedScripts),
    );
  });

const patchConsumerTsconfig = (
  content: string,
  consumer: OntosVerticalMetadata,
  producer: OntosVerticalMetadata,
) =>
  Effect.gen(function* patchConsumerTsconfigEffect() {
    const parsed = yield* Schema.decodeUnknownEffect(Schema.fromJsonString(Schema.Json))(
      content,
    ).pipe(
      Effect.mapError((cause) =>
        scaffoldError(cause, `vertical ${consumer.slug} tsconfig is not valid JSON`),
      ),
    );
    const root = yield* trySync(() => asJsonObject(parsed, `vertical ${consumer.slug} tsconfig`));
    const referencesValue = root['references'];
    const references = yield* Schema.decodeUnknownEffect(TsconfigReferencesSchema)(
      referencesValue,
    ).pipe(
      Effect.mapError((cause) =>
        scaffoldError(cause, `vertical ${consumer.slug} tsconfig references must be an array`),
      ),
    );
    const producerReference = `../${producer.slug}`;
    const matching = references.filter((reference) => reference.path === producerReference);
    if (consumer.slug === producer.slug) {
      if (matching.length > 0) {
        return yield* new OutboxWorkerScaffoldError({
          cause: producerReference,
          message: `vertical ${consumer.slug} has a circular self project reference`,
        });
      }
      return content;
    }
    if (matching.length > 1) {
      return yield* new OutboxWorkerScaffoldError({
        cause: matching,
        message: `vertical ${consumer.slug} has duplicate ${producerReference} references`,
      });
    }
    if (matching.length === 1) {
      return content;
    }
    const patched = [...references, { path: producerReference }].toSorted((left, right) =>
      left.path.localeCompare(right.path),
    );
    return yield* trySync(() => patchJsonObjectProperty(content, [], 'references', patched));
  });

const planOutboxWorkerScaffoldEffect = (
  workspaceRoot: string,
  config: OutboxWorkerScaffoldConfig,
): Effect.Effect<
  ScaffoldPlan<OutboxWorkerScaffoldResult>,
  OutboxWorkerScaffoldError | ScaffoldFailure,
  FileSystem.FileSystem
> =>
  Effect.gen(function* planOutboxWorkerScaffoldProgram() {
    const worker = yield* trySync(() => requireCanonicalSlug(config.worker, 'worker'));
    const topic = yield* trySync(() => requireTopic(config.topic));
    const [consumer, producer] = yield* Effect.all([
      discoverOntosModuleEffect(workspaceRoot, config.vertical),
      discoverOntosModuleEffect(workspaceRoot, config.producer),
    ]);
    const topicSlug = yield* trySync(() => topicToSlug(topic));
    const contractPath = yield* trySync(() =>
      resolveContainedPath(
        workspaceRoot,
        'verticals',
        producer.slug,
        'shared',
        'outbox',
        `${topicSlug}.ts`,
      ),
    );
    const contract = yield* readRequiredFile(contractPath, 'published producer Outbox contract');
    const contractExport = `./outbox/${topicSlug}`;
    const packageExports = producer.packageJson['exports'];
    if (packageExports === undefined) {
      return yield* new OutboxWorkerScaffoldError({
        cause: packageExports,
        message: `vertical ${producer.slug} package exports must be a JSON object`,
      });
    }
    const producerExports = yield* trySync(() =>
      asJsonObject(packageExports, `vertical ${producer.slug} package exports`),
    );
    if (producerExports[contractExport] !== `./shared/outbox/${topicSlug}.ts`) {
      return yield* new OutboxWorkerScaffoldError({
        cause: producerExports[contractExport],
        message: `topic ${topic} is not published by ${producer.packageName}`,
      });
    }
    if (
      !contract.startsWith(`${OUTBOX_CONTRACT_GENERATOR_HEADER}\n`) ||
      !contract.includes(`// @ontos-outbox-producer ${producer.moduleId}\n`) ||
      !contract.includes(`// @ontos-outbox-topic ${topic}\n`) ||
      !contract.includes(`export const outboxTopic = '${topic}' as const;`) ||
      !contract.includes(
        `export const outboxProducerModuleKey = '${producer.moduleId}' as const;`,
      ) ||
      !contract.includes('export const OutboxPayloadSchema =') ||
      /(?:src\/actions|create[A-Za-z0-9]+Message|handler|repository|transport)/u.test(contract)
    ) {
      return yield* new OutboxWorkerScaffoldError({
        cause: contractPath,
        message: `published Outbox contract for ${topic} has an owner/topic/schema mismatch`,
      });
    }

    const workerPath = yield* trySync(() =>
      resolveContainedPath(
        workspaceRoot,
        'verticals',
        consumer.slug,
        'src',
        'workers',
        `${worker}.worker.ts`,
      ),
    );
    const workerMutation = yield* createMutationEffect(
      workerPath,
      renderWorker(consumer, producer, worker, topic),
    );
    const registryPath = yield* trySync(() =>
      resolveContainedPath(workspaceRoot, 'verticals', consumer.slug, 'src', 'workers', 'index.ts'),
    );
    const registryContent = yield* readOptionalFile(registryPath);
    const workerVariable = `${toCamelCase(worker)}Worker`;
    let registryMutation: Mutation;
    if (Option.isSome(registryContent)) {
      if (
        !registryContent.value.includes(OUTBOX_WORKER_IMPORT_SLOT_START) ||
        !registryContent.value.includes(OUTBOX_WORKER_REGISTRY_SLOT_START)
      ) {
        return yield* new OutboxWorkerScaffoldError({
          cause: registryPath,
          message: 'generated worker registry does not contain its owned slots',
        });
      }
      if (new RegExp(`\\b${workerVariable}\\b`, 'u').test(registryContent.value)) {
        return yield* new OutboxWorkerScaffoldError({
          cause: workerVariable,
          message: `Outbox Worker identifier ${workerVariable} already exists`,
        });
      }
      const withRegistration = yield* trySync(() => {
        const withImport = insertSortedSlot(
          registryContent.value,
          OUTBOX_WORKER_IMPORT_SLOT_START,
          OUTBOX_WORKER_IMPORT_SLOT_END,
          [`import { ${workerVariable} } from './${worker}.worker.ts';`],
          (candidate) =>
            /^import \{ [A-Za-z0-9]+Worker \} from '\.\/[a-z0-9-]+\.worker\.ts';$/u.test(candidate),
        );
        return insertSortedSlot(
          withImport,
          OUTBOX_WORKER_REGISTRY_SLOT_START,
          OUTBOX_WORKER_REGISTRY_SLOT_END,
          [`${workerVariable},`],
          (candidate) => /^[a-z][A-Za-z0-9]+Worker,$/u.test(candidate),
        );
      });
      const updatedRegistry = yield* trySync(() =>
        updateMutation(registryPath, registryContent.value, withRegistration),
      );
      if (updatedRegistry === undefined) {
        return yield* new OutboxWorkerScaffoldError({
          cause: registryPath,
          message: 'Outbox Worker registry patch unexpectedly made no change',
        });
      }
      registryMutation = updatedRegistry;
    } else {
      const withRegistration = yield* trySync(() => {
        const emptyRegistry = renderRegistry();
        const withImport = insertSortedSlot(
          emptyRegistry,
          OUTBOX_WORKER_IMPORT_SLOT_START,
          OUTBOX_WORKER_IMPORT_SLOT_END,
          [`import { ${workerVariable} } from './${worker}.worker.ts';`],
          () => true,
        );
        return insertSortedSlot(
          withImport,
          OUTBOX_WORKER_REGISTRY_SLOT_START,
          OUTBOX_WORKER_REGISTRY_SLOT_END,
          [`${workerVariable},`],
          () => true,
        );
      });
      registryMutation = yield* createMutationEffect(registryPath, withRegistration);
    }

    const workerHostLayerPath = yield* trySync(() =>
      resolveContainedPath(
        workspaceRoot,
        'verticals',
        consumer.slug,
        'src',
        'worker-host',
        'layer.ts',
      ),
    );
    const workerHostMainPath = yield* trySync(() =>
      resolveContainedPath(
        workspaceRoot,
        'verticals',
        consumer.slug,
        'src',
        'worker-host',
        'main.ts',
      ),
    );
    const workerHostScriptPath = yield* trySync(() =>
      resolveContainedPath(
        workspaceRoot,
        'verticals',
        consumer.slug,
        'scripts',
        'outbox-worker.ts',
      ),
    );
    const [workerHostLayerMutation, workerHostMainMutation, workerHostScriptMutation] =
      yield* Effect.all([
        planWorkerHostFile(workerHostLayerPath, consumer, renderWorkerHostLayer(consumer)),
        planWorkerHostFile(workerHostMainPath, consumer, renderWorkerHostMain(consumer)),
        planWorkerHostFile(workerHostScriptPath, consumer, renderWorkerHostScript(consumer)),
      ]);

    const registrationImport = `import { ${workerVariable} } from './src/workers/${worker}.worker.ts';`;
    const nextRegistration = yield* trySync(() =>
      insertSortedSlot(
        insertSortedSlot(
          consumer.registrationContent,
          MODULE_REGISTRATION_IMPORT_SLOT_START,
          MODULE_REGISTRATION_IMPORT_SLOT_END,
          [registrationImport],
          (candidate) =>
            /^import \{ [a-z][A-Za-z0-9]*Worker \} from '\.\/src\/workers\/[a-z][a-z0-9-]*\.worker\.ts';$/u.test(
              candidate,
            ) ||
            /^import \{ [a-z][A-Za-z0-9]*Action \} from '\.\/src\/actions\/[a-z][a-z0-9-]*\.action\.ts';$/u.test(
              candidate,
            ),
        ),
        MODULE_REGISTRATION_WORKER_SLOT_START,
        MODULE_REGISTRATION_WORKER_SLOT_END,
        [`${workerVariable},`],
        (candidate) => /^[a-z][A-Za-z0-9]*Worker,$/u.test(candidate),
      ),
    );
    const ownerRegistrationMutation = yield* trySync(() =>
      updateMutation(consumer.registrationPath, consumer.registrationContent, nextRegistration),
    );

    const packageContent = yield* patchConsumerPackage(consumer, producer);
    const packageMutation = yield* trySync(() =>
      updateMutation(consumer.packagePath, consumer.packageContent, packageContent),
    );
    const tsconfigPath = yield* trySync(() =>
      resolveContainedPath(workspaceRoot, 'verticals', consumer.slug, 'tsconfig.json'),
    );
    const tsconfigContent = yield* readRequiredFile(
      tsconfigPath,
      `vertical ${consumer.slug} tsconfig`,
    );
    const patchedTsconfig = yield* patchConsumerTsconfig(tsconfigContent, consumer, producer);
    const tsconfigMutation = yield* trySync(() =>
      updateMutation(tsconfigPath, tsconfigContent, patchedTsconfig),
    );
    const mutations = [
      workerMutation,
      registryMutation,
      ...(ownerRegistrationMutation === undefined ? [] : [ownerRegistrationMutation]),
      ...Option.toArray(workerHostLayerMutation),
      ...Option.toArray(workerHostMainMutation),
      ...Option.toArray(workerHostScriptMutation),
      ...(packageMutation === undefined ? [] : [packageMutation]),
      ...(tsconfigMutation === undefined ? [] : [tsconfigMutation]),
    ];
    yield* trySync(() => ensureUniqueMutationPaths(mutations));
    return { mutations, result: { registryPath, workerPath } };
  });

export const planOutboxWorkerScaffold = planOutboxWorkerScaffoldEffect;

export default createCodesmithGenerator(planOutboxWorkerScaffold);
