// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.fx
// @ontos-action-http-slug change-manual-commercial-rate-policy
import { Effect, HttpApiBuilder, Layer } from '@modern-js/plugin-bff/effect-edge';
import type { HttpServerRequest } from 'effect/unstable/http';
import { Redacted, Schema } from 'effect';
import { commerceFxApi } from '../shared/api.ts';
import { changeManualCommercialRatePolicyAction } from '../src/actions/change-manual-commercial-rate-policy.action.ts';
import { bindActionHttpRunner } from './action-http-runner.ts';
import {
  changeManualCommercialRatePolicyActionProblem,
  changeManualCommercialRatePolicyActionSchemaErrorLive,
  mapChangeManualCommercialRatePolicyActionProblem,
} from './change-manual-commercial-rate-policy-action-problems.ts';

const runActionHttp = bindActionHttpRunner({
  authentication: changeManualCommercialRatePolicyActionProblem.authentication,
  unavailable: () =>
    changeManualCommercialRatePolicyActionProblem.unavailable('operation_context_unavailable'),
});

const execute = Effect.fn('ChangeManualCommercialRatePolicyActionServer.execute')(
  function* executeChangeManualCommercialRatePolicy(
    payload: typeof changeManualCommercialRatePolicyAction.descriptor.payloadSchema.Encoded,
    idempotencyKey: string | undefined,
    request: HttpServerRequest.HttpServerRequest,
  ) {
    const correlationId = request.headers['x-correlation-id'];
    if (correlationId !== undefined && correlationId.length > 200) {
      return yield* Effect.fail(changeManualCommercialRatePolicyActionProblem.invalid());
    }
    const decoded = yield* Schema.decodeUnknownEffect(
      changeManualCommercialRatePolicyAction.descriptor.payloadSchema,
    )(payload).pipe(Effect.mapError(changeManualCommercialRatePolicyActionProblem.invalid));
    return yield* runActionHttp({
      endpointHeaders: { idempotencyKey, traceId: request.headers['x-trace-id'] },
      internalProblem: changeManualCommercialRatePolicyActionProblem.internal,
      invalidCorrelationProblem: changeManualCommercialRatePolicyActionProblem.invalid,
      mapError: mapChangeManualCommercialRatePolicyActionProblem,
      payload: decoded,
      registration: changeManualCommercialRatePolicyAction,
      requestHeaders: {
        authorization: Redacted.make(request.headers['authorization']),
        'x-correlation-id': correlationId,
      },
    });
  },
);

export const changeManualCommercialRatePolicyActionApiLive = HttpApiBuilder.group(
  commerceFxApi,
  'changeManualCommercialRatePolicyAction',
  (handlers) =>
    handlers.handle('execute', ({ headers, payload, request }) =>
      execute(payload, headers['idempotency-key'], request),
    ),
).pipe(Layer.provide(changeManualCommercialRatePolicyActionSchemaErrorLive));
