// @generated by OntOS Codesmith Action v1
// @ontos-action-owner party.registry
// @ontos-action-slug archive-person-engagement
import {
  defineAction,
  defineActionResourcePermission,
  defineTenantModuleEntrypoint,
  OperationContextUnavailable,
} from '@app/core-runtime';
import { Effect } from 'effect';
import {
  PersonEngagementLifecyclePayloadSchema,
  PersonEngagementProfileSchema,
} from '../../shared/domain/engagement-profile.ts';
import type {
  PersonEngagementLifecyclePayload,
  PersonEngagementProfile,
} from '../../shared/domain/engagement-profile.ts';
import { transitionPersonEngagementProfile } from '../services/engagement-profile-persistence.service.ts';
import {
  EngagementLifecycleErrorSchema,
  handleEngagementLifecycle,
} from './engagement-lifecycle-handler.ts';

export const archivePersonEngagementAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'party.registry.archive-person-engagement.access.v1',
    },
    actionKey: 'party.registry.archive-person-engagement',
    auditProfile: 'standard',
    domainErrorSchema: EngagementLifecycleErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'tenant_membership_default' },
      entrypointKey: 'party.registry.archive-person-engagement',
      moduleKey: 'party.registry',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'required',
    owningModuleKey: 'party.registry',
    payloadSchema: PersonEngagementLifecyclePayloadSchema,
    policies: [],
    resourcePermission: defineActionResourcePermission<PersonEngagementLifecyclePayload>(
      (payload) => ({
        permission: 'write',
        resource: {
          moduleId: payload.profileRef.moduleId,
          resourceId: payload.profileRef.resourceId,
          resourceType: payload.profileRef.resourceType,
        },
      }),
    ),
    resultSchema: PersonEngagementProfileSchema,
    schemaVersion: '1',
  },
  handleEngagementLifecycle<PersonEngagementLifecyclePayload, PersonEngagementProfile>('archived'),
  (transaction, scope) => {
    if (scope.legalEntityId === undefined) {
      return Effect.fail(
        new OperationContextUnavailable({
          code: 'operation_context_unavailable',
          reason: 'Person engagement archive requires a trusted Legal Entity scope',
        }),
      );
    }
    return Effect.succeed({
      transition: (profileId) =>
        transitionPersonEngagementProfile(transaction, scope.tenantId, profileId, 'archived'),
    });
  },
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
