// @generated by OntOS Codesmith Action v1
// @ontos-action-owner party.registry
// @ontos-action-slug mark-duplicate-candidate-needs-evidence
import { createHash } from 'node:crypto';
import { defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';
import type { ActionHandlerContext } from '@app/core-runtime';
import { Effect, Schema } from 'effect';
import { PartyPersistenceUnavailable } from '../../shared/domain/identity-contracts.ts';
import { DuplicateCandidateConflict } from '../../shared/domain/matching-contracts.ts';
import { transitionDuplicateCandidateCase } from '../services/party-matching-persistence.service.ts';
import {
  MarkDuplicateCandidateNeedsEvidencePayloadSchema,
  MarkDuplicateCandidateNeedsEvidenceResultSchema,
} from '../../shared/actions/mark-duplicate-candidate-needs-evidence.ts';
import type { MarkDuplicateCandidateNeedsEvidencePayload } from '../../shared/actions/mark-duplicate-candidate-needs-evidence.ts';

export {
  MarkDuplicateCandidateNeedsEvidencePayloadSchema,
  MarkDuplicateCandidateNeedsEvidenceResultSchema,
} from '../../shared/actions/mark-duplicate-candidate-needs-evidence.ts';
export type {
  MarkDuplicateCandidateNeedsEvidencePayload,
  MarkDuplicateCandidateNeedsEvidenceResult,
} from '../../shared/actions/mark-duplicate-candidate-needs-evidence.ts';
const ErrorSchema = Schema.Union([DuplicateCandidateConflict, PartyPersistenceUnavailable]);
interface Services {
  readonly resolve: (
    payload: MarkDuplicateCandidateNeedsEvidencePayload,
    invocationId: string,
  ) => ReturnType<typeof transitionDuplicateCandidateCase>;
}
const handle = (
  payload: MarkDuplicateCandidateNeedsEvidencePayload,
  context: ActionHandlerContext<Readonly<Record<string, never>>, Services>,
) =>
  context.services.resolve(payload, context.actionInvocationId).pipe(
    Effect.tap((result) =>
      context.recordDataAccess({
        accessKind: 'read',
        queryHash: createHash('sha256')
          .update(`duplicate-case-invariants:${payload.caseRef.resourceId}`)
          .digest('hex'),
        resultCount: 1,
        servingModuleKey: 'party.registry',
        targetModuleKey: 'party.registry',
        targetResourceId: result.caseRef.resourceId,
        targetResourceType: result.caseRef.resourceType,
      }),
    ),
  );
export const markDuplicateCandidateNeedsEvidenceAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'party.registry.mark-duplicate-candidate-needs-evidence.access.v1',
    },
    actionKey: 'party.registry.mark-duplicate-candidate-needs-evidence',
    auditProfile: 'standard',
    domainErrorSchema: ErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      entrypointKey: 'party.registry.mark-duplicate-candidate-needs-evidence',
      moduleKey: 'party.registry',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'optional',
    owningModuleKey: 'party.registry',
    payloadSchema: MarkDuplicateCandidateNeedsEvidencePayloadSchema,
    policies: [],
    resultSchema: MarkDuplicateCandidateNeedsEvidenceResultSchema,
    schemaVersion: '1',
    tenantPermission: () => 'review_party_identity',
  },
  handle,
  (transaction, scope) =>
    Effect.succeed({
      resolve: (payload: MarkDuplicateCandidateNeedsEvidencePayload, invocationId: string) =>
        transitionDuplicateCandidateCase(transaction, {
          actionInvocationId: invocationId,
          candidateCaseId: payload.caseRef.resourceId,
          expectedRevision: payload.expectedRevision,
          outcome: 'NEEDS_EVIDENCE',
          reason: payload.reason,
          tenantId: scope.tenantId,
        }),
    }),
);
// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
