// @generated by OntOS Codesmith Action v1
// @ontos-action-owner party.registry
// @ontos-action-slug unarchive-organization-engagement
import { defineAction, OperationContextUnavailable } from '@app/core-runtime';
import { Effect } from 'effect';

import {
  OrganizationEngagementLifecyclePayloadSchema,
  OrganizationEngagementProfileSchema,
} from '../../shared/domain/engagement-profile.ts';
import type {
  OrganizationEngagementLifecyclePayload,
  OrganizationEngagementProfile,
} from '../../shared/domain/engagement-profile.ts';
import { transitionOrganizationEngagementProfile } from '../services/engagement-profile-persistence.service.ts';
import { handleEngagementLifecycle } from './engagement-lifecycle-handler.ts';
import { engagementLifecycleRegistration } from './engagement-lifecycle-registration.ts';

export const unarchiveOrganizationEngagementAction = defineAction(
  {
    ...engagementLifecycleRegistration<OrganizationEngagementLifecyclePayload>(
      'party.registry.unarchive-organization-engagement'
    ),
    payloadSchema: OrganizationEngagementLifecyclePayloadSchema,
    resultSchema: OrganizationEngagementProfileSchema,
  },
  handleEngagementLifecycle<
    OrganizationEngagementLifecyclePayload,
    OrganizationEngagementProfile
  >('active'),
  (transaction, scope) => {
    if (scope.legalEntityId === undefined) {
      return Effect.fail(
        new OperationContextUnavailable({
          code: 'operation_context_unavailable',
          reason:
            'Organization engagement unarchive requires a trusted Legal Entity scope',
        })
      );
    }
    return Effect.succeed({
      transition: (profileId) =>
        transitionOrganizationEngagementProfile(
          transaction,
          scope.tenantId,
          profileId,
          'active'
        ),
    });
  }
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
