// @generated by OntOS Codesmith module-api v1
import { OwnerVerifiableSetCompletenessEvidenceSchema } from '@app/shared-contracts';
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import { CatalogResourceRefSchema } from '../domain/catalog-revision-reference.ts';
import { SetCompositionRevisionSchema } from '../domain/set-composition.ts';
import { ProductRefSchema } from '../resources/product.ts';
import { VariantRefSchema } from '../resources/variant.ts';

const setCompositionRef = CatalogResourceRefSchema.check(
  Schema.makeFilter((ref) =>
    ref.resourceType === 'commerce.catalog.set-composition' ? undefined : 'Expected Set Composition Resource',
  ),
);
const nonEmptyText = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(1000), Schema.isTrimmed());

/** Component order is non-semantic; the owner revision represents a complete set of component identities. */

export const AssortmentSetCompositionObservationV1Schema = Schema.Struct({
  completeness: Schema.toEncoded(OwnerVerifiableSetCompletenessEvidenceSchema),
  composition: SetCompositionRevisionSchema,
  effectiveAt: Schema.DateTimeUtcFromString,
  effectiveFrom: Schema.DateTimeUtcFromString,
  effectiveTo: Schema.optionalKey(Schema.DateTimeUtcFromString),
  lifecycleState: Schema.Literal('ACTIVE'),
  observedAt: Schema.DateTimeUtcFromString,
  productRef: ProductRefSchema,
  requestedRevision: Schema.Finite.check(Schema.isInt(), Schema.isGreaterThan(0)),
  variantRef: VariantRefSchema,
}).annotate({ parseOptions: { onExcessProperty: 'error' } });
export type AssortmentSetCompositionObservationV1 = typeof AssortmentSetCompositionObservationV1Schema.Type;

const AssortmentSetCompositionV1OperationRequestSchema = Schema.Union([
  Schema.Struct({
    compositionRef: setCompositionRef,
    effectiveAt: Schema.DateTimeUtcFromString,
    operation: Schema.Literal('OBSERVE'),
    productRef: ProductRefSchema,
    requestedRevision: Schema.optionalKey(Schema.Finite.check(Schema.isInt(), Schema.isGreaterThan(0))),
    variantRef: VariantRefSchema,
  }),
  Schema.Struct({
    effectiveAt: Schema.DateTimeUtcFromString,
    observation: AssortmentSetCompositionObservationV1Schema,
    operation: Schema.Literal('VERIFY_CURRENT'),
  }),
]).annotate({ parseOptions: { onExcessProperty: 'error' } });
export const AssortmentSetCompositionV1RequestSchema = Schema.Struct({
  request: AssortmentSetCompositionV1OperationRequestSchema,
}).annotate({ parseOptions: { onExcessProperty: 'error' } });
export type AssortmentSetCompositionV1Request = typeof AssortmentSetCompositionV1RequestSchema.Type;
export type AssortmentSetCompositionV1OperationRequest = typeof AssortmentSetCompositionV1OperationRequestSchema.Type;

export const AssortmentSetCompositionV1ResponseSchema = Schema.Union([
  Schema.Struct({ observation: AssortmentSetCompositionObservationV1Schema, operation: Schema.Literal('OBSERVE') }),
  Schema.Struct({
    observation: AssortmentSetCompositionObservationV1Schema,
    operation: Schema.Literal('VERIFY_CURRENT'),
    status: Schema.Literal('CURRENT'),
  }),
  Schema.Struct({
    operation: Schema.Literal('VERIFY_CURRENT'),
    reason: nonEmptyText,
    status: Schema.Literal('STALE'),
  }),
  Schema.Struct({
    operation: Schema.Literal('VERIFY_CURRENT'),
    reason: nonEmptyText,
    status: Schema.Literal('UNAVAILABLE'),
  }),
]).annotate({ parseOptions: { onExcessProperty: 'error' } });

export const AssortmentSetCompositionV1AuthenticationProblemSchema = makeProblemDetailsSchema(
  'AssortmentSetCompositionV1AuthenticationProblem',
  401,
);
export const AssortmentSetCompositionV1InvalidProblemSchema = makeProblemDetailsSchema(
  'AssortmentSetCompositionV1InvalidProblem',
  400,
);
export const AssortmentSetCompositionV1UnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'AssortmentSetCompositionV1UnavailableProblem',
  503,
);
export const AssortmentSetCompositionV1ForbiddenProblemSchema = makeProblemDetailsSchema(
  'AssortmentSetCompositionV1ForbiddenProblem',
  403,
);
export const AssortmentSetCompositionV1NotFoundProblemSchema = makeProblemDetailsSchema(
  'AssortmentSetCompositionV1NotFoundProblem',
  404,
);
export const AssortmentSetCompositionV1PolicyProblemSchema = makeProblemDetailsSchema(
  'AssortmentSetCompositionV1PolicyProblem',
  422,
);
export const AssortmentSetCompositionV1PolicyConflictProblemSchema = makeProblemDetailsSchema(
  'AssortmentSetCompositionV1PolicyConflictProblem',
  409,
);
export const AssortmentSetCompositionV1InternalProblemSchema = makeProblemDetailsSchema(
  'AssortmentSetCompositionV1InternalProblem',
  500,
);

export const AssortmentSetCompositionV1Api = HttpApi.make('AssortmentSetCompositionV1Api').add(
  HttpApiGroup.make('assortmentSetCompositionV1').add(
    HttpApiEndpoint.post('execute', '/reads/assortment-set-composition-v1', {
      error: [
        AssortmentSetCompositionV1InvalidProblemSchema,
        AssortmentSetCompositionV1AuthenticationProblemSchema,
        AssortmentSetCompositionV1ForbiddenProblemSchema,
        AssortmentSetCompositionV1NotFoundProblemSchema,
        AssortmentSetCompositionV1PolicyConflictProblemSchema,
        AssortmentSetCompositionV1PolicyProblemSchema,
        AssortmentSetCompositionV1UnavailableProblemSchema,
        AssortmentSetCompositionV1InternalProblemSchema,
      ],
      payload: AssortmentSetCompositionV1RequestSchema,
      success: AssortmentSetCompositionV1ResponseSchema,
    }),
  ),
);
