// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import { ChangeLocalOverrideResultSchema } from '../actions/change-local-override.ts';
import { ProductActionInvocationIdSchema } from '../domain/product.ts';

export const ChangeLocalOverrideRecoveryRequestSchema = Schema.Struct({
  invocationId: ProductActionInvocationIdSchema,
});
export type ChangeLocalOverrideRecoveryRequest = typeof ChangeLocalOverrideRecoveryRequestSchema.Type;
export const ChangeLocalOverrideRecoveryResponseSchema = ChangeLocalOverrideResultSchema;

export const ChangeLocalOverrideRecoveryAuthenticationProblemSchema = makeProblemDetailsSchema(
  'ChangeLocalOverrideRecoveryAuthenticationProblem',
  401,
);
export const ChangeLocalOverrideRecoveryInvalidProblemSchema = makeProblemDetailsSchema(
  'ChangeLocalOverrideRecoveryInvalidProblem',
  400,
);
export const ChangeLocalOverrideRecoveryUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'ChangeLocalOverrideRecoveryUnavailableProblem',
  503,
);
export const ChangeLocalOverrideRecoveryForbiddenProblemSchema = makeProblemDetailsSchema(
  'ChangeLocalOverrideRecoveryForbiddenProblem',
  403,
);
export const ChangeLocalOverrideRecoveryNotFoundProblemSchema = makeProblemDetailsSchema(
  'ChangeLocalOverrideRecoveryNotFoundProblem',
  404,
);
export const ChangeLocalOverrideRecoveryPolicyProblemSchema = makeProblemDetailsSchema(
  'ChangeLocalOverrideRecoveryPolicyProblem',
  422,
);
export const ChangeLocalOverrideRecoveryPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'ChangeLocalOverrideRecoveryPolicyConflictProblem',
  409,
);
export const ChangeLocalOverrideRecoveryInternalProblemSchema = makeProblemDetailsSchema(
  'ChangeLocalOverrideRecoveryInternalProblem',
  500,
);

export const ChangeLocalOverrideRecoveryApi = HttpApi.make('ChangeLocalOverrideRecoveryApi').add(
  HttpApiGroup.make('changeLocalOverrideRecovery').add(
    HttpApiEndpoint.post('execute', '/reads/change-local-override-recovery', {
      error: [
        ChangeLocalOverrideRecoveryInvalidProblemSchema,
        ChangeLocalOverrideRecoveryAuthenticationProblemSchema,
        ChangeLocalOverrideRecoveryForbiddenProblemSchema,
        ChangeLocalOverrideRecoveryNotFoundProblemSchema,
        ChangeLocalOverrideRecoveryPolicyConflictProblemSchema,
        ChangeLocalOverrideRecoveryPolicyProblemSchema,
        ChangeLocalOverrideRecoveryUnavailableProblemSchema,
        ChangeLocalOverrideRecoveryInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: ChangeLocalOverrideRecoveryRequestSchema,
      query: {},
      success: ChangeLocalOverrideRecoveryResponseSchema,
    }),
  ),
);
