// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import { ColorDetailsSchema } from '../domain/color.ts';
import { ProductInstantSchema } from '../domain/product.ts';
import { AttributeDefinitionRefSchema } from '../resources/attribute-definition.ts';
import { ControlledAttributeValueRefSchema } from '../resources/controlled-attribute-value.ts';

export const ColorCurrentRequestSchema = Schema.Struct({ valueRef: ControlledAttributeValueRefSchema });
export type ColorCurrentRequest = typeof ColorCurrentRequestSchema.Type;
export const ColorCurrentResponseSchema = Schema.Struct({
  assignable: Schema.Boolean,
  attributeDefinitionId: AttributeDefinitionRefSchema.fields.resourceId,
  colorDetails: Schema.OptionFromNullOr(ColorDetailsSchema),
  displayName: Schema.NonEmptyString,
  lifecycleState: Schema.Literals(['ACTIVE', 'RETIRED']),
  recordedAt: ProductInstantSchema,
  revision: Schema.Int,
  valueRef: ControlledAttributeValueRefSchema,
});

export const ColorCurrentAuthenticationProblemSchema = makeProblemDetailsSchema(
  'ColorCurrentAuthenticationProblem',
  401,
);
export const ColorCurrentInvalidProblemSchema = makeProblemDetailsSchema('ColorCurrentInvalidProblem', 400);
export const ColorCurrentUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'ColorCurrentUnavailableProblem',
  503,
);
export const ColorCurrentForbiddenProblemSchema = makeProblemDetailsSchema('ColorCurrentForbiddenProblem', 403);
export const ColorCurrentNotFoundProblemSchema = makeProblemDetailsSchema('ColorCurrentNotFoundProblem', 404);
export const ColorCurrentPolicyProblemSchema = makeProblemDetailsSchema('ColorCurrentPolicyProblem', 422);
export const ColorCurrentPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'ColorCurrentPolicyConflictProblem',
  409,
);
export const ColorCurrentInternalProblemSchema = makeProblemDetailsSchema('ColorCurrentInternalProblem', 500);

export const ColorCurrentApi = HttpApi.make('ColorCurrentApi').add(
  HttpApiGroup.make('colorCurrent').add(
    HttpApiEndpoint.post('execute', '/reads/color-current', {
      error: [
        ColorCurrentInvalidProblemSchema,
        ColorCurrentAuthenticationProblemSchema,
        ColorCurrentForbiddenProblemSchema,
        ColorCurrentNotFoundProblemSchema,
        ColorCurrentPolicyConflictProblemSchema,
        ColorCurrentPolicyProblemSchema,
        ColorCurrentUnavailableProblemSchema,
        ColorCurrentInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: ColorCurrentRequestSchema,
      query: {},
      success: ColorCurrentResponseSchema,
    }),
  ),
);
