// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.catalog
// @ontos-action-http-slug retire-package-definition
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { HttpApi, HttpApiEndpoint, HttpApiGroup, Schema } from '@modern-js/bff-effect/effect-client';
import { HttpApiMiddleware } from 'effect/unstable/httpapi';
import {
  RetirePackageDefinitionPayloadSchema,
  RetirePackageDefinitionResultSchema,
} from '../actions/retire-package-definition.ts';

export { RetirePackageDefinitionPayloadSchema } from '../actions/retire-package-definition.ts';

const RetirePackageDefinitionActionHeadersSchema = Schema.Struct({
  'idempotency-key': Schema.optionalKey(Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(200))),
});

export const RetirePackageDefinitionActionInvalidProblemSchema = makeProblemDetailsSchema(
  'RetirePackageDefinitionActionInvalidProblem',
  400,
);
export const RetirePackageDefinitionActionAuthenticationProblemSchema = makeProblemDetailsSchema(
  'RetirePackageDefinitionActionAuthenticationProblem',
  401,
);
export const RetirePackageDefinitionActionForbiddenProblemSchema = makeProblemDetailsSchema(
  'RetirePackageDefinitionActionForbiddenProblem',
  403,
  {
    code: Schema.Literals([
      'action_permission_denied',
      'module_state_denied',
      'operation_context_denied',
      'operation_context_invalid',
    ]),
  },
);
export const RetirePackageDefinitionActionNotFoundProblemSchema = makeProblemDetailsSchema(
  'RetirePackageDefinitionActionNotFoundProblem',
  404,
  { code: Schema.Literal('action_invocation_not_found') },
);
export const RetirePackageDefinitionActionConflictProblemSchema = makeProblemDetailsSchema(
  'RetirePackageDefinitionActionConflictProblem',
  409,
  {
    code: Schema.Literals([
      'action_request_hash_conflict',
      'action_invocation_state_invalid',
      'package_definition_stale',
    ]),
  },
);
export const RetirePackageDefinitionActionIneligibleProblemSchema = makeProblemDetailsSchema(
  'RetirePackageDefinitionActionIneligibleProblem',
  422,
  { code: Schema.Literals(['action_policy_denied', 'package_definition_invalid']) },
);
export const RetirePackageDefinitionActionPreconditionProblemSchema = makeProblemDetailsSchema(
  'RetirePackageDefinitionActionPreconditionProblem',
  428,
);
export const RetirePackageDefinitionActionUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'RetirePackageDefinitionActionUnavailableProblem',
  503,
  {
    code: Schema.Literals([
      'action_invocation_persistence_failed',
      'action_permission_check_failed',
      'action_policy_evaluation_failed',
      'action_transaction_failed',
      'module_state_check_unavailable',
      'operation_context_unavailable',
      'package_definition_unavailable',
    ]),
  },
);
export const RetirePackageDefinitionActionAlreadyCommittedProblemSchema = makeProblemDetailsSchema(
  'RetirePackageDefinitionActionAlreadyCommittedProblem',
  409,
  {
    code: Schema.Literal('action_already_committed'),
    invocationId: Schema.String,
    resolution: Schema.Literal('RECOVER_RETIRE_PACKAGE_DEFINITION'),
    retryCommand: Schema.Literal(false),
  },
);
export const RetirePackageDefinitionActionCommitIndeterminateProblemSchema = makeProblemDetailsSchema(
  'RetirePackageDefinitionActionCommitIndeterminateProblem',
  503,
  {
    invocationId: Schema.String,
    resolution: Schema.Literal('RECOVER_RETIRE_PACKAGE_DEFINITION'),
    retryCommand: Schema.Literal(false),
  },
);
export const RetirePackageDefinitionActionInternalProblemSchema = makeProblemDetailsSchema(
  'RetirePackageDefinitionActionInternalProblem',
  500,
);

export type RetirePackageDefinitionActionProblem =
  | typeof RetirePackageDefinitionActionInvalidProblemSchema.Type
  | typeof RetirePackageDefinitionActionAuthenticationProblemSchema.Type
  | typeof RetirePackageDefinitionActionForbiddenProblemSchema.Type
  | typeof RetirePackageDefinitionActionNotFoundProblemSchema.Type
  | typeof RetirePackageDefinitionActionConflictProblemSchema.Type
  | typeof RetirePackageDefinitionActionIneligibleProblemSchema.Type
  | typeof RetirePackageDefinitionActionPreconditionProblemSchema.Type
  | typeof RetirePackageDefinitionActionUnavailableProblemSchema.Type
  | typeof RetirePackageDefinitionActionAlreadyCommittedProblemSchema.Type
  | typeof RetirePackageDefinitionActionCommitIndeterminateProblemSchema.Type
  | typeof RetirePackageDefinitionActionInternalProblemSchema.Type;

export class RetirePackageDefinitionActionSchemaErrorMiddleware extends HttpApiMiddleware.Service<RetirePackageDefinitionActionSchemaErrorMiddleware>()(
  'catalog/RetirePackageDefinitionActionSchemaErrorMiddleware',
  { error: RetirePackageDefinitionActionInvalidProblemSchema },
) {}

const actionErrors = [
  RetirePackageDefinitionActionInvalidProblemSchema,
  RetirePackageDefinitionActionAuthenticationProblemSchema,
  RetirePackageDefinitionActionForbiddenProblemSchema,
  RetirePackageDefinitionActionNotFoundProblemSchema,
  RetirePackageDefinitionActionConflictProblemSchema,
  RetirePackageDefinitionActionIneligibleProblemSchema,
  RetirePackageDefinitionActionPreconditionProblemSchema,
  RetirePackageDefinitionActionUnavailableProblemSchema,
  RetirePackageDefinitionActionAlreadyCommittedProblemSchema,
  RetirePackageDefinitionActionCommitIndeterminateProblemSchema,
  RetirePackageDefinitionActionInternalProblemSchema,
] as const;

export const RetirePackageDefinitionActionApi = HttpApi.make('RetirePackageDefinitionActionApi').add(
  HttpApiGroup.make('retirePackageDefinitionAction')
    .add(
      HttpApiEndpoint.post('execute', '/catalog/actions/retire-package-definition', {
        error: actionErrors,
        headers: RetirePackageDefinitionActionHeadersSchema,
        payload: Schema.toEncoded(RetirePackageDefinitionPayloadSchema),
        success: RetirePackageDefinitionResultSchema,
      }),
    )
    .middleware(RetirePackageDefinitionActionSchemaErrorMiddleware),
);
