// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import { ReviseConfigurationUnitResultSchema } from '../actions/revise-configuration-unit.ts';
import { ProductActionInvocationIdSchema } from '../domain/product.ts';

export const ReviseConfigurationUnitRecoveryRequestSchema = Schema.Struct({
  invocationId: ProductActionInvocationIdSchema,
});
export type ReviseConfigurationUnitRecoveryRequest = typeof ReviseConfigurationUnitRecoveryRequestSchema.Type;
export const ReviseConfigurationUnitRecoveryResponseSchema = ReviseConfigurationUnitResultSchema;

export const ReviseConfigurationUnitRecoveryAuthenticationProblemSchema = makeProblemDetailsSchema(
  'ReviseConfigurationUnitRecoveryAuthenticationProblem',
  401,
);
export const ReviseConfigurationUnitRecoveryInvalidProblemSchema = makeProblemDetailsSchema(
  'ReviseConfigurationUnitRecoveryInvalidProblem',
  400,
);
export const ReviseConfigurationUnitRecoveryUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'ReviseConfigurationUnitRecoveryUnavailableProblem',
  503,
);
export const ReviseConfigurationUnitRecoveryForbiddenProblemSchema = makeProblemDetailsSchema(
  'ReviseConfigurationUnitRecoveryForbiddenProblem',
  403,
);
export const ReviseConfigurationUnitRecoveryNotFoundProblemSchema = makeProblemDetailsSchema(
  'ReviseConfigurationUnitRecoveryNotFoundProblem',
  404,
);
export const ReviseConfigurationUnitRecoveryPolicyProblemSchema = makeProblemDetailsSchema(
  'ReviseConfigurationUnitRecoveryPolicyProblem',
  422,
);
export const ReviseConfigurationUnitRecoveryPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'ReviseConfigurationUnitRecoveryPolicyConflictProblem',
  409,
);
export const ReviseConfigurationUnitRecoveryInternalProblemSchema = makeProblemDetailsSchema(
  'ReviseConfigurationUnitRecoveryInternalProblem',
  500,
);

export const ReviseConfigurationUnitRecoveryApi = HttpApi.make('ReviseConfigurationUnitRecoveryApi').add(
  HttpApiGroup.make('reviseConfigurationUnitRecovery').add(
    HttpApiEndpoint.post('execute', '/reads/revise-configuration-unit-recovery', {
      error: [
        ReviseConfigurationUnitRecoveryInvalidProblemSchema,
        ReviseConfigurationUnitRecoveryAuthenticationProblemSchema,
        ReviseConfigurationUnitRecoveryForbiddenProblemSchema,
        ReviseConfigurationUnitRecoveryNotFoundProblemSchema,
        ReviseConfigurationUnitRecoveryPolicyConflictProblemSchema,
        ReviseConfigurationUnitRecoveryPolicyProblemSchema,
        ReviseConfigurationUnitRecoveryUnavailableProblemSchema,
        ReviseConfigurationUnitRecoveryInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: ReviseConfigurationUnitRecoveryRequestSchema,
      query: {},
      success: ReviseConfigurationUnitRecoveryResponseSchema,
    }),
  ),
);
