import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { performance } from 'node:perf_hooks';

import { NodeServices } from '@effect/platform-node';
import { Effect } from 'effect';
import { expect, it } from 'effect-rstest';

import { checkDatabaseAccessBoundaries } from '../check-database-access-boundaries.mts';

it.live(
  'allows owner database factories and rejects Action, read, nested BFF, hidden Core database, and second-driver bypasses deterministically',
  () =>
    Effect.gen(function* testEffect1() {
      const root = yield* Effect.acquireRelease(
        Effect.tryPromise(() => mkdtemp(path.join(os.tmpdir(), 'ontos-db-boundary-'))),
        (directory) => Effect.promise(() => rm(directory, { force: true, recursive: true })),
      );
      const files = {
        // Auth persistence sits outside the governed paths, yet must not open a second driver pool.
        'apps/shell/api/auth/db/client.ts':
          "import { drizzle } from 'drizzle-orm/node-postgres';\nimport { Pool } from 'pg';\n",
        'apps/shell/api/auth/db/types.ts': "import type { Pool } from 'pg';\n",
        'apps/shell/api/routes/private.ts': "const database = import(\n  '@app/core-runtime/db/schema'\n);\n",
        'packages/core-runtime/src/testing/actions.ts': 'export const makeActionTestHarness = () => undefined;\n',
        'verticals/stock/api/index.ts': "import { Pool } from 'pg';\n",
        'verticals/stock/api/routes/export.ts': "import { coreDatabaseSchema } from '@app/core-runtime';\n",
        'verticals/stock/src/actions/generated-safe.action.ts':
          "import { defineAction } from '@app/core-runtime/actions/definition';\n",
        'verticals/stock/src/actions/package-root.action.ts':
          "import { InventoryPersistence } from '@app/stock';\nconst reserve = Effect.flatMap(InventoryPersistence, Effect.succeed);\n",
        'verticals/stock/src/actions/reserve.action.ts':
          "import { CoreDatabase } from '@app/core-runtime';\nimport { InventoryPersistence } from '../infrastructure/inventory-persistence.ts';\nconst reserve = Effect.gen(function* testEffect2() { yield* InventoryPersistence; });\n",
        'verticals/stock/src/actions/scoped.action.ts':
          "import { makeScopedServices } from '../services/scoped-services.ts';\n",
        'verticals/stock/src/actions/side-effect.action.ts': "import '../infrastructure/inventory-persistence.ts';\n",
        'verticals/stock/src/db/billing-leak.ts': "import { invoices } from '../../../billing/src/db/schema.ts';\n",
        'verticals/stock/src/db/cross-owner.ts': "import { coreDatabaseSchema } from '@app/core-runtime/db/schema';\n",
        'verticals/stock/src/db/dynamic-core.ts': "const core = import(\n  '@app/core-runtime/db/schema'\n);\n",
        'verticals/stock/src/db/service-factory.ts':
          "import { makeWithDefaults } from 'drizzle-orm/effect-postgres';\n",
        'verticals/stock/src/index.ts':
          "export { InventoryPersistence } from './infrastructure/inventory-persistence.ts';\n",
        'verticals/stock/src/infrastructure/inventory-persistence.ts':
          "import { Pool } from 'pg';\nexport class InventoryPersistence {}\n",
        'verticals/stock/src/portal-auth/persistence/auth-database.ts': "import { Pool } from 'pg';\n",
        'verticals/stock/src/reads/list.read.ts': "import { stock } from '../db/schema.ts';\n",
        'verticals/stock/src/reads/side-effect.read.ts': "import 'pg';\n",
        'verticals/stock/src/services/generated-action-service.ts':
          "// @generated by OntOS Codesmith Action Service v1\nimport { eq } from 'drizzle-orm';\nimport { stock } from '../db/schema.ts';\nexport const findStock = () => eq(stock.id, 'one');\n",
        'verticals/stock/src/services/scoped-services.ts':
          "import { eq } from 'drizzle-orm';\nimport type { NodePgDatabase } from 'drizzle-orm/node-postgres';\nexport const makeScopedServices = (_transaction: Pick<NodePgDatabase, 'select'>) => eq;\n",
        'verticals/stock/src/testing-harness-dynamic-leak.ts':
          "const harness = import('../../../packages/core-runtime/src/testing/actions.ts');\n",
        'verticals/stock/src/testing-harness-export-leak.ts':
          "export { makeActionTestHarness } from '@app/core-runtime/testing/actions';\n",
        'verticals/stock/src/testing-harness-leak.ts':
          "import { makeActionTestHarness } from '@app/core-runtime/testing/actions';\n",
        'verticals/stock/tests/generated-source.test.ts':
          '// @generated by OntOS Codesmith Governed Contribution\nconst assertion = /CoreDatabase/;\n',
        'verticals/stock/tests/testing-harness.test.ts':
          "import { makeActionTestHarness } from '@app/core-runtime/testing/actions';\n",
      } as const;
      yield* Effect.all(
        Object.entries(files).map(([relative, source]) =>
          Effect.gen(function* testEffect3() {
            const file = path.join(root, relative);
            yield* Effect.tryPromise(() => mkdir(path.dirname(file), { recursive: true }));
            yield* Effect.tryPromise(() => writeFile(file, source));
          }),
        ),
      );
      const violations = yield* checkDatabaseAccessBoundaries(root).pipe(Effect.provide(NodeServices.layer));
      expect(violations.map(({ file, line }) => `${file}:${line}`)).toEqual([
        'apps/shell/api/auth/db/client.ts:1',
        'apps/shell/api/auth/db/client.ts:2',
        'apps/shell/api/routes/private.ts:1',
        'verticals/stock/api/index.ts:1',
        'verticals/stock/api/routes/export.ts:1',
        'verticals/stock/src/actions/package-root.action.ts:1',
        'verticals/stock/src/actions/reserve.action.ts:1',
        'verticals/stock/src/actions/reserve.action.ts:2',
        'verticals/stock/src/actions/side-effect.action.ts:1',
        'verticals/stock/src/db/billing-leak.ts:1',
        'verticals/stock/src/db/cross-owner.ts:1',
        'verticals/stock/src/db/dynamic-core.ts:1',
        'verticals/stock/src/infrastructure/inventory-persistence.ts:1',
        'verticals/stock/src/portal-auth/persistence/auth-database.ts:1',
        'verticals/stock/src/reads/list.read.ts:1',
        'verticals/stock/src/reads/side-effect.read.ts:1',
        'verticals/stock/src/testing-harness-dynamic-leak.ts:1',
        'verticals/stock/src/testing-harness-export-leak.ts:1',
        'verticals/stock/src/testing-harness-leak.ts:1',
      ]);
    }),
);

it.live('checks shared transitive import graphs without revisiting every import path', () =>
  Effect.gen(function* sharedTransitiveImportGraph() {
    const root = yield* Effect.acquireRelease(
      Effect.tryPromise(() => mkdtemp(path.join(os.tmpdir(), 'ontos-db-boundary-diamond-'))),
      (directory) => Effect.promise(() => rm(directory, { force: true, recursive: true })),
    );
    const write = (relative: string, source: string) =>
      Effect.gen(function* writeSource() {
        const file = path.join(root, relative);
        yield* Effect.tryPromise(() => mkdir(path.dirname(file), { recursive: true }));
        yield* Effect.tryPromise(() => writeFile(file, source));
      });

    yield* write(
      'verticals/stock/src/actions/check.action.ts',
      "import '../graph/left-0.ts';\nimport '../graph/right-0.ts';\n",
    );
    yield* Effect.forEach(
      Array.from({ length: 18 }, (_, index) => index),
      (index) => {
        const next = index + 1;
        const source =
          index === 17 ? 'export const leaf = true;\n' : `import './left-${next}.ts';\nimport './right-${next}.ts';\n`;
        return Effect.all(
          [
            write(`verticals/stock/src/graph/left-${index}.ts`, source),
            write(`verticals/stock/src/graph/right-${index}.ts`, source),
          ],
          { concurrency: 2, discard: true },
        );
      },
      { concurrency: 1, discard: true },
    );

    const started = performance.now();
    const violations = yield* checkDatabaseAccessBoundaries(root).pipe(Effect.provide(NodeServices.layer));
    const elapsedMilliseconds = performance.now() - started;

    expect(violations).toEqual([]);
    expect(elapsedMilliseconds).toBeLessThan(500);
  }),
);

it.live('allows private scoped service factories but rejects executor exposure to handlers', () =>
  Effect.gen(function* scopedServiceFactoryBoundary() {
    const root = yield* Effect.acquireRelease(
      Effect.tryPromise(() => mkdtemp(path.join(os.tmpdir(), 'ontos-db-boundary-scoped-factory-'))),
      (directory) => Effect.promise(() => rm(directory, { force: true, recursive: true })),
    );
    const files = {
      'verticals/stock/src/actions/leaky.action.ts':
        "import type { OperationalScope, ScopedTransactionExecutor as Executor } from '@app/core-runtime';\ninterface LeakyHandlerServices { readonly transaction: Executor; }\nconst handle = (transaction: Executor) => transaction;\n",
      'verticals/stock/src/actions/safe.action.ts':
        "import type { OperationalScope, ScopedTransactionExecutor as Executor } from '@app/core-runtime';\ninterface ScopedAuthority { readonly forScope: (transaction: Executor, scope: OperationalScope) => unknown; }\nconst actionServicesForScope = function* actionServicesForScope(transaction: Executor, scope: OperationalScope) { yield scope; return {}; };\n",
    } as const;
    yield* Effect.all(
      Object.entries(files).map(([relative, source]) =>
        Effect.gen(function* writeSource() {
          const file = path.join(root, relative);
          yield* Effect.tryPromise(() => mkdir(path.dirname(file), { recursive: true }));
          yield* Effect.tryPromise(() => writeFile(file, source));
        }),
      ),
    );

    const violations = yield* checkDatabaseAccessBoundaries(root).pipe(Effect.provide(NodeServices.layer));
    expect(violations.map(({ file, line }) => `${file}:${line}`)).toEqual([
      'verticals/stock/src/actions/leaky.action.ts:2',
      'verticals/stock/src/actions/leaky.action.ts:3',
    ]);
  }),
);
