import { execFileSync } from 'node:child_process';
import { access, mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { NodeServices } from '@effect/platform-node';
import { Cause, Effect, Exit } from 'effect';
import { expect, it } from 'effect-rstest';

import { hashAuthorizationEvidence } from '../check-authorization-readiness.mts';
import {
  planDeploymentImpact as planDeploymentImpactEffect,
  validateAuthorizationPromotionGate,
} from '../plan-deployment-impact.mts';
import type { AuthorizationPromotionGateInput, PlanDeploymentImpactOptions } from '../plan-deployment-impact.mts';

const planningFailure = <A, E>(effect: Effect.Effect<A, E>) =>
  effect.pipe(
    Effect.exit,
    Effect.map(
      Exit.match({
        onFailure: Cause.pretty,
        onSuccess: () => {
          throw new Error('Expected planning failure');
        },
      }),
    ),
  );

interface FixtureOptions {
  readonly includeContactOwner?: boolean;
  readonly includeWorker?: boolean;
  readonly setupIds?: readonly string[];
  readonly verticalId?: string;
}

interface FixtureOwner {
  readonly id: string;
  readonly package: string;
  readonly path: string;
}

interface FixtureOwnership {
  readonly owners: readonly FixtureOwner[];
  readonly schemaVersion?: number;
}

interface FixtureTopology {
  readonly schemaVersion: number;
  readonly sharedPackages: readonly FixtureOwner[];
  readonly shell: {
    readonly id: string;
    readonly package: string;
    readonly verticalRefs: readonly string[];
  };
  readonly verticals: readonly {
    readonly id: string;
    readonly moduleFederation: {
      readonly remotes: readonly string[];
      readonly verticalRefs: readonly string[];
    };
    readonly package: string;
    readonly path: string;
  }[];
}

type FixtureDocument = FixtureOwnership | FixtureTopology;

const CORE_RUNTIME_OWNER = {
  id: 'core-runtime',
  package: '@app/core-runtime',
  path: 'packages/core-runtime',
} as const satisfies FixtureOwner;
const SHARED_CONTRACTS_OWNER = {
  id: 'shared-contracts',
  package: '@app/shared-contracts',
  path: 'packages/shared-contracts',
} as const satisfies FixtureOwner;
const SHELL_ID = 'shell-super-app';
const SHELL_PACKAGE = '@app/shell-super-app';
const SHELL_OWNER = {
  id: SHELL_ID,
  package: SHELL_PACKAGE,
  path: 'apps/shell-super-app',
} as const satisfies FixtureOwner;
const OWNERSHIP_PATH = 'topology/ownership.json';
const DOCUMENTATION_PATH = 'docs/README.md';

const planDeploymentImpact = (options: PlanDeploymentImpactOptions) =>
  planDeploymentImpactEffect(options).pipe(Effect.provide(NodeServices.layer));

const writeJson = (root: string, relativePath: string, value: FixtureDocument) =>
  Effect.gen(function* testEffect1() {
    const target = path.join(root, relativePath);
    yield* Effect.tryPromise(() => mkdir(path.dirname(target), { recursive: true }));
    yield* Effect.tryPromise(() => writeFile(target, `${JSON.stringify(value, undefined, 2)}\n`, 'utf-8'));
  });

const makeFixture = (options: FixtureOptions = {}) =>
  Effect.gen(function* testEffect2() {
    const root = yield* Effect.acquireRelease(
      Effect.tryPromise(() => mkdtemp(path.join(os.tmpdir(), 'ontos-deployment-impact-'))),
      (directory) => Effect.tryPromise(() => rm(directory, { force: true, recursive: true })).pipe(Effect.orDie),
    );
    const verticalId = options.verticalId ?? 'contacts';
    const verticalPackage = `@app/${verticalId}`;
    const verticalPath = `verticals/${verticalId}`;
    yield* writeJson(root, 'topology/reference-topology.json', {
      schemaVersion: 1,
      sharedPackages: [CORE_RUNTIME_OWNER, SHARED_CONTRACTS_OWNER],
      shell: {
        id: SHELL_ID,
        package: SHELL_PACKAGE,
        verticalRefs: [verticalId],
      },
      verticals: [
        {
          id: verticalId,
          moduleFederation: { remotes: [], verticalRefs: [] },
          package: verticalPackage,
          path: verticalPath,
        },
      ],
    });
    yield* writeJson(root, OWNERSHIP_PATH, {
      owners: [
        CORE_RUNTIME_OWNER,
        SHARED_CONTRACTS_OWNER,
        SHELL_OWNER,
        ...(options.includeContactOwner === false
          ? []
          : [{ id: verticalId, package: verticalPackage, path: verticalPath }]),
      ],
      schemaVersion: 1,
    });
    if (options.includeWorker === true) {
      const workerRoot = path.join(root, verticalPath);
      yield* Effect.tryPromise(() => mkdir(path.join(workerRoot, 'src/worker-host'), { recursive: true }));
      yield* Effect.tryPromise(() =>
        writeFile(
          path.join(workerRoot, 'package.json'),
          `${JSON.stringify({ name: verticalPackage, scripts: { 'worker:start': 'node --experimental-strip-types ./src/worker-host/main.ts' } })}\n`,
        ),
      );
      yield* Effect.tryPromise(() =>
        writeFile(
          path.join(workerRoot, 'src/worker-host/main.ts'),
          '// @generated by scaffold:outbox-worker worker-host\n',
        ),
      );
    }
    const setups = options.setupIds ?? [
      'migrator',
      'spicedb',
      verticalId,
      ...(options.includeWorker === true ? [`${verticalId}-worker`] : []),
      'shellsuperapp',
    ];
    const setupLines = setups.map((setup) => `  - setup: '${setup}'`).join('\n');
    yield* Effect.tryPromise(() => writeFile(path.join(root, 'zerops.yaml'), `zerops:\n${setupLines}\n`, 'utf-8'));
    return root;
  });

const withFixture = (run: (root: string) => Effect.Effect<void, unknown>, options?: FixtureOptions) =>
  Effect.gen(function* testEffect3() {
    const root = yield* makeFixture(options);
    yield* run(root);
  }).pipe(Effect.scoped);

for (const termination of ['failure', 'interruption'] as const) {
  it.live(`removes the fixture after ${termination}`, () =>
    Effect.gen(function* verifiesFixtureCleanup() {
      let fixtureRoot = '';
      const outcome = yield* withFixture((root) => {
        fixtureRoot = root;
        return termination === 'failure' ? Effect.fail('fixture failure') : Effect.interrupt;
      }).pipe(Effect.exit);
      expect(Exit.isFailure(outcome)).toBe(true);
      expect(fixtureRoot).not.toBe('');
      const remaining = yield* Effect.tryPromise(() => access(fixtureRoot)).pipe(Effect.exit);
      expect(Exit.isFailure(remaining)).toBe(true);
    }),
  );
}

it.live('deploys a generated owner worker immediately after its provider', () =>
  Effect.gen(function* testEffect4() {
    yield* withFixture(
      (root) =>
        Effect.gen(function* testEffect5() {
          const plan = yield* planDeploymentImpact({
            changedPaths: ['verticals/contacts/src/workers/project-contact.worker.ts'],
            rootDirectory: root,
          });
          expect(plan.units.providers).toEqual(['contacts', 'contacts-worker']);
          expect(plan.phases.map((phase) => phase.id)).toEqual(['contacts', 'contacts-worker']);
          expect(plan.phases[1]?.serviceIdEnv).toBe('ZEROPS_CONTACTS_WORKER_SERVICE_ID');
        }),
      { includeWorker: true },
    );
  }),
);

const runGit = (root: string, argumentsList: readonly string[]): string =>
  execFileSync(
    '/usr/bin/git',
    ['-c', 'user.email=ontos-ci@example.invalid', '-c', 'user.name=OntOS CI', ...argumentsList],
    {
      cwd: root,
      encoding: 'utf-8',
    },
  ).trim();

it.live('plans current Contacts owner-local changes without a hard-coded owner registry', () =>
  Effect.gen(function* testEffect6() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect7() {
        const plan = yield* planDeploymentImpact({
          changedPaths: ['app/verticals/contacts/src/features/customers/customer-form.tsx'],
          rootDirectory: root,
        });
        expect(plan.units).toEqual({
          migrator: false,
          providers: ['contacts'],
          shell: false,
          spicedb: false,
        });
        expect(plan.phases.map((phase) => phase.id)).toEqual(['contacts']);
      }),
    );
  }),
);

it.live('orders authorization schema and replay migration before every affected consumer', () =>
  Effect.gen(function* testEffect8() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect9() {
        const plan = yield* planDeploymentImpact({
          changedPaths: ['app/scripts/authorization/rollout-contract.mts'],
          rootDirectory: root,
        });
        expect(plan.phases.map(({ id }) => id)).toEqual(['migrator', 'spicedb', 'contacts', SHELL_ID]);
      }),
    );
  }),
);

it.live('plans Shell-only changes for the topology-derived Shell owner', () =>
  Effect.gen(function* testEffect10() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect11() {
        const plan = yield* planDeploymentImpact({
          changedPaths: ['apps/shell-super-app/src/routes/shell-frame.tsx'],
          rootDirectory: root,
        });
        expect(plan.phases.map((phase) => phase.id)).toEqual([SHELL_ID]);
        expect(plan.units.shell).toBe(true);
      }),
    );
  }),
);

it.live('adds the migrator before an owner whose schema or migration contract changed', () =>
  Effect.gen(function* testEffect12() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect13() {
        const plan = yield* planDeploymentImpact({
          changedPaths: ['verticals/contacts/drizzle/0003_add_customer.sql'],
          rootDirectory: root,
        });
        expect(plan.phases.map((phase) => phase.id)).toEqual(['migrator', 'contacts']);
      }),
    );
  }),
);

for (const changedPath of [
  'scripts/run-zerops-migrator.mjs',
  'scripts/verify-application-db-schema.mts',
  'scripts/postgres/bootstrap-runtime-role.mts',
]) {
  it.live(`includes the migrator for root migration contract ${changedPath}`, () =>
    Effect.gen(function* testEffect14() {
      yield* withFixture((root) =>
        Effect.gen(function* testEffect15() {
          const plan = yield* planDeploymentImpact({
            changedPaths: [changedPath],
            rootDirectory: root,
          });
          expect(plan.phases.map((phase) => phase.id)).toEqual(['migrator']);
        }),
      );
    }),
  );
}

it.live('expands shared-package changes to every consumer in dependency order', () =>
  Effect.gen(function* testEffect18() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect19() {
        const plan = yield* planDeploymentImpact({
          changedPaths: ['packages/shared-contracts/src/gateway-context.ts'],
          rootDirectory: root,
        });
        expect(plan.phases.map((phase) => phase.id)).toEqual(['contacts', SHELL_ID]);
      }),
    );
  }),
);

it.live('expands a provider public-contract change to the dependent Shell', () =>
  Effect.gen(function* testEffect20() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect21() {
        const plan = yield* planDeploymentImpact({
          changedPaths: ['verticals/contacts/shared/api.ts'],
          rootDirectory: root,
        });
        expect(plan.phases.map((phase) => phase.id)).toEqual(['contacts', SHELL_ID]);
      }),
    );
  }),
);

it.live('orders SpiceDB before all consumers for authorization runtime changes', () =>
  Effect.gen(function* testEffect22() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect23() {
        const plan = yield* planDeploymentImpact({
          changedPaths: ['packages/core-runtime/spicedb/bootstrap.yaml'],
          rootDirectory: root,
        });
        expect(plan.phases.map((phase) => phase.id)).toEqual(['spicedb', 'contacts', SHELL_ID]);
      }),
    );
  }),
);

for (const changedPath of [
  'scripts/postgres/bootstrap-spicedb-database.mts',
  'packages/core-runtime/src/install/spicedb-database-config.ts',
  'pnpm-lock.yaml',
  'pnpm-workspace.yaml',
  '.mise.toml',
  'scripts/generate-outbox-worker-deployment.mjs',
  'scripts/materialize-outbox-worker.mjs',
  'scripts/materialize-zerops-runtime.mjs',
  'scripts/outbox-worker-delivery.mjs',
  'scripts/install-zerops-node.sh',
  'zerops.yaml',
  'topology/reference-topology.json',
]) {
  it.live(`conservatively deploys every phase for ${changedPath}`, () =>
    Effect.gen(function* testEffect24() {
      yield* withFixture((root) =>
        Effect.gen(function* testEffect25() {
          const plan = yield* planDeploymentImpact({
            changedPaths: [changedPath],
            rootDirectory: root,
          });
          expect(plan.phases.map((phase) => phase.id)).toEqual(['migrator', 'spicedb', 'contacts', SHELL_ID]);
        }),
      );
    }),
  );
}

it.live('produces a reviewed no-op for documentation-only changes', () =>
  Effect.gen(function* testEffect26() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect27() {
        const plan = yield* planDeploymentImpact({
          changedPaths: ['docs/architecture/DEPLOYMENT.md'],
          rootDirectory: root,
        });
        expect(plan.any).toBe(false);
        expect(plan.phases).toEqual([]);
      }),
    );
  }),
);

it.live('fails closed for the unknown destination of a renamed application directory', () =>
  Effect.gen(function* testEffect28() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect29() {
        expect(
          yield* planningFailure(
            planDeploymentImpact({
              changedPaths: ['verticals/contacts/src/index.ts', 'verticals/relationships/src/index.ts'],
              rootDirectory: root,
            }),
          ),
        ).toMatch(/unknown changed path "verticals\/relationships\/src\/index\.ts" in application area "verticals"/u);
      }),
    );
  }),
);

it.live('fails closed when a topology delivery unit has no ownership entry', () =>
  Effect.gen(function* testEffect30() {
    yield* withFixture(
      (root) =>
        Effect.gen(function* testEffect31() {
          expect(
            yield* planningFailure(
              planDeploymentImpact({
                changedPaths: [DOCUMENTATION_PATH],
                rootDirectory: root,
              }),
            ),
          ).toMatch(/topology delivery unit "contacts" is missing from topology\/ownership\.json/u);
        }),
      { includeContactOwner: false },
    );
  }),
);

it.live('fails closed when topology and ownership identities disagree', () =>
  Effect.gen(function* testEffect32() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect33() {
        yield* writeJson(root, OWNERSHIP_PATH, {
          owners: [
            CORE_RUNTIME_OWNER,
            SHARED_CONTRACTS_OWNER,
            SHELL_OWNER,
            {
              id: 'contacts',
              package: '@app/contacts-old',
              path: 'verticals/contacts-old',
            },
          ],
        });
        expect(
          yield* planningFailure(
            planDeploymentImpact({
              changedPaths: [DOCUMENTATION_PATH],
              rootDirectory: root,
            }),
          ),
        ).toMatch(/topology and ownership disagree for "contacts"/u);
      }),
    );
  }),
);

it.live('fails closed when shared-package topology and ownership identities disagree', () =>
  Effect.gen(function* testEffect34() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect35() {
        yield* writeJson(root, OWNERSHIP_PATH, {
          owners: [
            { ...CORE_RUNTIME_OWNER, path: 'packages/core-runtime-old' },
            SHARED_CONTRACTS_OWNER,
            SHELL_OWNER,
            {
              id: 'contacts',
              package: '@app/contacts',
              path: 'verticals/contacts',
            },
          ],
        });
        expect(
          yield* planningFailure(
            planDeploymentImpact({
              changedPaths: [DOCUMENTATION_PATH],
              rootDirectory: root,
            }),
          ),
        ).toMatch(/topology and ownership disagree for shared package "core-runtime"/u);
      }),
    );
  }),
);

it.live('fails closed when a topology unit has no supported stage setup', () =>
  Effect.gen(function* testEffect36() {
    yield* withFixture(
      (root) =>
        Effect.gen(function* testEffect37() {
          expect(
            yield* planningFailure(
              planDeploymentImpact({
                changedPaths: [DOCUMENTATION_PATH],
                rootDirectory: root,
              }),
            ),
          ).toMatch(/topology delivery unit "contacts" has unsupported stage setup "contacts"/u);
        }),
      { setupIds: ['migrator', 'spicedb', 'shellsuperapp'] },
    );
  }),
);

it.live('uses a safe full deployment for an all-zero comparison base', () =>
  Effect.gen(function* testEffect38() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect39() {
        const plan = yield* planDeploymentImpact({
          baseRevision: '0000000000000000000000000000000000000000',
          headRevision: 'HEAD',
          rootDirectory: root,
        });
        expect(plan.comparison.mode).toBe('full');
        expect(plan.comparison.reason ?? '').toMatch(/all-zero/u);
        expect(plan.phases.map((phase) => phase.id)).toEqual(['migrator', 'spicedb', 'contacts', SHELL_ID]);
      }),
    );
  }),
);

it.live('uses a safe full deployment for an unavailable comparison base', () =>
  Effect.gen(function* testEffect40() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect41() {
        const plan = yield* planDeploymentImpact({
          baseRevision: 'missing-base-revision',
          headRevision: 'HEAD',
          rootDirectory: root,
        });
        expect(plan.comparison.mode).toBe('full');
        expect(plan.comparison.reason ?? '').toMatch(/comparison base "missing-base-revision" is unavailable/u);
      }),
    );
  }),
);

it.live('uses a safe full deployment when the comparison base is not an ancestor', () =>
  Effect.gen(function* testEffect42() {
    yield* withFixture((root) =>
      Effect.gen(function* testEffect43() {
        runGit(root, ['init']);
        runGit(root, ['add', '.']);
        runGit(root, ['commit', '-m', 'fixture root']);
        const rootRevision = runGit(root, ['rev-parse', 'HEAD']);
        yield* Effect.tryPromise(() => writeFile(path.join(root, 'main-marker.txt'), 'main\n', 'utf-8'));
        runGit(root, ['add', 'main-marker.txt']);
        runGit(root, ['commit', '-m', 'main change']);
        const rewrittenBase = runGit(root, ['rev-parse', 'HEAD']);
        runGit(root, ['checkout', '-b', 'rewritten', rootRevision]);
        yield* Effect.tryPromise(() => writeFile(path.join(root, 'rewritten-marker.txt'), 'rewritten\n', 'utf-8'));
        runGit(root, ['add', 'rewritten-marker.txt']);
        runGit(root, ['commit', '-m', 'rewritten change']);

        const plan = yield* planDeploymentImpact({
          baseRevision: rewrittenBase,
          headRevision: 'HEAD',
          rootDirectory: root,
        });
        expect(plan.comparison.mode).toBe('full');
        expect(plan.comparison.reason ?? '').toMatch(/is not an ancestor/u);
      }),
    );
  }),
);

it.live('changing a topology identity changes the plan without editing planner source', () =>
  Effect.gen(function* testEffect44() {
    yield* withFixture(
      (root) =>
        Effect.gen(function* testEffect45() {
          const plan = yield* planDeploymentImpact({
            changedPaths: ['verticals/relationships/src/index.ts'],
            rootDirectory: root,
          });
          expect(plan.units.providers).toEqual(['relationships']);
          expect(plan.phases.map((phase) => phase.id)).toEqual(['relationships']);
          expect(plan.phases[0]?.serviceIdEnv).toBe('ZEROPS_RELATIONSHIPS_SERVICE_ID');
        }),
      { verticalId: 'relationships' },
    );
  }),
);

const promotionFixture = (): AuthorizationPromotionGateInput => {
  const inventory = {
    entries: [
      {
        authorization: { kind: 'public' as const },
        deployment: 'contacts',
        entrypointKey: 'contacts.route.home',
        owner: 'contacts.core',
        surface: 'route' as const,
      },
    ],
    inventoryHash: 'a'.repeat(64),
    schemaVersion: 1 as const,
    sourceRevision: 'revision',
  };
  const impact = {
    aggregates: [],
    inventoryHash: inventory.inventoryHash,
    observation: {
      endedAt: '2026-09-10T00:00:00.000Z',
      startedAt: '2026-09-02T00:00:00.000Z',
    },
    schemaVersion: 1 as const,
    sourceRevision: inventory.sourceRevision,
    totalWouldDeny: 0,
  };
  const negativeSmoke = {
    environment: 'stage' as const,
    inventoryHash: inventory.inventoryHash,
    scenarios: [],
    schemaVersion: 1 as const,
    sourceRevision: inventory.sourceRevision,
  };
  return {
    environment: 'stage',
    impact,
    inventory,
    negativeSmoke,
    nowEpochMs: Date.parse('2026-10-02T00:00:00.000Z'),
    readiness: {
      approvalReference: 'https://github.com/TechsioCZ/ontos/issues/169',
      environment: 'stage',
      fixedContextHash: 'b'.repeat(64),
      impactReportHash: hashAuthorizationEvidence(impact),
      inventoryHash: inventory.inventoryHash,
      moduleStateVersion: 'module-state-v1',
      negativeSmokeHash: hashAuthorizationEvidence(negativeSmoke),
      observation: { ...impact.observation },
      policyDataVersion: 'policy-v1',
      replayMigrationHash: 'c'.repeat(64),
      schemaVersion: 1,
      sourceRevision: inventory.sourceRevision,
      spiceDbSchemaHash: 'd'.repeat(64),
      status: 'ready',
      workerOwnershipVersion: 'worker-v1',
    },
    rollout: {
      activatedAt: '2026-09-01T00:00:00.000Z',
      baselineInventoryHash: inventory.inventoryHash,
      baselineSourceRevision: inventory.sourceRevision,
      compatibilityEligibleEntrypoints: [],
      decisionReference: 'https://github.com/TechsioCZ/ontos/issues/169',
      expiresAt: '2026-09-30T00:00:00.000Z',
      mode: 'enforced',
      schemaVersion: 1,
    },
  };
};

const withoutImpactEvidence = (input: AuthorizationPromotionGateInput): AuthorizationPromotionGateInput => {
  const { impact, ...remaining } = input;
  expect(impact !== undefined).toBe(true);
  return remaining;
};

const withoutNegativeSmokeEvidence = (input: AuthorizationPromotionGateInput): AuthorizationPromotionGateInput => {
  const { negativeSmoke, ...remaining } = input;
  expect(negativeSmoke !== undefined).toBe(true);
  return remaining;
};

const withoutReadinessEvidence = (input: AuthorizationPromotionGateInput): AuthorizationPromotionGateInput => {
  const { readiness, ...remaining } = input;
  expect(readiness !== undefined).toBe(true);
  return remaining;
};

it('requires exact impact, readiness, and negative-smoke evidence for enforced promotion', () => {
  expect(validateAuthorizationPromotionGate(promotionFixture())).toEqual({
    environment: 'stage',
    mode: 'enforced',
    status: 'ready',
  });
  for (const changed of [
    withoutImpactEvidence(promotionFixture()),
    withoutNegativeSmokeEvidence(promotionFixture()),
    withoutReadinessEvidence(promotionFixture()),
  ]) {
    expect(() => validateAuthorizationPromotionGate(changed)).toThrow(/requires impact/u);
  }
  const stale = promotionFixture();
  const staleReadiness = stale.readiness;
  expect(staleReadiness).toBeDefined();
  if (staleReadiness === undefined) {
    throw new Error('Expected readiness evidence');
  }
  expect(() =>
    validateAuthorizationPromotionGate({
      ...stale,
      readiness: { ...staleReadiness, inventoryHash: 'f'.repeat(64) },
    }),
  ).toThrow(/stale, mismatched/u);
});

it('report-only promotion is bounded, explicit-baseline-only, and never allowed in production', () => {
  const enforced = promotionFixture();
  const withoutRequiredEvidence = withoutReadinessEvidence(
    withoutNegativeSmokeEvidence(withoutImpactEvidence(enforced)),
  );
  const reportOnly = {
    ...withoutRequiredEvidence,
    nowEpochMs: Date.parse('2026-09-10T00:00:00.000Z'),
    rollout: { ...enforced.rollout, mode: 'report_only' as const },
  };
  expect(validateAuthorizationPromotionGate(reportOnly).status).toBe('observing');
  expect(() =>
    validateAuthorizationPromotionGate({
      ...reportOnly,
      environment: 'production',
    }),
  ).toThrow(/production.*report-only/u);
  expect(() =>
    validateAuthorizationPromotionGate({
      ...reportOnly,
      nowEpochMs: Date.parse(reportOnly.rollout.expiresAt),
    }),
  ).toThrow(/inactive or expired/u);
  expect(() =>
    validateAuthorizationPromotionGate({
      ...reportOnly,
      rollout: {
        ...reportOnly.rollout,
        compatibilityEligibleEntrypoints: ['contacts.route.new'],
      },
    }),
  ).toThrow(/unknown entrypoint/u);
});
