// @generated by OntOS Codesmith module-api v1
import {
  ReadHandlerNotFound,
  ReadHandlerUnavailable,
  defineRead,
  defineTenantModuleEntrypoint,
} from '@app/core-runtime';
import type { ReadHandlerContext, ReadHandlerResult } from '@app/core-runtime';
import { Effect, Option } from 'effect';
import { TaxRuleHistoryRequestSchema, TaxRuleHistoryResponseSchema } from '../../shared/apis/tax-rule-history.ts';
import type { TaxRuleHistoryRequest, TaxRuleHistoryResponse } from '../../shared/apis/tax-rule-history.ts';
import { taxGovernedReadsForScope } from '../services/tax-governed-read.service.ts';
import type { TaxGovernedReads } from '../services/tax-governed-read.service.ts';

const MODULE_KEY = 'commerce.tax';

interface TaxRuleHistoryServices {
  readonly governed: TaxGovernedReads;
}

const taxRuleHistoryEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'tax.evidence.read' },
  entrypointKey: 'commerce.tax.api.tax-rule-history',
  moduleKey: MODULE_KEY,
  role: 'api',
});

export const readTaxRuleHistory = (
  input: TaxRuleHistoryRequest,
  context: ReadHandlerContext<TaxRuleHistoryServices>,
): Effect.Effect<ReadHandlerResult<TaxRuleHistoryResponse>, ReadHandlerNotFound | ReadHandlerUnavailable> =>
  context.services.governed.taxRuleHistory(input).pipe(
    Effect.catchTag('TaxGovernancePersistenceUnavailable', () =>
      Effect.fail(
        new ReadHandlerUnavailable({
          code: 'read_handler_unavailable',
          reason: 'The Tax Rule history is temporarily unavailable',
        }),
      ),
    ),
    Effect.flatMap(
      Option.match({
        onNone: () =>
          Effect.fail(
            new ReadHandlerNotFound({ code: 'read_handler_not_found', reason: 'The Tax Rule does not exist' }),
          ),
        onSome: (result) => Effect.succeed({ evidence: { resultCount: 1 }, result }),
      }),
    ),
  );

export const taxRuleHistoryRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: taxRuleHistoryEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.tax.api.tax-rule-history.evidence.v1',
    },
    inputSchema: TaxRuleHistoryRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: MODULE_KEY,
    permissionTarget: 'module',
    policies: [],
    readKey: 'commerce.tax.api.tax-rule-history',
    resultSchema: TaxRuleHistoryResponseSchema,
    schemaVersion: '1',
  },
  readTaxRuleHistory,
  (transaction, scope) => Effect.succeed({ governed: taxGovernedReadsForScope(transaction, scope) }),
  () => ({ kind: 'module', moduleId: MODULE_KEY }),
);
