// @generated by OntOS Codesmith module-api v1
import { defineRead, defineTenantModuleEntrypoint } from '@app/core-runtime';
import type { ReadHandlerResult } from '@app/core-runtime';
import { Effect } from 'effect';
import {
  TaxMaterialityComparisonRequestSchema,
  TaxMaterialityComparisonResponseSchema,
} from '../../shared/apis/tax-materiality-comparison.ts';
import type {
  TaxMaterialityComparisonRequest,
  TaxMaterialityComparisonResponse,
} from '../../shared/apis/tax-materiality-comparison.ts';
import { compareTaxMateriality } from '../domain/tax-materiality.ts';
import { taxMeaningFingerprint } from '../services/tax-governance-fingerprint.ts';

const MODULE_KEY = 'commerce.tax';

const taxMaterialityComparisonEntrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: { kind: 'context_permission', permission: 'tax.governed.read' },
  entrypointKey: 'commerce.tax.api.tax-materiality-comparison',
  moduleKey: MODULE_KEY,
  role: 'api',
});

/** Stateless: the comparison reads no TAX state and persists nothing (#943 F11-F13). */
export const readTaxMaterialityComparison = (
  input: TaxMaterialityComparisonRequest,
): Effect.Effect<ReadHandlerResult<TaxMaterialityComparisonResponse>> =>
  Effect.succeed({ evidence: { resultCount: 1 }, result: compareTaxMateriality(input, taxMeaningFingerprint) });

export const taxMaterialityComparisonRead = defineRead(
  {
    accessKind: 'detail',
    entrypoint: taxMaterialityComparisonEntrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.tax.api.tax-materiality-comparison.evidence.v1',
    },
    inputSchema: TaxMaterialityComparisonRequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: MODULE_KEY,
    permissionTarget: 'module',
    policies: [],
    readKey: 'commerce.tax.api.tax-materiality-comparison',
    resultSchema: TaxMaterialityComparisonResponseSchema,
    schemaVersion: '1',
  },
  readTaxMaterialityComparison,
  () => Effect.succeed({}),
  () => ({ kind: 'module', moduleId: MODULE_KEY }),
);
