// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner party.registry
// @ontos-resource-slug duplicate-candidate-case
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(300));
const TenantIdSchema = Schema.String.check(Schema.isUUID());

export const DuplicateCandidateCaseRefSchema = Schema.Struct({
  moduleId: Schema.Literal('party.registry'),
  resourceId: ResourceIdSchema,
  resourceType: Schema.Literal('party.registry.duplicate-candidate-case'),
  tenantId: TenantIdSchema,
});
export type DuplicateCandidateCaseRef = typeof DuplicateCandidateCaseRefSchema.Type;
export const makeDuplicateCandidateCaseRef = (
  tenantId: string,
  resourceId: string,
): DuplicateCandidateCaseRef => ({
  moduleId: 'party.registry',
  resourceId,
  resourceType: 'party.registry.duplicate-candidate-case',
  tenantId,
});

export const duplicateCandidateCaseResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: true,
  },
  description: 'Duplicate Candidate Case resource.',
  key: 'party.registry.duplicate-candidate-case',
  label: 'Duplicate Candidate Case',
  owningModuleId: 'party.registry',
} as const satisfies OntosResourceType;
