// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner party.registry
// @ontos-resource-slug party-match-decision
import { timelineResource } from './timeline-resource.ts';

export const {
  descriptor: partyMatchDecisionResourceDescriptor,
  makeRef: makePartyMatchDecisionRef,
  refSchema: PartyMatchDecisionRefSchema,
} = timelineResource('party-match-decision', 'Party Match Decision');
export type PartyMatchDecisionRef = typeof PartyMatchDecisionRefSchema.Type;
