// @generated by OntOS Codesmith Resource v1
// @ontos-resource-owner party.registry
// @ontos-resource-slug party-contact-point
import type { OntosResourceType } from '@app/core-runtime';
import { Schema } from 'effect';

const ResourceIdSchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(300));
const TenantIdSchema = Schema.String.check(Schema.isUUID());

export const PartyContactPointRefSchema = Schema.Struct({
  moduleId: Schema.Literal('party.registry'),
  resourceId: ResourceIdSchema,
  resourceType: Schema.Literal('party.registry.party-contact-point'),
  tenantId: TenantIdSchema,
});
export type PartyContactPointRef = typeof PartyContactPointRefSchema.Type;

export const partyContactPointResourceDescriptor = {
  capabilities: {
    graphVisible: false,
    linkable: false,
    mediaAttachable: false,
    searchable: false,
    timelineVisible: false,
  },
  description: 'Party Contact Point resource.',
  key: 'party.registry.party-contact-point',
  label: 'Party Contact Point',
  owningModuleId: 'party.registry',
} as const satisfies OntosResourceType;
