// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug create-product-relationship
import type { ActionHandlerContext } from '@app/core-runtime';
import { Effect, Match, Schema } from 'effect';
import { ActionTransactionError, defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';

import {
  CreateProductRelationshipPayloadSchema,
  ProductRelationshipMutationResultSchema,
} from '../../shared/actions/product-relationship-mutations.ts';
import type { CreateProductRelationshipPayload } from '../../shared/actions/product-relationship-mutations.ts';
import type { ProductRelationshipPersistence } from '../persistence/product-relationship-persistence.ts';
import { captureCatalogActionResult } from '../persistence/catalog-action-result-snapshot.ts';
import { OutboxPayloadSchema } from '../../shared/outbox/commerce-catalog-product-relationship-changed-v1.ts';
import { createCreateProductRelationshipCommerceCatalogProductRelationshipChangedV1OutboxMessage } from './create-product-relationship-commerce-catalog-product-relationship-changed-v1.outbox-message.ts';
import {
  checkRelationshipTenant,
  ProductAuditEvidenceSchema,
  ProductRelationshipActionErrorSchema,
  recordRelationshipAccess,
  relationshipConflict,
  relationshipNotFound,
  relationshipPersistenceServiceFactory,
} from './product-relationship-action-support.ts';

export type { CreateProductRelationshipPayload } from '../../shared/actions/product-relationship-mutations.ts';
const CreateProductRelationshipResultSchema = ProductRelationshipMutationResultSchema;
type CreateProductRelationshipResult = typeof CreateProductRelationshipResultSchema.Type;

export const ProductRelationshipChangedEventSchema = OutboxPayloadSchema;
const domainEvents = {
  'commerce.catalog.product-relationship-changed.v1': ProductRelationshipChangedEventSchema,
} as const;
const catalogModuleKey = 'commerce.catalog';
const actionKey = 'commerce.catalog.create-product-relationship';

export const handleCreateProductRelationship = Effect.fn('CreateProductRelationshipAction.handle')(
  function* handleCreateProductRelationship(
    payload: CreateProductRelationshipPayload,
    context: ActionHandlerContext<typeof domainEvents, ProductRelationshipPersistence>,
  ) {
    yield* checkRelationshipTenant(context.scope.tenantId, payload.relationship.source);
    yield* checkRelationshipTenant(context.scope.tenantId, payload.relationship.target);
    const outcome = yield* context.services.create({
      actionInvocationId: context.actionInvocationId,
      principalId: context.scope.principalId,
      relationship: payload.relationship,
      relationshipId: payload.relationshipId,
    });
    const result = yield* Match.value(outcome).pipe(
      Match.tag('created', ({ relationship, relationshipId, revision }) =>
        Effect.succeed({ relationship, relationshipId, revision }),
      ),
      Match.tag('not_found', () => Effect.fail(relationshipNotFound())),
      Match.tag('revision_conflict', () => Effect.fail(relationshipConflict('REVISION'))),
      Match.tag('duplicate', () => Effect.fail(relationshipConflict('DUPLICATE'))),
      Match.tag('identity_conflict', () => Effect.fail(relationshipConflict('IDENTITY'))),
      Match.tag('lifecycle_conflict', () => Effect.fail(relationshipConflict('LIFECYCLE'))),
      Match.tag('invalid_change', () => Effect.fail(relationshipConflict('INVALID_CHANGE'))),
      Match.exhaustive,
    );
    yield* context.recordAuditEvidence({
      evidenceRefs: payload.relationship.evidenceRefs,
      reason: payload.relationship.reason,
    });
    yield* recordRelationshipAccess(context, result.relationship.source);
    yield* recordRelationshipAccess(context, result.relationship.target);
    const eventPayload = {
      changeKind: 'CREATED' as const,
      effectivePeriod: { ...result.relationship.effectivePeriod },
      relationshipId: result.relationshipId,
      revision: result.revision,
      source: { ...result.relationship.source },
      target: { ...result.relationship.target },
      tenantId: context.scope.tenantId,
      type: result.relationship.type,
    };
    const event = yield* context.addDomainEvent({
      eventType: 'commerce.catalog.product-relationship-changed.v1',
      payloadJson: eventPayload,
      producerModuleKey: catalogModuleKey,
      subjectModuleKey: catalogModuleKey,
      subjectResourceId: result.relationshipId,
      subjectResourceType: 'commerce.catalog.product-relationship',
    });
    yield* context.addOutboxMessage(
      event,
      createCreateProductRelationshipCommerceCatalogProductRelationshipChangedV1OutboxMessage(eventPayload),
    );
    return result;
  },
);

export const createProductRelationshipResultServiceFactory = (
  transaction: Parameters<typeof relationshipPersistenceServiceFactory>[0],
  scope: Parameters<typeof relationshipPersistenceServiceFactory>[1],
) =>
  relationshipPersistenceServiceFactory(transaction, scope).pipe(
    Effect.map(
      (
        services,
      ): ProductRelationshipPersistence & {
        captureResult: (
          actionInvocationId: string,
          result: CreateProductRelationshipResult,
        ) => Effect.Effect<void, ActionTransactionError>;
      } => ({
        ...services,
        captureResult: (actionInvocationId: string, result: CreateProductRelationshipResult) =>
          captureCatalogActionResult(
            transaction,
            scope,
            { actionInvocationId, actionKey, schemaVersion: 1 },
            {
              decode: Schema.decodeUnknownEffect(CreateProductRelationshipResultSchema),
              encode: Schema.encodeEffect(CreateProductRelationshipResultSchema),
            },
            result,
          ).pipe(
            Effect.mapError((cause) =>
              Object.assign(
                new ActionTransactionError({
                  code: 'action_transaction_failed',
                  reason: 'Catalog result capture failed',
                }),
                { cause },
              ),
            ),
          ),
      }),
    ),
  );

export const createProductRelationshipAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.create-product-relationship.access.v1',
    },
    actionKey,
    auditEvidenceSchema: ProductAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: ProductRelationshipActionErrorSchema,
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: actionKey,
      moduleKey: catalogModuleKey,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: catalogModuleKey,
    payloadSchema: CreateProductRelationshipPayloadSchema,
    policies: [],
    resultSchema: CreateProductRelationshipResultSchema,
    schemaVersion: '1',
  },
  handleCreateProductRelationship,
  createProductRelationshipResultServiceFactory,
  ({ actionInvocationId, result, services }) => services.captureResult(actionInvocationId, result),
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
