// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.catalog
// @ontos-action-slug create-product-unit
import type { ActionHandlerContext } from '@app/core-runtime';
import { Effect, Schema } from 'effect';
import { ActionTransactionError, defineAction, defineTenantModuleEntrypoint } from '@app/core-runtime';

import {
  CreateProductUnitPayloadSchema,
  CreateProductUnitResultSchema,
} from '../../shared/actions/create-product-unit.ts';
import type { CreateProductUnitPayload } from '../../shared/actions/create-product-unit.ts';
import {
  ProductUnitActionError,
  ProductUnitActionErrorSchema,
  ProductUnitAuditEvidenceSchema,
} from '../../shared/actions/product-unit-contract.ts';
import type { ProductUnitPersistence } from '../persistence/product-unit-persistence.ts';
import { captureCatalogActionResult } from '../persistence/catalog-action-result-snapshot.ts';
import {
  mapProductUnitPersistenceError,
  productUnitPersistenceServiceFactory,
  resolveProductUnitMutation,
} from './product-unit-action-support.ts';

export type { CreateProductUnitPayload } from '../../shared/actions/create-product-unit.ts';

export const handleCreateProductUnit = Effect.fn('CreateProductUnitAction.handle')(
  function* handleCreateProductUnitEffect(
    payload: CreateProductUnitPayload,
    context: ActionHandlerContext<Readonly<Record<string, never>>, ProductUnitPersistence>,
  ) {
    if (payload.unitRef.tenantId !== context.scope.tenantId) {
      return yield* new ProductUnitActionError({
        code: 'product_unit_invalid',
        reason: 'Unit must belong to the trusted Tenant',
      });
    }
    const outcome = yield* context.services
      .create({ actionInvocationId: context.actionInvocationId, payload, principalId: context.scope.principalId })
      .pipe(Effect.mapError(mapProductUnitPersistenceError));
    const result = yield* resolveProductUnitMutation(outcome);
    yield* context.recordAuditEvidence({ evidenceRefs: payload.evidenceRefs, reason: payload.reason });
    return result;
  },
);

const ACTION_KEY = 'commerce.catalog.create-product-unit' as const;

export const createProductUnitAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.catalog.create-product-unit.access.v1',
    },
    actionKey: ACTION_KEY,
    auditEvidenceSchema: ProductUnitAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: ProductUnitActionErrorSchema,
    domainEvents: {},
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: ACTION_KEY,
      moduleKey: 'commerce.catalog',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'forbidden',
    owningModuleKey: 'commerce.catalog',
    payloadSchema: CreateProductUnitPayloadSchema,
    policies: [],
    resultSchema: CreateProductUnitResultSchema,
    schemaVersion: '1',
  },
  handleCreateProductUnit,
  (transaction, scope) =>
    productUnitPersistenceServiceFactory(transaction, scope).pipe(
      Effect.map(
        (
          services,
        ): ProductUnitPersistence & {
          captureResult: (
            actionInvocationId: string,
            result: typeof CreateProductUnitResultSchema.Type,
          ) => Effect.Effect<void, ActionTransactionError>;
        } => ({
          ...services,
          captureResult: (actionInvocationId: string, result: typeof CreateProductUnitResultSchema.Type) =>
            captureCatalogActionResult(
              transaction,
              scope,
              { actionInvocationId, actionKey: ACTION_KEY, schemaVersion: 1 },
              {
                decode: Schema.decodeUnknownEffect(CreateProductUnitResultSchema),
                encode: Schema.encodeEffect(CreateProductUnitResultSchema),
              },
              result,
            ).pipe(
              Effect.mapError((cause) => {
                const failure = new ActionTransactionError({
                  code: 'action_transaction_failed',
                  reason: 'Catalog result capture failed',
                });
                Object.defineProperty(failure, 'cause', { configurable: true, value: cause });
                return failure;
              }),
            ),
        }),
      ),
    ),
  ({ actionInvocationId, result, services }) => services.captureResult(actionInvocationId, result),
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
