import ultramodernBuildArtifact from './ultramodern-build.json';
export { ultramodernBuildArtifact };
export declare const ultramodernDeliveryUnit: {
  schemaVersion: number;
  kind: string;
  unitId: string;
  appId: string;
  packageName: string;
  version: string;
  sourceRevision: string;
  buildMarker: string;
  deployProfile: string;
  build: string;
};
export declare const ultramodernVerticalIdentity: {
  schemaVersion: number;
  kind: string;
  unitId: string;
  appId: string;
  packageName: string;
  version: string;
  sourceRevision: string;
  buildMarker: string;
  deployProfile: string;
  build: string;
};
export declare const ultramodernUiMarker: {
  schemaVersion: number;
  kind: string;
  unitId: string;
  appId: string;
  packageName: string;
  version: string;
  sourceRevision: string;
  buildMarker: string;
  deployProfile: string;
  build: string;
  surface: string;
};
export declare const ultramodernApiMarker: {
  schemaVersion: number;
  kind: string;
  unitId: string;
  appId: string;
  packageName: string;
  version: string;
  sourceRevision: string;
  buildMarker: string;
  deployProfile: string;
  build: string;
  surface: string;
};
