// @generated by OntOS Codesmith Outbox Message Contract v1
// @ontos-outbox-producer commerce.catalog
// @ontos-outbox-topic commerce.catalog.package-definition-revised.v1
import { Schema } from 'effect';

import { CatalogRevisionInstantSchema } from '../domain/catalog-revision-reference.ts';
import { PackageDefinitionSelectionRevisionSchema } from '../domain/catalog-selection-evidence.ts';
import { PackageDefinitionRefSchema } from '../resources/package-definition.ts';

const checkedUuid = Schema.String.check(Schema.isUUID(), Schema.isTrimmed());
const TenantIdSchema = checkedUuid.pipe(Schema.brand('CatalogTenantId'), Schema.decodeTo(checkedUuid));

export const OutboxPayloadSchema = Schema.Struct({
  changeKind: Schema.Literals(['physical_change', 'correction']),
  contentRevision: PackageDefinitionSelectionRevisionSchema,
  definitionRef: PackageDefinitionRefSchema,
  effectiveAt: CatalogRevisionInstantSchema,
  tenantId: TenantIdSchema,
}).check(
  Schema.makeFilter(({ contentRevision, definitionRef, tenantId }) =>
    contentRevision.resourceRef.tenantId === tenantId && definitionRef.tenantId === tenantId
      ? undefined
      : 'Package Definition revision event revision and definition must belong to the event Tenant',
  ),
);
export type OutboxPayload = Schema.Schema.Type<typeof OutboxPayloadSchema>;

export const outboxTopic = 'commerce.catalog.package-definition-revised.v1' as const;
export const outboxProducerModuleKey = 'commerce.catalog' as const;
