// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.tax
// @ontos-action-http-slug create-tax-rule
import { decodeActionEndpointHeaders } from '@app/core-runtime/http/action-runner';
import { Effect, HttpApiBuilder, Layer } from '@modern-js/bff-effect/effect-edge';
import type { HttpServerRequest } from 'effect/unstable/http';
import { Redacted, Schema } from 'effect';
import { taxApi } from '../shared/api.ts';
import { createTaxRuleAction } from '../src/actions/create-tax-rule.action.ts';
import { bindActionHttpRunner } from './action-http-runner.ts';
import {
  createTaxRuleActionProblem,
  createTaxRuleActionSchemaErrorLive,
  mapCreateTaxRuleActionProblem,
} from './create-tax-rule-action-problems.ts';

const runActionHttp = bindActionHttpRunner({
  authentication: createTaxRuleActionProblem.authentication,
  unavailable: () => createTaxRuleActionProblem.unavailable('operation_context_unavailable'),
});

const execute = Effect.fn('CreateTaxRuleActionServer.execute')(function* executeCreateTaxRule(
  payload: typeof createTaxRuleAction.descriptor.payloadSchema.Encoded,
  request: HttpServerRequest.HttpServerRequest,
) {
  const correlationId = request.headers['x-correlation-id'];
  if (correlationId !== undefined && correlationId.length > 200) {
    return yield* Effect.fail(createTaxRuleActionProblem.invalid());
  }
  const endpointHeaders = yield* decodeActionEndpointHeaders(request.headers).pipe(
    Effect.mapError(createTaxRuleActionProblem.invalid),
  );
  const decoded = yield* Schema.decodeEffect(createTaxRuleAction.descriptor.payloadSchema)(payload).pipe(
    Effect.mapError(createTaxRuleActionProblem.invalid),
  );
  return yield* runActionHttp({
    endpointHeaders,
    internalProblem: createTaxRuleActionProblem.internal,
    invalidCorrelationProblem: createTaxRuleActionProblem.invalid,
    mapError: mapCreateTaxRuleActionProblem,
    payload: decoded,
    registration: createTaxRuleAction,
    requestHeaders: {
      authorization: Redacted.make(request.headers['authorization']),
      'x-correlation-id': correlationId,
    },
  });
});

export const createTaxRuleActionApiLive = HttpApiBuilder.group(taxApi, 'createTaxRuleAction', (handlers) =>
  handlers.handle('execute', ({ payload, request }) => execute(payload, request)),
).pipe(Layer.provide(createTaxRuleActionSchemaErrorLive));
