// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.tax
// @ontos-action-http-slug end-tax-rule-revision
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  EndTaxRuleRevisionActionAlreadyCommittedProblemSchema,
  EndTaxRuleRevisionActionAuthenticationProblemSchema,
  EndTaxRuleRevisionActionCommitIndeterminateProblemSchema,
  EndTaxRuleRevisionActionConflictProblemSchema,
  EndTaxRuleRevisionActionForbiddenProblemSchema,
  EndTaxRuleRevisionActionIneligibleProblemSchema,
  EndTaxRuleRevisionActionInternalProblemSchema,
  EndTaxRuleRevisionActionInvalidProblemSchema,
  EndTaxRuleRevisionActionNotFoundProblemSchema,
  EndTaxRuleRevisionActionPreconditionProblemSchema,
  EndTaxRuleRevisionActionSchemaErrorMiddleware,
  EndTaxRuleRevisionActionUnavailableProblemSchema,
} from '../shared/apis/end-tax-rule-revision-action.ts';
import type { EndTaxRuleRevisionActionProblem } from '../shared/apis/end-tax-rule-revision-action.ts';
import { endTaxRuleRevisionAction } from '../src/actions/end-tax-rule-revision.action.ts';

type DomainError = typeof endTaxRuleRevisionAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends EndTaxRuleRevisionActionProblem['_tag']> = Extract<
  EndTaxRuleRevisionActionProblem,
  { readonly _tag: Tag }
>;

const problemStatus = {
  authentication: 401,
  conflict: 409,
  forbidden: 403,
  ineligible: 422,
  internal: 500,
  invalid: 400,
  notFound: 404,
  precondition: 428,
  rateLimited: 429,
  timeout: 504,
  unavailable: 503,
} as const;

export const endTaxRuleRevisionActionProblem = {
  authentication: (): ProblemOf<'EndTaxRuleRevisionActionAuthenticationProblem'> =>
    EndTaxRuleRevisionActionAuthenticationProblemSchema.make({
      detail: 'A valid audience-scoped Bearer assertion is required.',
      status: problemStatus.authentication,
      title: 'Authentication required',
      type: 'https://ontos.dev/problems/operation-authentication-required',
    }),
  conflict: (
    code: ProblemOf<'EndTaxRuleRevisionActionConflictProblem'>['code'],
  ): ProblemOf<'EndTaxRuleRevisionActionConflictProblem'> =>
    EndTaxRuleRevisionActionConflictProblemSchema.make({
      code,
      detail: 'The Action conflicts with current state.',
      status: problemStatus.conflict,
      title: 'Action conflict',
      type: 'https://ontos.dev/problems/action-conflict',
    }),
  forbidden: (
    code: ProblemOf<'EndTaxRuleRevisionActionForbiddenProblem'>['code'],
  ): ProblemOf<'EndTaxRuleRevisionActionForbiddenProblem'> =>
    EndTaxRuleRevisionActionForbiddenProblemSchema.make({
      code,
      detail: 'The principal is not permitted to perform this Action.',
      status: problemStatus.forbidden,
      title: 'Action forbidden',
      type: 'https://ontos.dev/problems/action-forbidden',
    }),
  ineligible: (
    code: ProblemOf<'EndTaxRuleRevisionActionIneligibleProblem'>['code'],
  ): ProblemOf<'EndTaxRuleRevisionActionIneligibleProblem'> =>
    EndTaxRuleRevisionActionIneligibleProblemSchema.make({
      code,
      detail: 'The request is not eligible for this Action.',
      status: problemStatus.ineligible,
      title: 'Action ineligible',
      type: 'https://ontos.dev/problems/action-ineligible',
    }),
  internal: (): ProblemOf<'EndTaxRuleRevisionActionInternalProblem'> =>
    EndTaxRuleRevisionActionInternalProblemSchema.make({
      detail: 'The Action could not be completed.',
      status: problemStatus.internal,
      title: 'Action failed',
      type: 'https://ontos.dev/problems/action-failed',
    }),
  invalid: (): ProblemOf<'EndTaxRuleRevisionActionInvalidProblem'> =>
    EndTaxRuleRevisionActionInvalidProblemSchema.make({
      detail: 'The end-tax-rule-revision Action request is invalid.',
      status: problemStatus.invalid,
      title: 'Invalid Action request',
      type: 'https://ontos.dev/problems/action-invalid',
    }),
  notFound: (
    code: ProblemOf<'EndTaxRuleRevisionActionNotFoundProblem'>['code'],
  ): ProblemOf<'EndTaxRuleRevisionActionNotFoundProblem'> =>
    EndTaxRuleRevisionActionNotFoundProblemSchema.make({
      code,
      detail: 'The requested resource was not found.',
      status: problemStatus.notFound,
      title: 'Resource not found',
      type: 'https://ontos.dev/problems/action-resource-not-found',
    }),
  precondition: (): ProblemOf<'EndTaxRuleRevisionActionPreconditionProblem'> =>
    EndTaxRuleRevisionActionPreconditionProblemSchema.make({
      detail: 'An Idempotency-Key header is required.',
      status: problemStatus.precondition,
      title: 'Idempotency key required',
      type: 'https://ontos.dev/problems/idempotency-key-required',
    }),
  unavailable: (
    code: ProblemOf<'EndTaxRuleRevisionActionUnavailableProblem'>['code'],
  ): ProblemOf<'EndTaxRuleRevisionActionUnavailableProblem'> =>
    EndTaxRuleRevisionActionUnavailableProblemSchema.make({
      code,
      detail: 'The Action capability is temporarily unavailable.',
      retryable: true,
      status: problemStatus.unavailable,
      title: 'Action unavailable',
      type: 'https://ontos.dev/problems/action-unavailable',
    }),
} as const;

const mapDomainProblem = (error: DomainError): EndTaxRuleRevisionActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      TaxGovernanceConflict: () => endTaxRuleRevisionActionProblem.conflict('tax_governance_conflict'),
      TaxGovernanceNotFound: () => endTaxRuleRevisionActionProblem.notFound('tax_governance_not_found'),
      TaxGovernancePersistenceUnavailable: () =>
        endTaxRuleRevisionActionProblem.unavailable('tax_governance_persistence_unavailable'),
      TaxGovernanceStaleBasis: () => endTaxRuleRevisionActionProblem.conflict('tax_governance_stale_basis'),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): EndTaxRuleRevisionActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        EndTaxRuleRevisionActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: endTaxRuleRevisionActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        EndTaxRuleRevisionActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: endTaxRuleRevisionActionProblem.internal,
      ActionIdempotencyKeyRequired: endTaxRuleRevisionActionProblem.precondition,
      ActionInvocationNotFound: (failure) => endTaxRuleRevisionActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) => endTaxRuleRevisionActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => endTaxRuleRevisionActionProblem.conflict(failure.code),
      ActionPayloadValidationError: endTaxRuleRevisionActionProblem.invalid,
      ActionPermissionCheckError: (failure) => endTaxRuleRevisionActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => endTaxRuleRevisionActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => endTaxRuleRevisionActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => endTaxRuleRevisionActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => endTaxRuleRevisionActionProblem.conflict(failure.code),
      ActionResultValidationError: endTaxRuleRevisionActionProblem.internal,
      ActionTransactionError: (failure) => endTaxRuleRevisionActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: endTaxRuleRevisionActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) => endTaxRuleRevisionActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => endTaxRuleRevisionActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: endTaxRuleRevisionActionProblem.authentication,
      OperationContextDenied: (failure) => endTaxRuleRevisionActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => endTaxRuleRevisionActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => endTaxRuleRevisionActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(endTaxRuleRevisionAction.descriptor.domainErrorSchema);
export const mapEndTaxRuleRevisionActionProblem = (
  error: ActionCoreError | DomainError,
): EndTaxRuleRevisionActionProblem => (isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error));

export const endTaxRuleRevisionActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  EndTaxRuleRevisionActionSchemaErrorMiddleware,
  () => Effect.fail(endTaxRuleRevisionActionProblem.invalid()),
);
