// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { taxApi } from '../shared/api.ts';
import {
  SellerVatRegimeHistoryAuthenticationProblemSchema,
  SellerVatRegimeHistoryForbiddenProblemSchema,
  SellerVatRegimeHistoryInternalProblemSchema,
  SellerVatRegimeHistoryInvalidProblemSchema,
  SellerVatRegimeHistoryNotFoundProblemSchema,
  SellerVatRegimeHistoryPolicyConflictProblemSchema,
  SellerVatRegimeHistoryPolicyProblemSchema,
  SellerVatRegimeHistoryUnavailableProblemSchema,
} from '../shared/apis/seller-vat-regime-history.ts';
import { sellerVatRegimeHistoryRead } from '../src/api/seller-vat-regime-history.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: SellerVatRegimeHistoryAuthenticationProblemSchema,
  forbidden: SellerVatRegimeHistoryForbiddenProblemSchema,
  internal: SellerVatRegimeHistoryInternalProblemSchema,
  invalid: SellerVatRegimeHistoryInvalidProblemSchema,
  notFound: SellerVatRegimeHistoryNotFoundProblemSchema,
  policyConflict: SellerVatRegimeHistoryPolicyConflictProblemSchema,
  policyIneligible: SellerVatRegimeHistoryPolicyProblemSchema,
  unavailable: SellerVatRegimeHistoryUnavailableProblemSchema,
});

export const sellerVatRegimeHistoryReadApiLive = HttpApiBuilder.group(taxApi, 'sellerVatRegimeHistory', (handlers) =>
  handlers.handle(
    'execute',
    makeGovernedReadHttpHandler({
      authenticatePrincipal: authenticateOperationPrincipal,
      problems,
      registration: sellerVatRegimeHistoryRead,
    }),
  ),
);
