// @generated by OntOS Codesmith Outbox Message Contract v1
// @ontos-outbox-producer party.registry
// @ontos-outbox-topic party.registry.contact-point-added.v1
import { Schema } from 'effect';
import { PartyContactPointRefSchema } from '../resources/party-contact-point.ts';
import { PartyRefSchema } from '../resources/party.ts';

export const OutboxPayloadSchema = Schema.Struct({
  contactPointRef: PartyContactPointRefSchema,
  partyRef: PartyRefSchema,
});
export type OutboxPayload = Schema.Schema.Type<typeof OutboxPayloadSchema>;

export const outboxTopic = 'party.registry.contact-point-added.v1' as const;
export const outboxProducerModuleKey = 'party.registry' as const;
