// @generated by OntOS Codesmith Action v1
// @ontos-action-owner core.identity
// @ontos-action-slug set-managed-api-key-binding-status
import { Effect, Schema } from 'effect';
import type { ActionHandlerContext } from '../../actions/context.ts';
import { defineAction } from '../../actions/definition.ts';
import { setApiKeyBindingStatus } from '../../auth/principal-management.ts';
import { PrincipalManagementError } from '../../auth/principal-management-errors.ts';
import { defineSystemModuleEntrypoint } from '../module-entrypoint.ts';

const uuid = Schema.String.check(Schema.isUUID());
const status = Schema.Literals(['active', 'disabled', 'revoked']);
const reason = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(500));
export const SetManagedApiKeyBindingStatusPayload = Schema.Union([
  Schema.Struct({
    authBindingId: uuid,
    expectedStatus: status,
    newStatus: Schema.Literals(['active', 'disabled']),
    principalId: uuid,
    reason: Schema.optionalKey(reason),
  }),
  Schema.Struct({
    authBindingId: uuid,
    expectedStatus: status,
    newStatus: Schema.Literal('revoked'),
    principalId: uuid,
    reason,
  }),
]);
export type SetManagedApiKeyBindingStatusPayload = Schema.Schema.Type<
  typeof SetManagedApiKeyBindingStatusPayload
>;
export const SetManagedApiKeyBindingStatusResult = Schema.Struct({
  previousStatus: status,
  status,
});
export type SetManagedApiKeyBindingStatusResult = Schema.Schema.Type<
  typeof SetManagedApiKeyBindingStatusResult
>;
type Input = Parameters<typeof setApiKeyBindingStatus>[1];
type Result = ReturnType<typeof setApiKeyBindingStatus>;
const handle = (
  payload: SetManagedApiKeyBindingStatusPayload,
  context: ActionHandlerContext<
    Readonly<Record<never, never>>,
    { readonly setStatus: (input: Input) => Result }
  >,
) =>
  Effect.gen(function* setManagedApiKeyBindingStatusHandler() {
    const result = yield* context.services.setStatus({
      ...payload,
      managed: true,
      tenantId: context.scope.tenantId,
    });
    yield* context.recordDataAccess({
      accessKind: 'read',
      queryHash: `api-key-binding-prior:${payload.authBindingId}`,
      resultCount: 1,
      servingModuleKey: 'core.identity',
      targetModuleKey: 'core.identity',
      targetResourceId: payload.authBindingId,
      targetResourceType: 'principal-auth-binding',
    });
    return result;
  });
export const setManagedApiKeyBindingStatusAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'core.identity.set-managed-api-key-binding-status.access.v1',
    },
    actionKey: 'core.identity.set-managed-api-key-binding-status',
    auditProfile: 'sensitive',
    domainErrorSchema: PrincipalManagementError,
    domainEvents: {},
    entrypoint: defineSystemModuleEntrypoint({
      access: 'write',
      entrypointKey: 'core.identity.set-managed-api-key-binding-status',
      moduleKey: 'core.identity',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'optional',
    owningModuleKey: 'core.identity',
    payloadSchema: SetManagedApiKeyBindingStatusPayload,
    policies: [],
    resultSchema: SetManagedApiKeyBindingStatusResult,
    schemaVersion: '1',
    tenantPermission: () => 'manage_identity',
  },
  handle,
  (transaction) =>
    Effect.succeed({ setStatus: (input) => setApiKeyBindingStatus(transaction, input) }),
);
