-- Drizzle Kit emits composite foreign keys before their supporting unique indexes.
-- Install the generated parent indexes first so this migration is executable.
CREATE UNIQUE INDEX "core_audit_events_tenant_id_uk" ON "core"."audit_events" USING btree ("tenant_id","audit_event_id");--> statement-breakpoint
CREATE UNIQUE INDEX "core_data_access_events_tenant_id_uk" ON "core"."data_access_events" USING btree ("tenant_id","data_access_event_id");--> statement-breakpoint
CREATE UNIQUE INDEX "core_domain_events_tenant_id_uk" ON "core"."domain_events" USING btree ("tenant_id","domain_event_id");--> statement-breakpoint
CREATE UNIQUE INDEX "core_media_assets_tenant_id_uk" ON "core"."media_assets" USING btree ("tenant_id","media_asset_id");--> statement-breakpoint
ALTER TABLE "core"."evidence_references" ADD CONSTRAINT "core_evidence_tenant_legal_entity_fk" FOREIGN KEY ("tenant_id","legal_entity_id") REFERENCES "core"."legal_entities"("tenant_id","legal_entity_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."evidence_references" ADD CONSTRAINT "core_evidence_tenant_asset_fk" FOREIGN KEY ("tenant_id","media_asset_id") REFERENCES "core"."media_assets"("tenant_id","media_asset_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."evidence_references" ADD CONSTRAINT "core_evidence_tenant_invocation_fk" FOREIGN KEY ("tenant_id","action_invocation_id") REFERENCES "core"."action_invocations"("tenant_id","action_invocation_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."evidence_references" ADD CONSTRAINT "core_evidence_tenant_audit_fk" FOREIGN KEY ("tenant_id","audit_event_id") REFERENCES "core"."audit_events"("tenant_id","audit_event_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."evidence_references" ADD CONSTRAINT "core_evidence_tenant_data_access_fk" FOREIGN KEY ("tenant_id","data_access_event_id") REFERENCES "core"."data_access_events"("tenant_id","data_access_event_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."evidence_references" ADD CONSTRAINT "core_evidence_tenant_domain_event_fk" FOREIGN KEY ("tenant_id","domain_event_id") REFERENCES "core"."domain_events"("tenant_id","domain_event_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."media_assets" ADD CONSTRAINT "core_media_assets_tenant_legal_entity_fk" FOREIGN KEY ("tenant_id","legal_entity_id") REFERENCES "core"."legal_entities"("tenant_id","legal_entity_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."media_assets" ADD CONSTRAINT "core_media_assets_tenant_principal_fk" FOREIGN KEY ("tenant_id","ingested_by_principal_id") REFERENCES "core"."principals"("tenant_id","principal_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."media_links" ADD CONSTRAINT "core_media_links_tenant_asset_fk" FOREIGN KEY ("tenant_id","media_asset_id") REFERENCES "core"."media_assets"("tenant_id","media_asset_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."media_links" ADD CONSTRAINT "core_media_links_tenant_principal_fk" FOREIGN KEY ("tenant_id","linked_by_principal_id") REFERENCES "core"."principals"("tenant_id","principal_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."media_links" ADD CONSTRAINT "core_media_links_tenant_invocation_fk" FOREIGN KEY ("tenant_id","action_invocation_id") REFERENCES "core"."action_invocations"("tenant_id","action_invocation_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."outbox_messages" ADD CONSTRAINT "core_outbox_messages_tenant_domain_event_fk" FOREIGN KEY ("tenant_id","domain_event_id") REFERENCES "core"."domain_events"("tenant_id","domain_event_id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "core"."search_index_entries" ADD CONSTRAINT "core_search_index_entries_tenant_legal_entity_fk" FOREIGN KEY ("tenant_id","legal_entity_id") REFERENCES "core"."legal_entities"("tenant_id","legal_entity_id") ON DELETE restrict ON UPDATE no action;
