// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner privacy.core
// @ontos-action-http-slug consent-self-service
import { decodeActionEndpointHeaders } from '@app/core-runtime/http/action-runner';
import { Effect, HttpApiBuilder, Layer } from '@modern-js/bff-effect/effect-edge';
import type { HttpServerRequest } from 'effect/unstable/http';
import { Redacted, Schema } from 'effect';
import { privacyApi } from '../shared/api.ts';
import { consentSelfServiceAction } from '../src/actions/consent-self-service.action.ts';
import { bindActionHttpRunner } from './action-http-runner.ts';
import {
  consentSelfServiceActionProblem,
  consentSelfServiceActionSchemaErrorLive,
  mapConsentSelfServiceActionProblem,
} from './consent-self-service-action-problems.ts';

const runActionHttp = bindActionHttpRunner({
  authentication: consentSelfServiceActionProblem.authentication,
  unavailable: () => consentSelfServiceActionProblem.unavailable('operation_context_unavailable'),
});

const execute = Effect.fn('ConsentSelfServiceActionServer.execute')(function* executeConsentSelfService(
  payload: typeof consentSelfServiceAction.descriptor.payloadSchema.Encoded,
  request: HttpServerRequest.HttpServerRequest,
) {
  const correlationId = request.headers['x-correlation-id'];
  if (correlationId !== undefined && correlationId.length > 200) {
    return yield* Effect.fail(consentSelfServiceActionProblem.invalid());
  }
  const endpointHeaders = yield* decodeActionEndpointHeaders(request.headers).pipe(
    Effect.mapError(consentSelfServiceActionProblem.invalid),
  );
  const decoded = yield* Schema.decodeEffect(consentSelfServiceAction.descriptor.payloadSchema)(payload).pipe(
    Effect.mapError(consentSelfServiceActionProblem.invalid),
  );
  return yield* runActionHttp({
    endpointHeaders,
    internalProblem: consentSelfServiceActionProblem.internal,
    invalidCorrelationProblem: consentSelfServiceActionProblem.invalid,
    mapError: mapConsentSelfServiceActionProblem,
    payload: decoded,
    registration: consentSelfServiceAction,
    requestHeaders: {
      authorization: Redacted.make(request.headers['authorization']),
      'x-correlation-id': correlationId,
    },
  });
});

export const consentSelfServiceActionApiLive = HttpApiBuilder.group(
  privacyApi,
  'consentSelfServiceAction',
  (handlers) => handlers.handle('execute', ({ payload, request }) => execute(payload, request)),
).pipe(Layer.provide(consentSelfServiceActionSchemaErrorLive));
