import { Effect, FileSystem, Schema } from 'effect';
import {
  MODULE_MANIFEST_API_SLOT_END,
  MODULE_MANIFEST_API_SLOT_START,
  MODULE_MANIFEST_COMPONENT_SLOT_END,
  MODULE_MANIFEST_COMPONENT_SLOT_START,
  MODULE_MANIFEST_IMPORT_SLOT_END,
  MODULE_MANIFEST_IMPORT_SLOT_START,
  MODULE_MANIFEST_REPORT_SLOT_END,
  MODULE_MANIFEST_REPORT_SLOT_START,
  MODULE_MANIFEST_SEARCH_SLOT_END,
  MODULE_MANIFEST_SEARCH_SLOT_START,
  MODULE_MANIFEST_SHELL_COMPONENT_SLOT_END,
  MODULE_MANIFEST_SHELL_COMPONENT_SLOT_START,
  MODULE_MANIFEST_SHELL_REPORT_SLOT_END,
  MODULE_MANIFEST_SHELL_REPORT_SLOT_START,
  MODULE_MANIFEST_SHELL_SEARCH_SLOT_END,
  MODULE_MANIFEST_SHELL_SEARCH_SLOT_START,
  MODULE_REGISTRATION_API_SLOT_END,
  MODULE_REGISTRATION_API_SLOT_START,
  MODULE_REGISTRATION_COMPONENT_SLOT_END,
  MODULE_REGISTRATION_COMPONENT_SLOT_START,
  MODULE_REGISTRATION_REPORT_SLOT_END,
  MODULE_REGISTRATION_REPORT_SLOT_START,
  MODULE_REGISTRATION_SEARCH_SLOT_END,
  MODULE_REGISTRATION_SEARCH_SLOT_START,
  createMutationEffect,
  discoverOntosModuleEffect,
  ensureUniqueMutationPaths,
  insertSortedSlot,
  insertModuleFederationExposure,
  isModuleManifestImport,
  raiseScaffoldFailure,
  requireCanonicalSlug,
  resolveContainedPath,
  scaffoldFailure,
  toCamelCase,
  toPascalCase,
  toTitle,
  tryScaffold,
  updateMutation,
} from '../shared.mts';
import { planActionBoundaryScaffold } from '../microvertical-action-boundary/scaffold.mts';
import type {
  GovernedContributionScaffoldConfig,
  Mutation,
  OntosVerticalMetadata,
} from '../shared.mts';

const MODULE_API_KIND = 'module-api';
const PUBLIC_COMPONENT_KIND = 'public-component';
const REPORT_KIND = 'report';
const SEARCH_PROVIDER_KIND = 'search-provider';

const GovernedContributionKindSchema = Schema.Literals([
  MODULE_API_KIND,
  PUBLIC_COMPONENT_KIND,
  REPORT_KIND,
  SEARCH_PROVIDER_KIND,
]);
export type GovernedContributionKind = typeof GovernedContributionKindSchema.Type;

const ProviderContributionKindSchema = Schema.Literals([REPORT_KIND, SEARCH_PROVIDER_KIND]);
type ProviderContributionKind = typeof ProviderContributionKindSchema.Type;
const isProviderContribution = Schema.is(ProviderContributionKindSchema);

const generatedHeader = (kind: GovernedContributionKind) =>
  isProviderContribution(kind)
    ? `// @generated by OntOS Codesmith Governed Contribution v1\n// @ontos-contribution-kind ${kind}`
    : `// @generated by OntOS Codesmith ${kind} v1`;

const manifestImport = (kind: GovernedContributionKind, name: string): string | undefined => {
  const value = `${toPascalCase(name)}${kind === PUBLIC_COMPONENT_KIND ? '' : 'Api'}`;
  if (kind === PUBLIC_COMPONENT_KIND) {
    return `import { ${value} } from './src/components/${name}.tsx';`;
  }
  if (kind === MODULE_API_KIND) {
    return `import { ${value} } from './shared/apis/${name}.ts';`;
  }
  return undefined;
};

const renderPublicComponent = (name: string): string => {
  const value = toPascalCase(name);
  return `${generatedHeader(PUBLIC_COMPONENT_KIND)}
export const ${value} = () => null;
`;
};

const renderApiContract = (name: string): string => {
  const type = toPascalCase(name);
  const value = `${toPascalCase(name)}Api`;
  return `${generatedHeader(MODULE_API_KIND)}
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

export const ${type}RequestSchema = Schema.Struct({});
export type ${type}Request = typeof ${type}RequestSchema.Type;
export const ${type}ResponseSchema = Schema.Struct({ ok: Schema.Literal(true) });
export type ${type}Response = typeof ${type}ResponseSchema.Type;

export const ${type}AuthenticationProblemSchema = makeProblemDetailsSchema(
  '${type}AuthenticationProblem',
  401,
);
export const ${type}InvalidProblemSchema = makeProblemDetailsSchema('${type}InvalidProblem', 400);
export const ${type}UnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  '${type}UnavailableProblem',
  503,
);
export const ${type}ForbiddenProblemSchema = makeProblemDetailsSchema('${type}ForbiddenProblem', 403);
export const ${type}NotFoundProblemSchema = makeProblemDetailsSchema('${type}NotFoundProblem', 404);
export const ${type}PolicyProblemSchema = makeProblemDetailsSchema('${type}PolicyProblem', 422);
export const ${type}PolicyConflictProblemSchema = makeProblemDetailsSchema(
  '${type}PolicyConflictProblem',
  409,
);
export const ${type}InternalProblemSchema = makeProblemDetailsSchema('${type}InternalProblem', 500);

export const ${value} = HttpApi.make('${value}').add(
  HttpApiGroup.make('${toCamelCase(name)}').add(
    HttpApiEndpoint.post('execute', '/reads/${name}', {
      error: [
        ${type}InvalidProblemSchema,
        ${type}AuthenticationProblemSchema,
        ${type}ForbiddenProblemSchema,
        ${type}NotFoundProblemSchema,
        ${type}PolicyConflictProblemSchema,
        ${type}PolicyProblemSchema,
        ${type}UnavailableProblemSchema,
        ${type}InternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: ${type}RequestSchema,
      query: {},
      success: ${type}ResponseSchema,
    }),
  ),
);
`;
};

const renderReadAuthorization = (
  config: Pick<GovernedContributionScaffoldConfig, 'authorization' | 'permission'>,
): string => {
  if (config.authorization === 'context_permission') {
    if (
      config.permission === undefined ||
      !/^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/u.test(config.permission)
    ) {
      return raiseScaffoldFailure(
        'context_permission authorization requires a stable --permission value',
      );
    }
    return `{ kind: 'context_permission', permission: '${config.permission}' }`;
  }
  if (config.permission !== undefined) {
    return raiseScaffoldFailure('--permission is valid only for context_permission authorization');
  }
  return `{ kind: '${config.authorization}' }`;
};

const renderModuleApiRead = (
  vertical: OntosVerticalMetadata,
  name: string,
  config: Pick<GovernedContributionScaffoldConfig, 'authorization' | 'permission'>,
): string => {
  const type = toPascalCase(name);
  return `${generatedHeader(MODULE_API_KIND)}
import { defineRead, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect } from 'effect';
import { ${type}RequestSchema, ${type}ResponseSchema } from '../../shared/apis/${name}.ts';

export const ${toCamelCase(name)}Entrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: ${renderReadAuthorization(config)},
  entrypointKey: '${vertical.moduleId}.api.${name}',
  moduleKey: '${vertical.moduleId}',
  role: 'api',
});

export const ${toCamelCase(name)}Read = defineRead(
  {
    accessKind: 'detail',
    entrypoint: ${toCamelCase(name)}Entrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: '${vertical.moduleId}.api.${name}.evidence.v1',
    },
    inputSchema: ${type}RequestSchema,
    legalEntityScope: 'required',
    owningModuleKey: '${vertical.moduleId}',
    permissionTarget: 'module',
    policies: [],
    readKey: '${vertical.moduleId}.api.${name}',
    resultSchema: ${type}ResponseSchema,
    schemaVersion: '1',
  },
  () => Effect.succeed({ evidence: { resultCount: 1 }, result: { ok: true as const } }),
  () => Effect.succeed({}),
  () => ({ kind: 'module', moduleId: '${vertical.moduleId}' }),
);
`;
};

const renderApiClient = (vertical: OntosVerticalMetadata, name: string): string => {
  const type = toPascalCase(name);
  const value = `${toPascalCase(name)}Api`;
  return `${generatedHeader(MODULE_API_KIND)}
import { Context, Effect } from 'effect';
import { HttpClient, HttpClientRequest } from 'effect/unstable/http';
import { makeEffectHttpApiClient } from '@modern-js/plugin-bff/effect-client';
import { ${value} } from '../../shared/apis/${name}.ts';
import type { ${type}Request } from '../../shared/apis/${name}.ts';
import { operationGateway } from './action-gateway.ts';

export interface ${type}ClientOptions {
  readonly baseUrl?: string | URL;
}

interface ${type}RequestOptions extends ${type}ClientOptions {
  readonly authorization: string;
  readonly correlationId: string;
}

const ${type}RequestOptions = Context.Reference<${type}RequestOptions>(
  '${type}RequestOptions',
  { defaultValue: () => ({ authorization: '', correlationId: '' }) },
);

const ${toCamelCase(name)}Client = makeEffectHttpApiClient(${value}, {
  transformClient: HttpClient.mapRequestEffect((request) =>
    ${type}RequestOptions.pipe(
      Effect.map(({ authorization, baseUrl, correlationId }) =>
        HttpClientRequest.prependUrl(request, (baseUrl ?? '/${vertical.appId}-api').toString()).pipe(
          HttpClientRequest.setHeaders({ authorization, 'x-correlation-id': correlationId }),
        ),
      ),
    ),
  ),
});

export const execute${type}WithAuthorization = (
  payload: ${type}Request,
  authorization: string,
  correlationId: string,
  options: ${type}ClientOptions = {},
) =>
  ${toCamelCase(name)}Client.pipe(
    Effect.flatMap((client) =>
      client.${toCamelCase(name)}.execute({ headers: {}, params: {}, payload, query: {} }),
    ),
    Effect.provideService(${type}RequestOptions, { ...options, authorization, correlationId }),
  );

export const execute${type} = (
  payload: ${type}Request,
  correlationId: string,
  options: ${type}ClientOptions = {},
) =>
  operationGateway.invoke((authorization) =>
    execute${type}WithAuthorization(payload, authorization, correlationId, options),
  );
`;
};

const renderProvider = (
  kind: ProviderContributionKind,
  vertical: OntosVerticalMetadata,
  name: string,
  config: Pick<GovernedContributionScaffoldConfig, 'authorization' | 'permission'>,
): string => {
  const type = toPascalCase(name);
  const role = kind === REPORT_KIND ? REPORT_KIND : 'search';
  const contract = `${name}-${kind === REPORT_KIND ? REPORT_KIND : 'search'}`;
  const inputSchema = `${type}ProviderRequestSchema`;
  const inputType = `${type}ProviderRequest`;
  const resultSchema = `${type}ProviderResponseSchema`;
  const resultType = `${type}ProviderResponse`;
  const emptyResult = kind === REPORT_KIND ? '{ rows: [] }' : '[]';
  const resultCount = kind === REPORT_KIND ? 'result.rows.length' : 'result.length';
  return `${generatedHeader(kind)}
import { Effect } from 'effect';
import { defineRead, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { ${inputSchema}, ${resultSchema} } from '../../shared/apis/${contract}.ts';
import type { ${inputType}, ${resultType} } from '../../shared/apis/${contract}.ts';

export const ${toCamelCase(name)}Entrypoint = defineTenantModuleEntrypoint({
  access: 'read',
  authorization: ${renderReadAuthorization(config)},
  entrypointKey: '${vertical.moduleId}.${role}.${name}',
  moduleKey: '${vertical.moduleId}',
  role: '${role}',
});

const load${type} = (_input: ${inputType}) =>
  Effect.succeed(${emptyResult} satisfies ${resultType});

export const ${toCamelCase(name)}Read = defineRead(
  {
    accessKind: '${kind === REPORT_KIND ? REPORT_KIND : 'search'}',
    entrypoint: ${toCamelCase(name)}Entrypoint,
    evidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: '${vertical.moduleId}.${role}.${name}.evidence.v1',
    },
    inputSchema: ${inputSchema},
    legalEntityScope: 'required',
    owningModuleKey: '${vertical.moduleId}',
    permissionTarget: 'module',
    policies: [],
    readKey: '${vertical.moduleId}.${role}.${name}',
    resultSchema: ${resultSchema},
    schemaVersion: '1',
  },
  (input, context) =>
    context.services.load(input).pipe(
      Effect.map((result) => ({
        evidence: { resultCount: ${resultCount} },
        result,
      })),
    ),
  () => Effect.succeed({ load: load${type} }),
  () => ({ kind: 'module', moduleId: '${vertical.moduleId}' }),
${kind === SEARCH_PROVIDER_KIND ? '  (result) => result.map(({ ref }) => ref),\n' : ''});
`;
};

const renderProviderClient = (
  kind: ProviderContributionKind,
  vertical: OntosVerticalMetadata,
  name: string,
): string => {
  const type = toPascalCase(name);
  const apiValue = `${type}${kind === REPORT_KIND ? 'Report' : 'Search'}Api`;
  const group = kind === REPORT_KIND ? 'reports' : 'search';
  return `${generatedHeader(kind)}
import { makeEffectHttpApiClient } from '@modern-js/plugin-bff/effect-client';
import { Context, Effect } from 'effect';
import { HttpClient, HttpClientRequest } from 'effect/unstable/http';
import { ${apiValue} } from '../../shared/apis/${name}-${kind === REPORT_KIND ? REPORT_KIND : 'search'}.ts';
import type { ${type}ProviderRequest } from '../../shared/apis/${name}-${kind === REPORT_KIND ? REPORT_KIND : 'search'}.ts';
import { operationGateway } from './action-gateway.ts';

export interface ${type}ClientOptions {
  readonly baseUrl?: string | URL;
}

interface ${type}RequestOptions extends ${type}ClientOptions {
  readonly authorization: string;
  readonly correlationId: string;
}

const ${type}RequestOptions = Context.Reference<${type}RequestOptions>(
  '${type}RequestOptions',
  { defaultValue: () => ({ authorization: '', correlationId: '' }) },
);

const ${toCamelCase(name)}Client = makeEffectHttpApiClient(${apiValue}, {
  transformClient: HttpClient.mapRequestEffect((request) =>
    ${type}RequestOptions.pipe(
      Effect.map(({ authorization, baseUrl, correlationId }) =>
        HttpClientRequest.prependUrl(request, (baseUrl ?? '/${vertical.appId}-api').toString()).pipe(
          HttpClientRequest.setHeaders({ authorization, 'x-correlation-id': correlationId }),
        ),
      ),
    ),
  ),
});

export const load${type}ClientWithAuthorization = (
  payload: ${type}ProviderRequest,
  authorization: string,
  correlationId: string,
  options: ${type}ClientOptions = {},
) =>
  ${toCamelCase(name)}Client.pipe(
    Effect.flatMap((client) => client.${group}.execute({ payload })),
    Effect.provideService(${type}RequestOptions, { ...options, authorization, correlationId }),
  );

export const load${type}Client = (
  payload: ${type}ProviderRequest,
  correlationId: string,
  options: ${type}ClientOptions = {},
) =>
  operationGateway.invoke((authorization) =>
    load${type}ClientWithAuthorization(payload, authorization, correlationId, options),
  );
`;
};

const renderProviderApiContract = (
  kind: ProviderContributionKind,
  vertical: OntosVerticalMetadata,
  name: string,
): string => {
  const type = toPascalCase(name);
  const apiValue = `${type}${kind === REPORT_KIND ? 'Report' : 'Search'}Api`;
  const group = kind === REPORT_KIND ? 'reports' : 'search';
  const payloadField = kind === REPORT_KIND ? 'parameters' : 'query';
  const success =
    kind === REPORT_KIND
      ? `Schema.Struct({ rows: Schema.Array(Schema.Record(Schema.String, Schema.String)) })`
      : `Schema.Array(
  Schema.Struct({
    ref: Schema.Struct({ moduleId: Schema.String, resourceId: Schema.String, resourceType: Schema.String }),
    title: Schema.String,
  }),
)`;
  return `${generatedHeader(kind)}
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

export const ${type}ProviderRequestSchema = Schema.Struct({
  ${payloadField}: ${kind === REPORT_KIND ? 'Schema.Record(Schema.String, Schema.String)' : 'Schema.String'},
});
export type ${type}ProviderRequest = typeof ${type}ProviderRequestSchema.Type;

export const ${type}ProviderResponseSchema = ${success};
export type ${type}ProviderResponse = typeof ${type}ProviderResponseSchema.Type;

export const ${type}ProviderUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  '${type}ProviderUnavailableProblem',
  503,
);

export const ${type}ProviderAuthenticationProblemSchema = makeProblemDetailsSchema(
  '${type}ProviderAuthenticationProblem',
  401,
);
export const ${type}ProviderInvalidProblemSchema = makeProblemDetailsSchema('${type}ProviderInvalidProblem', 400);
export const ${type}ProviderForbiddenProblemSchema = makeProblemDetailsSchema(
  '${type}ProviderForbiddenProblem',
  403,
);
export const ${type}ProviderNotFoundProblemSchema = makeProblemDetailsSchema(
  '${type}ProviderNotFoundProblem',
  404,
);
export const ${type}ProviderPolicyProblemSchema = makeProblemDetailsSchema('${type}ProviderPolicyProblem', 422);
export const ${type}ProviderPolicyConflictProblemSchema = makeProblemDetailsSchema(
  '${type}ProviderPolicyConflictProblem',
  409,
);
export const ${type}ProviderInternalProblemSchema = makeProblemDetailsSchema(
  '${type}ProviderInternalProblem',
  500,
);

export const ${apiValue} = HttpApi.make('${apiValue}').add(
  HttpApiGroup.make('${group}').add(
    HttpApiEndpoint.post('execute', '/${vertical.moduleId}/${group}/${name}', {
      error: [
        ${type}ProviderInvalidProblemSchema,
        ${type}ProviderAuthenticationProblemSchema,
        ${type}ProviderForbiddenProblemSchema,
        ${type}ProviderNotFoundProblemSchema,
        ${type}ProviderPolicyConflictProblemSchema,
        ${type}ProviderPolicyProblemSchema,
        ${type}ProviderUnavailableProblemSchema,
        ${type}ProviderInternalProblemSchema,
      ],
      payload: ${type}ProviderRequestSchema,
      success: ${type}ProviderResponseSchema,
    }),
  ),
);
`;
};

const renderGovernedServer = (
  kind: Exclude<GovernedContributionKind, typeof PUBLIC_COMPONENT_KIND>,
  name: string,
): string => {
  const type = toPascalCase(name);
  const isModuleApi = kind === MODULE_API_KIND;
  /* eslint-disable no-nested-ternary, unicorn/no-nested-ternary -- Preserve the compact established generator-name mapping. */
  const suffix = kind === REPORT_KIND ? REPORT_KIND : kind === SEARCH_PROVIDER_KIND ? 'search' : '';
  const contract = isModuleApi ? name : `${name}-${suffix}`;
  const apiValue = isModuleApi
    ? `${type}Api`
    : `${type}${kind === REPORT_KIND ? 'Report' : 'Search'}Api`;
  const group = isModuleApi ? toCamelCase(name) : kind === REPORT_KIND ? 'reports' : 'search';
  const readValue = `${toCamelCase(name)}Read`;
  const readImport = isModuleApi
    ? `../src/api/${name}.read.ts`
    : `../src/${kind === REPORT_KIND ? 'reports' : 'search'}/${name}.provider.ts`;
  /* eslint-enable no-nested-ternary, unicorn/no-nested-ternary */
  const problemStem = `${type}${isModuleApi ? '' : 'Provider'}`;
  return `${generatedHeader(kind)}
import { ReadRuntime } from '@app/core-runtime';
import type { ReadCoreError } from '@app/core-runtime';
import {
  Effect,
  HttpApiBuilder,
  HttpEffect,
  HttpServerResponse,
} from '@modern-js/plugin-bff/effect-edge';
import { Match, Redacted } from 'effect';
import { ${apiValue} } from '../shared/apis/${contract}.ts';
import { ${readValue} } from '${readImport}';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const authenticationProblem = () => ({
  _tag: '${problemStem}AuthenticationProblem' as const,
  detail: 'A valid audience-scoped Bearer assertion is required.',
  status: 401 as const,
  title: 'Authentication required',
  type: 'https://ontos.dev/problems/operation-authentication-required',
});
const unavailableProblem = () => ({
  _tag: '${problemStem}UnavailableProblem' as const,
  detail: 'The governed read is temporarily unavailable.',
  retryable: true as const,
  status: 503 as const,
  title: 'Read unavailable',
  type: 'https://ontos.dev/problems/read-unavailable',
});
const invalidProblem = () => ({
  _tag: '${problemStem}InvalidProblem' as const,
  detail: 'The governed read request is invalid.',
  status: 400 as const,
  title: 'Invalid read request',
  type: 'https://ontos.dev/problems/read-invalid',
});
const forbiddenProblem = () => ({
  _tag: '${problemStem}ForbiddenProblem' as const,
  detail: 'The principal is not permitted to perform this read.',
  status: 403 as const,
  title: 'Read forbidden',
  type: 'https://ontos.dev/problems/read-forbidden',
});
const notFoundProblem = () => ({
  _tag: '${problemStem}NotFoundProblem' as const,
  detail: 'The requested resource was not found.',
  status: 404 as const,
  title: 'Resource not found',
  type: 'https://ontos.dev/problems/read-not-found',
});
const policyProblem = (status: 409 | 422) =>
  status === 409
    ? ({
        _tag: '${problemStem}PolicyConflictProblem' as const,
        detail: 'The read conflicts with the current business state.',
        status: 409 as const,
        title: 'Read conflict',
        type: 'https://ontos.dev/problems/read-policy-conflict',
      })
    : ({
        _tag: '${problemStem}PolicyProblem' as const,
        detail: 'The read is not eligible under the current business policy.',
        status: 422 as const,
        title: 'Read ineligible',
        type: 'https://ontos.dev/problems/read-policy-denied',
      });
const internalProblem = () => ({
  _tag: '${problemStem}InternalProblem' as const,
  detail: 'The governed read could not be completed.',
  status: 500 as const,
  title: 'Read failed',
  type: 'https://ontos.dev/problems/read-failed',
});
const bearerChallenge = HttpEffect.appendPreResponseHandler((_request, response) =>
  Effect.succeed(HttpServerResponse.setHeader(response, 'www-authenticate', 'Bearer')),
);
const readProblem = (error: ReadCoreError) =>
  Match.value(error).pipe(
    Match.tags({
      ModuleStateCheckUnavailableError: unavailableProblem,
      ModuleStateDeniedError: forbiddenProblem,
      OperationAuthenticationRequired: authenticationProblem,
      OperationContextDenied: forbiddenProblem,
      OperationContextInvalid: forbiddenProblem,
      OperationContextUnavailable: unavailableProblem,
      ReadEvidencePersistenceError: unavailableProblem,
      ReadEvidenceValidationError: internalProblem,
      ReadHandlerExecutionError: internalProblem,
      ReadHandlerNotFound: notFoundProblem,
      ReadHandlerUnavailable: unavailableProblem,
      ReadInputValidationError: invalidProblem,
      ReadPermissionDenied: forbiddenProblem,
      ReadPermissionUnavailable: unavailableProblem,
      ReadPolicyDenied: (failure) => policyProblem(failure.httpStatus),
      ReadPolicyEvaluationError: unavailableProblem,
      ReadResultValidationError: internalProblem,
    }),
    Match.exhaustive,
  );

export const ${toCamelCase(name)}ReadApiLive = HttpApiBuilder.group(
  ${apiValue},
  '${group}',
  (handlers) =>
    handlers.handle('execute', ({ payload, request }) =>
      Effect.gen(function* governedProviderRead() {
        const correlationId = request.headers['x-correlation-id'];
        if (correlationId === undefined || correlationId.trim().length === 0) {
          return yield* Effect.fail(invalidProblem());
        }
        const principal = yield* authenticateOperationPrincipal(
          Redacted.make(request.headers.authorization),
          {
            authentication: authenticationProblem,
            unavailable: unavailableProblem,
          },
        );
        const runtime = yield* ReadRuntime;
        return yield* runtime
          .runRead({
            input: payload,
            principal,
            registration: ${readValue},
            transport: { correlationId },
          })
          .pipe(
            Effect.catch((error) => {
              const problem = readProblem(error);
              return (problem.status === 401 ? bearerChallenge : Effect.void).pipe(
                Effect.andThen(Effect.fail(problem)),
              );
            }),
          );
      }),
    ),
);
`;
};

interface GovernedContributionSlots {
  readonly manifest: readonly [string, string, string][];
  readonly registration: readonly [string, string, string][];
}

const slotLine = (
  kind: GovernedContributionKind,
  vertical: OntosVerticalMetadata,
  name: string,
  resource: string | undefined,
  config: Pick<GovernedContributionScaffoldConfig, 'authorization' | 'permission'>,
): GovernedContributionSlots => {
  const key = `${vertical.moduleId}.${name}`;
  if (kind === PUBLIC_COMPONENT_KIND) {
    return {
      manifest: [
        [
          MODULE_MANIFEST_COMPONENT_SLOT_START,
          MODULE_MANIFEST_COMPONENT_SLOT_END,
          `'${name}': ${toPascalCase(name)},`,
        ],
        [
          MODULE_MANIFEST_SHELL_COMPONENT_SLOT_START,
          MODULE_MANIFEST_SHELL_COMPONENT_SLOT_END,
          `publicComponentContribution({ componentKey: '${key}', contributionKey: '${vertical.moduleId}.component.${name}', entrypoint: { access: 'read', authorization: ${renderReadAuthorization(config)}, entrypointKey: '${vertical.moduleId}.component.${name}', moduleKey: '${vertical.moduleId}', role: 'public_component', scope: 'tenant' } }),`,
        ],
      ],
      registration: [
        [
          MODULE_REGISTRATION_COMPONENT_SLOT_START,
          MODULE_REGISTRATION_COMPONENT_SLOT_END,
          `'${name}': () => import('./src/components/${name}.tsx'),`,
        ],
      ],
    };
  }
  if (kind === MODULE_API_KIND) {
    return {
      manifest: [
        [
          MODULE_MANIFEST_API_SLOT_START,
          MODULE_MANIFEST_API_SLOT_END,
          `'${name}': ${toPascalCase(name)}Api,`,
        ],
      ],
      registration: [
        [
          MODULE_REGISTRATION_API_SLOT_START,
          MODULE_REGISTRATION_API_SLOT_END,
          `'${name}': () => import('./src/api/${name}-client.ts'),`,
        ],
      ],
    };
  }
  if (resource === undefined) {
    return raiseScaffoldFailure(`--resource is required for ${kind}`);
  }
  const resourceKey = `${vertical.moduleId}.${resource}`;
  if (kind === SEARCH_PROVIDER_KIND) {
    return {
      manifest: [
        [
          MODULE_MANIFEST_SEARCH_SLOT_START,
          MODULE_MANIFEST_SEARCH_SLOT_END,
          `{ accessFiltering: 'resource_permission', key: '${key}', owningModuleId: '${vertical.moduleId}', resourceType: '${resourceKey}' },`,
        ],
        [
          MODULE_MANIFEST_SHELL_SEARCH_SLOT_START,
          MODULE_MANIFEST_SHELL_SEARCH_SLOT_END,
          `searchContribution({ contributionKey: '${vertical.moduleId}.search.${name}', entrypoint: { access: 'read', authorization: ${renderReadAuthorization(config)}, entrypointKey: '${vertical.moduleId}.search.${name}', moduleKey: '${vertical.moduleId}', role: 'search', scope: 'tenant' }, searchKey: '${key}' }),`,
        ],
      ],
      registration: [
        [
          MODULE_REGISTRATION_SEARCH_SLOT_START,
          MODULE_REGISTRATION_SEARCH_SLOT_END,
          `'${name}': () => import('./src/api/${name}-search-client.ts'),`,
        ],
      ],
    };
  }
  return {
    manifest: [
      [
        MODULE_MANIFEST_REPORT_SLOT_START,
        MODULE_MANIFEST_REPORT_SLOT_END,
        `{ accessFiltering: 'resource_permission', dimensions: [], key: '${key}', label: '${toTitle(name)}', owningModuleId: '${vertical.moduleId}', resourceTypes: ['${resourceKey}'] },`,
      ],
      [
        MODULE_MANIFEST_SHELL_REPORT_SLOT_START,
        MODULE_MANIFEST_SHELL_REPORT_SLOT_END,
        `reportContribution({ contributionKey: '${vertical.moduleId}.report.${name}', entrypoint: { access: 'read', authorization: ${renderReadAuthorization(config)}, entrypointKey: '${vertical.moduleId}.report.${name}', moduleKey: '${vertical.moduleId}', role: 'report', scope: 'tenant' }, reportKey: '${key}' }),`,
      ],
    ],
    registration: [
      [
        MODULE_REGISTRATION_REPORT_SLOT_START,
        MODULE_REGISTRATION_REPORT_SLOT_END,
        `'${name}': () => import('./src/api/${name}-report-client.ts'),`,
      ],
    ],
  };
};

/* eslint-disable unicorn/no-array-reduce -- Slot patches intentionally flow through the accumulated document. */
const patchSlots = (content: string, slots: readonly [string, string, string][]): string =>
  slots.reduce(
    (current, [start, end, line]) =>
      insertSortedSlot(current, start, end, [line], (candidate) => candidate.endsWith(',')),
    content,
  );
/* eslint-enable unicorn/no-array-reduce */

const patchFederationExposure = Effect.fn('GovernedContributionScaffold.patchFederationExposure')(
  function* patchFederationExposure(vertical: OntosVerticalMetadata, name: string) {
    const configPath = yield* tryScaffold('failed to resolve Module Federation config path', () =>
      resolveContainedPath(vertical.directory, 'module-federation.config.ts'),
    );
    const fileSystem = yield* FileSystem.FileSystem;
    const content = yield* fileSystem
      .readFileString(configPath)
      .pipe(
        Effect.mapError((cause) =>
          scaffoldFailure(`failed to read Module Federation config ${configPath}`, cause),
        ),
      );
    const next = yield* tryScaffold('failed to patch Module Federation exposure', () =>
      insertModuleFederationExposure(
        content,
        `./${toPascalCase(name)}`,
        `./src/components/${name}.tsx`,
      ),
    );
    return { content: next, kind: 'update' as const, path: configPath };
  },
);

/* eslint-disable no-nested-ternary, unicorn/no-nested-ternary -- Existing kind dispatch is kept behaviorally unchanged while the standalone lint gate is enforced. */
export const planGovernedContributionScaffold = Effect.fn('GovernedContributionScaffold.plan')(
  function* planGovernedContributionScaffold(
    workspaceRoot: string,
    kind: GovernedContributionKind,
    config: GovernedContributionScaffoldConfig,
  ) {
    const name = yield* tryScaffold('governed contribution name is invalid', () =>
      requireCanonicalSlug(config.name, kind),
    );
    const resource =
      config.resource === undefined
        ? undefined
        : yield* tryScaffold('governed contribution resource is invalid', () =>
            requireCanonicalSlug(config.resource ?? '', 'resource'),
          );
    const vertical = yield* discoverOntosModuleEffect(workspaceRoot, config.vertical);
    const isComponent = kind === PUBLIC_COMPONENT_KIND;
    const isApi = kind === MODULE_API_KIND;
    const directory =
      kind === REPORT_KIND ? 'reports' : kind === SEARCH_PROVIDER_KIND ? 'search' : '';
    const artifactPath = yield* tryScaffold('failed to resolve governed contribution path', () =>
      resolveContainedPath(
        vertical.directory,
        ...(isComponent
          ? ['src', 'components', `${name}.tsx`]
          : isApi
            ? ['shared', 'apis', `${name}.ts`]
            : ['src', directory, `${name}.provider.ts`]),
      ),
    );
    const artifact = yield* tryScaffold('failed to render governed contribution', () => {
      if (isComponent) {
        return renderPublicComponent(name);
      }
      if (isApi) {
        return renderApiContract(name);
      }
      if (isProviderContribution(kind)) {
        return renderProvider(kind, vertical, name, config);
      }
      return raiseScaffoldFailure('unsupported governed contribution', kind);
    });
    const mutations: Mutation[] = [yield* createMutationEffect(artifactPath, artifact)];
    if (isApi) {
      const readPath = yield* tryScaffold('failed to resolve governed read path', () =>
        resolveContainedPath(vertical.directory, 'src', 'api', `${name}.read.ts`),
      );
      const readSource = yield* tryScaffold('failed to render governed read', () =>
        renderModuleApiRead(vertical, name, config),
      );
      mutations.push(yield* createMutationEffect(readPath, readSource));
    }
    let clientPath: string | undefined;
    let serverPath: string | undefined;
    if (kind === MODULE_API_KIND || isProviderContribution(kind)) {
      const suffix = isApi ? 'client' : kind === REPORT_KIND ? 'report-client' : 'search-client';
      clientPath = yield* tryScaffold('failed to resolve governed client path', () =>
        resolveContainedPath(vertical.directory, 'src', 'api', `${name}-${suffix}.ts`),
      );
      mutations.push(
        yield* createMutationEffect(
          clientPath,
          isApi ? renderApiClient(vertical, name) : renderProviderClient(kind, vertical, name),
        ),
      );
      if (isProviderContribution(kind)) {
        const providerContractPath = yield* tryScaffold(
          'failed to resolve provider contract path',
          () =>
            resolveContainedPath(
              vertical.directory,
              'shared',
              'apis',
              `${name}-${kind === REPORT_KIND ? REPORT_KIND : 'search'}.ts`,
            ),
        );
        mutations.push(
          yield* createMutationEffect(
            providerContractPath,
            renderProviderApiContract(kind, vertical, name),
          ),
        );
      }
      serverPath = yield* tryScaffold('failed to resolve governed server path', () =>
        resolveContainedPath(
          vertical.directory,
          'api',
          `${name}-${isApi ? 'read' : kind === REPORT_KIND ? REPORT_KIND : 'search'}-server.ts`,
        ),
      );
      mutations.push(yield* createMutationEffect(serverPath, renderGovernedServer(kind, name)));
      const boundary = yield* planActionBoundaryScaffold(workspaceRoot, {
        vertical: vertical.slug,
      });
      mutations.push(...boundary.mutations);
    }
    const ownerImport = manifestImport(kind, name);
    let manifest = vertical.manifestContent;
    if (ownerImport !== undefined) {
      manifest = yield* tryScaffold('failed to patch module manifest imports', () =>
        insertSortedSlot(
          manifest,
          MODULE_MANIFEST_IMPORT_SLOT_START,
          MODULE_MANIFEST_IMPORT_SLOT_END,
          [ownerImport],
          isModuleManifestImport,
        ),
      );
    }
    const slots = yield* tryScaffold('failed to plan governed contribution owner slots', () =>
      slotLine(kind, vertical, name, resource, config),
    );
    const registration = yield* tryScaffold('failed to patch governed contribution slots', () => {
      manifest = patchSlots(manifest, slots.manifest);
      return patchSlots(vertical.registrationContent, slots.registration);
    });
    const manifestMutation = yield* tryScaffold('failed to update module manifest', () =>
      updateMutation(vertical.manifestPath, vertical.manifestContent, manifest),
    );
    const registrationMutation = yield* tryScaffold('failed to update module registration', () =>
      updateMutation(vertical.registrationPath, vertical.registrationContent, registration),
    );
    if (manifestMutation !== undefined) {
      mutations.push(manifestMutation);
    }
    if (registrationMutation !== undefined) {
      mutations.push(registrationMutation);
    }
    if (isComponent) {
      mutations.push(yield* patchFederationExposure(vertical, name));
    }
    yield* tryScaffold('governed contribution mutation paths are invalid', () =>
      ensureUniqueMutationPaths(mutations),
    );
    const result =
      clientPath === undefined || serverPath === undefined
        ? { artifactPath }
        : { artifactPath, clientPath, serverPath };
    return { mutations, result };
  },
);
/* eslint-enable no-nested-ternary, unicorn/no-nested-ternary */
