// @generated by OntOS Codesmith Action v1
// @ontos-action-owner commerce.tax
// @ontos-action-slug end-tax-rule-revision
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineActionBusinessPermission, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect, Schema } from 'effect';

import {
  EndTaxRuleRevisionPayloadSchema,
  EndTaxRuleRevisionResultSchema,
} from '../../shared/actions/tax-governance.ts';
import type { EndTaxRuleRevisionPayload } from '../../shared/actions/tax-governance.ts';
import {
  TaxGovernanceAuditEvidenceSchema,
  TaxGovernanceConflict,
  TaxGovernanceNotFound,
  TaxGovernancePersistenceUnavailable,
  TaxGovernanceStaleBasis,
} from '../../shared/domain/tax-governance-errors.ts';
import type { TaxRuleGovernancePersistence } from '../services/tax-rule-governance.service.ts';
import { taxRuleRevisionRef, taxRuleGovernanceServiceFactory } from '../services/tax-rule-governance.service.ts';
import { failGovernance, governedInvocation } from './tax-governance-support.ts';

const domainEvents = {} as const;
const ActionErrorSchema = Schema.Union([
  TaxGovernanceConflict,
  TaxGovernanceNotFound,
  TaxGovernancePersistenceUnavailable,
  TaxGovernanceStaleBasis,
]);

export const handleEndTaxRuleRevision = Effect.fn('EndTaxRuleRevisionAction.handle')(function* endTaxRuleRevision(
  payload: EndTaxRuleRevisionPayload,
  context: ActionHandlerContext<typeof domainEvents, TaxRuleGovernancePersistence>,
) {
  const outcome = yield* context.services.endTaxRuleRevision({ ...payload, ...(yield* governedInvocation(context)) });
  if ('kind' in outcome) {
    return yield* failGovernance(outcome, 'Tax Rule Revision');
  }
  yield* context.recordAuditEvidence({
    action: 'END_TAX_RULE_REVISION',
    changed: outcome.ended,
    expectedBasisFingerprint: payload.expectedBasisFingerprint,
    meaningFingerprint: outcome.meaningFingerprint,
    operation: 'END',
    reason: payload.reason,
    resourceId: outcome.revisionId,
    resourceType: 'commerce.tax.tax-rule-revision',
    resultingEndFactId: outcome.endFactId,
  });
  return {
    ended: outcome.ended,
    taxRuleRevisionRef: taxRuleRevisionRef(context.scope.tenantId, outcome.revisionId),
  };
});

export const endTaxRuleRevisionAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'commerce.tax.end-tax-rule-revision.access.v1',
    },
    actionKey: 'commerce.tax.end-tax-rule-revision',
    auditEvidenceSchema: TaxGovernanceAuditEvidenceSchema,
    auditProfile: 'sensitive',
    businessPermission: defineActionBusinessPermission<EndTaxRuleRevisionPayload>((_payload, scope) => ({
      permission: 'tax.rule.manage',
      target: { kind: 'tax_selling_legal_entity', legalEntityId: scope.legalEntityId ?? '', tenantId: scope.tenantId },
    })),
    domainErrorSchema: ActionErrorSchema,
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'commerce.tax.end-tax-rule-revision',
      moduleKey: 'commerce.tax',
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'required',
    owningModuleKey: 'commerce.tax',
    payloadSchema: EndTaxRuleRevisionPayloadSchema,
    policies: [],
    resultSchema: EndTaxRuleRevisionResultSchema,
    schemaVersion: '1',
  },
  handleEndTaxRuleRevision,
  taxRuleGovernanceServiceFactory,
);

// <generated-outbox-message-exports>
// </generated-outbox-message-exports>
