// @generated by OntOS Codesmith Action v1
// @ontos-action-owner payment.term-catalog
// @ontos-action-slug configure-payment-term-source-authority
import type { ActionHandlerContext } from '@app/core-runtime';
import { defineAction, defineActionResourcePermission, defineTenantModuleEntrypoint } from '@app/core-runtime';
import { Effect, Predicate, Schema } from 'effect';
import {
  ConfigurePaymentTermSourceAuthorityPayloadSchema,
  ConfigurePaymentTermSourceAuthorityResultSchema,
} from '../../shared/actions/configure-payment-term-source-authority.ts';
import type { ConfigurePaymentTermSourceAuthorityPayload } from '../../shared/actions/configure-payment-term-source-authority.ts';
import { PaymentTermAuditEvidenceSchema } from '../../shared/domain/payment-term.ts';
import type { PaymentTermSourcePersistence } from '../persistence/payment-term-source-persistence.ts';
import { paymentTermSourcePersistenceForScope } from '../persistence/payment-term-source-persistence.ts';
import {
  PaymentTermCatalogPersistenceConflict,
  PaymentTermCatalogPersistenceUnavailable,
} from '../persistence/errors.ts';
import { createConfigurePaymentTermSourceAuthorityPaymentTermCatalogSourceAuthorityConfiguredV1OutboxMessage } from './configure-payment-term-source-authority-payment-term-catalog-source-authority-configured-v1.outbox-message.ts';

export { ConfigurePaymentTermSourceAuthorityPayloadSchema } from '../../shared/actions/configure-payment-term-source-authority.ts';
const MODULE_KEY = 'payment.term-catalog' as const;
const ROOT_RESOURCE_TYPE = 'payment.term-catalog.payment-term-catalog-root' as const;
const domainEvents = {
  'payment.term-catalog.source-authority-configured.v1': ConfigurePaymentTermSourceAuthorityResultSchema,
} as const;
export const handleConfigurePaymentTermSourceAuthority = Effect.fn('ConfigurePaymentTermSourceAuthority.handle')(
  function* configurePaymentTermSourceAuthority(
    payload: ConfigurePaymentTermSourceAuthorityPayload,
    context: ActionHandlerContext<typeof domainEvents, PaymentTermSourcePersistence>,
  ) {
    const outcome = yield* context.services.configureSourceAuthority({
      ...payload,
      actingPrincipalId: context.scope.principalId,
      actionInvocationId: context.actionInvocationId,
    });
    const result = outcome;
    const changed = Predicate.isTagged(outcome, 'configured');
    yield* context.recordAuditEvidence({ reason: payload.reason });
    yield* context.recordDataAccess({
      accessKind: 'read',
      queryHash: 'source-authority-configured',
      resultCount: 1,
      servingModuleKey: MODULE_KEY,
      targetModuleKey: MODULE_KEY,
      targetResourceId: context.scope.legalEntityId ?? '',
      targetResourceType: ROOT_RESOURCE_TYPE,
    });
    if (changed) {
      const event = yield* context.addDomainEvent({
        eventType: 'payment.term-catalog.source-authority-configured.v1',
        payloadJson: result,
        producerModuleKey: MODULE_KEY,
        subjectModuleKey: MODULE_KEY,
        subjectResourceId: context.scope.legalEntityId ?? '',
        subjectResourceType: ROOT_RESOURCE_TYPE,
      });
      yield* context.addOutboxMessage(
        event,
        createConfigurePaymentTermSourceAuthorityPaymentTermCatalogSourceAuthorityConfiguredV1OutboxMessage(result),
      );
    }
    return result;
  },
);
export const configurePaymentTermSourceAuthorityAction = defineAction(
  {
    accessEvidencePolicy: {
      captureMode: 'metadata_only',
      policyKey: 'payment.term-catalog.configure-payment-term-source-authority.access.v1',
    },
    actionKey: 'payment.term-catalog.configure-payment-term-source-authority',
    auditEvidenceSchema: PaymentTermAuditEvidenceSchema,
    auditProfile: 'standard',
    domainErrorSchema: Schema.Union([PaymentTermCatalogPersistenceConflict, PaymentTermCatalogPersistenceUnavailable]),
    domainEvents,
    entrypoint: defineTenantModuleEntrypoint({
      access: 'write',
      authorization: { kind: 'action_execution', provisioning: 'explicit' },
      entrypointKey: 'payment.term-catalog.configure-payment-term-source-authority',
      moduleKey: MODULE_KEY,
      role: 'action',
    }),
    idempotency: 'required',
    legalEntityScope: 'required',
    owningModuleKey: MODULE_KEY,
    payloadSchema: ConfigurePaymentTermSourceAuthorityPayloadSchema,
    policies: [],
    resourcePermission: defineActionResourcePermission<ConfigurePaymentTermSourceAuthorityPayload>(
      (_payload, scope) => ({
        permission: 'write',
        resource: {
          moduleId: MODULE_KEY,
          resourceId: scope.legalEntityId ?? '',
          resourceType: ROOT_RESOURCE_TYPE,
        },
      }),
    ),
    resultSchema: ConfigurePaymentTermSourceAuthorityResultSchema,
    schemaVersion: '1',
  },
  handleConfigurePaymentTermSourceAuthority,
  paymentTermSourcePersistenceForScope,
);
// <generated-outbox-message-exports>
export { ConfigurePaymentTermSourceAuthorityPaymentTermCatalogSourceAuthorityConfiguredV1OutboxPayloadSchema } from './configure-payment-term-source-authority-payment-term-catalog-source-authority-configured-v1.outbox-message.ts';
export { ConfigurePaymentTermSourceAuthorityPaymentTermCatalogSourceAuthorityConfiguredV1OutboxProducerModuleKey } from './configure-payment-term-source-authority-payment-term-catalog-source-authority-configured-v1.outbox-message.ts';
export { ConfigurePaymentTermSourceAuthorityPaymentTermCatalogSourceAuthorityConfiguredV1OutboxTopic } from './configure-payment-term-source-authority-payment-term-catalog-source-authority-configured-v1.outbox-message.ts';
export { createConfigurePaymentTermSourceAuthorityPaymentTermCatalogSourceAuthorityConfiguredV1OutboxMessage } from './configure-payment-term-source-authority-payment-term-catalog-source-authority-configured-v1.outbox-message.ts';
export type { ConfigurePaymentTermSourceAuthorityPaymentTermCatalogSourceAuthorityConfiguredV1OutboxPayload } from './configure-payment-term-source-authority-payment-term-catalog-source-authority-configured-v1.outbox-message.ts';
// </generated-outbox-message-exports>
