// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner payment.term-catalog
// @ontos-action-http-slug retire-payment-term
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted, Schema } from 'effect';
import {
  RetirePaymentTermActionApi,
  RetirePaymentTermPayloadSchema,
} from '../../shared/apis/retire-payment-term-action.ts';
import type { RetirePaymentTermPayload } from '../../shared/actions/retire-payment-term.ts';
import { operationGateway } from './action-gateway.ts';

const traceIdOption = 'traceId' as const;

export interface RetirePaymentTermActionClientOptions {
  readonly baseUrl?: string | URL;
  readonly gateway?: Parameters<typeof operationGateway.invoke>[1];
  readonly idempotencyKey: string;
  readonly [traceIdOption]?: string;
}

type AuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options: RetirePaymentTermActionClientOptions,
];
type OperationInvocation = readonly [
  requestCorrelation: string,
  options: RetirePaymentTermActionClientOptions,
];

interface MakeClientOptions {
  readonly credential: Redacted.Redacted;
  readonly options: RetirePaymentTermActionClientOptions;
  readonly requestCorrelation: string;
}

const makeClient = ({ credential, options, requestCorrelation }: MakeClientOptions) =>
  makeGovernedEffectBffClient(
    {
      api: RetirePaymentTermActionApi,
      credential,
      defaultApiPrefix: '/payment-term-catalog-api',
      requestCorrelation,
    },
    options,
  );

export const executeRetirePaymentTermWithAuthorization = (
  payload: RetirePaymentTermPayload,
  ...[credential, requestCorrelation, options]: AuthorizedInvocation
) =>
  Schema.encodeUnknownEffect(RetirePaymentTermPayloadSchema)(payload).pipe(
    Effect.flatMap((encoded) =>
      makeClient({ credential: Redacted.make(credential), options, requestCorrelation }).pipe(
        Effect.flatMap((client) =>
          client.retirePaymentTermAction.execute({
            headers: { 'idempotency-key': options.idempotencyKey },
            payload: encoded,
          }),
        ),
      ),
    ),
  );

export const executeRetirePaymentTerm = (
  payload: RetirePaymentTermPayload,
  ...[requestCorrelation, options]: OperationInvocation
) =>
  operationGateway.invoke(
    (credential) =>
      executeRetirePaymentTermWithAuthorization(payload, credential, requestCorrelation, options),
    options.gateway,
  );
