export const PRICING_RUNTIME_TABLE_GRANTS = [
  { privileges: ['select'], table: 'contractual_discount_action_invocation_receipts' },
  { privileges: ['select'], table: 'contractual_discount_revisions' },
  { privileges: ['select'], table: 'contractual_discount_schedule_acknowledgements' },
  { privileges: ['select'], table: 'contractual_discount_schedule_heads' },
  { privileges: ['select'], table: 'contractual_discount_set_heads' },
  { privileges: ['select'], table: 'contractual_discount_set_revisions' },
  { privileges: ['select'], table: 'contractual_discount_set_roots' },
  { privileges: ['select'], table: 'contractual_discounts' },
  { privileges: ['select'], table: 'currency_support_action_result_receipts' },
  {
    privileges: ['select', 'insert'],
    table: 'currency_support_roots',
  },
  {
    privileges: ['select', 'insert'],
    table: 'currency_support_schedule_entries',
  },
  {
    privileges: ['select', 'insert', 'update'],
    table: 'currency_support_schedule_heads',
  },
  {
    privileges: ['select', 'insert'],
    table: 'currency_support_schedule_revisions',
  },
  {
    privileges: ['select', 'insert'],
    table: 'currency_support_value_revisions',
  },
  {
    privileges: ['select', 'insert'],
    table: 'fee_action_invocation_receipts',
  },
  {
    privileges: ['select', 'insert'],
    table: 'fee_revisions',
  },
  {
    privileges: ['select', 'insert'],
    table: 'external_price_source_authority_grants',
  },
  { privileges: ['select'], table: 'fee_set_heads' },
  { privileges: ['select'], table: 'fee_set_revisions' },
  { privileges: ['select'], table: 'fee_set_roots' },
  {
    privileges: ['select', 'insert'],
    table: 'fee_schedule_acknowledgements',
  },
  {
    privileges: ['select', 'insert'],
    table: 'fee_schedule_entries',
  },
  {
    privileges: ['select', 'insert', 'update'],
    table: 'fee_schedule_heads',
  },
  {
    privileges: ['select', 'insert'],
    table: 'fee_schedule_revisions',
  },
  {
    privileges: ['select', 'insert'],
    table: 'fees',
  },
  {
    privileges: ['delete', 'insert', 'select'],
    table: 'gateway_assertion_redemptions',
  },
  { privileges: ['select'], table: 'price_candidate_set_heads' },
  { privileges: ['select'], table: 'price_candidate_set_revisions' },
  { privileges: ['select'], table: 'price_candidate_set_roots' },
  { privileges: ['select'], table: 'price_fee_action_invocation_claims' },
  { privileges: ['select'], table: 'price_fee_action_result_receipts' },
  {
    privileges: ['select', 'insert'],
    table: 'price_invocation_receipts',
  },
  {
    privileges: ['select', 'insert'],
    table: 'price_revisions',
  },
  {
    privileges: ['select', 'insert'],
    table: 'price_schedule_acknowledgements',
  },
  {
    privileges: ['select', 'insert'],
    table: 'price_schedule_entries',
  },
  {
    privileges: ['select', 'insert', 'update'],
    table: 'price_schedule_heads',
  },
  {
    privileges: ['select', 'insert'],
    table: 'price_schedule_revisions',
  },
  {
    privileges: ['select', 'insert'],
    table: 'price_source_assertion_deliveries',
  },
  {
    privileges: ['select', 'insert'],
    table: 'price_source_assertions',
  },
  {
    privileges: ['select', 'insert'],
    table: 'prices',
  },
  { privileges: ['select', 'insert'], table: 'pricing_commitment_confirmations' },
  { privileges: ['select', 'insert'], table: 'pricing_quotations' },
  { privileges: ['select'], table: 'quantity_tier_action_result_receipts' },
  {
    privileges: ['select', 'insert'],
    table: 'quantity_tier_revisions',
  },
  {
    privileges: ['select', 'insert'],
    table: 'quantity_tier_schedule_acknowledgements',
  },
  {
    privileges: ['select', 'insert'],
    table: 'quantity_tier_schedule_entries',
  },
  {
    privileges: ['select', 'insert', 'update'],
    table: 'quantity_tier_schedule_heads',
  },
  {
    privileges: ['select', 'insert'],
    table: 'quantity_tier_schedule_revisions',
  },
  {
    privileges: ['select', 'insert'],
    table: 'quantity_tiers',
  },
  { privileges: ['select', 'insert', 'update'], table: 'quantity_tier_set_heads' },
  { privileges: ['select', 'insert'], table: 'quantity_tier_set_revisions' },
  { privileges: ['select', 'insert'], table: 'quantity_tier_set_roots' },
  { privileges: ['select'], table: 'zero_floor_action_invocation_receipts' },
  { privileges: ['select'], table: 'zero_floor_authorization_revisions' },
  { privileges: ['select'], table: 'zero_floor_authorization_schedule_heads' },
  { privileges: ['select'], table: 'zero_floor_authorizations' },
  { privileges: ['select'], table: 'zero_floor_governance_approvals' },
  { privileges: ['select'], table: 'zero_floor_schedule_acknowledgements' },
  { privileges: ['select'], table: 'zero_floor_set_heads' },
  { privileges: ['select'], table: 'zero_floor_set_revisions' },
  { privileges: ['select'], table: 'zero_floor_set_roots' },
] as const;

export const PRICING_RUNTIME_ROUTINE_SIGNATURES = [
  'pricing.assess_external_price_source_authority_v1(uuid,uuid,jsonb)',
  'pricing.bind_price_source_provenance_v1(uuid,uuid,uuid,uuid,jsonb)',
  'pricing.compensate_tenant_currency_support_recovery_v1(uuid,jsonb)',
  'pricing.currency_support_schedule_acknowledgement_v1(uuid,uuid,uuid,integer,uuid,timestamptz,jsonb,uuid)',
  'pricing.currency_support_scheduled_revision_json_v1(uuid,uuid,uuid,timestamptz,timestamptz)',
  'pricing.define_commercial_fee_v1(uuid,uuid,jsonb)',
  'pricing.define_price_v2(uuid,uuid,jsonb)',
  'pricing.lookup_exact_current_price_v1(uuid,uuid,jsonb)',
  'pricing.lookup_exact_current_price_v2(uuid,uuid,jsonb)',
  'pricing.fee_id_for_identity_v1(uuid,uuid,jsonb)',
  'pricing.fee_identity_json_v1(uuid,uuid,uuid)',
  'pricing.price_source_provenance_json_v1(uuid,uuid,uuid,uuid)',
  'pricing.price_schedule_acknowledgement_v1(uuid,uuid,uuid,uuid,integer,uuid,timestamptz,text,numeric,text,uuid)',
  'pricing.quantity_tier_id_for_identity_v1(uuid,uuid,jsonb)',
  'pricing.quantity_tier_identity_json_v1(uuid,uuid,uuid)',
  'pricing.read_commercial_fee_schedule_v1(uuid,uuid,jsonb)',
  'pricing.read_current_commercial_fee_v1(uuid,uuid,jsonb)',
  'pricing.read_current_quantity_tier_v1(uuid,uuid,jsonb)',
  'pricing.read_current_supported_currencies(uuid,uuid,jsonb)',
  'pricing.read_current_price_definition_v1(uuid,uuid,uuid)',
  'pricing.read_price_schedule_v1(uuid,uuid,jsonb)',
  'pricing.read_quantity_tier_schedule_v1(uuid,uuid,jsonb)',
  'pricing.read_tenant_currency_support_v1(uuid,jsonb)',
  'pricing.read_tenant_supported_currencies_v2(uuid,uuid,jsonb)',
  'pricing.revalidate_tenant_currency_support_v1(uuid)',
  'pricing.issue_tenant_currency_support_proof_v1(uuid,jsonb)',
  'pricing.resolve_tenant_currency_support_proof_v1(uuid,jsonb)',
  'pricing.revise_price_v2(uuid,uuid,jsonb)',
  'pricing.revise_commercial_fee_v1(uuid,uuid,jsonb)',
  'pricing.manage_commercial_fee_revision_v1(uuid,uuid,jsonb)',
  'pricing.scheduled_fee_revision_json_v1(uuid,uuid,uuid,uuid,timestamp with time zone,timestamp with time zone)',
  'pricing.scheduled_quantity_tier_revision_json_v1(uuid,uuid,uuid,uuid,timestamp with time zone,timestamp with time zone)',
  'pricing.scheduled_price_revision_json_v1(uuid,uuid,uuid,uuid,timestamptz,timestamptz)',
  'pricing.set_supported_currencies(uuid,uuid,jsonb)',
  'pricing.set_tenant_currency_support_v1(uuid,jsonb)',
  // #797 set authorities and governed owner-result lookup.
  'pricing.read_current_quantity_tier_set_v1(uuid,uuid,jsonb)',
  'pricing.resolve_quantity_tier_set_proof_v1(uuid,uuid,jsonb)',
  'pricing.verify_quantity_tier_set_generation_v1(uuid,uuid,jsonb)',
  'pricing.read_exact_price_candidate_set_v1(uuid,uuid,jsonb)',
  'pricing.verify_exact_price_candidate_set_generation_v1(uuid,uuid,jsonb)',
  'pricing.read_current_commercial_fee_set_v1(uuid,uuid,jsonb)',
  'pricing.verify_commercial_fee_set_generation_v1(uuid,uuid,jsonb)',
  'pricing.encode_uri_component_v1(text)',
  'pricing.canonicalize_management_json_v1(jsonb)',
  'pricing.management_instant_v1(timestamptz)',
  'pricing.management_fingerprint_v1(jsonb)',
  'pricing.zero_floor_predicate_ref_v1(jsonb)',
  'pricing.zero_floor_authorization_fingerprint_v1(jsonb)',
  'pricing.zero_floor_schedule_at_v1(jsonb)',
  'pricing.uri_encode_component_v1(text)',
  'pricing.contractual_discount_identity_ref_v1(jsonb)',
  'pricing.contractual_discount_predicate_ref_v1(jsonb)',
  'pricing.contractual_discount_schedule_at_v1(jsonb,timestamptz)',
  'pricing.manage_contractual_discount_v1(uuid,uuid,jsonb)',
  'pricing.lookup_contractual_discount_result_v1(uuid,uuid,jsonb)',
  'pricing.read_current_contractual_discount_set_v1(uuid,uuid,jsonb)',
  'pricing.resolve_contractual_discount_set_proof_v1(uuid,uuid,jsonb)',
  'pricing.verify_contractual_discount_set_generation_v1(uuid,uuid,jsonb)',
  'pricing.zero_floor_current_revision_v1(jsonb,timestamptz)',
  'pricing.zero_floor_instant_v1(timestamptz)',
  'pricing.zero_floor_approval_for_v1(uuid,uuid,jsonb,timestamptz)',
  'pricing.zero_floor_governance_proof_matches_v1(uuid,uuid,jsonb,jsonb,timestamptz)',
  'pricing.create_zero_floor_authorization_v1(uuid,uuid,jsonb)',
  'pricing.manage_zero_floor_authorization_v1(uuid,uuid,jsonb)',
  'pricing.read_current_zero_floor_authorization_set_v1(uuid,uuid,jsonb)',
  'pricing.read_current_zero_floor_authorization_governance_proof_v1(uuid,uuid,jsonb)',
  'pricing.verify_zero_floor_authorization_set_generation_v1(uuid,uuid,jsonb)',
  'pricing.resolve_material_proof_v1(uuid,uuid,jsonb)',
  'pricing.read_zero_floor_authorization_schedule_v1(uuid,uuid,jsonb)',
  'pricing.lookup_zero_floor_authorization_result_v1(uuid,uuid,jsonb)',
  'pricing.define_price_v3(uuid,uuid,jsonb)',
  'pricing.revise_price_v3(uuid,uuid,jsonb)',
  'pricing.define_commercial_fee_v2(uuid,uuid,jsonb)',
  'pricing.revise_commercial_fee_v2(uuid,uuid,jsonb)',
  'pricing.manage_commercial_fee_revision_v2(uuid,uuid,jsonb)',
  'pricing.lookup_price_action_result_v1(uuid,uuid,jsonb)',
  'pricing.lookup_commercial_fee_action_result_v1(uuid,uuid,jsonb)',
  'pricing.lookup_quantity_tier_action_result_v1(uuid,uuid,jsonb)',
  'pricing.define_quantity_tier_v2(uuid,uuid,jsonb)',
  'pricing.revise_quantity_tier_v2(uuid,uuid,jsonb)',
  'pricing.set_tenant_currency_support_v2(uuid,jsonb)',
  'pricing.store_external_price_source_authority_grant_v1(uuid,uuid,jsonb)',
  'pricing.lookup_tenant_currency_support_result_v1(uuid,jsonb)',
  'pricing.verify_tenant_currency_support_generation_v1(uuid,jsonb)',
  'pricing.persist_pricing_commitment_confirmation_v1(uuid,uuid,jsonb)',
  'pricing.persist_pricing_quotation_v1(uuid,uuid,uuid,uuid,text,jsonb)',
  'pricing.read_pricing_commitment_confirmation_v1(uuid,uuid,text)',
  'pricing.read_pricing_quotation_v1(uuid,uuid,uuid,text)',
  'pricing.lookup_pricing_quotation_invocation_v1(uuid,uuid,uuid,uuid)',
  'pricing.read_pricing_quotation_history_v1(uuid,uuid,uuid,integer)',
] as const;
