// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { catalogApi } from '../shared/api.ts';
import {
  ActivatePackageDefinitionRecoveryAuthenticationProblemSchema,
  ActivatePackageDefinitionRecoveryForbiddenProblemSchema,
  ActivatePackageDefinitionRecoveryInternalProblemSchema,
  ActivatePackageDefinitionRecoveryInvalidProblemSchema,
  ActivatePackageDefinitionRecoveryNotFoundProblemSchema,
  ActivatePackageDefinitionRecoveryPolicyConflictProblemSchema,
  ActivatePackageDefinitionRecoveryPolicyProblemSchema,
  ActivatePackageDefinitionRecoveryUnavailableProblemSchema,
} from '../shared/apis/activate-package-definition-recovery.ts';
import { activatePackageDefinitionRecoveryRead } from '../src/api/activate-package-definition-recovery.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: ActivatePackageDefinitionRecoveryAuthenticationProblemSchema,
  forbidden: ActivatePackageDefinitionRecoveryForbiddenProblemSchema,
  internal: ActivatePackageDefinitionRecoveryInternalProblemSchema,
  invalid: ActivatePackageDefinitionRecoveryInvalidProblemSchema,
  notFound: ActivatePackageDefinitionRecoveryNotFoundProblemSchema,
  policyConflict: ActivatePackageDefinitionRecoveryPolicyConflictProblemSchema,
  policyIneligible: ActivatePackageDefinitionRecoveryPolicyProblemSchema,
  unavailable: ActivatePackageDefinitionRecoveryUnavailableProblemSchema,
});

export const activatePackageDefinitionRecoveryReadApiLive = HttpApiBuilder.group(
  catalogApi,
  'activatePackageDefinitionRecovery',
  (handlers) =>
    handlers.handle(
      'execute',
      makeGovernedReadHttpHandler({
        authenticatePrincipal: authenticateOperationPrincipal,
        problems,
        registration: activatePackageDefinitionRecoveryRead,
      }),
    ),
);
