// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.catalog
// @ontos-action-http-slug correct-sku
import { decodeActionEndpointHeaders } from '@app/core-runtime/http/action-runner';
import { Effect, HttpApiBuilder, Layer } from '@modern-js/bff-effect/effect-edge';
import type { HttpServerRequest } from 'effect/unstable/http';
import { Redacted, Schema } from 'effect';
import { catalogApi } from '../shared/api.ts';
import { correctSkuAction } from '../src/actions/correct-sku.action.ts';
import { bindActionHttpRunner } from './action-http-runner.ts';
import {
  correctSkuActionProblem,
  correctSkuActionSchemaErrorLive,
  mapCorrectSkuActionProblem,
} from './correct-sku-action-problems.ts';

const runActionHttp = bindActionHttpRunner({
  authentication: correctSkuActionProblem.authentication,
  unavailable: () => correctSkuActionProblem.unavailable('operation_context_unavailable'),
});

const execute = Effect.fn('CorrectSkuActionServer.execute')(function* executeCorrectSku(
  payload: typeof correctSkuAction.descriptor.payloadSchema.Encoded,
  request: HttpServerRequest.HttpServerRequest,
) {
  const correlationId = request.headers['x-correlation-id'];
  if (correlationId !== undefined && correlationId.length > 200) {
    return yield* Effect.fail(correctSkuActionProblem.invalid());
  }
  const endpointHeaders = yield* decodeActionEndpointHeaders(request.headers).pipe(
    Effect.mapError(correctSkuActionProblem.invalid),
  );
  const decoded = yield* Schema.decodeEffect(correctSkuAction.descriptor.payloadSchema)(payload).pipe(
    Effect.mapError(correctSkuActionProblem.invalid),
  );
  return yield* runActionHttp({
    endpointHeaders,
    internalProblem: correctSkuActionProblem.internal,
    invalidCorrelationProblem: correctSkuActionProblem.invalid,
    mapError: mapCorrectSkuActionProblem,
    payload: decoded,
    registration: correctSkuAction,
    requestHeaders: {
      authorization: Redacted.make(request.headers['authorization']),
      'x-correlation-id': correlationId,
    },
  });
});

export const correctSkuActionApiLive = HttpApiBuilder.group(catalogApi, 'correctSkuAction', (handlers) =>
  handlers.handle('execute', ({ payload, request }) => execute(payload, request)),
).pipe(Layer.provide(correctSkuActionSchemaErrorLive));
