// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { catalogApi } from '../shared/api.ts';
import {
  CreateProductRecoveryAuthenticationProblemSchema,
  CreateProductRecoveryForbiddenProblemSchema,
  CreateProductRecoveryInternalProblemSchema,
  CreateProductRecoveryInvalidProblemSchema,
  CreateProductRecoveryNotFoundProblemSchema,
  CreateProductRecoveryPolicyConflictProblemSchema,
  CreateProductRecoveryPolicyProblemSchema,
  CreateProductRecoveryUnavailableProblemSchema,
} from '../shared/apis/create-product-recovery.ts';
import { createProductRecoveryRead } from '../src/api/create-product-recovery.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: CreateProductRecoveryAuthenticationProblemSchema,
  forbidden: CreateProductRecoveryForbiddenProblemSchema,
  internal: CreateProductRecoveryInternalProblemSchema,
  invalid: CreateProductRecoveryInvalidProblemSchema,
  notFound: CreateProductRecoveryNotFoundProblemSchema,
  policyConflict: CreateProductRecoveryPolicyConflictProblemSchema,
  policyIneligible: CreateProductRecoveryPolicyProblemSchema,
  unavailable: CreateProductRecoveryUnavailableProblemSchema,
});

export const createProductRecoveryReadApiLive = HttpApiBuilder.group(catalogApi, 'createProductRecovery', (handlers) =>
  handlers.handle(
    'execute',
    makeGovernedReadHttpHandler({
      authenticatePrincipal: authenticateOperationPrincipal,
      problems,
      registration: createProductRecoveryRead,
    }),
  ),
);
