// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { catalogApi } from '../shared/api.ts';
import {
  GovernVariantAllowedValuesRecoveryAuthenticationProblemSchema,
  GovernVariantAllowedValuesRecoveryForbiddenProblemSchema,
  GovernVariantAllowedValuesRecoveryInternalProblemSchema,
  GovernVariantAllowedValuesRecoveryInvalidProblemSchema,
  GovernVariantAllowedValuesRecoveryNotFoundProblemSchema,
  GovernVariantAllowedValuesRecoveryPolicyConflictProblemSchema,
  GovernVariantAllowedValuesRecoveryPolicyProblemSchema,
  GovernVariantAllowedValuesRecoveryUnavailableProblemSchema,
} from '../shared/apis/govern-variant-allowed-values-recovery.ts';
import { governVariantAllowedValuesRecoveryRead } from '../src/api/govern-variant-allowed-values-recovery.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: GovernVariantAllowedValuesRecoveryAuthenticationProblemSchema,
  forbidden: GovernVariantAllowedValuesRecoveryForbiddenProblemSchema,
  internal: GovernVariantAllowedValuesRecoveryInternalProblemSchema,
  invalid: GovernVariantAllowedValuesRecoveryInvalidProblemSchema,
  notFound: GovernVariantAllowedValuesRecoveryNotFoundProblemSchema,
  policyConflict: GovernVariantAllowedValuesRecoveryPolicyConflictProblemSchema,
  policyIneligible: GovernVariantAllowedValuesRecoveryPolicyProblemSchema,
  unavailable: GovernVariantAllowedValuesRecoveryUnavailableProblemSchema,
});

export const governVariantAllowedValuesRecoveryReadApiLive = HttpApiBuilder.group(
  catalogApi,
  'governVariantAllowedValuesRecovery',
  (handlers) =>
    handlers.handle(
      'execute',
      makeGovernedReadHttpHandler({
        authenticatePrincipal: authenticateOperationPrincipal,
        problems,
        registration: governVariantAllowedValuesRecoveryRead,
      }),
    ),
);
