// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { catalogApi } from '../shared/api.ts';
import {
  QuantityBasisCompatibilityAuthenticationProblemSchema,
  QuantityBasisCompatibilityForbiddenProblemSchema,
  QuantityBasisCompatibilityInternalProblemSchema,
  QuantityBasisCompatibilityInvalidProblemSchema,
  QuantityBasisCompatibilityNotFoundProblemSchema,
  QuantityBasisCompatibilityPolicyConflictProblemSchema,
  QuantityBasisCompatibilityPolicyProblemSchema,
  QuantityBasisCompatibilityUnavailableProblemSchema,
} from '../shared/apis/quantity-basis-compatibility.ts';
import { quantityBasisCompatibilityRead } from '../src/api/quantity-basis-compatibility.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: QuantityBasisCompatibilityAuthenticationProblemSchema,
  forbidden: QuantityBasisCompatibilityForbiddenProblemSchema,
  internal: QuantityBasisCompatibilityInternalProblemSchema,
  invalid: QuantityBasisCompatibilityInvalidProblemSchema,
  notFound: QuantityBasisCompatibilityNotFoundProblemSchema,
  policyConflict: QuantityBasisCompatibilityPolicyConflictProblemSchema,
  policyIneligible: QuantityBasisCompatibilityPolicyProblemSchema,
  unavailable: QuantityBasisCompatibilityUnavailableProblemSchema,
});

export const quantityBasisCompatibilityReadApiLive = HttpApiBuilder.group(
  catalogApi,
  'quantityBasisCompatibility',
  (handlers) =>
    handlers.handle(
      'execute',
      makeGovernedReadHttpHandler({
        authenticatePrincipal: authenticateOperationPrincipal,
        problems,
        registration: quantityBasisCompatibilityRead,
      }),
    ),
);
