// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.catalog
// @ontos-action-http-slug remove-product-category-assignment
// oxlint-disable sonarjs/function-name -- Effect Match.tags requires owner-declared tag keys; remove-when: sonarjs accepts discriminant-map properties.
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  RemoveProductCategoryAssignmentActionAlreadyCommittedProblemSchema,
  RemoveProductCategoryAssignmentActionAuthenticationProblemSchema,
  RemoveProductCategoryAssignmentActionCommitIndeterminateProblemSchema,
  RemoveProductCategoryAssignmentActionConflictProblemSchema,
  RemoveProductCategoryAssignmentActionForbiddenProblemSchema,
  RemoveProductCategoryAssignmentActionIneligibleProblemSchema,
  RemoveProductCategoryAssignmentActionInternalProblemSchema,
  RemoveProductCategoryAssignmentActionInvalidProblemSchema,
  RemoveProductCategoryAssignmentActionNotFoundProblemSchema,
  RemoveProductCategoryAssignmentActionPreconditionProblemSchema,
  RemoveProductCategoryAssignmentActionSchemaErrorMiddleware,
  RemoveProductCategoryAssignmentActionUnavailableProblemSchema,
} from '../shared/apis/remove-product-category-assignment-action.ts';
import type { RemoveProductCategoryAssignmentActionProblem } from '../shared/apis/remove-product-category-assignment-action.ts';
import { removeProductCategoryAssignmentAction } from '../src/actions/remove-product-category-assignment.action.ts';

type DomainError = typeof removeProductCategoryAssignmentAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends RemoveProductCategoryAssignmentActionProblem['_tag']> = Extract<
  RemoveProductCategoryAssignmentActionProblem,
  { readonly _tag: Tag }
>;
type DomainProblemIdentity =
  | {
      readonly code: 'category_conflict' | 'category_reference_conflict' | 'category_revision_conflict';
      readonly kind: 'conflict';
    }
  | { readonly code: 'category_not_found'; readonly kind: 'notFound' }
  | { readonly code: 'category_persistence_unavailable'; readonly kind: 'unavailable' };

const problemStatus = {
  authentication: 401,
  conflict: 409,
  forbidden: 403,
  ineligible: 422,
  internal: 500,
  invalid: 400,
  notFound: 404,
  precondition: 428,
  rateLimited: 429,
  timeout: 504,
  unavailable: 503,
} as const;

const categoryActionRejectedProblemByCode = {
  category_conflict: { code: 'category_conflict', kind: 'conflict' },
  category_not_found: { code: 'category_not_found', kind: 'notFound' },
  category_reference_conflict: { code: 'category_reference_conflict', kind: 'conflict' },
  category_revision_conflict: { code: 'category_revision_conflict', kind: 'conflict' },
} as const satisfies Record<
  Extract<DomainError, { readonly _tag: 'CategoryActionRejected' }>['code'],
  DomainProblemIdentity
>;

export const removeProductCategoryAssignmentActionProblem = {
  authentication: (): ProblemOf<'RemoveProductCategoryAssignmentActionAuthenticationProblem'> =>
    RemoveProductCategoryAssignmentActionAuthenticationProblemSchema.make({
      detail: 'A valid audience-scoped Bearer assertion is required.',
      status: problemStatus.authentication,
      title: 'Authentication required',
      type: 'https://ontos.dev/problems/operation-authentication-required',
    }),
  conflict: (
    code: ProblemOf<'RemoveProductCategoryAssignmentActionConflictProblem'>['code'],
    revision?: { readonly actualRevision: number; readonly expectedRevision: number },
  ): ProblemOf<'RemoveProductCategoryAssignmentActionConflictProblem'> =>
    RemoveProductCategoryAssignmentActionConflictProblemSchema.make({
      code,
      detail: 'The Action conflicts with current state.',
      ...revision,
      status: problemStatus.conflict,
      title: 'Action conflict',
      type: 'https://ontos.dev/problems/action-conflict',
    }),
  forbidden: (
    code: ProblemOf<'RemoveProductCategoryAssignmentActionForbiddenProblem'>['code'],
  ): ProblemOf<'RemoveProductCategoryAssignmentActionForbiddenProblem'> =>
    RemoveProductCategoryAssignmentActionForbiddenProblemSchema.make({
      code,
      detail: 'The principal is not permitted to perform this Action.',
      status: problemStatus.forbidden,
      title: 'Action forbidden',
      type: 'https://ontos.dev/problems/action-forbidden',
    }),
  ineligible: (
    code: ProblemOf<'RemoveProductCategoryAssignmentActionIneligibleProblem'>['code'],
  ): ProblemOf<'RemoveProductCategoryAssignmentActionIneligibleProblem'> =>
    RemoveProductCategoryAssignmentActionIneligibleProblemSchema.make({
      code,
      detail: 'The request is not eligible for this Action.',
      status: problemStatus.ineligible,
      title: 'Action ineligible',
      type: 'https://ontos.dev/problems/action-ineligible',
    }),
  internal: (): ProblemOf<'RemoveProductCategoryAssignmentActionInternalProblem'> =>
    RemoveProductCategoryAssignmentActionInternalProblemSchema.make({
      detail: 'The Action could not be completed.',
      status: problemStatus.internal,
      title: 'Action failed',
      type: 'https://ontos.dev/problems/action-failed',
    }),
  invalid: (): ProblemOf<'RemoveProductCategoryAssignmentActionInvalidProblem'> =>
    RemoveProductCategoryAssignmentActionInvalidProblemSchema.make({
      detail: 'The remove-product-category-assignment Action request is invalid.',
      status: problemStatus.invalid,
      title: 'Invalid Action request',
      type: 'https://ontos.dev/problems/action-invalid',
    }),
  notFound: (
    code: ProblemOf<'RemoveProductCategoryAssignmentActionNotFoundProblem'>['code'],
  ): ProblemOf<'RemoveProductCategoryAssignmentActionNotFoundProblem'> =>
    RemoveProductCategoryAssignmentActionNotFoundProblemSchema.make({
      code,
      detail: 'The requested resource was not found.',
      status: problemStatus.notFound,
      title: 'Resource not found',
      type: 'https://ontos.dev/problems/action-resource-not-found',
    }),
  precondition: (): ProblemOf<'RemoveProductCategoryAssignmentActionPreconditionProblem'> =>
    RemoveProductCategoryAssignmentActionPreconditionProblemSchema.make({
      detail: 'An Idempotency-Key header is required.',
      status: problemStatus.precondition,
      title: 'Idempotency key required',
      type: 'https://ontos.dev/problems/idempotency-key-required',
    }),
  unavailable: (
    code: ProblemOf<'RemoveProductCategoryAssignmentActionUnavailableProblem'>['code'],
  ): ProblemOf<'RemoveProductCategoryAssignmentActionUnavailableProblem'> =>
    RemoveProductCategoryAssignmentActionUnavailableProblemSchema.make({
      code,
      detail: 'The Action capability is temporarily unavailable.',
      retryable: true,
      status: problemStatus.unavailable,
      title: 'Action unavailable',
      type: 'https://ontos.dev/problems/action-unavailable',
    }),
} as const;

const mapDomainIdentity = (identity: DomainProblemIdentity): RemoveProductCategoryAssignmentActionProblem =>
  Match.value(identity).pipe(
    Match.when({ kind: 'conflict' as const }, (matched) =>
      removeProductCategoryAssignmentActionProblem.conflict(matched.code),
    ),
    Match.when({ kind: 'notFound' as const }, (matched) =>
      removeProductCategoryAssignmentActionProblem.notFound(matched.code),
    ),
    Match.when({ kind: 'unavailable' as const }, (matched) =>
      removeProductCategoryAssignmentActionProblem.unavailable(matched.code),
    ),
    Match.exhaustive,
  );

const mapDomainProblem = (error: DomainError): RemoveProductCategoryAssignmentActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      CategoryActionRejected: (failure) => mapDomainIdentity(categoryActionRejectedProblemByCode[failure.code]),
      CategoryPersistenceUnavailable: () =>
        removeProductCategoryAssignmentActionProblem.unavailable('category_persistence_unavailable'),
      CategoryRevisionConflict: (failure) =>
        removeProductCategoryAssignmentActionProblem.conflict('category_revision_conflict', {
          actualRevision: failure.actualRevision,
          expectedRevision: failure.expectedRevision,
        }),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): RemoveProductCategoryAssignmentActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        RemoveProductCategoryAssignmentActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Recover its original result by invocation.',
          invocationId: failure.invocationId,
          resolution: 'RECOVER_REMOVE_PRODUCT_CATEGORY_ASSIGNMENT',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: removeProductCategoryAssignmentActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        RemoveProductCategoryAssignmentActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RECOVER_REMOVE_PRODUCT_CATEGORY_ASSIGNMENT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: removeProductCategoryAssignmentActionProblem.internal,
      ActionIdempotencyKeyRequired: removeProductCategoryAssignmentActionProblem.precondition,
      ActionInvocationNotFound: (failure) => removeProductCategoryAssignmentActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) =>
        removeProductCategoryAssignmentActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => removeProductCategoryAssignmentActionProblem.conflict(failure.code),
      ActionPayloadValidationError: removeProductCategoryAssignmentActionProblem.invalid,
      ActionPermissionCheckError: (failure) => removeProductCategoryAssignmentActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => removeProductCategoryAssignmentActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => removeProductCategoryAssignmentActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => removeProductCategoryAssignmentActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => removeProductCategoryAssignmentActionProblem.conflict(failure.code),
      ActionResultValidationError: removeProductCategoryAssignmentActionProblem.internal,
      ActionTransactionError: (failure) => removeProductCategoryAssignmentActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: removeProductCategoryAssignmentActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) =>
        removeProductCategoryAssignmentActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => removeProductCategoryAssignmentActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: removeProductCategoryAssignmentActionProblem.authentication,
      OperationContextDenied: (failure) => removeProductCategoryAssignmentActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => removeProductCategoryAssignmentActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => removeProductCategoryAssignmentActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(removeProductCategoryAssignmentAction.descriptor.domainErrorSchema);
export const mapRemoveProductCategoryAssignmentActionProblem = (
  error: ActionCoreError | DomainError,
): RemoveProductCategoryAssignmentActionProblem =>
  isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error);

export const removeProductCategoryAssignmentActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  RemoveProductCategoryAssignmentActionSchemaErrorMiddleware,
  () => Effect.fail(removeProductCategoryAssignmentActionProblem.invalid()),
);
