// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { catalogApi } from '../shared/api.ts';
import {
  RemoveProductLocalizedFactsRecoveryAuthenticationProblemSchema,
  RemoveProductLocalizedFactsRecoveryForbiddenProblemSchema,
  RemoveProductLocalizedFactsRecoveryInternalProblemSchema,
  RemoveProductLocalizedFactsRecoveryInvalidProblemSchema,
  RemoveProductLocalizedFactsRecoveryNotFoundProblemSchema,
  RemoveProductLocalizedFactsRecoveryPolicyConflictProblemSchema,
  RemoveProductLocalizedFactsRecoveryPolicyProblemSchema,
  RemoveProductLocalizedFactsRecoveryUnavailableProblemSchema,
} from '../shared/apis/remove-product-localized-facts-recovery.ts';
import { removeProductLocalizedFactsRecoveryRead } from '../src/api/remove-product-localized-facts-recovery.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: RemoveProductLocalizedFactsRecoveryAuthenticationProblemSchema,
  forbidden: RemoveProductLocalizedFactsRecoveryForbiddenProblemSchema,
  internal: RemoveProductLocalizedFactsRecoveryInternalProblemSchema,
  invalid: RemoveProductLocalizedFactsRecoveryInvalidProblemSchema,
  notFound: RemoveProductLocalizedFactsRecoveryNotFoundProblemSchema,
  policyConflict: RemoveProductLocalizedFactsRecoveryPolicyConflictProblemSchema,
  policyIneligible: RemoveProductLocalizedFactsRecoveryPolicyProblemSchema,
  unavailable: RemoveProductLocalizedFactsRecoveryUnavailableProblemSchema,
});

export const removeProductLocalizedFactsRecoveryReadApiLive = HttpApiBuilder.group(
  catalogApi,
  'removeProductLocalizedFactsRecovery',
  (handlers) =>
    handlers.handle(
      'execute',
      makeGovernedReadHttpHandler({
        authenticatePrincipal: authenticateOperationPrincipal,
        problems,
        registration: removeProductLocalizedFactsRecoveryRead,
      }),
    ),
);
