// @generated by OntOS Codesmith module-api v1
import { PrivacyOwnerCoverageResultSchema, PrivacyOwnerScopeSchema } from '@app/shared-contracts';
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Match, Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

import { CatalogToStockBindingHistoryEntrySchema } from '../domain/catalog-to-stock-binding.ts';
import { CommitmentProtectionSchema } from '../domain/commitment-protection.ts';
import { ExternalStockCorrelationSchema } from '../domain/external-stock-correlation.ts';
import {
  InventoryEffectLedgerEffectIdSchema,
  InventoryEffectLedgerRecordSchema,
} from '../domain/inventory-effect-ledger.ts';
import { InventorySourceConflictSchema } from '../domain/inventory-source-conflict.ts';
import { ReservationConfirmationSchema } from '../domain/reservation-confirmation.ts';
import { StockSharingEligibilitySchema } from '../domain/stock-sharing-eligibility.ts';
import { CatalogToStockBindingRefSchema } from '../resources/catalog-to-stock-binding.ts';
import { CommitmentProtectionRefSchema } from '../resources/commitment-protection.ts';
import { ExternalStockCorrelationRefSchema } from '../resources/external-stock-correlation.ts';
import { InventoryReservationRefSchema } from '../resources/inventory-reservation.ts';
import { InventorySourceConflictRefSchema } from '../resources/inventory-source-conflict.ts';
import { ReservationConfirmationRefSchema } from '../resources/reservation-confirmation.ts';
import { StockPositionRefSchema } from '../resources/stock-position.ts';
import { StockSharingEligibilityRefSchema } from '../resources/stock-sharing-eligibility.ts';
import { inventoryPrivacyOwnerScopeParts } from '../inventory-privacy-owner-contract.ts';
import { InventoryReconciliationEvidenceDomainPolicyProblemSchema } from './inventory-reconciliation-evidence-domain-policy-problem.ts';
import { InventoryReconciliationEvidenceDomainUnavailableProblemSchema } from './inventory-reconciliation-evidence-domain-unavailable-problem.ts';

export {
  type InventoryReconciliationEvidenceDomainPolicyProblem,
  InventoryReconciliationEvidenceDomainPolicyProblemSchema,
} from './inventory-reconciliation-evidence-domain-policy-problem.ts';
export {
  type InventoryReconciliationEvidenceDomainUnavailableProblem,
  InventoryReconciliationEvidenceDomainUnavailableProblemSchema,
} from './inventory-reconciliation-evidence-domain-unavailable-problem.ts';

export const INVENTORY_RECONCILIATION_EVIDENCE_LIMIT = 100;

const BoundedBindingHistorySchema = Schema.Array(CatalogToStockBindingHistoryEntrySchema).check(
  Schema.isMaxLength(INVENTORY_RECONCILIATION_EVIDENCE_LIMIT),
);
const BoundedSharingHistorySchema = Schema.Array(StockSharingEligibilitySchema).check(
  Schema.isMaxLength(INVENTORY_RECONCILIATION_EVIDENCE_LIMIT),
);
const BoundedConfirmationHistorySchema = Schema.Array(ReservationConfirmationSchema).check(
  Schema.isMaxLength(INVENTORY_RECONCILIATION_EVIDENCE_LIMIT),
);
const BoundedProtectionHistorySchema = Schema.Array(CommitmentProtectionSchema).check(
  Schema.isMaxLength(INVENTORY_RECONCILIATION_EVIDENCE_LIMIT),
);

const EffectOwnerRefSchema = Schema.Union([InventoryReservationRefSchema, StockPositionRefSchema]);

const PrivacyLookupRefSchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(1000), Schema.isTrimmed());

export const InventoryPrivacyOwnerLookupSchema = Schema.Union([
  Schema.TaggedStruct('RESERVATION_OBLIGATION', {
    lookupRef: PrivacyLookupRefSchema,
  }),
  Schema.TaggedStruct('BINDING_HISTORY', {
    bindingRef: CatalogToStockBindingRefSchema,
    lookupRef: PrivacyLookupRefSchema,
  }),
  Schema.TaggedStruct('CONFIRMATION_HISTORY', {
    confirmationRef: ReservationConfirmationRefSchema,
    lookupRef: PrivacyLookupRefSchema,
  }),
  Schema.TaggedStruct('PROTECTION_HISTORY', {
    lookupRef: PrivacyLookupRefSchema,
    protectionRef: CommitmentProtectionRefSchema,
  }),
  Schema.TaggedStruct('EFFECT_OUTCOME', {
    effectId: InventoryEffectLedgerEffectIdSchema,
    lookupRef: PrivacyLookupRefSchema,
  }),
  Schema.TaggedStruct('EXTERNAL_CORRELATION', {
    correlationRef: ExternalStockCorrelationRefSchema,
    lookupRef: PrivacyLookupRefSchema,
  }),
]);
export type InventoryPrivacyOwnerLookup = typeof InventoryPrivacyOwnerLookupSchema.Type;

const inventoryPrivacyOwnerScopeRefs = inventoryPrivacyOwnerScopeParts.map(
  (scopePart) => `commerce.inventory/privacy-owner-scope/${scopePart}`,
);

const hasExactReferenceSet = (left: readonly string[], right: readonly string[]): boolean => {
  const rightSet = new Set(right);
  return (
    left.length === right.length && rightSet.size === right.length && left.every((reference) => rightSet.has(reference))
  );
};

const privacyLookupTenantId = (lookup: InventoryPrivacyOwnerLookup): null | string =>
  Match.value(lookup).pipe(
    Match.tag('BINDING_HISTORY', ({ bindingRef }) => bindingRef.tenantId),
    Match.tag('CONFIRMATION_HISTORY', ({ confirmationRef }) => confirmationRef.tenantId),
    Match.tag('EXTERNAL_CORRELATION', ({ correlationRef }) => correlationRef.tenantId),
    Match.tag('PROTECTION_HISTORY', ({ protectionRef }) => protectionRef.tenantId),
    Match.tag('EFFECT_OUTCOME', () => null),
    Match.tag('RESERVATION_OBLIGATION', () => null),
    Match.exhaustive,
  );

const InventoryPrivacyOwnerCoverageQuerySchema = Schema.TaggedStruct('PRIVACY_OWNER_COVERAGE', {
  ownerRef: InventoryReservationRefSchema,
  scope: PrivacyOwnerScopeSchema,
  trustedLookups: Schema.Array(InventoryPrivacyOwnerLookupSchema).check(
    Schema.isMaxLength(INVENTORY_RECONCILIATION_EVIDENCE_LIMIT),
  ),
}).check(
  Schema.makeFilter(({ ownerRef, scope, trustedLookups }) => {
    const lookupRefs = trustedLookups.map((lookup: InventoryPrivacyOwnerLookup) => lookup.lookupRef);
    if (scope.ownerCapability !== 'commerce.inventory') {
      return { issue: 'privacy owner capability must be commerce.inventory', path: ['scope', 'ownerCapability'] };
    }
    if (String(scope.tenantId) !== String(ownerRef.tenantId)) {
      return { issue: 'privacy owner scope and owner Resource must share one Tenant', path: ['scope', 'tenantId'] };
    }
    if (!hasExactReferenceSet(scope.requestedScopePartRefs, inventoryPrivacyOwnerScopeRefs)) {
      return {
        issue: 'privacy owner scope must request the exact Inventory owner responsibility set',
        path: ['scope', 'requestedScopePartRefs'],
      };
    }
    if (!hasExactReferenceSet(scope.trustedLookupRefs, lookupRefs)) {
      return {
        issue: 'trusted Inventory lookup references must exactly match the typed owner lookups',
        path: ['trustedLookups'],
      };
    }
    const hasCrossTenantLookup = trustedLookups.some((lookup: InventoryPrivacyOwnerLookup) => {
      const lookupTenantId = privacyLookupTenantId(lookup);
      return lookupTenantId !== null && lookupTenantId !== scope.tenantId;
    });
    return hasCrossTenantLookup
      ? { issue: 'every trusted Inventory lookup must remain in the authorized Tenant', path: ['trustedLookups'] }
      : undefined;
  }),
);

export const InventoryReconciliationEvidenceQuerySchema = Schema.Union([
  Schema.TaggedStruct('BINDING_HISTORY', { bindingRef: CatalogToStockBindingRefSchema }),
  Schema.TaggedStruct('ENDED_CORRELATION', { correlationRef: ExternalStockCorrelationRefSchema }),
  Schema.TaggedStruct('SHARING_HISTORY', { relationRef: StockSharingEligibilityRefSchema }),
  Schema.TaggedStruct('CONFIRMATION_HISTORY', { confirmationRef: ReservationConfirmationRefSchema }),
  Schema.TaggedStruct('PROTECTION_HISTORY', { protectionRef: CommitmentProtectionRefSchema }),
  Schema.TaggedStruct('EFFECT_OUTCOME', {
    effectId: InventoryEffectLedgerEffectIdSchema,
    ownerRef: EffectOwnerRefSchema,
  }),
  Schema.TaggedStruct('SOURCE_CONFLICT_DETAIL', { conflictRef: InventorySourceConflictRefSchema }),
  InventoryPrivacyOwnerCoverageQuerySchema,
]);
export type InventoryReconciliationEvidenceQuery = typeof InventoryReconciliationEvidenceQuerySchema.Type;
export const InventoryReconciliationEvidenceRequestSchema = Schema.Struct({
  query: InventoryReconciliationEvidenceQuerySchema,
});
export type InventoryReconciliationEvidenceRequest = typeof InventoryReconciliationEvidenceRequestSchema.Type;

export const InventoryReconciliationEvidenceResponseSchema = Schema.Union([
  Schema.TaggedStruct('BINDING_HISTORY', {
    bindingRef: CatalogToStockBindingRefSchema,
    entries: BoundedBindingHistorySchema,
  }),
  Schema.TaggedStruct('ENDED_CORRELATION', {
    correlation: ExternalStockCorrelationSchema,
    correlationRef: ExternalStockCorrelationRefSchema,
  }),
  Schema.TaggedStruct('SHARING_HISTORY', {
    entries: BoundedSharingHistorySchema,
    relationRef: StockSharingEligibilityRefSchema,
  }),
  Schema.TaggedStruct('CONFIRMATION_HISTORY', {
    confirmationRef: ReservationConfirmationRefSchema,
    entries: BoundedConfirmationHistorySchema,
  }),
  Schema.TaggedStruct('PROTECTION_HISTORY', {
    entries: BoundedProtectionHistorySchema,
    protectionRef: CommitmentProtectionRefSchema,
  }),
  Schema.TaggedStruct('EFFECT_OUTCOME', {
    ownerRef: EffectOwnerRefSchema,
    record: InventoryEffectLedgerRecordSchema,
  }),
  Schema.TaggedStruct('SOURCE_CONFLICT_DETAIL', {
    conflict: InventorySourceConflictSchema,
    conflictRef: InventorySourceConflictRefSchema,
  }),
  Schema.TaggedStruct('PRIVACY_OWNER_COVERAGE', {
    coverage: Schema.toEncoded(PrivacyOwnerCoverageResultSchema),
    ownerRef: InventoryReservationRefSchema,
  }),
]);
export type InventoryReconciliationEvidenceResponse = typeof InventoryReconciliationEvidenceResponseSchema.Type;

export const InventoryReconciliationEvidenceAuthenticationProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidenceAuthenticationProblem',
  401,
);
export const InventoryReconciliationEvidenceInvalidProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidenceInvalidProblem',
  400,
);
export const InventoryReconciliationEvidenceUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'InventoryReconciliationEvidenceUnavailableProblem',
  503,
);
export const InventoryReconciliationEvidenceForbiddenProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidenceForbiddenProblem',
  403,
);
export const InventoryReconciliationEvidenceNotFoundProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidenceNotFoundProblem',
  404,
);
export const InventoryReconciliationEvidencePolicyProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidencePolicyProblem',
  422,
);
export const InventoryReconciliationEvidencePolicyConflictProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidencePolicyConflictProblem',
  409,
);
export const InventoryReconciliationEvidenceInternalProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidenceInternalProblem',
  500,
);

export const InventoryReconciliationEvidenceApi = HttpApi.make('InventoryReconciliationEvidenceApi').add(
  HttpApiGroup.make('inventoryReconciliationEvidence').add(
    HttpApiEndpoint.post('execute', '/reads/inventory-reconciliation-evidence', {
      error: [
        InventoryReconciliationEvidenceInvalidProblemSchema,
        InventoryReconciliationEvidenceAuthenticationProblemSchema,
        InventoryReconciliationEvidenceForbiddenProblemSchema,
        InventoryReconciliationEvidenceNotFoundProblemSchema,
        InventoryReconciliationEvidencePolicyConflictProblemSchema,
        InventoryReconciliationEvidencePolicyProblemSchema,
        InventoryReconciliationEvidenceDomainPolicyProblemSchema,
        InventoryReconciliationEvidenceDomainUnavailableProblemSchema,
        InventoryReconciliationEvidenceUnavailableProblemSchema,
        InventoryReconciliationEvidenceInternalProblemSchema,
      ],
      payload: InventoryReconciliationEvidenceRequestSchema,
      success: InventoryReconciliationEvidenceResponseSchema,
    }),
  ),
);
