// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';

import { CatalogToStockBindingHistoryEntrySchema } from '../domain/catalog-to-stock-binding.ts';
import { CommitmentProtectionSchema } from '../domain/commitment-protection.ts';
import { ExternalStockCorrelationSchema } from '../domain/external-stock-correlation.ts';
import {
  InventoryEffectLedgerEffectIdSchema,
  InventoryEffectLedgerRecordSchema,
} from '../domain/inventory-effect-ledger.ts';
import { InventorySourceConflictSchema } from '../domain/inventory-source-conflict.ts';
import { ReservationConfirmationSchema } from '../domain/reservation-confirmation.ts';
import { StockSharingEligibilitySchema } from '../domain/stock-sharing-eligibility.ts';
import { CatalogToStockBindingRefSchema } from '../resources/catalog-to-stock-binding.ts';
import { CommitmentProtectionRefSchema } from '../resources/commitment-protection.ts';
import { ExternalStockCorrelationRefSchema } from '../resources/external-stock-correlation.ts';
import { InventoryReservationRefSchema } from '../resources/inventory-reservation.ts';
import { InventorySourceConflictRefSchema } from '../resources/inventory-source-conflict.ts';
import { ReservationConfirmationRefSchema } from '../resources/reservation-confirmation.ts';
import { StockPositionRefSchema } from '../resources/stock-position.ts';
import { StockSharingEligibilityRefSchema } from '../resources/stock-sharing-eligibility.ts';
import { InventoryReconciliationEvidenceDomainPolicyProblemSchema } from './inventory-reconciliation-evidence-domain-policy-problem.ts';
import { InventoryReconciliationEvidenceDomainUnavailableProblemSchema } from './inventory-reconciliation-evidence-domain-unavailable-problem.ts';

export {
  InventoryReconciliationEvidenceDomainPolicyProblem,
  InventoryReconciliationEvidenceDomainPolicyProblemSchema,
} from './inventory-reconciliation-evidence-domain-policy-problem.ts';
export {
  InventoryReconciliationEvidenceDomainUnavailableProblem,
  InventoryReconciliationEvidenceDomainUnavailableProblemSchema,
} from './inventory-reconciliation-evidence-domain-unavailable-problem.ts';

export const INVENTORY_RECONCILIATION_EVIDENCE_LIMIT = 100;

const BoundedBindingHistorySchema = Schema.Array(CatalogToStockBindingHistoryEntrySchema).check(
  Schema.isMaxLength(INVENTORY_RECONCILIATION_EVIDENCE_LIMIT),
);
const BoundedSharingHistorySchema = Schema.Array(StockSharingEligibilitySchema).check(
  Schema.isMaxLength(INVENTORY_RECONCILIATION_EVIDENCE_LIMIT),
);
const BoundedConfirmationHistorySchema = Schema.Array(ReservationConfirmationSchema).check(
  Schema.isMaxLength(INVENTORY_RECONCILIATION_EVIDENCE_LIMIT),
);
const BoundedProtectionHistorySchema = Schema.Array(CommitmentProtectionSchema).check(
  Schema.isMaxLength(INVENTORY_RECONCILIATION_EVIDENCE_LIMIT),
);

const EffectOwnerRefSchema = Schema.Union([InventoryReservationRefSchema, StockPositionRefSchema]);

export const InventoryReconciliationEvidenceQuerySchema = Schema.Union([
  Schema.TaggedStruct('BINDING_HISTORY', { bindingRef: CatalogToStockBindingRefSchema }),
  Schema.TaggedStruct('ENDED_CORRELATION', { correlationRef: ExternalStockCorrelationRefSchema }),
  Schema.TaggedStruct('SHARING_HISTORY', { relationRef: StockSharingEligibilityRefSchema }),
  Schema.TaggedStruct('CONFIRMATION_HISTORY', { confirmationRef: ReservationConfirmationRefSchema }),
  Schema.TaggedStruct('PROTECTION_HISTORY', { protectionRef: CommitmentProtectionRefSchema }),
  Schema.TaggedStruct('EFFECT_OUTCOME', {
    effectId: InventoryEffectLedgerEffectIdSchema,
    ownerRef: EffectOwnerRefSchema,
  }),
  Schema.TaggedStruct('SOURCE_CONFLICT_DETAIL', { conflictRef: InventorySourceConflictRefSchema }),
]);
export type InventoryReconciliationEvidenceQuery = typeof InventoryReconciliationEvidenceQuerySchema.Type;
export const InventoryReconciliationEvidenceRequestSchema = Schema.Struct({
  query: InventoryReconciliationEvidenceQuerySchema,
});
export type InventoryReconciliationEvidenceRequest = typeof InventoryReconciliationEvidenceRequestSchema.Type;

export const InventoryReconciliationEvidenceResponseSchema = Schema.Union([
  Schema.TaggedStruct('BINDING_HISTORY', {
    bindingRef: CatalogToStockBindingRefSchema,
    entries: BoundedBindingHistorySchema,
  }),
  Schema.TaggedStruct('ENDED_CORRELATION', {
    correlation: ExternalStockCorrelationSchema,
    correlationRef: ExternalStockCorrelationRefSchema,
  }),
  Schema.TaggedStruct('SHARING_HISTORY', {
    entries: BoundedSharingHistorySchema,
    relationRef: StockSharingEligibilityRefSchema,
  }),
  Schema.TaggedStruct('CONFIRMATION_HISTORY', {
    confirmationRef: ReservationConfirmationRefSchema,
    entries: BoundedConfirmationHistorySchema,
  }),
  Schema.TaggedStruct('PROTECTION_HISTORY', {
    entries: BoundedProtectionHistorySchema,
    protectionRef: CommitmentProtectionRefSchema,
  }),
  Schema.TaggedStruct('EFFECT_OUTCOME', {
    ownerRef: EffectOwnerRefSchema,
    record: InventoryEffectLedgerRecordSchema,
  }),
  Schema.TaggedStruct('SOURCE_CONFLICT_DETAIL', {
    conflict: InventorySourceConflictSchema,
    conflictRef: InventorySourceConflictRefSchema,
  }),
]);
export type InventoryReconciliationEvidenceResponse = typeof InventoryReconciliationEvidenceResponseSchema.Type;

export const InventoryReconciliationEvidenceAuthenticationProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidenceAuthenticationProblem',
  401,
);
export const InventoryReconciliationEvidenceInvalidProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidenceInvalidProblem',
  400,
);
export const InventoryReconciliationEvidenceUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'InventoryReconciliationEvidenceUnavailableProblem',
  503,
);
export const InventoryReconciliationEvidenceForbiddenProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidenceForbiddenProblem',
  403,
);
export const InventoryReconciliationEvidenceNotFoundProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidenceNotFoundProblem',
  404,
);
export const InventoryReconciliationEvidencePolicyProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidencePolicyProblem',
  422,
);
export const InventoryReconciliationEvidencePolicyConflictProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidencePolicyConflictProblem',
  409,
);
export const InventoryReconciliationEvidenceInternalProblemSchema = makeProblemDetailsSchema(
  'InventoryReconciliationEvidenceInternalProblem',
  500,
);

export const InventoryReconciliationEvidenceApi = HttpApi.make('InventoryReconciliationEvidenceApi').add(
  HttpApiGroup.make('inventoryReconciliationEvidence').add(
    HttpApiEndpoint.post('execute', '/reads/inventory-reconciliation-evidence', {
      error: [
        InventoryReconciliationEvidenceInvalidProblemSchema,
        InventoryReconciliationEvidenceAuthenticationProblemSchema,
        InventoryReconciliationEvidenceForbiddenProblemSchema,
        InventoryReconciliationEvidenceNotFoundProblemSchema,
        InventoryReconciliationEvidencePolicyConflictProblemSchema,
        InventoryReconciliationEvidencePolicyProblemSchema,
        InventoryReconciliationEvidenceDomainPolicyProblemSchema,
        InventoryReconciliationEvidenceDomainUnavailableProblemSchema,
        InventoryReconciliationEvidenceUnavailableProblemSchema,
        InventoryReconciliationEvidenceInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: InventoryReconciliationEvidenceRequestSchema,
      query: {},
      success: InventoryReconciliationEvidenceResponseSchema,
    }),
  ),
);
