// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import {
  ProvisionalInventoryReservationSchema,
  RuntimeCommittedInventoryObligationSchema,
} from '../domain/inventory-obligation.ts';
import { InventoryReservationRefSchema } from '../resources/inventory-reservation.ts';
import { InventoryReservationDetailDomainConflictProblemSchema } from './inventory-reservation-detail-domain-conflict-problem.ts';
import { InventoryReservationDetailDomainPolicyProblemSchema } from './inventory-reservation-detail-domain-policy-problem.ts';
import { InventoryReservationDetailDomainUnavailableProblemSchema } from './inventory-reservation-detail-domain-unavailable-problem.ts';

export {
  InventoryReservationDetailDomainConflictProblem,
  InventoryReservationDetailDomainConflictProblemSchema,
} from './inventory-reservation-detail-domain-conflict-problem.ts';
export {
  InventoryReservationDetailDomainPolicyProblem,
  InventoryReservationDetailDomainPolicyProblemSchema,
} from './inventory-reservation-detail-domain-policy-problem.ts';
export {
  InventoryReservationDetailDomainUnavailableProblem,
  InventoryReservationDetailDomainUnavailableProblemSchema,
} from './inventory-reservation-detail-domain-unavailable-problem.ts';

export const RuntimeInventoryReservationSchema = Schema.Union([
  ProvisionalInventoryReservationSchema,
  RuntimeCommittedInventoryObligationSchema,
]);

export const InventoryReservationDetailRequestSchema = Schema.Struct({
  reservationRef: InventoryReservationRefSchema,
});
export type InventoryReservationDetailRequest = typeof InventoryReservationDetailRequestSchema.Type;
export const InventoryReservationDetailResponseSchema = Schema.Struct({
  reservation: RuntimeInventoryReservationSchema,
});
export type InventoryReservationDetailResponse = typeof InventoryReservationDetailResponseSchema.Type;

export const InventoryReservationDetailAuthenticationProblemSchema = makeProblemDetailsSchema(
  'InventoryReservationDetailAuthenticationProblem',
  401,
);
export const InventoryReservationDetailInvalidProblemSchema = makeProblemDetailsSchema(
  'InventoryReservationDetailInvalidProblem',
  400,
);
export const InventoryReservationDetailUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'InventoryReservationDetailUnavailableProblem',
  503,
);
export const InventoryReservationDetailForbiddenProblemSchema = makeProblemDetailsSchema(
  'InventoryReservationDetailForbiddenProblem',
  403,
);
export const InventoryReservationDetailNotFoundProblemSchema = makeProblemDetailsSchema(
  'InventoryReservationDetailNotFoundProblem',
  404,
);
export const InventoryReservationDetailPolicyProblemSchema = makeProblemDetailsSchema(
  'InventoryReservationDetailPolicyProblem',
  422,
);
export const InventoryReservationDetailPolicyConflictProblemSchema = makeProblemDetailsSchema(
  'InventoryReservationDetailPolicyConflictProblem',
  409,
);
export const InventoryReservationDetailInternalProblemSchema = makeProblemDetailsSchema(
  'InventoryReservationDetailInternalProblem',
  500,
);

export const InventoryReservationDetailApi = HttpApi.make('InventoryReservationDetailApi').add(
  HttpApiGroup.make('inventoryReservationDetail').add(
    HttpApiEndpoint.post('execute', '/reads/inventory-reservation-detail', {
      error: [
        InventoryReservationDetailInvalidProblemSchema,
        InventoryReservationDetailAuthenticationProblemSchema,
        InventoryReservationDetailForbiddenProblemSchema,
        InventoryReservationDetailNotFoundProblemSchema,
        InventoryReservationDetailPolicyConflictProblemSchema,
        InventoryReservationDetailPolicyProblemSchema,
        InventoryReservationDetailDomainConflictProblemSchema,
        InventoryReservationDetailDomainPolicyProblemSchema,
        InventoryReservationDetailDomainUnavailableProblemSchema,
        InventoryReservationDetailUnavailableProblemSchema,
        InventoryReservationDetailInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: InventoryReservationDetailRequestSchema,
      query: {},
      success: InventoryReservationDetailResponseSchema,
    }),
  ),
);
