// @generated by OntOS Codesmith module-api v1
import { makeProblemDetailsSchema, makeRetryableProblemDetailsSchema } from '@app/shared-contracts/problem-details';
import { Match, Schema } from 'effect';
import { HttpApi, HttpApiEndpoint, HttpApiGroup } from 'effect/unstable/httpapi';
import {
  InventoryEffectLedgerEffectIdSchema,
  InventoryEffectLedgerIntentSchema,
  InventoryEffectLedgerResolutionSchema,
} from '../domain/inventory-effect-ledger.ts';
import { InventoryEffectOutcomeDomainConflictProblemSchema } from './inventory-effect-outcome-domain-conflict-problem.ts';
import { InventoryEffectOutcomeDomainUnavailableProblemSchema } from './inventory-effect-outcome-domain-unavailable-problem.ts';

export { InventoryEffectOutcomeDomainConflictProblem } from './inventory-effect-outcome-domain-conflict-problem.ts';
export { InventoryEffectOutcomeDomainUnavailableProblem } from './inventory-effect-outcome-domain-unavailable-problem.ts';

export const InventoryEffectOutcomeRequestSchema = Schema.Struct({
  effectId: InventoryEffectLedgerEffectIdSchema,
  intent: InventoryEffectLedgerIntentSchema,
}).check(
  Schema.makeFilter(({ effectId, intent }) =>
    String(effectId) === String(intent.request.effectId)
      ? undefined
      : 'Inventory Effect lookup must retain the original effect identity from its exact intent',
  ),
);
export type InventoryEffectOutcomeRequest = typeof InventoryEffectOutcomeRequestSchema.Type;
const effectOutcomeIdentity = {
  effectId: InventoryEffectLedgerEffectIdSchema,
  intent: InventoryEffectLedgerIntentSchema,
} as const;
export const InventoryEffectOutcomeResponseSchema = Schema.Union([
  Schema.TaggedStruct('UNRESOLVED', {
    ...effectOutcomeIdentity,
    currentState: Schema.Literal('REQUESTED'),
    nextStep: Schema.Literal('RECOVER_ORIGINAL_EFFECT'),
  }),
  Schema.TaggedStruct('INDETERMINATE', {
    ...effectOutcomeIdentity,
    currentState: Schema.Literal('INDETERMINATE'),
    nextStep: Schema.Literal('RECOVER_ORIGINAL_EFFECT'),
    // oxlint-disable-next-line effect-native/no-nullable-schema-field -- The public outcome preserves the ledger's explicit null until owner recovery proves a resolution; expires: 2027-03-31.
    resolution: Schema.NullOr(InventoryEffectLedgerResolutionSchema),
  }),
  Schema.TaggedStruct('RESOLVED', {
    ...effectOutcomeIdentity,
    currentState: Schema.Literals(['SUCCEEDED', 'REJECTED']),
    nextStep: Schema.Literals(['CONTINUE', 'STOP']),
    resolution: InventoryEffectLedgerResolutionSchema,
  }),
]).check(
  Schema.makeFilter((result) =>
    Match.value(result).pipe(
      Match.tag('INDETERMINATE', () => true),
      Match.tag('UNRESOLVED', () => true),
      Match.tag('RESOLVED', ({ currentState, nextStep }) =>
        (currentState === 'SUCCEEDED' && nextStep === 'CONTINUE') ||
        (currentState === 'REJECTED' && nextStep === 'STOP')
          ? undefined
          : 'Resolved Inventory Effect outcome must preserve the terminal state safe next step',
      ),
      Match.exhaustive,
    ),
  ),
);
export type InventoryEffectOutcomeResponse = typeof InventoryEffectOutcomeResponseSchema.Type;

export const InventoryEffectOutcomeAuthenticationProblemSchema = makeProblemDetailsSchema(
  'InventoryEffectOutcomeAuthenticationProblem',
  401,
);
export const InventoryEffectOutcomeInvalidProblemSchema = makeProblemDetailsSchema(
  'InventoryEffectOutcomeInvalidProblem',
  400,
);
export const InventoryEffectOutcomeUnavailableProblemSchema = makeRetryableProblemDetailsSchema(
  'InventoryEffectOutcomeUnavailableProblem',
  503,
);
export const InventoryEffectOutcomeForbiddenProblemSchema = makeProblemDetailsSchema(
  'InventoryEffectOutcomeForbiddenProblem',
  403,
);
export const InventoryEffectOutcomeNotFoundProblemSchema = makeProblemDetailsSchema(
  'InventoryEffectOutcomeNotFoundProblem',
  404,
);
export const InventoryEffectOutcomePolicyProblemSchema = makeProblemDetailsSchema(
  'InventoryEffectOutcomePolicyProblem',
  422,
);
export const InventoryEffectOutcomePolicyConflictProblemSchema = makeProblemDetailsSchema(
  'InventoryEffectOutcomePolicyConflictProblem',
  409,
);
export const InventoryEffectOutcomeInternalProblemSchema = makeProblemDetailsSchema(
  'InventoryEffectOutcomeInternalProblem',
  500,
);

export const InventoryEffectOutcomeApi = HttpApi.make('InventoryEffectOutcomeApi').add(
  HttpApiGroup.make('inventoryEffectOutcome').add(
    HttpApiEndpoint.post('execute', '/reads/inventory-effect-outcome', {
      error: [
        InventoryEffectOutcomeInvalidProblemSchema,
        InventoryEffectOutcomeAuthenticationProblemSchema,
        InventoryEffectOutcomeForbiddenProblemSchema,
        InventoryEffectOutcomeNotFoundProblemSchema,
        InventoryEffectOutcomePolicyConflictProblemSchema,
        InventoryEffectOutcomePolicyProblemSchema,
        InventoryEffectOutcomeDomainConflictProblemSchema,
        InventoryEffectOutcomeDomainUnavailableProblemSchema,
        InventoryEffectOutcomeUnavailableProblemSchema,
        InventoryEffectOutcomeInternalProblemSchema,
      ],
      headers: {},
      params: {},
      payload: InventoryEffectOutcomeRequestSchema,
      query: {},
      success: InventoryEffectOutcomeResponseSchema,
    }),
  ),
);
