export const COMMERCE_CUSTOMER_CONTEXT_API_PREFIX = '/commerce-customer-context-api';
export const COMMERCE_PORTAL_AUTH_INTERNAL_BASE_PATH = '/api/portal-auth';
export const COMMERCE_PORTAL_AUTH_PUBLIC_BASE_PATH = `${COMMERCE_CUSTOMER_CONTEXT_API_PREFIX}${COMMERCE_PORTAL_AUTH_INTERNAL_BASE_PATH}`;
