// @generated by OntOS Codesmith Governed Contribution v1
// @ontos-contribution-kind search-provider
import { Redacted } from 'effect';
import type { CounterpartiesProviderRequest } from '../../shared/apis/counterparties-search.ts';
import { operationGateway } from './action-gateway.ts';
import {
  authenticatePartyRegistryHttpRequest,
  invokePartyRegistryHttpClient,
  partyRegistryHttpRequestContext,
} from './party-registry-http-client.ts';
import type {
  PartyRegistryAuthorizedInvocation,
  PartyRegistryOperationInvocation,
} from './party-registry-http-client.ts';

export interface CounterpartiesSearchClientOptions {
  readonly baseUrl?: string | URL;
}

export const loadCounterpartiesClientWithAuthorization = (
  payload: CounterpartiesProviderRequest,
  ...[
    credential,
    requestCorrelation,
    options = {},
  ]: PartyRegistryAuthorizedInvocation<CounterpartiesSearchClientOptions>
) =>
  invokePartyRegistryHttpClient(
    authenticatePartyRegistryHttpRequest(
      partyRegistryHttpRequestContext(options),
      Redacted.make(credential),
      requestCorrelation,
    ),
    (client) => client.counterpartiesSearch.execute({ payload }),
  );

export const loadCounterpartiesClient = (
  payload: CounterpartiesProviderRequest,
  ...[
    requestCorrelation,
    options = {},
  ]: PartyRegistryOperationInvocation<CounterpartiesSearchClientOptions>
) =>
  operationGateway.invoke((credential) =>
    loadCounterpartiesClientWithAuthorization(payload, credential, requestCorrelation, options),
  );
