// @generated by OntOS Codesmith module-api v1
import { makeEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';
import { DuplicateCandidateDetailApi } from '../../shared/apis/duplicate-candidate-detail.ts';
import type { DuplicateCandidateDetailRequest } from '../../shared/apis/duplicate-candidate-detail.ts';
import { operationGateway } from './action-gateway.ts';

export interface DuplicateCandidateDetailClientOptions {
  readonly baseUrl?: string | URL;
}

type DuplicateCandidateDetailAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: DuplicateCandidateDetailClientOptions,
];

type DuplicateCandidateDetailOperationInvocation = readonly [
  requestCorrelation: string,
  options?: DuplicateCandidateDetailClientOptions,
];

const duplicateCandidateDetailClient = (
  credential: Redacted.Redacted<string>,
  requestCorrelation: string,
  options: DuplicateCandidateDetailClientOptions,
) => {
  const clientConfig = {
    api: DuplicateCandidateDetailApi,
    defaultApiPrefix: '/party-registry-api',
    transportHeaders: {
      authorization: Redacted.value(credential),
      'x-correlation-id': requestCorrelation,
    },
  };
  return makeEffectBffClient(
    options.baseUrl === undefined ? clientConfig : { ...clientConfig, baseUrl: options.baseUrl },
  );
};

export const executeDuplicateCandidateDetailWithAuthorization = (
  payload: DuplicateCandidateDetailRequest,
  ...[credential, requestCorrelation, options = {}]: DuplicateCandidateDetailAuthorizedInvocation
) =>
  duplicateCandidateDetailClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) =>
      client.duplicateCandidateDetail.execute({ headers: {}, params: {}, payload, query: {} }),
    ),
  );

export const executeDuplicateCandidateDetail = (
  payload: DuplicateCandidateDetailRequest,
  ...[requestCorrelation, options = {}]: DuplicateCandidateDetailOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executeDuplicateCandidateDetailWithAuthorization(
      payload,
      credential,
      requestCorrelation,
      options,
    ),
  );
