// @generated by OntOS Codesmith module-api v1
import { Effect } from 'effect';
import { HttpClient, HttpClientRequest } from 'effect/unstable/http';
import { makeEffectHttpApiClient } from '@modern-js/plugin-bff/effect-client';
import { PartyOfficialIdentifierDetailApi } from '../../shared/apis/party-official-identifier-detail.ts';
import type { PartyOfficialIdentifierDetailRequest } from '../../shared/apis/party-official-identifier-detail.ts';
import { operationGateway } from './action-gateway.ts';

export interface PartyOfficialIdentifierDetailClientOptions {
  readonly baseUrl?: string | URL;
}

export const executePartyOfficialIdentifierDetailWithAuthorization = (
  payload: PartyOfficialIdentifierDetailRequest,
  authorization: string,
  correlationId: string,
  options: PartyOfficialIdentifierDetailClientOptions = {},
) =>
  makeEffectHttpApiClient(PartyOfficialIdentifierDetailApi, {
    baseUrl: options.baseUrl ?? '/party-registry-api',
    transformClient: HttpClient.mapRequest(
      HttpClientRequest.setHeaders({ authorization, 'x-correlation-id': correlationId }),
    ),
  }).pipe(
    Effect.flatMap((client) =>
      client.partyOfficialIdentifierDetail.execute({ headers: {}, params: {}, payload, query: {} }),
    ),
  );

export const executePartyOfficialIdentifierDetail = (
  payload: PartyOfficialIdentifierDetailRequest,
  correlationId: string,
  options: PartyOfficialIdentifierDetailClientOptions = {},
) =>
  operationGateway.invoke((authorization) =>
    executePartyOfficialIdentifierDetailWithAuthorization(
      payload,
      authorization,
      correlationId,
      options,
    ),
  );
