// @generated by OntOS Codesmith module-api v1
import { Effect, Redacted } from 'effect';
import { HttpClient, HttpClientRequest } from 'effect/unstable/http';
import { makeEffectHttpApiClient } from '@modern-js/plugin-bff/effect-client';
import { PartyDetailApi } from '../../shared/apis/party-detail.ts';
import type { PartyDetailRequest } from '../../shared/apis/party-detail.ts';
import { operationGateway } from './action-gateway.ts';

export interface PartyDetailClientOptions {
  readonly baseUrl?: string | URL;
}

export const executePartyDetailWithAuthorization = (
  payload: PartyDetailRequest,
  authorization: Redacted.Redacted<string>,
  correlationId: string,
  options: PartyDetailClientOptions = {},
) =>
  makeEffectHttpApiClient(PartyDetailApi, {
    baseUrl: options.baseUrl ?? '/party-registry-api',
    transformClient: HttpClient.mapRequest(
      HttpClientRequest.setHeaders({
        authorization: Redacted.value(authorization),
        'x-correlation-id': correlationId,
      }),
    ),
  }).pipe(
    Effect.flatMap((client) =>
      client.partyDetail.execute({ headers: {}, params: {}, payload, query: {} }),
    ),
  );

export const executePartyDetail = (
  payload: PartyDetailRequest,
  correlationId: string,
  options: PartyDetailClientOptions = {},
) =>
  operationGateway.invoke((authorization) =>
    executePartyDetailWithAuthorization(payload, authorization, correlationId, options),
  );
