// @generated by OntOS Codesmith module-api v1
import { makeGovernedEffectBffClient } from '@app/shared-contracts/client-runtime';
import { Effect, Redacted } from 'effect';

import { PartyMatchDecisionApi } from '../../shared/apis/party-match-decision.ts';
import type { PartyMatchDecisionRequest } from '../../shared/apis/party-match-decision.ts';
import { operationGateway } from './action-gateway.ts';

export interface PartyMatchDecisionClientOptions {
  readonly baseUrl?: string | URL;
}

type PartyMatchDecisionAuthorizedInvocation = readonly [
  credential: string,
  requestCorrelation: string,
  options?: PartyMatchDecisionClientOptions,
];

type PartyMatchDecisionOperationInvocation = readonly [
  requestCorrelation: string,
  options?: PartyMatchDecisionClientOptions,
];

const partyMatchDecisionClient = (
  credential: Redacted.Redacted,
  requestCorrelation: string,
  options: PartyMatchDecisionClientOptions,
) =>
  makeGovernedEffectBffClient(
    {
      api: PartyMatchDecisionApi,
      credential,
      defaultApiPrefix: '/party-registry-api',
      requestCorrelation,
    },
    options,
  );

export const executePartyMatchDecisionWithAuthorization = (
  payload: PartyMatchDecisionRequest,
  ...[credential, requestCorrelation, options = {}]: PartyMatchDecisionAuthorizedInvocation
) =>
  partyMatchDecisionClient(Redacted.make(credential), requestCorrelation, options).pipe(
    Effect.flatMap((client) =>
      client.partyMatchDecision.execute({
        headers: {},
        params: {},
        payload,
        query: {},
      }),
    ),
  );

export const executePartyMatchDecision = (
  payload: PartyMatchDecisionRequest,
  ...[requestCorrelation, options = {}]: PartyMatchDecisionOperationInvocation
) =>
  operationGateway.invoke((credential) =>
    executePartyMatchDecisionWithAuthorization(payload, credential, requestCorrelation, options),
  );
