// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.assortment
// @ontos-action-http-slug create-rule-revision
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  CreateRuleRevisionActionAlreadyCommittedProblemSchema,
  CreateRuleRevisionActionAuthenticationProblemSchema,
  CreateRuleRevisionActionCommitIndeterminateProblemSchema,
  CreateRuleRevisionActionConflictProblemSchema,
  CreateRuleRevisionActionForbiddenProblemSchema,
  CreateRuleRevisionActionIneligibleProblemSchema,
  CreateRuleRevisionActionInternalProblemSchema,
  CreateRuleRevisionActionInvalidProblemSchema,
  CreateRuleRevisionActionNotFoundProblemSchema,
  CreateRuleRevisionActionPreconditionProblemSchema,
  CreateRuleRevisionActionSchemaErrorMiddleware,
  CreateRuleRevisionActionUnavailableProblemSchema,
} from '../shared/apis/create-rule-revision-action.ts';
import type { CreateRuleRevisionActionProblem } from '../shared/apis/create-rule-revision-action.ts';
import { createRuleRevisionAction } from '../src/actions/create-rule-revision.action.ts';

type DomainError = typeof createRuleRevisionAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends CreateRuleRevisionActionProblem['_tag']> = Extract<
  CreateRuleRevisionActionProblem,
  { readonly _tag: Tag }
>;

const problemStatus = {
  authentication: 401,
  conflict: 409,
  forbidden: 403,
  ineligible: 422,
  internal: 500,
  invalid: 400,
  notFound: 404,
  precondition: 428,
  rateLimited: 429,
  timeout: 504,
  unavailable: 503,
} as const;

export const createRuleRevisionActionProblem = {
  authentication: (): ProblemOf<'CreateRuleRevisionActionAuthenticationProblem'> =>
    CreateRuleRevisionActionAuthenticationProblemSchema.make({
      detail: 'A valid audience-scoped Bearer assertion is required.',
      status: problemStatus.authentication,
      title: 'Authentication required',
      type: 'https://ontos.dev/problems/operation-authentication-required',
    }),
  conflict: (
    code: ProblemOf<'CreateRuleRevisionActionConflictProblem'>['code'],
  ): ProblemOf<'CreateRuleRevisionActionConflictProblem'> =>
    CreateRuleRevisionActionConflictProblemSchema.make({
      code,
      detail: 'The Action conflicts with current state.',
      status: problemStatus.conflict,
      title: 'Action conflict',
      type: 'https://ontos.dev/problems/action-conflict',
    }),
  forbidden: (
    code: ProblemOf<'CreateRuleRevisionActionForbiddenProblem'>['code'],
  ): ProblemOf<'CreateRuleRevisionActionForbiddenProblem'> =>
    CreateRuleRevisionActionForbiddenProblemSchema.make({
      code,
      detail: 'The principal is not permitted to perform this Action.',
      status: problemStatus.forbidden,
      title: 'Action forbidden',
      type: 'https://ontos.dev/problems/action-forbidden',
    }),
  ineligible: (
    code: ProblemOf<'CreateRuleRevisionActionIneligibleProblem'>['code'],
  ): ProblemOf<'CreateRuleRevisionActionIneligibleProblem'> =>
    CreateRuleRevisionActionIneligibleProblemSchema.make({
      code,
      detail: 'The request is not eligible for this Action.',
      status: problemStatus.ineligible,
      title: 'Action ineligible',
      type: 'https://ontos.dev/problems/action-ineligible',
    }),
  internal: (): ProblemOf<'CreateRuleRevisionActionInternalProblem'> =>
    CreateRuleRevisionActionInternalProblemSchema.make({
      detail: 'The Action could not be completed.',
      status: problemStatus.internal,
      title: 'Action failed',
      type: 'https://ontos.dev/problems/action-failed',
    }),
  invalid: (): ProblemOf<'CreateRuleRevisionActionInvalidProblem'> =>
    CreateRuleRevisionActionInvalidProblemSchema.make({
      detail: 'The create-rule-revision Action request is invalid.',
      status: problemStatus.invalid,
      title: 'Invalid Action request',
      type: 'https://ontos.dev/problems/action-invalid',
    }),
  notFound: (
    code: ProblemOf<'CreateRuleRevisionActionNotFoundProblem'>['code'],
  ): ProblemOf<'CreateRuleRevisionActionNotFoundProblem'> =>
    CreateRuleRevisionActionNotFoundProblemSchema.make({
      code,
      detail: 'The requested resource was not found.',
      status: problemStatus.notFound,
      title: 'Resource not found',
      type: 'https://ontos.dev/problems/action-resource-not-found',
    }),
  precondition: (): ProblemOf<'CreateRuleRevisionActionPreconditionProblem'> =>
    CreateRuleRevisionActionPreconditionProblemSchema.make({
      detail: 'An Idempotency-Key header is required.',
      status: problemStatus.precondition,
      title: 'Idempotency key required',
      type: 'https://ontos.dev/problems/idempotency-key-required',
    }),
  unavailable: (
    code: ProblemOf<'CreateRuleRevisionActionUnavailableProblem'>['code'],
  ): ProblemOf<'CreateRuleRevisionActionUnavailableProblem'> =>
    CreateRuleRevisionActionUnavailableProblemSchema.make({
      code,
      detail: 'The Action capability is temporarily unavailable.',
      retryable: true,
      status: problemStatus.unavailable,
      title: 'Action unavailable',
      type: 'https://ontos.dev/problems/action-unavailable',
    }),
} as const;

const mapDomainProblem = (error: DomainError): CreateRuleRevisionActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      AssortmentPolicyConflict: () => createRuleRevisionActionProblem.conflict('assortment_policy_conflict'),
      AssortmentPolicyNotFound: () => createRuleRevisionActionProblem.notFound('assortment_policy_not_found'),
      AssortmentPolicyPersistenceUnavailable: () =>
        createRuleRevisionActionProblem.unavailable('assortment_policy_persistence_unavailable'),
      AssortmentPolicyStaleBasis: () => createRuleRevisionActionProblem.conflict('assortment_policy_stale_basis'),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): CreateRuleRevisionActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        CreateRuleRevisionActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: createRuleRevisionActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        CreateRuleRevisionActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: createRuleRevisionActionProblem.internal,
      ActionIdempotencyKeyRequired: createRuleRevisionActionProblem.precondition,
      ActionInvocationNotFound: (failure) => createRuleRevisionActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) => createRuleRevisionActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => createRuleRevisionActionProblem.conflict(failure.code),
      ActionPayloadValidationError: createRuleRevisionActionProblem.invalid,
      ActionPermissionCheckError: (failure) => createRuleRevisionActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => createRuleRevisionActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => createRuleRevisionActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => createRuleRevisionActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => createRuleRevisionActionProblem.conflict(failure.code),
      ActionResultValidationError: createRuleRevisionActionProblem.internal,
      ActionTransactionError: (failure) => createRuleRevisionActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: createRuleRevisionActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) => createRuleRevisionActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => createRuleRevisionActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: createRuleRevisionActionProblem.authentication,
      OperationContextDenied: (failure) => createRuleRevisionActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => createRuleRevisionActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => createRuleRevisionActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(createRuleRevisionAction.descriptor.domainErrorSchema);
export const mapCreateRuleRevisionActionProblem = (
  error: ActionCoreError | DomainError,
): CreateRuleRevisionActionProblem => (isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error));

export const createRuleRevisionActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  CreateRuleRevisionActionSchemaErrorMiddleware,
  () => Effect.fail(createRuleRevisionActionProblem.invalid()),
);
