// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.assortment
// @ontos-action-http-slug retire-rule
import { Effect, HttpApiBuilder, Layer } from '@modern-js/bff-effect/effect-edge';
import type { HttpServerRequest } from 'effect/unstable/http';
import { Redacted, Schema } from 'effect';
import { assortmentApi } from '../shared/api.ts';
import { retireRuleAction } from '../src/actions/retire-rule.action.ts';
import { bindActionHttpRunner } from './action-http-runner.ts';
import {
  retireRuleActionProblem,
  retireRuleActionSchemaErrorLive,
  mapRetireRuleActionProblem,
} from './retire-rule-action-problems.ts';

const runActionHttp = bindActionHttpRunner({
  authentication: retireRuleActionProblem.authentication,
  unavailable: () => retireRuleActionProblem.unavailable('operation_context_unavailable'),
});

const execute = Effect.fn('RetireRuleActionServer.execute')(function* executeRetireRule(
  payload: typeof retireRuleAction.descriptor.payloadSchema.Encoded,
  idempotencyKey: string | undefined,
  request: HttpServerRequest.HttpServerRequest,
) {
  const correlationId = request.headers['x-correlation-id'];
  if (correlationId !== undefined && correlationId.length > 200) {
    return yield* Effect.fail(retireRuleActionProblem.invalid());
  }
  const decoded = yield* Schema.decodeEffect(retireRuleAction.descriptor.payloadSchema)(payload).pipe(
    Effect.mapError(retireRuleActionProblem.invalid),
  );
  return yield* runActionHttp({
    endpointHeaders: { idempotencyKey, traceId: request.headers['x-trace-id'] },
    internalProblem: retireRuleActionProblem.internal,
    invalidCorrelationProblem: retireRuleActionProblem.invalid,
    mapError: mapRetireRuleActionProblem,
    payload: decoded,
    registration: retireRuleAction,
    requestHeaders: {
      authorization: Redacted.make(request.headers['authorization']),
      'x-correlation-id': correlationId,
    },
  });
});

export const retireRuleActionApiLive = HttpApiBuilder.group(assortmentApi, 'retireRuleAction', (handlers) =>
  handlers.handle('execute', ({ headers, payload, request }) => execute(payload, headers['idempotency-key'], request)),
).pipe(Layer.provide(retireRuleActionSchemaErrorLive));
