// @generated by OntOS Codesmith Module Contract v1
// @ontos-deployment-app-id commerce-fx
// @ontos-module-id commerce.fx
import { defineVerticalRuntimeRegistration } from '@app/core-runtime';
import { commerceFxManifest } from './vertical.manifest.ts';
// <generated-module-registration-imports>
import { changeManualCommercialRatePolicyAction } from './src/actions/change-manual-commercial-rate-policy.action.ts';
// </generated-module-registration-imports>

export const commerceFxRegistration = defineVerticalRuntimeRegistration({
  actions: [
    // <generated-module-registration-actions>
    changeManualCommercialRatePolicyAction,
    // </generated-module-registration-actions>
  ],
  entrypoints: {
    api: {
      // <generated-module-registration-apis>
      'commercial-fx-conversion': () => import('./src/api/commercial-fx-conversion-client.ts'),
      // </generated-module-registration-apis>
    },
    components: {
      // <generated-module-registration-components>
      // </generated-module-registration-components>
    },
    pages: {
      // <generated-module-registration-pages>
      // </generated-module-registration-pages>
    },
    reports: {
      // <generated-module-registration-reports>
      // </generated-module-registration-reports>
    },
    search: {
      // <generated-module-registration-search>
      // </generated-module-registration-search>
    },
  },
  manifest: commerceFxManifest,
  outboxWorkers: [
    // <generated-module-registration-workers>
    // </generated-module-registration-workers>
  ],
});

// <generated-public-component-registrations>
// </generated-public-component-registrations>
// <generated-search-registrations>
// </generated-search-registrations>
// <generated-report-registrations>
// </generated-report-registrations>
