// @generated by OntOS Codesmith Governed Contribution v1
// @ontos-contribution-kind search-provider
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/plugin-bff/effect-edge';

import { partyRegistryApi } from '../shared/api.ts';
import {
  PartiesProviderAuthenticationProblemSchema,
  PartiesProviderForbiddenProblemSchema,
  PartiesProviderInternalProblemSchema,
  PartiesProviderInvalidProblemSchema,
  PartiesProviderNotFoundProblemSchema,
  PartiesProviderPolicyConflictProblemSchema,
  PartiesProviderPolicyProblemSchema,
  PartiesProviderUnavailableProblemSchema,
} from '../shared/apis/parties-search.ts';
import { partiesRead } from '../src/search/parties.provider.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: PartiesProviderAuthenticationProblemSchema,
  forbidden: PartiesProviderForbiddenProblemSchema,
  internal: PartiesProviderInternalProblemSchema,
  invalid: PartiesProviderInvalidProblemSchema,
  notFound: PartiesProviderNotFoundProblemSchema,
  policyConflict: PartiesProviderPolicyConflictProblemSchema,
  policyIneligible: PartiesProviderPolicyProblemSchema,
  unavailable: PartiesProviderUnavailableProblemSchema,
});

export const partiesReadApiLive = HttpApiBuilder.group(partyRegistryApi, 'partiesSearch', (handlers) =>
  handlers.handle(
    'execute',
    makeGovernedReadHttpHandler({
      authenticatePrincipal: authenticateOperationPrincipal,
      problems,
      registration: partiesRead,
    }),
  ),
);
