#!/usr/bin/env node
import { NodeRuntime, NodeServices } from '@effect/platform-node';
import {
  LanguageVariant,
  SyntaxKind,
  createScanner,
} from '@typescript/native/unstable/ast';
import {
  Config,
  Console,
  Effect,
  FileSystem,
  Function as EffectFunction,
  Layer,
  Match,
  Option,
  Path,
  Schema,
} from 'effect';
import type { PlatformError } from 'effect/PlatformError';
import { ChildProcess, ChildProcessSpawner } from 'effect/unstable/process';

import {
  gatewayContextAuthorizationEntrypoints,
  shellGatewayContextContract,
} from '../packages/shared-contracts/src/gateway-context.ts';
import {
  PROTECTED_ENTRYPOINT_INVENTORY_SCHEMA_VERSION,
  hashProtectedEntrypointInventory,
  normalizeProtectedEntrypointInventory,
  serializeProtectedEntrypointInventory,
} from './authorization/protected-entrypoint-inventory.mts';
import type {
  InventoryAuthorization,
  ProtectedEntrypointInventoryEntry,
} from './authorization/protected-entrypoint-inventory.mts';
import { topLevelSeparators } from './boundary-source-structure.mts';
import {
  hasCompleteGeneratedModuleApiSeam,
  hasGeneratedGovernedServerContract,
} from './generated-governed-http-boundary.mts';
import {
  toPascalCase,
  generatedApiGroup,
  generatedProviderIdentities,
  hasExactGeneratedProviderIdentityTopology,
  hasGeneratedGovernedClientContract,
  hasEngagementLifecycleRegistrationContract,
  hasGeneratedOperationGatewayContract,
  hasMatchingGeneratedProviderAuthorization,
  hasGeneratedProviderApiContract,
  hasGeneratedProviderManifest,
  hasGeneratedProviderReadContract,
  hasGeneratedProviderRegistration,
  hasGeneratedSourceHeader,
} from './generated-module-api-boundary.mts';
import { maskNonCode } from './scaffolding/shared.mts';

const SOURCE_EXTENSIONS = new Set([
  '.js',
  '.jsx',
  '.mjs',
  '.mts',
  '.ts',
  '.tsx',
]);
const ACTION_EXTENSION = '.action.ts';
const ACTION_HEADER = '// @generated by OntOS Codesmith Action v1';
const WORKER_HEADER = '// @generated by OntOS Codesmith Outbox Worker v1';
const APPROVED_REMOTE_LOADER =
  'apps/shell-super-app/src/routes/module-entrypoint-loader.ts';
const SourceRevisionSchema = Schema.String.check(
  Schema.isPattern(/^[a-zA-Z0-9._-]{1,100}$/u)
);

const sortStrings = (values: readonly string[]): readonly string[] => {
  const sorted: string[] = [];
  for (const value of values) {
    let insertionIndex = 0;
    while (
      insertionIndex < sorted.length &&
      (sorted[insertionIndex]?.localeCompare(value) ?? 0) <= 0
    ) {
      insertionIndex += 1;
    }
    sorted.splice(insertionIndex, 0, value);
  }
  return sorted;
};

const isGeneratedInfrastructureReadinessApi = (
  file: string,
  source: string
): boolean => {
  const stem = /(?<stem>[^/]+)\/[^/]+\/[^/]+$/u.exec(file)?.groups?.stem;
  if (stem === undefined) {
    return false;
  }
  const endpoints = [
    ...source.matchAll(
      /HttpApiEndpoint\.(?<method>get|post)\(\s*'(?<name>[^']+)'\s*,\s*'(?<path>[^']+)'/gu
    ),
  ].map((match) => {
    const { groups } = match;
    return `${groups?.method}:${groups?.name}:${groups?.path}`;
  });
  return (
    endpoints.length === 1 &&
    endpoints[0] === `get:readiness:/${stem}/readiness` &&
    source.includes(`export const ${stem}ApiContract = {`)
  );
};

const SKIPPED_DIRECTORIES = new Set(['.output', 'node_modules']);

const walk = (
  directory: string
): Effect.Effect<
  readonly string[],
  PlatformError,
  FileSystem.FileSystem | Path.Path
> =>
  Effect.gen(function* walkEffect() {
    const fileSystem = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    if (!(yield* fileSystem.exists(directory))) {
      return [];
    }
    const entries = yield* fileSystem.readDirectory(directory);
    const discovered: (readonly string[])[] = [];
    for (const entry of entries) {
      if (SKIPPED_DIRECTORIES.has(entry) || entry.startsWith('dist')) {
        discovered.push([]);
      } else {
        const entryPath = path.join(directory, entry);
        const info = yield* fileSystem.stat(entryPath);
        discovered.push(
          info.type === 'Directory' ? yield* walk(entryPath) : [entryPath]
        );
      }
    }
    return sortStrings(discovered.flat());
  });

const relative = (path: Path.Path, root: string, file: string): string =>
  path.relative(root, file).replaceAll('\\', '/');

class ModuleEntrypointBoundaryError extends Schema.TaggedError<ModuleEntrypointBoundaryError>()(
  'ModuleEntrypointBoundaryError',
  { message: Schema.String }
) {}

const fail = (file: string, message: string) =>
  Effect.fail(
    new ModuleEntrypointBoundaryError({ message: `${file}: ${message}` })
  );

const requireDefined = <Value,>(
  value: Value | undefined,
  file: string,
  message: string
): Effect.Effect<Value, ModuleEntrypointBoundaryError> =>
  value === undefined ? fail(file, message) : Effect.succeed(value);

interface ParsedEntrypoint {
  readonly access?: string;
  readonly authorization?: InventoryAuthorization;
  readonly entrypointKey?: string;
  readonly moduleKey?: string;
  readonly role?: string;
  readonly scope: 'System' | 'Tenant';
}

interface SourceToken {
  readonly kind: SyntaxKind;
  readonly value: string;
}

interface ObjectProperties {
  readonly closeBraceIndex: number;
  readonly values: ReadonlyMap<string, string>;
}

const tokenKindAt = (
  tokens: readonly SourceToken[],
  index: number
): SyntaxKind | undefined => tokens[index]?.kind;

const isPropertyValue = (
  tokens: readonly SourceToken[],
  index: number,
  valueKind: SyntaxKind
): boolean =>
  tokenKindAt(tokens, index) === SyntaxKind.Identifier &&
  tokenKindAt(tokens, index + 1) === SyntaxKind.ColonToken &&
  tokenKindAt(tokens, index + 2) === valueKind;

const readObjectStringProperties = (
  tokens: readonly SourceToken[],
  openBraceIndex: number
): ObjectProperties => {
  const values = new Map<string, string>();
  let depth = 0;
  for (let cursor = openBraceIndex; cursor < tokens.length; cursor += 1) {
    const current = tokens[cursor];
    if (current === undefined) {
      continue;
    }
    if (current.kind === SyntaxKind.OpenBraceToken) {
      depth += 1;
    } else if (current.kind === SyntaxKind.CloseBraceToken) {
      depth -= 1;
      if (depth === 0) {
        return { closeBraceIndex: cursor, values };
      }
    } else if (
      depth === 1 &&
      isPropertyValue(tokens, cursor, SyntaxKind.StringLiteral)
    ) {
      values.set(current.value, tokens[cursor + 2]?.value ?? '');
    }
  }
  return { closeBraceIndex: tokens.length, values };
};

const readContextPermission = (
  properties: ReadonlyMap<string, string>
): InventoryAuthorization | undefined => {
  const permission = properties.get('permission');
  return properties.size === 2 && permission !== undefined
    ? { kind: 'context_permission', permission }
    : undefined;
};

const readActionExecution = (
  properties: ReadonlyMap<string, string>
): InventoryAuthorization | undefined => {
  const provisioning = properties.get('provisioning');
  return properties.size === 2 &&
    (provisioning === 'explicit' ||
      provisioning === 'tenant_membership_default')
    ? { kind: 'action_execution', provisioning }
    : undefined;
};

const readCapabilityIssuance = (
  properties: ReadonlyMap<string, string>
): InventoryAuthorization | undefined => {
  const credential = properties.get('credential');
  return properties.size === 2 &&
    (credential === 'api_key' || credential === 'session')
    ? { credential, kind: 'capability_issuance' }
    : undefined;
};

const readAuthorization = (
  tokens: readonly SourceToken[],
  openBraceIndex: number
): InventoryAuthorization | undefined => {
  const properties = readObjectStringProperties(tokens, openBraceIndex).values;
  return Match.value(properties.get('kind')).pipe(
    Match.when('public', (kind) =>
      properties.size === 1 ? { kind } : undefined
    ),
    Match.when('authenticated_principal', (kind) =>
      properties.size === 1 ? { kind } : undefined
    ),
    Match.when('owner_local_background', (kind) =>
      properties.size === 1 ? { kind } : undefined
    ),
    Match.when('context_permission', () => readContextPermission(properties)),
    Match.when('action_execution', () => readActionExecution(properties)),
    Match.when('capability_issuance', () => readCapabilityIssuance(properties)),
    Match.orElse(EffectFunction.constUndefined)
  );
};

const rescanTemplateClose = (
  scanner: ReturnType<typeof createScanner>,
  depths: number[]
): SyntaxKind => {
  const index = depths.length - 1;
  const depth = depths[index] ?? 0;
  if (depth !== 0) {
    depths[index] = depth - 1;
    return SyntaxKind.CloseBraceToken;
  }
  const kind = scanner.reScanTemplateToken(false);
  if (kind === SyntaxKind.TemplateTail) {
    depths.pop();
  }
  return kind;
};

const updateTemplateToken = (
  scanner: ReturnType<typeof createScanner>,
  kind: SyntaxKind,
  depths: number[]
): SyntaxKind => {
  if (kind === SyntaxKind.TemplateHead) {
    depths.push(0);
  } else if (depths.length > 0) {
    const index = depths.length - 1;
    if (kind === SyntaxKind.OpenBraceToken) {
      depths[index] = (depths[index] ?? 0) + 1;
    } else if (kind === SyntaxKind.CloseBraceToken) {
      return rescanTemplateClose(scanner, depths);
    }
  }
  return kind;
};

const tokenize = (source: string): readonly SourceToken[] => {
  const scanner = createScanner(true, LanguageVariant.Standard, source);
  const tokens: SourceToken[] = [];
  const templateExpressionBraceDepths: number[] = [];
  let scannedKind = scanner.scan();
  while (scannedKind !== SyntaxKind.EndOfFile) {
    const kind = updateTemplateToken(
      scanner,
      scannedKind,
      templateExpressionBraceDepths
    );
    tokens.push({ kind, value: scanner.getTokenValue() });
    scannedKind = scanner.scan();
  }
  return tokens;
};

const entrypointScope = (
  token: SourceToken
): ParsedEntrypoint['scope'] | undefined => {
  if (token.kind !== SyntaxKind.Identifier) {
    return undefined;
  }
  return Match.value(token.value).pipe(
    Match.when('defineSystemModuleEntrypoint', () => 'System' as const),
    Match.when('defineTenantModuleEntrypoint', () => 'Tenant' as const),
    Match.orElse(EffectFunction.constUndefined)
  );
};

const readEntrypointAuthorization = (
  tokens: readonly SourceToken[],
  start: number,
  end: number
): InventoryAuthorization | undefined => {
  let authorization: InventoryAuthorization | undefined;
  for (let cursor = start; cursor < end; cursor += 1) {
    if (
      tokens[cursor]?.value === 'authorization' &&
      isPropertyValue(tokens, cursor, SyntaxKind.OpenBraceToken)
    ) {
      authorization = readAuthorization(tokens, cursor + 2);
    }
  }
  return authorization;
};

const readEntrypoints = (source: string): readonly ParsedEntrypoint[] => {
  const tokens = tokenize(source);
  const entrypoints: ParsedEntrypoint[] = [];
  for (const [index, token] of tokens.entries()) {
    const scope = entrypointScope(token);
    if (
      scope !== undefined &&
      tokenKindAt(tokens, index + 1) === SyntaxKind.OpenParenToken &&
      tokenKindAt(tokens, index + 2) === SyntaxKind.OpenBraceToken
    ) {
      const properties = readObjectStringProperties(tokens, index + 2);
      entrypoints.push({
        access: properties.values.get('access'),
        authorization: readEntrypointAuthorization(
          tokens,
          index + 3,
          properties.closeBraceIndex
        ),
        entrypointKey: properties.values.get('entrypointKey'),
        moduleKey: properties.values.get('moduleKey'),
        role: properties.values.get('role'),
        scope,
      });
    }
  }
  return entrypoints;
};

const readStringProperties = (
  source: string,
  propertyName: string
): ReadonlySet<string> => {
  const tokens = tokenize(source);
  const values = new Set<string>();
  for (const [index, token] of tokens.entries()) {
    if (
      token.kind === SyntaxKind.Identifier &&
      token.value === propertyName &&
      tokens[index + 1]?.kind === SyntaxKind.ColonToken &&
      tokens[index + 2]?.kind === SyntaxKind.StringLiteral
    ) {
      const value = tokens[index + 2]?.value;
      if (value !== undefined) {
        values.add(value);
      }
    }
  }
  return values;
};

const callsIdentifier = (source: string, identifier: string): boolean => {
  const tokens = tokenize(source);
  return tokens.some(
    (token, index) =>
      token.kind === SyntaxKind.Identifier &&
      token.value === identifier &&
      tokens[index + 1]?.kind === SyntaxKind.OpenParenToken
  );
};

const containsIdentifier = (
  source: string,
  identifiers: ReadonlySet<string>
): boolean =>
  tokenize(source).some(
    (token) =>
      token.kind === SyntaxKind.Identifier && identifiers.has(token.value)
  );

const isModuleSpecifierPosition = (
  tokens: readonly SourceToken[],
  index: number
): boolean => {
  const previous = tokenKindAt(tokens, index - 1);
  return (
    previous === SyntaxKind.FromKeyword ||
    previous === SyntaxKind.ImportKeyword ||
    (previous === SyntaxKind.OpenParenToken &&
      tokenKindAt(tokens, index - 2) === SyntaxKind.ImportKeyword)
  );
};

const readImportedModuleSpecifiers = (source: string): readonly string[] => {
  const tokens = tokenize(source);
  const specifiers: string[] = [];
  for (const [index, token] of tokens.entries()) {
    if (token.kind !== SyntaxKind.StringLiteral) {
      continue;
    }
    if (isModuleSpecifierPosition(tokens, index)) {
      specifiers.push(token.value);
    }
  }
  return specifiers;
};

const authorizationEquals = (
  left: InventoryAuthorization | undefined,
  right: InventoryAuthorization
): boolean => {
  if (left?.kind !== right.kind) {
    return false;
  }
  if (right.kind === 'action_execution') {
    return left.kind === right.kind && left.provisioning === right.provisioning;
  }
  if (right.kind === 'capability_issuance') {
    return left.kind === right.kind && left.credential === right.credential;
  }
  if (right.kind === 'context_permission') {
    return left.kind === right.kind && left.permission === right.permission;
  }
  return true;
};

const sourceOrEmpty = (
  sourceMap: ReadonlyMap<string, string>,
  file: string
): string => sourceMap.get(file) ?? '';

const readActionEntrypoints = (
  sourceMap: ReadonlyMap<string, string>,
  file: string,
  source: string
): readonly ParsedEntrypoint[] => {
  const inline = readEntrypoints(source);
  const action =
    /^verticals\/party-registry\/src\/actions\/(?<action>(?:archive|unarchive)-(?:organization|person)-engagement)\.action\.ts$/u.exec(
      file
    )?.groups?.action;
  if (
    action === undefined &&
    !containsIdentifier(source, new Set(['engagementLifecycleRegistration']))
  ) {
    return inline;
  }
  if (
    action === undefined ||
    inline.length !== 0 ||
    !hasEngagementLifecycleRegistrationContract(
      source,
      sourceOrEmpty(
        sourceMap,
        'verticals/party-registry/src/actions/engagement-lifecycle-registration.ts'
      ),
      action
    )
  ) {
    return [];
  }
  return [
    {
      access: 'write',
      authorization: {
        kind: 'action_execution',
        provisioning: 'tenant_membership_default',
      },
      entrypointKey: `party.registry.${action}`,
      moduleKey: 'party.registry',
      role: 'action',
      scope: 'Tenant',
    },
  ];
};

const requireExactEntrypoint = (
  file: string,
  source: string,
  expected: Required<ParsedEntrypoint>,
  remediation: string,
  entrypoints = readEntrypoints(source)
): Effect.Effect<ParsedEntrypoint, ModuleEntrypointBoundaryError> =>
  Effect.gen(function* requireExactEntrypointEffect() {
    const entrypoint = yield* requireDefined(entrypoints[0], file, remediation);
    if (
      entrypoints.length !== 1 ||
      entrypoint.scope !== expected.scope ||
      !authorizationEquals(entrypoint.authorization, expected.authorization) ||
      entrypoint.access !== expected.access ||
      entrypoint.entrypointKey !== expected.entrypointKey ||
      entrypoint.moduleKey !== expected.moduleKey ||
      entrypoint.role !== expected.role
    ) {
      yield* fail(file, remediation);
    }
    return entrypoint;
  });

const requireGeneratedActionEntrypoint = (
  sourceMap: ReadonlyMap<string, string>,
  file: string,
  source: string
) =>
  Effect.gen(function* requireGeneratedActionEntrypointEffect() {
    if (!hasGeneratedSourceHeader(source, `${ACTION_HEADER}\n`)) {
      yield* fail(
        file,
        'Actions must be created and maintained with scaffold:action'
      );
    }
    const owner = /^\/\/ @ontos-action-owner (?<owner>.+)$/mu.exec(source)
      ?.groups?.owner;
    const action = /^\/\/ @ontos-action-slug (?<action>.+)$/mu.exec(source)
      ?.groups?.action;
    const descriptorMessage =
      'regenerate this Action with scaffold:action so it has its governed action/write entrypoint';
    const definedOwner = yield* requireDefined(owner, file, descriptorMessage);
    const definedAction = yield* requireDefined(
      action,
      file,
      descriptorMessage
    );
    const entrypoints = readActionEntrypoints(sourceMap, file, source);
    const rawAuthorization = entrypoints[0]?.authorization;
    const authorization = yield* rawAuthorization?.kind === 'action_execution'
      ? Effect.succeed(rawAuthorization)
      : fail(
          file,
          'regenerate this Action with scaffold:action so it declares action_execution authorization and provisioning intent'
        );
    yield* requireExactEntrypoint(
      file,
      source,
      {
        access: 'write',
        authorization,
        entrypointKey: `${definedOwner}.${definedAction}`,
        moduleKey: definedOwner,
        role: 'action',
        scope: definedOwner.startsWith('core.') ? 'System' : 'Tenant',
      },
      descriptorMessage,
      entrypoints
    );
  });

const requireGeneratedWorkerEntrypoint = (file: string, source: string) =>
  Effect.gen(function* requireGeneratedWorkerEntrypointEffect() {
    if (!hasGeneratedSourceHeader(source, `${WORKER_HEADER}\n`)) {
      yield* fail(
        file,
        'Outbox Workers must be created and maintained with scaffold:outbox-worker'
      );
    }
    const owner = /^\/\/ @ontos-outbox-worker-owner (?<owner>.+)$/mu.exec(
      source
    )?.groups?.owner;
    const workerKey = /^\/\/ @ontos-outbox-worker-key (?<workerKey>.+)$/mu.exec(
      source
    )?.groups?.workerKey;
    const descriptorMessage =
      'regenerate this Worker with scaffold:outbox-worker so it has its governed worker/background entrypoint';
    const definedOwner = yield* requireDefined(owner, file, descriptorMessage);
    const definedWorkerKey = yield* requireDefined(
      workerKey,
      file,
      descriptorMessage
    );
    yield* requireExactEntrypoint(
      file,
      source,
      {
        access: 'background',
        authorization: { kind: 'owner_local_background' },
        entrypointKey: definedWorkerKey,
        moduleKey: definedOwner,
        role: 'worker',
        scope: 'Tenant',
      },
      descriptorMessage
    );
  });

const requireRouteEntrypoint = (
  file: string,
  source: string,
  moduleOwner: string,
  expectedScope: 'system' | 'tenant'
): Effect.Effect<string, ModuleEntrypointBoundaryError> =>
  Effect.gen(function* requireRouteEntrypointEffect() {
    const entrypoints = readEntrypoints(source);
    const remediation =
      'regenerate this route with scaffold:microvertical-page and load it through the Shell module-entrypoint gateway';
    const entrypoint = yield* requireDefined(entrypoints[0], file, remediation);
    const requiredScope = expectedScope === 'system' ? 'System' : 'Tenant';
    if (
      entrypoints.length !== 1 ||
      entrypoint.scope !== requiredScope ||
      entrypoint.role !== 'page' ||
      entrypoint.moduleKey !== moduleOwner ||
      entrypoint.authorization === undefined ||
      entrypoint.entrypointKey?.startsWith(`${moduleOwner}.page.`) !== true ||
      (entrypoint.access !== 'read' && entrypoint.access !== 'historical_read')
    ) {
      yield* fail(file, remediation);
    }
    return yield* requireDefined(entrypoint.entrypointKey, file, remediation);
  });

const TopologyMetadataSchema = Schema.Struct({
  topology: Schema.optionalKey(
    Schema.Struct({
      apps: Schema.optionalKey(
        Schema.Array(Schema.Struct({ id: Schema.String, path: Schema.String }))
      ),
    })
  ),
});
const decodeTopologyMetadata = Schema.decodeUnknownEffect(
  Schema.fromJsonString(TopologyMetadataSchema)
);

const VerticalPackageJsonSchema = Schema.Struct({
  exports: Schema.optionalKey(Schema.Record(Schema.String, Schema.String)),
});
const decodeVerticalPackageJson = Schema.decodeUnknownEffect(
  Schema.fromJsonString(VerticalPackageJsonSchema)
);

const readTopologyOwners = (root: string) =>
  Effect.gen(function* readTopologyOwnersEffect() {
    const fileSystem = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const metadata = yield* fileSystem
      .readFileString(path.join(root, '.modernjs/ultramodern.json'), 'utf-8')
      .pipe(Effect.flatMap(decodeTopologyMetadata));
    return new Map(
      (metadata.topology?.apps ?? []).map((app) => [
        app.path.replaceAll('\\', '/'),
        app.id,
      ])
    );
  });

const readSourceRevision = (root: string) =>
  Effect.gen(function* readSourceRevisionEffect() {
    const configured = yield* Config.option(
      Config.string('ULTRAMODERN_SOURCE_REVISION')
    );
    if (Option.isSome(configured)) {
      return configured.value;
    }
    const spawner = yield* ChildProcessSpawner.ChildProcessSpawner;
    return yield* spawner
      .string(ChildProcess.make('git', ['rev-parse', 'HEAD'], { cwd: root }))
      .pipe(
        Effect.map((revision) => {
          const trimmed = revision.trim();
          return trimmed.length === 0 ? 'working-tree' : trimmed;
        }),
        Effect.catch(() => Effect.succeed('working-tree'))
      );
  });

interface RouteEntrypointRecord {
  readonly deployment: string;
  readonly entrypointKey: string;
  readonly file: string;
}

interface BoundaryCheckState {
  readonly inventoryEntries: ProtectedEntrypointInventoryEntry[];
  readonly owners: ReadonlyMap<string, string>;
  readonly routeEntrypoints: RouteEntrypointRecord[];
  readonly sourceMap: ReadonlyMap<string, string>;
}

const governedSourceHeader = (
  category: string | undefined
): string | undefined => {
  if (category === 'components') {
    return '// @generated by OntOS Codesmith public-component v1\n';
  }
  if (category === 'reports') {
    return '// @generated by OntOS Codesmith Governed Contribution v1\n// @ontos-contribution-kind report\n';
  }
  if (category === 'search') {
    return '// @generated by OntOS Codesmith Governed Contribution v1\n// @ontos-contribution-kind search-provider\n';
  }
  return undefined;
};

const inventorySurface = (
  role: string
): ProtectedEntrypointInventoryEntry['surface'] => {
  if (role === 'action') {
    return 'action';
  }
  return role === 'worker' ? 'worker' : 'route';
};

const validateRouteSource = (
  state: BoundaryCheckState,
  file: string,
  source: string
) =>
  Effect.gen(function* validateRouteSourceEffect() {
    if (!file.endsWith('/route.meta.ts')) {
      return;
    }
    const ownerEntry = [...state.owners.entries()].find(([appPath]) =>
      file.startsWith(`${appPath}/`)
    );
    const [, owner] = yield* requireDefined(
      ownerEntry,
      file,
      'route owner is absent from the generated topology'
    );
    const ownerAppIds = readStringProperties(source, 'ownerAppId');
    if (ownerAppIds.size !== 1 || !ownerAppIds.has(owner)) {
      yield* fail(
        file,
        'route ownerAppId must match the generated topology deployment identity'
      );
    }
    const expectedScope = owner.startsWith('shell-') ? 'system' : 'tenant';
    const moduleIds = readStringProperties(source, 'moduleId');
    const moduleOwner = expectedScope === 'tenant' ? [...moduleIds][0] : owner;
    if (
      moduleOwner === undefined ||
      (expectedScope === 'tenant' && moduleIds.size !== 1)
    ) {
      yield* fail(
        file,
        'MicroVertical route metadata must declare exactly one manifest moduleId'
      );
    }
    state.routeEntrypoints.push({
      deployment: owner,
      entrypointKey: yield* requireRouteEntrypoint(
        file,
        source,
        moduleOwner,
        expectedScope
      ),
      file,
    });
  });

const validateGovernedSource = (file: string, source: string) =>
  Effect.gen(function* validateGovernedSourceEffect() {
    const category = /\/src\/(?<category>components|search|reports)\//u.exec(
      `/${file}`
    )?.groups?.category;
    const expectedHeader = governedSourceHeader(category);
    const invalidGovernedSource =
      /\/src\/public-components\//u.test(`/${file}`) ||
      (expectedHeader !== undefined &&
        !hasGeneratedSourceHeader(source, expectedHeader));
    if (invalidGovernedSource) {
      yield* fail(
        file,
        'public components, search, and reports require an approved Codesmith generator and reserved runtime registration first'
      );
    }
  });

const SEARCH_PROVIDER_KIND = 'search-provider';

interface GeneratedProviderLocation {
  readonly kind: 'report' | 'search';
  readonly name: string;
  readonly vertical: string;
}

const generatedProviderLocation = (
  file: string,
  source: string
): GeneratedProviderLocation | undefined => {
  if (
    !['report', SEARCH_PROVIDER_KIND].some((kind) =>
      hasGeneratedSourceHeader(
        source,
        `// @generated by OntOS Codesmith Governed Contribution v1\n// @ontos-contribution-kind ${kind}\n`
      )
    )
  ) {
    return undefined;
  }
  const locations = [
    /^(?<vertical>verticals\/[^/]+)\/src\/api\/(?<name>[^/]+)-(?<kind>search|report)-client\.ts$/u,
    /^(?<vertical>verticals\/[^/]+)\/shared\/apis\/(?<name>[^/]+)-(?<kind>search|report)\.ts$/u,
    /^(?<vertical>verticals\/[^/]+)\/src\/(?<kind>search|reports)\/(?<name>[^/]+)\.provider\.ts$/u,
    /^(?<vertical>verticals\/[^/]+)\/api\/(?<name>[^/]+)-(?<kind>search|report)-server\.ts$/u,
  ];
  for (const pattern of locations) {
    const provider = pattern.exec(file)?.groups;
    if (provider?.name !== undefined && provider.vertical !== undefined) {
      return {
        kind: provider.kind === 'search' ? 'search' : 'report',
        name: provider.name,
        vertical: provider.vertical,
      };
    }
  }
  return undefined;
};

const providerModuleId = (manifest: string): string =>
  /@ontos-module-id (?<moduleId>[a-z0-9]+(?:\.[a-z0-9]+)*)/u.exec(manifest)
    ?.groups?.moduleId ?? '';

const validateGeneratedProviderClient = (
  sourceMap: ReadonlyMap<string, string>,
  file: string,
  deploymentAppId: string,
  discoveredProvider?: GeneratedProviderLocation
) =>
  Effect.gen(function* validateGeneratedProviderClientEffect() {
    const provider =
      discoveredProvider ??
      generatedProviderLocation(file, sourceOrEmpty(sourceMap, file));
    if (provider === undefined) {
      return;
    }
    const { kind, name, vertical } = provider;
    const kindDetails =
      kind === 'search'
        ? {
            apiSuffix: 'Search',
            contributionKind: 'search-provider',
            directory: 'search',
            endpointGroup: 'search',
          }
        : {
            apiSuffix: 'Report',
            contributionKind: 'report',
            directory: 'reports',
            endpointGroup: 'reports',
          };
    const generatedHeader = `// @generated by OntOS Codesmith Governed Contribution v1\n// @ontos-contribution-kind ${kindDetails.contributionKind}\n`;
    const contractPath = `${vertical}/shared/apis/${name}-${kind}.ts`;
    const contractSource = sourceOrEmpty(sourceMap, contractPath);
    const clientPath = `${vertical}/src/api/${name}-${kind}-client.ts`;
    const clientSource = sourceOrEmpty(sourceMap, clientPath);
    const providerPath = `${vertical}/src/${kindDetails.directory}/${name}.provider.ts`;
    const providerSource = sourceOrEmpty(sourceMap, providerPath);
    const serverPath = `${vertical}/api/${name}-${kind}-server.ts`;
    const serverSource = sourceOrEmpty(sourceMap, serverPath);
    const manifest = sourceOrEmpty(
      sourceMap,
      `${vertical}/vertical.manifest.ts`
    );
    const registration = sourceOrEmpty(
      sourceMap,
      `${vertical}/vertical.registration.ts`
    );
    const gateway = sourceOrEmpty(
      sourceMap,
      `${vertical}/src/api/action-gateway.ts`
    );
    const moduleId = providerModuleId(manifest);
    const type = toPascalCase(name);
    const camel = `${type.slice(0, 1).toLowerCase()}${type.slice(1)}`;
    const ownerApiValue = `${type}${kindDetails.apiSuffix}Api`;
    const endpointGroup =
      generatedApiGroup(contractSource, ownerApiValue) ?? '';
    const expectedGroups = new Set([
      kindDetails.endpointGroup,
      `${camel}${kindDetails.apiSuffix}`,
    ]);
    const providerChecks = {
      apiContract: hasGeneratedProviderApiContract(
        contractSource,
        ownerApiValue,
        moduleId,
        name,
        kind
      ),
      authorization: hasMatchingGeneratedProviderAuthorization(
        providerSource,
        manifest,
        moduleId,
        name,
        kind
      ),
      clientContract: hasGeneratedGovernedClientContract(clientSource, {
        authorizedOperation: `load${type}ClientWithAuthorization`,
        defaultApiPrefix: `/${deploymentAppId}-api`,
        endpointGroup,
        generatedHeader,
        invocationKind: 'provider',
        ownerApiValue,
        ownerContractImport: `../../shared/apis/${name}-${kind}.ts`,
        publicOperation: `load${type}Client`,
      }),
      clientHeader: hasGeneratedSourceHeader(clientSource, generatedHeader),
      contractHeader: hasGeneratedSourceHeader(contractSource, generatedHeader),
      endpointGroup: expectedGroups.has(endpointGroup),
      manifest: hasGeneratedProviderManifest(manifest, moduleId, name, kind),
      operationGateway: hasGeneratedOperationGatewayContract(
        gateway,
        deploymentAppId
      ),
      providerHeader: hasGeneratedSourceHeader(providerSource, generatedHeader),
      readContract: hasGeneratedProviderReadContract(
        providerSource,
        moduleId,
        name,
        kind
      ),
      registration: hasGeneratedProviderRegistration(registration, name, kind),
      serverContract: hasGeneratedGovernedServerContract(
        serverSource,
        `${camel}ReadApiLive`,
        sourceOrEmpty(sourceMap, `${vertical}/shared/api.ts`)
      ),
      serverHeader: hasGeneratedSourceHeader(serverSource, generatedHeader),
    };
    const failedChecks = Object.entries(providerChecks)
      .filter(([, valid]) => !valid)
      .map(([checkName]) => checkName);
    if (failedChecks.length > 0) {
      yield* fail(
        file,
        `generated search and report clients require the shared client runtime, owner-local contract, operation gateway, authorization, and correlation metadata (failed: ${failedChecks.join(', ')})`
      );
    }
  });

const validatePublishedProviderIdentities = (
  state: BoundaryCheckState,
  file: string,
  verticalPath: string | undefined
) =>
  Effect.gen(function* validatePublishedProviderIdentitiesEffect() {
    if (
      verticalPath === undefined ||
      (file !== `${verticalPath}/vertical.manifest.ts` &&
        file !== `${verticalPath}/vertical.registration.ts`)
    ) {
      return;
    }
    const manifest = sourceOrEmpty(
      state.sourceMap,
      `${verticalPath}/vertical.manifest.ts`
    );
    const registration = sourceOrEmpty(
      state.sourceMap,
      `${verticalPath}/vertical.registration.ts`
    );
    const moduleId = providerModuleId(manifest);
    const deploymentAppId =
      state.owners.get(verticalPath) ?? file.split('/')[1] ?? '';
    if (
      !hasExactGeneratedProviderIdentityTopology(
        manifest,
        registration,
        moduleId
      )
    ) {
      yield* fail(
        file,
        'generated search and report clients require the shared client runtime and exact manifest and registration identity topology'
      );
    }
    for (const provider of generatedProviderIdentities(
      manifest,
      registration,
      moduleId
    )) {
      yield* validateGeneratedProviderClient(
        state.sourceMap,
        file,
        deploymentAppId,
        {
          ...provider,
          vertical: verticalPath,
        }
      );
    }
  });

const validateVerticalApiSource = (
  state: BoundaryCheckState,
  file: string,
  source: string
) =>
  Effect.gen(function* validateVerticalApiSourceEffect() {
    const { sourceMap } = state;
    const diagnostics: string[] = [];
    if (
      file.endsWith('/shared/api.ts') &&
      source.includes('HttpApiEndpoint') &&
      !isGeneratedInfrastructureReadinessApi(file, source) &&
      !hasCompleteGeneratedModuleApiSeam(
        sourceMap,
        file,
        state.owners.get(file.slice(0, -'/shared/api.ts'.length)),
        diagnostics
      )
    ) {
      yield* fail(
        file,
        `module APIs require an approved Codesmith generator, structured api registration, trusted context, and server ModuleEntrypointGateway integration first (failed: ${diagnostics.join('; ')})`
      );
    }
    if (
      /\/shared\/apis\/[^/]+\.ts$/u.test(`/${file}`) &&
      !hasGeneratedSourceHeader(
        source,
        '// @generated by OntOS Codesmith module-api v1\n'
      ) &&
      !['report', SEARCH_PROVIDER_KIND].some((kind) =>
        hasGeneratedSourceHeader(
          source,
          `// @generated by OntOS Codesmith Governed Contribution v1\n// @ontos-contribution-kind ${kind}\n`
        )
      )
    ) {
      yield* fail(file, 'module APIs must be created with scaffold:module-api');
    }
  });

const validateVerticalSource = (
  state: BoundaryCheckState,
  file: string,
  source: string,
  importedModuleSpecifiers: readonly string[]
) =>
  Effect.gen(function* validateVerticalSourceEffect() {
    const { sourceMap } = state;
    if (!file.includes('/verticals/') && !file.startsWith('verticals/')) {
      return;
    }
    const verticalPath = /^verticals\/[^/]+/u.exec(file)?.[0];
    yield* validatePublishedProviderIdentities(state, file, verticalPath);
    yield* validateGeneratedProviderClient(
      sourceMap,
      file,
      (verticalPath === undefined
        ? undefined
        : state.owners.get(verticalPath)) ??
        file.split('/')[1] ??
        ''
    );
    yield* validateVerticalApiSource(state, file, source);
    yield* validateGovernedSource(file, source);
    const privateImport = importedModuleSpecifiers.some((specifier) =>
      /(?:verticals\/|@app\/).*\/(?:src|vertical\.registration|workers|search|reports|db)(?:\/|$)/u.test(
        specifier
      )
    );
    if (privateImport) {
      yield* fail(
        file,
        'cross-vertical private imports are forbidden; use a public descriptor/client and the Shell/Core gateway'
      );
    }
  });

const validatePrivateHandlerAccess = (file: string, source: string) =>
  Effect.gen(function* validatePrivateHandlerAccessEffect() {
    const unauthorizedActionHandler =
      callsIdentifier(source, 'getActionHandler') &&
      file !== 'packages/core-runtime/src/actions/runtime.ts' &&
      file !== 'packages/core-runtime/src/actions/definition.ts';
    const unauthorizedWorkerHandler =
      callsIdentifier(source, 'getOutboxWorkerHandler') &&
      file !== 'packages/core-runtime/src/outbox/runtime.ts' &&
      file !== 'packages/core-runtime/src/outbox/definition.ts';
    if (unauthorizedActionHandler || unauthorizedWorkerHandler) {
      yield* fail(
        file,
        'private handler accessors may only be called by their Core runtime after the module-state gate'
      );
    }
  });

const validatePackageExports = (file: string, source: string) =>
  Effect.gen(function* validatePackageExportsEffect() {
    if (file.startsWith('verticals/') && file.endsWith('package.json')) {
      const packageJson = yield* decodeVerticalPackageJson(source);
      const privateExport = Object.values(packageJson.exports ?? {}).some(
        (target) =>
          /(?:vertical\.registration|\/src\/(?:handlers|workers|routes|search|reports|db))/u.test(
            target
          )
      );
      if (privateExport) {
        yield* fail(
          file,
          'package exports must not publish private entrypoint implementations or registrations'
        );
      }
    }
  });

const validateRegistrationSlots = (file: string, source: string) =>
  Effect.gen(function* validateRegistrationSlotsEffect() {
    if (file.endsWith('/vertical.registration.ts')) {
      for (const marker of [
        'generated-public-component-registrations',
        'generated-search-registrations',
        'generated-report-registrations',
      ]) {
        if (
          !source.includes(`<${marker}>`) ||
          !source.includes(`</${marker}>`)
        ) {
          yield* fail(
            file,
            `Vertical Runtime Registration is missing reserved ${marker} slots; extend Codesmith first`
          );
        }
      }
    }
  });

const validateCoreExports = (file: string, source: string) =>
  Effect.gen(function* validateCoreExportsEffect() {
    if (file === 'packages/core-runtime/src/index.ts') {
      const forbiddenGateExports = new Set([
        'checkModuleEntrypoint',
        'makeModuleEntrypointGateway',
        'makeModuleStateGate',
        'makeModuleStateSnapshot',
        'prepareModuleStateSnapshot',
      ]);
      if (containsIdentifier(source, forbiddenGateExports)) {
        yield* fail(
          file,
          'Core may export only module-entrypoint descriptors, service/gateway contracts and live layers, and typed gate failures'
        );
      }
    }
  });

const validateGeneralSource = (
  file: string,
  source: string,
  importedModuleSpecifiers: readonly string[]
) =>
  Effect.gen(function* validateGeneralSourceEffect() {
    if (
      callsIdentifier(source, 'loadRemote') &&
      file !== APPROVED_REMOTE_LOADER
    ) {
      yield* fail(
        file,
        'raw loadRemote(...) is forbidden outside the approved Shell module-entrypoint loader'
      );
    }
    if (
      importedModuleSpecifiers.some((specifier) =>
        /\/(?:remote|exposes)\//u.test(specifier)
      )
    ) {
      yield* fail(
        file,
        'eager remote implementation imports are forbidden; pass a lazy thunk to the gateway'
      );
    }
    yield* validatePrivateHandlerAccess(file, source);
    yield* validatePackageExports(file, source);
    yield* validateRegistrationSlots(file, source);
    yield* validateCoreExports(file, source);
  });

const isInventoryDescriptorSource = (file: string): boolean =>
  file.endsWith(ACTION_EXTENSION) ||
  (file.endsWith('.worker.ts') && file.includes('/src/workers/')) ||
  file.endsWith('/route.meta.ts') ||
  (file.endsWith('.read.ts') && file.includes('/src/api/')) ||
  file === 'apps/shell-super-app/api/modules/shell-governed-reads.ts' ||
  file === 'packages/core-runtime/src/auth/principal-administration-reads.ts';

const appendInventoryEntries = (
  state: BoundaryCheckState,
  file: string,
  source: string
) =>
  Effect.gen(function* appendInventoryEntriesEffect() {
    if (!isInventoryDescriptorSource(file)) {
      return;
    }
    const deployment =
      [...state.owners.entries()].find(([appPath]) =>
        file.startsWith(`${appPath}/`)
      )?.[1] ?? 'shell-super-app';
    const entrypoints = file.endsWith(ACTION_EXTENSION)
      ? readActionEntrypoints(state.sourceMap, file, source)
      : readEntrypoints(source);
    for (const entrypoint of entrypoints) {
      const descriptorMessage =
        'every runtime entrypoint must declare exactly one valid authorization';
      const authorization = yield* requireDefined(
        entrypoint.authorization,
        file,
        descriptorMessage
      );
      const entrypointKey = yield* requireDefined(
        entrypoint.entrypointKey,
        file,
        descriptorMessage
      );
      const owner = yield* requireDefined(
        entrypoint.moduleKey,
        file,
        descriptorMessage
      );
      const role = yield* requireDefined(
        entrypoint.role,
        file,
        descriptorMessage
      );
      state.inventoryEntries.push({
        authorization,
        deployment,
        entrypointKey,
        owner,
        surface: inventorySurface(role),
      });
    }
  });

const validateProductionSource = (
  state: BoundaryCheckState,
  file: string,
  source: string
) =>
  Effect.gen(function* validateProductionSourceEffect() {
    if (file.endsWith(ACTION_EXTENSION)) {
      yield* requireGeneratedActionEntrypoint(state.sourceMap, file, source);
    }
    if (file.endsWith('.worker.ts') && file.includes('/src/workers/')) {
      yield* requireGeneratedWorkerEntrypoint(file, source);
    }
    yield* validateRouteSource(state, file, source);
    const importedModuleSpecifiers = readImportedModuleSpecifiers(source);
    yield* validateVerticalSource(
      state,
      file,
      source,
      importedModuleSpecifiers
    );
    yield* validateGeneralSource(file, source, importedModuleSpecifiers);
    yield* appendInventoryEntries(state, file, source);
  });

const collectRouteSourceKeys = (state: BoundaryCheckState) =>
  Effect.gen(function* collectRouteSourceKeysEffect() {
    const routeSourceKeysByDeployment = new Map<string, Set<string>>();
    for (const route of state.routeEntrypoints) {
      const sourceKeys =
        routeSourceKeysByDeployment.get(route.deployment) ?? new Set<string>();
      if (sourceKeys.has(route.entrypointKey)) {
        yield* fail(
          route.file,
          `route entrypoint ${route.entrypointKey} is duplicated`
        );
      }
      sourceKeys.add(route.entrypointKey);
      routeSourceKeysByDeployment.set(route.deployment, sourceKeys);
    }
    return routeSourceKeysByDeployment;
  });

const validateManifestKeys = (
  state: BoundaryCheckState,
  normalizedFile: string,
  sourceKeys: ReadonlySet<string>
) =>
  Effect.gen(function* validateManifestKeysEffect() {
    const manifestSource = sourceOrEmpty(state.sourceMap, normalizedFile);
    const manifestKeys = readStringProperties(manifestSource, 'entrypointKey');
    const missing = [...sourceKeys].filter(
      (entrypointKey) => !manifestKeys.has(entrypointKey)
    );
    const stale = [...manifestKeys].filter(
      (entrypointKey) => !sourceKeys.has(entrypointKey)
    );
    if (missing.length > 0 || stale.length > 0) {
      const missingLabel =
        missing.length === 0 ? 'none' : sortStrings(missing).join(', ');
      const staleLabel =
        stale.length === 0 ? 'none' : sortStrings(stale).join(', ');
      yield* fail(
        normalizedFile,
        `generated route manifest is stale (missing: ${missingLabel}; orphaned: ${staleLabel}); rerun the route generator`
      );
    }
  });

const validateRouteManifests = (
  path: Path.Path,
  files: readonly string[],
  root: string,
  state: BoundaryCheckState
) =>
  Effect.gen(function* validateRouteManifestsEffect() {
    const routeSourceKeysByDeployment = yield* collectRouteSourceKeys(state);
    const routeManifests = files.filter((file) =>
      file.endsWith('/ultramodern-route-metadata.ts')
    );
    const seenManifestDeployments = new Set<string>();
    for (const manifestFile of routeManifests) {
      const normalizedFile = relative(path, root, manifestFile);
      const ownerEntry = [...state.owners.entries()].find(([appPath]) =>
        normalizedFile.startsWith(`${appPath}/`)
      );
      const [, deployment] = yield* requireDefined(
        ownerEntry,
        normalizedFile,
        'generated route manifest owner is absent from topology'
      );
      if (seenManifestDeployments.has(deployment)) {
        yield* fail(
          normalizedFile,
          `deployment ${deployment} has multiple generated route manifests`
        );
      }
      seenManifestDeployments.add(deployment);
      yield* validateManifestKeys(
        state,
        normalizedFile,
        routeSourceKeysByDeployment.get(deployment) ?? new Set<string>()
      );
    }
    for (const deployment of routeSourceKeysByDeployment.keys()) {
      if (!seenManifestDeployments.has(deployment)) {
        yield* fail(
          'generated route manifests',
          `deployment ${deployment} is missing its route manifest`
        );
      }
    }
  });

const validateIssuerCredentials = () =>
  Effect.gen(function* validateIssuerCredentialsEffect() {
    const issuerCredentials = new Set(
      gatewayContextAuthorizationEntrypoints.map(
        ({ authorization }) => authorization.credential
      )
    );
    if (
      gatewayContextAuthorizationEntrypoints.length !== 2 ||
      !issuerCredentials.has('session') ||
      !issuerCredentials.has('api_key')
    ) {
      yield* fail(
        'packages/shared-contracts/src/gateway-context.ts',
        'gateway authorization contract must classify exactly the session and API-key issuers'
      );
    }
  });

const hasIssuerHandler = (source: string, name: string): boolean =>
  source.includes(`.handle('${name}'`) ||
  containsIdentifier(source, new Set([name]));

const validateGatewayRuntime = (
  shellApiContract: string,
  shellApiRuntime: string
) =>
  Effect.gen(function* validateGatewayRuntimeEffect() {
    const missingApiKeyHandler = !hasIssuerHandler(
      shellApiRuntime,
      'issueApiKeyGatewayContext'
    );
    const missingSessionHandler = !hasIssuerHandler(
      shellApiRuntime,
      'issueGatewayContext'
    );
    if (
      !shellApiContract.includes('.add(GatewayContextApiGroup)') ||
      shellGatewayContextContract.issueGatewayContextPath !==
        gatewayContextAuthorizationEntrypoints[0]?.path ||
      shellGatewayContextContract.issueApiKeyGatewayContextPath !==
        gatewayContextAuthorizationEntrypoints[1]?.path ||
      missingApiKeyHandler ||
      missingSessionHandler
    ) {
      yield* fail(
        'apps/shell-super-app/api/index.ts',
        'both classified capability issuers must be mounted by the Shell API runtime'
      );
    }
  });

const gatewayDeclaration = (source: string, name: string): string => {
  const structure = maskNonCode(source);
  const declaration = new RegExp(`export\\s+const\\s+${name}\\s*=`, 'u').exec(
    structure
  );
  if (declaration === null) {
    return '';
  }
  const start = declaration.index + declaration[0].length;
  const end = topLevelSeparators(structure, ';', start)[0] ?? source.length;
  return maskNonCode(source.slice(start, end), true).trim();
};

const hasMountedIssuerPath = (
  source: string,
  gatewaySource: string,
  issuer: (typeof gatewayContextAuthorizationEntrypoints)[number]
): boolean => {
  const name =
    issuer.authorization.credential === 'session'
      ? 'issueGatewayContext'
      : 'issueApiKeyGatewayContext';
  const endpointPath = issuer.path.slice(
    shellGatewayContextContract.apiPrefix.length
  );
  const group = gatewayDeclaration(gatewaySource, 'GatewayContextApiGroup');
  const shellApi = gatewayDeclaration(source, 'ShellAuthenticationApi');
  return (
    maskNonCode(source, true).includes(
      "import { GatewayContextApiGroup } from '@app/shared-contracts'"
    ) &&
    shellApi.startsWith('HttpApi.make(') &&
    /\.add\(\s*GatewayContextApiGroup\s*\)/u.test(shellApi) &&
    group.startsWith("HttpApiGroup.make('gatewayContext')") &&
    new RegExp(
      `\\.add\\(\\s*HttpApiEndpoint\\.post\\(\\s*'${name}'\\s*,\\s*'${endpointPath}'\\s*,`,
      'u'
    ).test(group)
  );
};

const validateGatewayContract = (state: BoundaryCheckState) =>
  Effect.gen(function* validateGatewayContractEffect() {
    const gatewayContract = sourceOrEmpty(
      state.sourceMap,
      'packages/shared-contracts/src/gateway-context.ts'
    );
    const shellApiContract = sourceOrEmpty(
      state.sourceMap,
      'apps/shell-super-app/shared/api.ts'
    );
    const shellApiRuntime = sourceOrEmpty(
      state.sourceMap,
      'apps/shell-super-app/api/index.ts'
    );
    yield* validateIssuerCredentials();
    for (const issuer of gatewayContextAuthorizationEntrypoints) {
      if (
        !gatewayContract.includes(`'${issuer.path}'`) ||
        !hasMountedIssuerPath(shellApiContract, gatewayContract, issuer)
      ) {
        yield* fail(
          'apps/shell-super-app/shared/api.ts',
          `capability issuer ${issuer.path} is missing from the mounted gateway contract`
        );
      }
      state.inventoryEntries.push(issuer);
    }
    yield* validateGatewayRuntime(shellApiContract, shellApiRuntime);
  });

const checkModuleEntrypointBoundariesEffect = (root: string) =>
  Effect.gen(function* checkModuleEntrypointBoundariesProgram() {
    const fileSystem = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const owners = yield* readTopologyOwners(root);
    const files = [
      ...(yield* walk(path.join(root, 'apps'))),
      ...(yield* walk(path.join(root, 'verticals'))),
      ...(yield* walk(path.join(root, 'packages'))),
    ];
    const sourcePairs: (readonly [string, string])[] = [];
    for (const file of files) {
      const source = yield* fileSystem.readFileString(file, 'utf-8');
      sourcePairs.push([relative(path, root, file), source]);
    }
    const sourceMap = new Map(sourcePairs);
    const state: BoundaryCheckState = {
      inventoryEntries: [],
      owners,
      routeEntrypoints: [],
      sourceMap,
    };
    for (const [file, source] of sourcePairs) {
      const supportedFile =
        SOURCE_EXTENSIONS.has(path.extname(file)) ||
        file.endsWith('package.json');
      const productionFile =
        !file.includes('/tests/') && !file.includes('/fixtures/');
      if (supportedFile && productionFile) {
        yield* validateProductionSource(state, file, source);
      }
    }
    yield* validateRouteManifests(path, files, root, state);
    yield* validateGatewayContract(state);
    const sourceRevision = yield* readSourceRevision(root).pipe(
      Effect.flatMap(Schema.decodeUnknownEffect(SourceRevisionSchema)),
      Effect.mapError(
        () =>
          new ModuleEntrypointBoundaryError({
            message:
              'protected entrypoint inventory: sourceRevision must be a stable revision identifier',
          })
      )
    );
    const entries = normalizeProtectedEntrypointInventory(
      state.inventoryEntries
    );
    const inventory = {
      entries,
      inventoryHash: hashProtectedEntrypointInventory(entries),
      schemaVersion: PROTECTED_ENTRYPOINT_INVENTORY_SCHEMA_VERSION,
      sourceRevision,
    };
    const reportDirectory = path.join(root, '.codex/reports/authorization');
    yield* fileSystem.makeDirectory(reportDirectory, { recursive: true });
    yield* fileSystem.writeFileString(
      path.join(reportDirectory, 'protected-entrypoints.json'),
      serializeProtectedEntrypointInventory(inventory)
    );
  });

export const checkModuleEntrypointBoundaries =
  checkModuleEntrypointBoundariesEffect;

const [, invokedPath] = process.argv;
if (invokedPath !== undefined && invokedPath === import.meta.filename) {
  const main = Effect.gen(function* moduleEntrypointBoundaryMain() {
    const path = yield* Path.Path;
    const root = yield* Config.string('ULTRAMODERN_WORKSPACE_ROOT').pipe(
      Config.withDefault(path.resolve(import.meta.dirname, '..'))
    );
    yield* checkModuleEntrypointBoundariesEffect(root);
    yield* Console.log('Module entrypoint boundaries are valid.');
  });
  const runnable = Effect.scoped(
    Layer.build(
      Layer.effectDiscard(main).pipe(Layer.provide(NodeServices.layer))
    )
  ).pipe(Effect.asVoid);
  NodeRuntime.runMain(runnable);
}
