import { NodeServices } from '@effect/platform-node';
import { Array as EffectArray, Console, Effect, Exit, FileSystem, ManagedRuntime, Order, Path, Schema } from 'effect';
import type { PlatformError } from 'effect/PlatformError';
import { parseSync, Visitor } from 'oxc-parser';
import type { ImportDeclaration, ParamPattern, Span, TSTypeAnnotation, TSTypeReference } from 'oxc-parser';

export interface DatabaseAccessViolation {
  readonly file: string;
  readonly line: number;
  readonly reason: string;
}

const sourceExtensions = new Set(['.ts', '.tsx', '.mts']);
const ignoredDirectories = new Set(['dist', 'node_modules', 'repos', '.output', '.codex']);
const coreRuntimeSourcePrefix = 'packages/core-runtime/src/';

const collect = (root: string): Effect.Effect<readonly string[], PlatformError, FileSystem.FileSystem | Path.Path> =>
  Effect.gen(function* collectSourceFiles() {
    const fileSystem = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const entries = yield* fileSystem.readDirectory(root);
    const discovered = yield* Effect.all(
      entries.map((entry) => {
        if (ignoredDirectories.has(entry)) {
          return Effect.succeed<readonly string[]>([]);
        }
        const candidate = path.join(root, entry);
        return fileSystem.stat(candidate).pipe(
          Effect.flatMap((info) => {
            if (info.type === 'Directory') {
              return collect(candidate);
            }
            return Effect.succeed(sourceExtensions.has(path.extname(entry)) ? [candidate] : []);
          }),
        );
      }),
      { concurrency: 'unbounded' },
    );
    return EffectArray.sort(discovered.flat(), Order.String);
  });

const isGovernedAdapter = (relative: string, source: string): boolean =>
  !/(?:^|\/)(?:tests?|__tests__)\//u.test(relative) &&
  ((!relative.startsWith(coreRuntimeSourcePrefix) && /(?:^|\/)src\/(?:actions|reads)\//u.test(relative)) ||
    /(?:^|\/)verticals\/[^/]+\/api\//u.test(relative) ||
    (/(?:^|\/)apps\/[^/]+\/api\//u.test(relative) &&
      !/(?:^|\/)api\/(?:[^/]+\/)*(?:db|repositories?)\//u.test(relative) &&
      !/(?:service|runtime-infrastructure)\.ts$/u.test(relative)) ||
    (!relative.startsWith('packages/core-runtime/') &&
      !relative.startsWith('scripts/') &&
      /@generated by OntOS Codesmith (?:Action v|Governed Contribution)/u.test(source)));

const isOwnerOperationSource = (relative: string, source: string): boolean =>
  !/(?:^|\/)(?:tests?|__tests__)\//u.test(relative) &&
  ((!relative.startsWith(coreRuntimeSourcePrefix) && /(?:^|\/)src\/(?:actions|reads)\//u.test(relative)) ||
    (!relative.startsWith('packages/core-runtime/') &&
      !relative.startsWith('scripts/') &&
      /@generated by OntOS Codesmith (?:Action v|Governed Contribution)/u.test(source)));

const importPrefix = String.raw`(?:from\s+|import\s*\(\s*|import\s+)`;
const forbiddenImportPattern = `${importPrefix}['"](?:drizzle-orm(?:\\/[^'"]*)?|pg|@app\\/core-runtime\\/db(?:\\/[^'"]*)?|[^'"]*\\/(?:db\\/(?:client|schema|types|scoped-transaction)|repositories?\\/|schema)(?:\\.[^'"]*)?)['"]`;
const forbiddenImport = new RegExp(forbiddenImportPattern, 'u');
const multilineForbiddenImport = new RegExp(forbiddenImportPattern, 'gu');
const importedSpecifier = new RegExp(`${importPrefix}['"](?<specifier>[^'"]+)['"]`, 'gu');
const isTestSource = (relative: string): boolean =>
  /(?:^|\/)(?:tests?|__tests__)\//u.test(relative) || relative.startsWith('packages/core-runtime/src/testing/');
const hiddenCapability =
  /\b(?:CoreDatabase|CoreDatabaseExecutor|CoreTransaction|ActionTransactionExecutor|coreDatabaseSchema|actionInvocations|CORE_TABLES)\b/u;
const hiddenCoreSchema = /\b(?:coreDatabaseSchema|actionInvocations|CORE_TABLES)\b/u;
const scopedTransactionExecutor = /\bScopedTransactionExecutor\b/u;
const isVerticalOwnerSource = (relative: string): boolean => /(?:^|\/)verticals\/[^/]+\/src\//u.test(relative);
const importsCoreDatabaseSchema = new RegExp(`${importPrefix}['"]@app\\/core-runtime\\/db\\/schema['"]`, 'u');
const importSpecifier = new RegExp(`${importPrefix}['"](?<specifier>[^'"]+)['"]`, 'u');
const valueImportPrefix = String.raw`(?:import\s+(?!type\b)[^;]*?\s+from\s+|import\s*\(\s*|import\s+|export\s+(?!type\b)[^;]*?\s+from\s+)`;
const postgresDriver = String.raw`pg|drizzle-orm\/node-postgres`;
const globalDatabaseImplementationImport = new RegExp(
  String.raw`${valueImportPrefix}['"](?:${postgresDriver}|@app\/core-runtime\/db\/client|[^'"]*\/db\/client(?:\.[^'"]*)?)['"]`,
  'u',
);
// The native Effect client is the only PostgreSQL driver; a second one opens a second pool per owner.
const secondPostgresDriverImport = new RegExp(String.raw`${valueImportPrefix}['"](?:${postgresDriver})['"]`, 'gu');

const candidatesFor = (path: Path.Path, unresolved: string): readonly string[] => {
  const extension = path.extname(unresolved);
  if (extension.length === 0) {
    return [
      unresolved,
      `${unresolved}.ts`,
      `${unresolved}.tsx`,
      `${unresolved}.mts`,
      path.join(unresolved, 'index.ts'),
    ];
  }
  if (extension !== '.js' && extension !== '.mjs') {
    return [unresolved];
  }
  const stem = unresolved.slice(0, -extension.length);
  return [unresolved, `${stem}.ts`, `${stem}.mts`];
};

const resolveLocalSource = (
  sourceFiles: ReadonlySet<string>,
  path: Path.Path,
  root: string,
  importer: string,
  specifier: string,
): string | undefined => {
  if (specifier.startsWith('.')) {
    return candidatesFor(path, path.resolve(path.dirname(importer), specifier)).find((candidate) =>
      sourceFiles.has(candidate),
    );
  }
  const packageGroups = /^@app\/(?<packageName>[^/]+)(?:\/(?<subpath>.+))?$/u.exec(specifier)?.groups;
  const packageName = packageGroups?.packageName;
  if (packageName === undefined) {
    return undefined;
  }
  const subpath = packageGroups?.subpath;
  const candidates = ['apps', 'packages', 'verticals'].flatMap((ownerRoot) => {
    const packageRoot = path.join(root, ownerRoot, packageName);
    if (subpath === undefined) {
      return [
        path.join(packageRoot, 'src/index.ts'),
        path.join(packageRoot, 'index.ts'),
        path.join(packageRoot, 'vertical.registration.ts'),
      ];
    }
    return [
      ...candidatesFor(path, path.join(packageRoot, subpath)),
      ...candidatesFor(path, path.join(packageRoot, 'src', subpath)),
    ];
  });
  return candidates.find((candidate) => sourceFiles.has(candidate));
};

const typeReferenceNamed = (annotation: TSTypeAnnotation | null | undefined, name: string): boolean => {
  const type = annotation?.typeAnnotation;
  return type?.type === 'TSTypeReference' && type.typeName.type === 'Identifier' && type.typeName.name === name;
};

const parameterNamed = (parameter: ParamPattern, name: string, typeName: string): boolean =>
  parameter.type === 'Identifier' && parameter.name === name && typeReferenceNamed(parameter.typeAnnotation, typeName);

const scopedFactoryTransactionSpan = (
  parameters: readonly ParamPattern[],
  executorNames: ReadonlySet<string>,
): Span | undefined => {
  const hasOperationalScope = parameters.some((parameter) => parameterNamed(parameter, 'scope', 'OperationalScope'));
  if (!hasOperationalScope) {
    return undefined;
  }
  for (const parameter of parameters) {
    if (
      parameter.type === 'Identifier' &&
      parameter.name === 'transaction' &&
      parameter.typeAnnotation?.typeAnnotation.type === 'TSTypeReference' &&
      parameter.typeAnnotation.typeAnnotation.typeName.type === 'Identifier' &&
      executorNames.has(parameter.typeAnnotation.typeAnnotation.typeName.name)
    ) {
      return parameter.typeAnnotation.typeAnnotation;
    }
  }
  return undefined;
};

const executorImport = (
  declaration: ImportDeclaration,
): { readonly localName: string; readonly span: Span; readonly typeOnly: boolean } | undefined => {
  const specifier = declaration.specifiers.find(
    (candidate) =>
      candidate.type === 'ImportSpecifier' &&
      candidate.imported.type === 'Identifier' &&
      candidate.imported.name === 'ScopedTransactionExecutor',
  );
  if (specifier?.type !== 'ImportSpecifier') {
    return undefined;
  }
  return {
    localName: specifier.local.name,
    span: specifier,
    typeOnly: declaration.importKind === 'type' || specifier.importKind === 'type',
  };
};

/**
 * Core passes the scoped executor only to a private owner service factory. The factory may name that
 * input in its `(transaction, scope)` signature, but the executor must never become handler services.
 */
const scopedTransactionExposureIndexes = (file: string, source: string): readonly number[] => {
  if (!scopedTransactionExecutor.test(source)) {
    return [];
  }
  const parsed = parseSync(file, source, {
    astType: 'ts',
    lang: file.endsWith('.tsx') ? 'tsx' : 'ts',
    sourceType: 'module',
  });
  if (parsed.errors.length > 0) {
    return [...source.matchAll(new RegExp(scopedTransactionExecutor, 'gu'))].map((match) => match.index);
  }

  const executorNames = new Set(['ScopedTransactionExecutor']);
  const invalidImportSpans: Span[] = [];
  for (const statement of parsed.program.body) {
    if (statement.type !== 'ImportDeclaration') {
      continue;
    }
    const imported = executorImport(statement);
    if (imported !== undefined) {
      executorNames.add(imported.localName);
      if (!imported.typeOnly) {
        invalidImportSpans.push(imported.span);
      }
    }
  }

  const allowedFactoryParameters: Span[] = [];
  const allowScopedFactoryParameter = (parameters: readonly ParamPattern[]): void => {
    const span = scopedFactoryTransactionSpan(parameters, executorNames);
    if (span !== undefined) {
      allowedFactoryParameters.push(span);
    }
  };
  new Visitor({
    ArrowFunctionExpression: (node) => allowScopedFactoryParameter(node.params),
    FunctionDeclaration: (node) => allowScopedFactoryParameter(node.params),
    FunctionExpression: (node) => allowScopedFactoryParameter(node.params),
    TSFunctionType: (node) => allowScopedFactoryParameter(node.params),
  }).visit(parsed.program);

  const invalidReferences: number[] = invalidImportSpans.map((span) => span.start);
  const recordExecutorReference = (reference: TSTypeReference): void => {
    if (
      reference.typeName.type === 'Identifier' &&
      executorNames.has(reference.typeName.name) &&
      !allowedFactoryParameters.some((span) => span.start <= reference.start && reference.end <= span.end)
    ) {
      invalidReferences.push(reference.start);
    }
  };
  new Visitor({ TSTypeReference: recordExecutorReference }).visit(parsed.program);
  return EffectArray.sort([...new Set(invalidReferences)], Order.Number);
};

const containsGlobalDatabaseCapability = (file: string, source: string): boolean =>
  globalDatabaseImplementationImport.test(source) ||
  hiddenCapability.test(source) ||
  scopedTransactionExposureIndexes(file, source).length > 0;

const globalDatabaseCapabilityClosure = (
  sources: ReadonlyMap<string, string>,
  sourceFiles: ReadonlySet<string>,
  path: Path.Path,
  root: string,
): ReadonlySet<string> => {
  const importersByDependency = new Map<string, Set<string>>();
  const closure = new Set<string>();
  const pending: string[] = [];
  for (const [file, source] of sources) {
    const relative = path.relative(root, file).split(path.sep).join('/');
    // Core's public runtime modules are the sanctioned governed-operation boundary.
    // Direct Core database imports and named hidden capabilities are checked at the
    // owning source line; recursively treating every safe Core type dependency as a
    // database leak makes generated Action and Read registrations impossible.
    if (!relative.startsWith(coreRuntimeSourcePrefix)) {
      if (containsGlobalDatabaseCapability(file, source)) {
        closure.add(file);
        pending.push(file);
      }
      for (const match of source.matchAll(importedSpecifier)) {
        const specifier = match.groups?.specifier;
        const dependency =
          specifier === undefined ? undefined : resolveLocalSource(sourceFiles, path, root, file, specifier);
        if (dependency !== undefined) {
          const importers = importersByDependency.get(dependency) ?? new Set<string>();
          importers.add(file);
          importersByDependency.set(dependency, importers);
        }
      }
    }
  }
  while (pending.length > 0) {
    const dependency = pending.pop();
    if (dependency !== undefined) {
      for (const importer of importersByDependency.get(dependency) ?? []) {
        if (!closure.has(importer)) {
          closure.add(importer);
          pending.push(importer);
        }
      }
    }
  }
  return closure;
};

const crossOwnerPrivateImport = (
  path: Path.Path,
  root: string,
  file: string,
  relative: string,
  line: string,
): boolean => {
  const sourceOwner = /(?:^|\/)verticals\/(?<owner>[^/]+)\/src\//u.exec(relative)?.groups?.owner;
  const specifier = importSpecifier.exec(line)?.groups?.specifier;
  if (sourceOwner === undefined || specifier === undefined) {
    return false;
  }
  const targetRelative = specifier.startsWith('.')
    ? path
        .relative(root, path.resolve(path.dirname(file), specifier))
        .split(path.sep)
        .join('/')
    : specifier.replace(/^@app\//u, '');
  const targetOwner = /(?:^|\/)verticals\/(?<owner>[^/]+)\//u.exec(targetRelative)?.groups?.owner;
  return (
    targetOwner !== undefined &&
    targetOwner !== sourceOwner &&
    /(?:^|\/)src\/(?:db|repositories?)\//u.test(targetRelative)
  );
};

interface SourceCheckContext {
  readonly file: string;
  readonly globalDatabaseCapabilityFiles: ReadonlySet<string>;
  readonly governedAdapter: boolean;
  readonly path: Path.Path;
  readonly record: (violation: DatabaseAccessViolation) => void;
  readonly relative: string;
  readonly root: string;
  readonly source: string;
  readonly sourceFiles: ReadonlySet<string>;
}

const sourceLine = (source: string, index: number): number => source.slice(0, index).split('\n').length;

const recordProductionTestingImports = (context: SourceCheckContext): void => {
  if (isTestSource(context.relative)) {
    return;
  }
  for (const match of context.source.matchAll(importedSpecifier)) {
    const specifier = match.groups?.specifier;
    if (specifier === undefined) {
      continue;
    }
    const dependency = resolveLocalSource(context.sourceFiles, context.path, context.root, context.file, specifier);
    const dependencyRelative =
      dependency === undefined
        ? undefined
        : context.path.relative(context.root, dependency).split(context.path.sep).join('/');
    if (
      specifier.startsWith('@app/core-runtime/testing/') ||
      dependencyRelative?.startsWith('packages/core-runtime/src/testing/') === true
    ) {
      context.record({
        file: context.relative,
        line: sourceLine(context.source, match.index),
        reason: 'test-only Core runtime imported by production source',
      });
    }
  }
};

const recordTransitiveDatabaseCapabilities = (context: SourceCheckContext): void => {
  if (!isOwnerOperationSource(context.relative, context.source)) {
    return;
  }
  for (const match of context.source.matchAll(importedSpecifier)) {
    const specifier = match.groups?.specifier;
    if (specifier === undefined) {
      continue;
    }
    const dependency = resolveLocalSource(context.sourceFiles, context.path, context.root, context.file, specifier);
    if (dependency !== undefined && context.globalDatabaseCapabilityFiles.has(dependency)) {
      context.record({
        file: context.relative,
        line: sourceLine(context.source, match.index),
        reason: 'transitive global database capability in governed handler requirements',
      });
    }
  }
};

const isDirectDatabaseImport = (context: SourceCheckContext, source: string): boolean =>
  context.governedAdapter ||
  (isVerticalOwnerSource(context.relative) && importsCoreDatabaseSchema.test(source)) ||
  crossOwnerPrivateImport(context.path, context.root, context.file, context.relative, source);

const recordMultilineDatabaseImports = (context: SourceCheckContext): void => {
  for (const match of context.source.matchAll(multilineForbiddenImport)) {
    if (!match[0].includes('\n') || !isDirectDatabaseImport(context, match[0])) {
      continue;
    }
    context.record({
      file: context.relative,
      line: sourceLine(context.source, match.index),
      reason: 'direct database/private repository import in governed handler or transport adapter',
    });
  }
};

const exposesHiddenCapability = (context: SourceCheckContext, line: string): boolean => {
  const hasCapability = context.governedAdapter
    ? hiddenCapability.test(line)
    : isVerticalOwnerSource(context.relative) && hiddenCoreSchema.test(line);
  return hasCapability && !line.trimStart().startsWith('//');
};

const recordLineDatabaseViolations = (context: SourceCheckContext): void => {
  for (const [index, line] of context.source.split('\n').entries()) {
    const directImport =
      (context.governedAdapter && forbiddenImport.test(line)) ||
      (isVerticalOwnerSource(context.relative) && importsCoreDatabaseSchema.test(line)) ||
      crossOwnerPrivateImport(context.path, context.root, context.file, context.relative, line);
    if (directImport) {
      context.record({
        file: context.relative,
        line: index + 1,
        reason: 'direct database/private repository import in governed handler or transport adapter',
      });
    } else if (exposesHiddenCapability(context, line)) {
      context.record({
        file: context.relative,
        line: index + 1,
        reason: 'database capability exposed through governed handler requirements',
      });
    }
  }
};

const recordScopedTransactionExposure = (context: SourceCheckContext): void => {
  if (!context.governedAdapter) {
    return;
  }
  for (const index of scopedTransactionExposureIndexes(context.file, context.source)) {
    context.record({
      file: context.relative,
      line: sourceLine(context.source, index),
      reason: 'database capability exposed through governed handler requirements',
    });
  }
};

const recordSecondPostgresDriver = (context: SourceCheckContext): void => {
  // Governed handlers and adapters already reject every database import.
  if (isTestSource(context.relative) || context.governedAdapter) {
    return;
  }
  for (const match of context.source.matchAll(secondPostgresDriverImport)) {
    context.record({
      file: context.relative,
      line: sourceLine(context.source, match.index),
      reason:
        'second PostgreSQL driver: build the owner database on @effect/sql-pg with drizzle-orm/effect-postgres instead of pg or drizzle-orm/node-postgres',
    });
  }
};

const compareViolations = (left: DatabaseAccessViolation, right: DatabaseAccessViolation): -1 | 0 | 1 => {
  const fileOrder = left.file.localeCompare(right.file);
  if (fileOrder < 0) {
    return -1;
  }
  if (fileOrder > 0) {
    return 1;
  }
  const lineOrder = left.line - right.line;
  if (lineOrder < 0) {
    return -1;
  }
  if (lineOrder > 0) {
    return 1;
  }
  const reasonOrder = left.reason.localeCompare(right.reason);
  if (reasonOrder < 0) {
    return -1;
  }
  return reasonOrder > 0 ? 1 : 0;
};

const ViolationOrder = Order.make(compareViolations);

export const checkDatabaseAccessBoundaries = (root: string) =>
  Effect.gen(function* checkDatabaseAccessBoundariesProgram() {
    const fileSystem = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const violations: DatabaseAccessViolation[] = [];
    const files = yield* collect(root);
    const sourcePairs = yield* Effect.all(
      files.map((file) =>
        fileSystem.readFileString(file, 'utf-8').pipe(Effect.map((source) => [file, source] as const)),
      ),
      { concurrency: 'unbounded' },
    );
    const sources = new Map(sourcePairs);
    const sourceFiles = new Set(files);
    const globalDatabaseCapabilityFiles = globalDatabaseCapabilityClosure(sources, sourceFiles, path, root);
    const recorded = new Set<string>();
    const record = (violation: DatabaseAccessViolation): void => {
      const key = `${violation.file}:${violation.line}:${violation.reason}`;
      if (recorded.has(key)) {
        return;
      }
      recorded.add(key);
      violations.push(violation);
    };
    for (const [file, source] of sourcePairs) {
      const relative = path.relative(root, file).split(path.sep).join('/');
      const context: SourceCheckContext = {
        file,
        globalDatabaseCapabilityFiles,
        governedAdapter: isGovernedAdapter(relative, source),
        path,
        record,
        relative,
        root,
        source,
        sourceFiles,
      };
      recordProductionTestingImports(context);
      recordTransitiveDatabaseCapabilities(context);
      recordMultilineDatabaseImports(context);
      recordLineDatabaseViolations(context);
      recordScopedTransactionExposure(context);
      recordSecondPostgresDriver(context);
    }
    return EffectArray.sort(violations, ViolationOrder);
  });

class DatabaseAccessBoundaryCheckFailed extends Schema.TaggedError<DatabaseAccessBoundaryCheckFailed>()(
  'DatabaseAccessBoundaryCheckFailed',
  { violationCount: Schema.Number },
) {}

const main = Effect.gen(function* databaseAccessBoundaryMain() {
  const path = yield* Path.Path;
  const violations = yield* checkDatabaseAccessBoundaries(path.resolve(process.cwd()));
  if (violations.length > 0) {
    yield* Effect.all(
      violations.map((violation) => Console.error(`${violation.file}:${violation.line}: ${violation.reason}`)),
      { concurrency: 1, discard: true },
    );
    return yield* Effect.fail(
      new DatabaseAccessBoundaryCheckFailed({
        violationCount: violations.length,
      }),
    );
  }
  return yield* Console.log('Database access boundaries verified');
});

const [, invokedPath] = process.argv;
if (invokedPath === import.meta.filename) {
  const databaseAccessBoundaryRuntime = ManagedRuntime.make(NodeServices.layer);
  const exit = await databaseAccessBoundaryRuntime.runPromiseExit(main);
  process.exitCode = Exit.isSuccess(exit) ? 0 : 1;
}
