import path from 'node:path';
import { Schema } from 'effect';
import { isCodePosition, maskNonCode } from './scaffolding/shared.mts';

const MODULE_API_HEADER = '// @generated by OntOS Codesmith module-api v1\n';
const GOVERNED_CONTRIBUTION_HEADER = '// @generated by OntOS Codesmith Governed Contribution v1\n';
const MODULE_API_KIND = 'module-api';
const REPORT_KIND = 'report';
const SEARCH_PROVIDER_KIND = 'search-provider';
const GOVERNED_HANDLER_LAYER_SLOT_START = '// <generated-governed-http-handler-layers>';
const GOVERNED_HANDLER_LAYER_SLOT_END = '// </generated-governed-http-handler-layers>';
const HTTP_API_MAKE = 'HttpApi.make(';
const HTTP_API_CONTRACT_MODULE = 'effect/unstable/httpapi';

const GovernedReadKindSchema = Schema.Literals([
  MODULE_API_KIND,
  REPORT_KIND,
  SEARCH_PROVIDER_KIND,
]);
type GovernedReadKind = typeof GovernedReadKindSchema.Type;
const isGovernedReadKind = Schema.is(GovernedReadKindSchema);

interface GovernedReadContribution {
  readonly contractStem: string;
  readonly kind: GovernedReadKind;
  readonly name: string;
}

const escapeRegExp = (value: string): string =>
  value.replaceAll(/[.*+?^${}()|[\]\\]/gu, String.raw`\$&`);

const toPascalCase = (value: string): string =>
  value
    .split('-')
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join('');

const toCamelCase = (value: string): string => {
  const pascal = toPascalCase(value);
  return `${pascal.slice(0, 1).toLowerCase()}${pascal.slice(1)}`;
};

const matches = (source: string | undefined, expression: RegExp): boolean =>
  source !== undefined && expression.test(source);

const hasExactlyOne = (source: string | undefined, expression: RegExp): boolean =>
  source !== undefined && [...source.matchAll(expression)].length === 1;

const QuoteSchema = Schema.Literals(["'", '"', '`']);
type Quote = typeof QuoteSchema.Type;

const matchingDelimiterEnd = (
  source: string,
  start: number,
  opening: string,
  closing: string,
): number | undefined => {
  let depth = 0;
  let quote: Quote | null = null;
  let escaped = false;
  for (let index = start; index < source.length; index += 1) {
    const character = source[index];
    if (quote !== null) {
      if (escaped) {
        escaped = false;
      } else if (character === '\\') {
        escaped = true;
      } else if (character === quote) {
        quote = null;
      }
      continue;
    }
    if (character === "'" || character === '"' || character === '`') {
      quote = character;
    } else if (character === opening) {
      depth += 1;
    } else if (character === closing) {
      depth -= 1;
      if (depth === 0) {
        return index;
      }
    }
  }
  return undefined;
};

const maskComments = (source: string): string => maskNonCode(source, true);

/* eslint-disable complexity -- These lexical helpers deliberately track all JavaScript delimiter kinds. */
const callArgument = (
  source: string,
  declaration: RegExp,
  argumentIndex = 0,
): string | undefined => {
  const code = maskComments(source);
  const match = declaration.exec(code);
  if (match?.index === undefined) {
    return undefined;
  }
  const callStart = code.indexOf('(', match.index);
  const callEnd = callStart === -1 ? null : matchingDelimiterEnd(code, callStart, '(', ')');
  if (callStart === -1 || callEnd === null || callEnd === undefined) {
    return undefined;
  }
  const argumentRanges: (readonly [number, number])[] = [];
  let argumentStart = callStart + 1;
  let roundDepth = 0;
  let squareDepth = 0;
  let curlyDepth = 0;
  let quote: Quote | null = null;
  let escaped = false;
  for (let index = callStart + 1; index <= callEnd; index += 1) {
    const character = code[index];
    if (quote !== null) {
      if (escaped) {
        escaped = false;
      } else if (character === '\\') {
        escaped = true;
      } else if (character === quote) {
        quote = null;
      }
      continue;
    }
    if (character === "'" || character === '"' || character === '`') {
      quote = character;
    } else if (character === '(') {
      roundDepth += 1;
    } else if (character === ')') {
      if (roundDepth > 0) {
        roundDepth -= 1;
      }
    } else if (character === '[') {
      squareDepth += 1;
    } else if (character === ']') {
      squareDepth -= 1;
    } else if (character === '{') {
      curlyDepth += 1;
    } else if (character === '}') {
      curlyDepth -= 1;
    }
    if (
      (character === ',' || index === callEnd) &&
      roundDepth === 0 &&
      squareDepth === 0 &&
      curlyDepth === 0
    ) {
      argumentRanges.push([argumentStart, index]);
      argumentStart = index + 1;
    }
  }
  const range = argumentRanges[argumentIndex];
  if (range === undefined) {
    return undefined;
  }
  return code.slice(range[0], range[1]).trim();
};
/* eslint-enable complexity */

const objectArgument = (
  source: string,
  declaration: RegExp,
  argumentIndex = 0,
): string | undefined => {
  const argument = callArgument(source, declaration, argumentIndex);
  if (argument === undefined) {
    return undefined;
  }
  if (!argument.startsWith('{')) {
    return undefined;
  }
  const end = matchingDelimiterEnd(argument, 0, '{', '}');
  return end === argument.length - 1 ? argument : undefined;
};

const topLevelObjectEntries = (source: string): readonly string[] | undefined => {
  if (!source.startsWith('{') || matchingDelimiterEnd(source, 0, '{', '}') !== source.length - 1) {
    return undefined;
  }
  const code = maskNonCode(source);
  const entries: string[] = [];
  let start = 1;
  let roundDepth = 0;
  let squareDepth = 0;
  let curlyDepth = 0;
  for (let index = 1; index < code.length - 1; index += 1) {
    const character = code[index];
    if (character === '(') {
      roundDepth += 1;
    } else if (character === ')') {
      roundDepth -= 1;
    } else if (character === '[') {
      squareDepth += 1;
    } else if (character === ']') {
      squareDepth -= 1;
    } else if (character === '{') {
      curlyDepth += 1;
    } else if (character === '}') {
      curlyDepth -= 1;
    } else if (character === ',' && roundDepth === 0 && squareDepth === 0 && curlyDepth === 0) {
      const entry = source.slice(start, index).trim();
      if (entry !== '') {
        entries.push(entry);
      }
      start = index + 1;
    }
  }
  const finalEntry = source.slice(start, -1).trim();
  if (finalEntry !== '') {
    entries.push(finalEntry);
  }
  return entries;
};

const objectProperty = (source: string, property: string): string | undefined => {
  const entries = topLevelObjectEntries(source);
  const prefix = new RegExp(`^${escapeRegExp(property)}:\\s*`, 'u');
  const candidates = entries?.filter((entry) => prefix.test(entry)) ?? [];
  return candidates.length === 1 ? candidates[0]?.replace(prefix, '').trim() : undefined;
};

const objectPropertyValue = (source: string, property: string): string | undefined => {
  const explicit = objectProperty(source, property);
  if (explicit !== undefined) {
    return explicit;
  }
  const shorthand = topLevelObjectEntries(source)?.filter((entry) => entry === property) ?? [];
  return shorthand.length === 1 ? property : undefined;
};

const isEffectFnCallback = (source: string): boolean => {
  if (!source.startsWith('Effect.fn(')) {
    return false;
  }
  const opening = source.indexOf('(');
  const closing = matchingDelimiterEnd(source, opening, '(', ')');
  const invocation = closing === undefined ? '' : source.slice(closing + 1).trim();
  const callback = invocation.startsWith('(')
    ? callArgument(`invoke${invocation}`, /^invoke\(/u)
    : undefined;
  return (
    callback !== undefined &&
    matchingDelimiterEnd(invocation, 0, '(', ')') === invocation.length - 1 &&
    (matches(callback, /^(?:async\s+)?function\*?(?:\s+[A-Za-z_$][A-Za-z0-9_$]*)?\s*\(/u) ||
      matches(callback, /^(?:async\s+)?(?:\([^)]*\)|[A-Za-z_$][A-Za-z0-9_$]*)\s*=>/u))
  );
};

const isExecutableCallback = (candidate: string | undefined, ownerSource?: string): boolean => {
  if (candidate === undefined || /^(?:null|undefined)(?:\s+as\b[\s\S]*)?$/u.test(candidate)) {
    return false;
  }
  if (
    matches(candidate, /^(?:async\s+)?(?:\([^)]*\)|[A-Za-z_$][A-Za-z0-9_$]*)\s*=>/u) ||
    isEffectFnCallback(candidate) ||
    matches(candidate, /^(?:async\s+)?function\*?(?:\s+[A-Za-z_$][A-Za-z0-9_$]*)?\s*\(/u)
  ) {
    return true;
  }
  if (ownerSource === undefined || !/^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(candidate)) {
    return false;
  }
  // eslint-disable-next-line no-use-before-define -- Identifier callbacks are resolved after the shared top-level declaration parser initializes.
  const initializer = assignedExpression(
    ownerSource,
    new RegExp(`(?:export\\s+)?const ${escapeRegExp(candidate)}\\s*=\\s*`, 'u'),
  );
  return (
    initializer !== undefined && initializer !== candidate && isExecutableCallback(initializer)
  );
};

const callbackReturnedExpression = (handlerSource: string): string | undefined => {
  const structure = maskNonCode(handlerSource);
  const arrow = structure.indexOf('=>');
  if (arrow === -1) {
    return undefined;
  }
  const body = handlerSource.slice(arrow + 2).trim();
  if (!body.startsWith('{')) {
    return body;
  }
  const bodyStructure = maskNonCode(body);
  const returns = [...bodyStructure.matchAll(/\breturn\s+/gu)].filter(
    // eslint-disable-next-line no-use-before-define -- Callback results reuse the shared lexical-depth scanner declared below.
    (match) => match.index !== undefined && codeDepthBeforePosition(body, match.index) === 1,
  );
  const finalReturn = returns.at(-1);
  if (finalReturn?.index === undefined) {
    return undefined;
  }
  const returned = body.slice(finalReturn.index + finalReturn[0].length);
  const statementEnd = returned.indexOf(';');
  return (statementEnd === -1 ? returned : returned.slice(0, statementEnd)).trim();
};

const isReadHandlerCallback = (candidate: string | undefined, ownerSource: string): boolean => {
  if (!isExecutableCallback(candidate, ownerSource) || candidate === undefined) {
    return false;
  }
  const resolved = /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(candidate)
    ? // eslint-disable-next-line no-use-before-define -- Identifier callbacks are resolved after the shared top-level declaration parser initializes.
      assignedExpression(
        ownerSource,
        new RegExp(`(?:export\\s+)?const ${escapeRegExp(candidate)}\\s*=\\s*`, 'u'),
      )
    : candidate;
  if (resolved === undefined) {
    return false;
  }
  if (isEffectFnCallback(resolved)) {
    return /\byield\*|\.pipe\(/u.test(maskNonCode(resolved, true));
  }
  const expression = callbackReturnedExpression(resolved);
  return /\bEffect\.[A-Za-z_$][A-Za-z0-9_$]*\s*\(|\.pipe\(/u.test(
    maskNonCode(expression ?? '', true),
  );
};

const isWholeCallExpression = (source: string, declaration: RegExp): boolean => {
  const match = declaration.exec(source);
  if (match?.index === undefined) {
    return false;
  }
  const opening = source.indexOf('(', match.index);
  const closing = matchingDelimiterEnd(source, opening, '(', ')');
  return opening !== -1 && closing === source.length - 1;
};

interface SourceDepthAnalysis {
  readonly code: string;
  readonly prefixDepths: Int32Array;
}

// Source strings are immutable cache keys. Bound retained analyses because scripts may validate
// many disposable owners in one process; repeated contributions reuse the same owner sources.
const sourceDepthAnalyses = new Map<string, SourceDepthAnalysis>();
const MAX_SOURCE_DEPTH_ANALYSES = 32;
const sourceDepthAnalysis = (source: string): SourceDepthAnalysis => {
  const cached = sourceDepthAnalyses.get(source);
  if (cached !== undefined) {
    return cached;
  }
  const code = maskNonCode(source);
  const prefixDepths = new Int32Array(code.length + 1);
  let depth = 0;
  for (let index = 0; index < code.length; index += 1) {
    const character = code[index];
    if (character === '{' || character === '(' || character === '[') {
      depth += 1;
    } else if (character === '}' || character === ')' || character === ']') {
      depth -= 1;
    }
    prefixDepths[index + 1] = depth;
  }
  if (sourceDepthAnalyses.size >= MAX_SOURCE_DEPTH_ANALYSES) {
    const oldest = sourceDepthAnalyses.keys().next().value;
    if (oldest !== undefined) {
      sourceDepthAnalyses.delete(oldest);
    }
  }
  const analysis = { code, prefixDepths };
  sourceDepthAnalyses.set(source, analysis);
  return analysis;
};

const codeDepthBeforePosition = (source: string, target: number): number =>
  sourceDepthAnalysis(source).prefixDepths[target] ?? 0;

const codeDepthAtPosition = (source: string, target: number): number | undefined =>
  isCodePosition(source, target) ? codeDepthBeforePosition(source, target) : undefined;

const isTopLevelCodePosition = (source: string, target: number): boolean =>
  codeDepthAtPosition(source, target) === 0;

interface SourceRange {
  readonly end: number;
  readonly start: number;
  readonly value: string;
}

const assignedExpressionRange = (source: string, declaration: RegExp): SourceRange | undefined => {
  const code = maskComments(source);
  const structure = sourceDepthAnalysis(source).code;
  const flags = declaration.flags.includes('g') ? declaration.flags : `${declaration.flags}g`;
  const declarations = [...structure.matchAll(new RegExp(declaration.source, flags))].filter(
    (candidate) => candidate.index !== undefined && isTopLevelCodePosition(source, candidate.index),
  );
  if (declarations.length !== 1) {
    return undefined;
  }
  const [match] = declarations;
  if (match?.index === undefined) {
    return undefined;
  }
  const start = match.index + match[0].length;
  let roundDepth = 0;
  let squareDepth = 0;
  let curlyDepth = 0;
  for (let index = start; index < code.length; index += 1) {
    const character = structure[index];
    if (character === '(') {
      roundDepth += 1;
    } else if (character === ')') {
      roundDepth -= 1;
    } else if (character === '[') {
      squareDepth += 1;
    } else if (character === ']') {
      squareDepth -= 1;
    } else if (character === '{') {
      curlyDepth += 1;
    } else if (character === '}') {
      curlyDepth -= 1;
    } else if (character === ';' && roundDepth === 0 && squareDepth === 0 && curlyDepth === 0) {
      const valueStart = start + (/^\s*/u.exec(code.slice(start, index))?.[0].length ?? 0);
      const valueEnd = index - (/\s*$/u.exec(code.slice(start, index))?.[0].length ?? 0);
      return { end: valueEnd, start: valueStart, value: code.slice(valueStart, valueEnd) };
    }
  }
  return undefined;
};

const assignedExpression = (source: string, declaration: RegExp): string | undefined =>
  assignedExpressionRange(source, declaration)?.value;

interface GeneratedSlotRange {
  readonly bodyEnd: number;
  readonly bodyStart: number;
  readonly depth: number;
  readonly markerEnd: number;
  readonly markerStart: number;
}

const generatedSlotRange = (
  source: string,
  startMarker: string,
  endMarker: string,
): GeneratedSlotRange | undefined => {
  const markerStart = source.indexOf(startMarker);
  const markerEnd = source.indexOf(endMarker);
  const depth = markerStart === -1 ? undefined : codeDepthBeforePosition(source, markerStart);
  if (
    markerStart === -1 ||
    markerEnd <= markerStart ||
    depth === undefined ||
    !isCodePosition(source, markerStart) ||
    !isCodePosition(source, markerEnd) ||
    codeDepthBeforePosition(source, markerEnd) !== depth ||
    source.includes(startMarker, markerStart + startMarker.length) ||
    source.includes(endMarker, markerEnd + endMarker.length)
  ) {
    return undefined;
  }
  return {
    bodyEnd: markerEnd,
    bodyStart: markerStart + startMarker.length,
    depth,
    markerEnd,
    markerStart,
  };
};

const generatedSlotEntries = (
  source: string,
  startMarker: string,
  endMarker: string,
): readonly string[] | undefined => {
  const slot = generatedSlotRange(source, startMarker, endMarker);
  if (slot === undefined) {
    return undefined;
  }
  const structure = sourceDepthAnalysis(source).code;
  const entries: string[] = [];
  let start = slot.bodyStart;
  for (let index = slot.bodyStart; index < slot.bodyEnd; index += 1) {
    if (structure[index] === ',' && codeDepthBeforePosition(source, index) === slot.depth) {
      const entry = source.slice(start, index).trim();
      if (entry !== '') {
        entries.push(entry);
      }
      start = index + 1;
    }
  }
  const finalEntry = source.slice(start, slot.bodyEnd).trim();
  if (finalEntry !== '') {
    entries.push(finalEntry);
  }
  return entries;
};

const entriesAcrossSlots = (
  source: string,
  slots: readonly (readonly [string, string])[],
): readonly string[] | undefined => {
  const entries = slots.map(([start, end]) => generatedSlotEntries(source, start, end));
  return entries.some((candidate) => candidate === undefined)
    ? undefined
    : entries.flatMap((candidate) => candidate ?? []);
};

const objectEntryKey = (entry: string): string | undefined => {
  const match =
    /^(?:'(?<single>[^']+)'|"(?<double>[^"]+)"|(?<bare>[A-Za-z][A-Za-z0-9-]*))\s*:/u.exec(entry);
  return match?.groups?.single ?? match?.groups?.double ?? match?.groups?.bare;
};

const slotHasExactlyOneCodeMatch = (
  source: string,
  startMarker: string,
  endMarker: string,
  expression: RegExp,
  depthOffset: number | null = 0,
): boolean => {
  const slot = generatedSlotRange(source, startMarker, endMarker);
  if (slot === undefined) {
    return false;
  }
  const flags = expression.flags.includes('g') ? expression.flags : `${expression.flags}g`;
  return (
    [
      ...source.slice(slot.bodyStart, slot.bodyEnd).matchAll(new RegExp(expression.source, flags)),
    ].filter((candidate) => {
      if (candidate.index === undefined) {
        return false;
      }
      const depth = codeDepthAtPosition(source, slot.bodyStart + candidate.index);
      return depth !== undefined && (depthOffset === null || depth === slot.depth + depthOffset);
    }).length === 1
  );
};

const slotIsInsideObjectProperty = (
  source: string,
  property: string,
  startMarker: string,
  endMarker: string,
): boolean => {
  const code = maskComments(source);
  const slot = generatedSlotRange(source, startMarker, endMarker);
  if (slot === undefined) {
    return false;
  }
  const propertyPattern = new RegExp(`\\b${escapeRegExp(property)}:\\s*\\{`, 'gu');
  const containers = [...code.matchAll(propertyPattern)].filter((match) => {
    const opening = code.indexOf('{', match.index);
    const closing = matchingDelimiterEnd(code, opening, '{', '}');
    return (
      match.index !== undefined &&
      codeDepthAtPosition(source, match.index) === slot.depth - 1 &&
      closing !== undefined &&
      opening < slot.markerStart &&
      closing > slot.markerEnd
    );
  });
  return containers.length === 1;
};

const defaultExportExpression = (source: string): string | undefined =>
  assignedExpression(source, /^\s*export default\s+/mu);

const returnedEffectBffDefinition = (source: string): string | undefined => {
  const structure = maskNonCode(source);
  const returnedCalls = [
    ...structure.matchAll(/\breturn\s+(?:defineEffectBff|assembleEffectBffRuntime)\(/gu),
  ];
  if (returnedCalls.length !== 1 || returnedCalls[0]?.index === undefined) {
    return undefined;
  }
  const callStart =
    returnedCalls[0].index +
    returnedCalls[0][0].search(/(?:defineEffectBff|assembleEffectBffRuntime)\(/u);
  const opening = structure.indexOf('(', callStart);
  const closing = matchingDelimiterEnd(structure, opening, '(', ')');
  if (closing === undefined) {
    return undefined;
  }
  return objectArgument(
    source.slice(callStart, closing + 1),
    /^(?:defineEffectBff|assembleEffectBffRuntime)\(/u,
  );
};

const exportedRuntimeFactory = (source: string): SourceRange | undefined => {
  const exported = defaultExportExpression(source);
  if (exported === undefined || !/^[A-Za-z][A-Za-z0-9]*$/u.test(exported)) {
    return undefined;
  }
  const runtimeInitializer = assignedExpression(
    source,
    new RegExp(`const ${escapeRegExp(exported)}\\s*=\\s*`, 'u'),
  );
  const factory = /^(?<factory>make[A-Za-z][A-Za-z0-9]*ApiRuntime)\(/u.exec(
    runtimeInitializer ?? '',
  )?.groups?.factory;
  const factoryExpression =
    factory === undefined
      ? undefined
      : assignedExpressionRange(
          source,
          new RegExp(`export const ${escapeRegExp(factory)}\\s*=\\s*`, 'u'),
        );
  return factoryExpression === undefined ||
    runtimeInitializer === undefined ||
    !isWholeCallExpression(
      runtimeInitializer,
      new RegExp(`^${escapeRegExp(factory ?? '')}\\(`, 'u'),
    )
    ? undefined
    : factoryExpression;
};

const effectBffDefinition = (source: string): string | undefined => {
  const exported = defaultExportExpression(source);
  if (exported === undefined) {
    return undefined;
  }
  if (/^(?:defineEffectBff|assembleEffectBffRuntime)\(/u.test(exported)) {
    return isWholeCallExpression(exported, /^(?:defineEffectBff|assembleEffectBffRuntime)\(/u)
      ? objectArgument(exported, /^(?:defineEffectBff|assembleEffectBffRuntime)\(/u)
      : undefined;
  }
  if (!/^[A-Za-z][A-Za-z0-9]*$/u.test(exported)) {
    return undefined;
  }
  const factory = exportedRuntimeFactory(source);
  return factory === undefined ? undefined : returnedEffectBffDefinition(factory.value);
};

const hasExactValueImport = (source: string, value: string, modulePath: string): boolean => {
  const code = maskComments(source);
  const imports = [
    ...source.matchAll(
      new RegExp(
        `^\\s*import\\s*\\{(?<values>[^}]*)\\}\\s*from\\s*'${escapeRegExp(modulePath)}';`,
        'gmu',
      ),
    ),
  ].filter(
    (candidate) => candidate.index !== undefined && isTopLevelCodePosition(source, candidate.index),
  );
  const importedValues = imports.flatMap((candidate) =>
    (candidate.groups?.values ?? '').split(',').map((entry) => entry.trim()),
  );
  return (
    imports.length === 1 &&
    importedValues.filter((candidate) => candidate === value).length === 1 &&
    !matches(
      code,
      new RegExp(`\\b(?:class|const|function|let|var)\\s+${escapeRegExp(value)}\\b`, 'u'),
    )
  );
};

const slotIsMountedByAssembler = (
  source: string,
  runtimeSource: string,
  layerName: string,
  expectedApi: string,
): boolean => {
  const definition = effectBffDefinition(source);
  if (
    definition === undefined ||
    definition.includes('...') ||
    objectPropertyValue(definition, 'api') !== expectedApi ||
    !hasExactlyOne(maskNonCode(source), /\bassembleEffectBffRuntime\(/gu) ||
    !hasExactValueImport(
      source,
      'assembleEffectBffRuntime',
      '@app/shared-contracts/server/effect-bff-runtime',
    )
  ) {
    return false;
  }
  const handlers = objectPropertyValue(definition, 'handlers');
  if (handlers === layerName) {
    return true;
  }
  if (handlers === undefined || !/^[A-Za-z][A-Za-z0-9]*$/u.test(handlers)) {
    return false;
  }
  const resolved = assignedExpression(
    runtimeSource,
    new RegExp(`const ${escapeRegExp(handlers)}\\s*=\\s*`, 'u'),
  );
  return (
    resolved !== undefined &&
    isWholeCallExpression(resolved, new RegExp(`^${escapeRegExp(layerName)}\\.pipe\\(`, 'u'))
  );
};

// eslint-disable-next-line complexity -- Mount validation traces the generated slot through its aggregate, runtime, and exported BFF root.
const slotIsInsideMountedLayer = (
  source: string,
  startMarker: string,
  endMarker: string,
  expectedApi: string,
): boolean => {
  const code = maskComments(source);
  const slot = generatedSlotRange(source, startMarker, endMarker);
  if (slot === undefined) {
    return false;
  }
  const declarations = [
    ...code
      .slice(0, slot.markerStart)
      .matchAll(
        /(?:export\s+)?const\s+(?<name>[A-Za-z][A-Za-z0-9]*)\s*=\s*(?:GovernedReadLayer|Layer)\.mergeAll\(/gu,
      ),
  ];
  let declaration: RegExpExecArray | undefined;
  for (const candidate of declarations) {
    if (
      candidate.index !== undefined &&
      codeDepthAtPosition(source, candidate.index) === slot.depth - 1
    ) {
      declaration = candidate;
    }
  }
  const layerName = declaration?.groups?.name;
  if (declaration?.index === undefined || layerName === undefined) {
    return false;
  }
  const layerStart = declaration.index;
  const opening = code.indexOf('(', layerStart);
  const closing = matchingDelimiterEnd(code, opening, '(', ')');
  if (closing === undefined || closing <= slot.markerEnd) {
    return false;
  }
  const runtimeSource = code.slice(closing + 1);
  if (slotIsMountedByAssembler(source, runtimeSource, layerName, expectedApi)) {
    return true;
  }
  const runtimeDeclaration =
    /const\s+(?<name>[A-Za-z][A-Za-z0-9]*)\s*=\s*HttpApiBuilder\.layer\(/u.exec(runtimeSource);
  const runtimeName = runtimeDeclaration?.groups?.name;
  const runtimeStart =
    runtimeDeclaration?.index === undefined ? -1 : closing + 1 + runtimeDeclaration.index;
  const runtimeEnd =
    runtimeStart === -1 ? -1 : code.indexOf('satisfies EffectRuntimeLayer', runtimeStart);
  const runtimeSlice =
    runtimeStart === -1 || runtimeEnd === -1 ? '' : code.slice(runtimeStart, runtimeEnd);
  const definition = effectBffDefinition(source);
  return (
    runtimeName !== undefined &&
    runtimeStart !== -1 &&
    runtimeEnd > runtimeStart &&
    callArgument(runtimeSlice, /HttpApiBuilder\.layer\(/u) === expectedApi &&
    matches(
      runtimeSlice,
      new RegExp(`(?:GovernedReadLayer|Layer)\\.provide\\(${escapeRegExp(layerName)}\\)`, 'u'),
    ) &&
    hasExactlyOne(code, /\bdefineEffectBff\(/gu) &&
    definition !== undefined &&
    !definition.includes('...') &&
    objectPropertyValue(definition, 'api') === expectedApi &&
    hasExactlyOne(
      definition,
      runtimeName === 'layer'
        ? /(?:\{|,)\s*layer(?:\s*:\s*layer)?\s*(?:,|\})/gu
        : new RegExp(`(?:\\{|,)\\s*layer\\s*:\\s*${escapeRegExp(runtimeName)}\\s*(?:,|\\})`, 'gu'),
    )
  );
};

const governedSharedApiRoot = (source: string): SourceRange | undefined => {
  const governed = assignedExpressionRange(source, /export const governedHttpApi\s*=\s*/u);
  if (governed === undefined) {
    return undefined;
  }
  let apiRoot: SourceRange | undefined;
  if (governed.value.startsWith(HTTP_API_MAKE)) {
    apiRoot = governed;
  } else if (/^[A-Za-z][A-Za-z0-9]*$/u.test(governed.value)) {
    apiRoot = assignedExpressionRange(
      source,
      new RegExp(`export const ${escapeRegExp(governed.value)}\\s*=\\s*`, 'u'),
    );
  }
  const slot = generatedSlotRange(
    source,
    '// <generated-governed-http-api-additions>',
    '// </generated-governed-http-api-additions>',
  );
  if (
    apiRoot === undefined ||
    !apiRoot.value.startsWith(HTTP_API_MAKE) ||
    slot === undefined ||
    slot.markerStart <= apiRoot.start ||
    slot.markerEnd >= apiRoot.end
  ) {
    return undefined;
  }
  const governedDeclaration = maskNonCode(source, true).indexOf('export const governedHttpApi');
  const aliasedStatementEnd =
    governed.value.startsWith(HTTP_API_MAKE) || governedDeclaration === -1
      ? -1
      : source.lastIndexOf(';', governedDeclaration);
  const effectiveRoot =
    aliasedStatementEnd > apiRoot.start
      ? {
          end: aliasedStatementEnd,
          start: apiRoot.start,
          value: source.slice(apiRoot.start, aliasedStatementEnd).trimEnd(),
        }
      : apiRoot;
  if (slot.markerEnd >= effectiveRoot.end) {
    return undefined;
  }
  const additions = maskNonCode(source.slice(slot.bodyStart, slot.bodyEnd), true).trim();
  const trailing = source
    .slice(slot.markerEnd + '// </generated-governed-http-api-additions>'.length, effectiveRoot.end)
    .trim();
  return /^(?:\.addHttpApi\([A-Za-z][A-Za-z0-9]*\)\s*)*$/u.test(additions) &&
    (trailing === '' || trailing === '.pipe(identity)')
    ? effectiveRoot
    : undefined;
};

const hasGovernedSharedApiRoot = (source: string): boolean =>
  governedSharedApiRoot(source) !== undefined;

const hasInjectedGovernedReadRuntime = (source: string): boolean => {
  const factory = exportedRuntimeFactory(source);
  if (factory === undefined) {
    return false;
  }
  const code = maskNonCode(factory.value);
  // The generated binding may be the first explicitly typed injection in an owner runtime
  // factory. Its caller and mounted layers are checked separately, and TS checks the layer type.
  const injection =
    /const\s+\[\s*governedReadRuntimeLive,\s*[A-Za-z0-9_,\s]+\]\s*=\s*(?<args>[A-Za-z][A-Za-z0-9]*)\s*;/u.exec(
      code,
    );
  const args = injection?.groups?.args;
  if (
    args === undefined ||
    injection?.index === undefined ||
    codeDepthAtPosition(factory.value, injection.index) !== 1
  ) {
    return false;
  }
  const signature = new RegExp(
    `\\.\\.\\.${escapeRegExp(args)}:\\s*(?<type>[A-Za-z][A-Za-z0-9]*)`,
    'u',
  ).exec(code);
  const type = signature?.groups?.type;
  return (
    type !== undefined &&
    new RegExp(
      `type ${escapeRegExp(type)}\\s*=\\s*readonly\\s*\\[\\s*readRuntime:\\s*Layer\\.Layer<ReadRuntime\\s*[,>]`,
      'u',
    ).test(maskNonCode(source)) &&
    effectBffDefinition(source) !== undefined
  );
};

const hasGovernedHandlerRoot = (source: string): boolean => {
  if (hasInjectedGovernedReadRuntime(source)) {
    return true;
  }
  const runtime = assignedExpression(source, /const governedReadRuntimeLive\s*=\s*/u);
  if (
    runtime === undefined ||
    (!/^readRuntimeLive$/u.test(runtime) && !runtime.startsWith('GovernedReadRuntimeLive.pipe('))
  ) {
    return false;
  }
  if (runtime === 'readRuntimeLive') {
    const ownerRuntime = assignedExpression(source, /const readRuntimeLive\s*=\s*/u);
    if (
      ownerRuntime === undefined ||
      !isWholeCallExpression(ownerRuntime, /^ReadRuntimeLive\.pipe\(/u) ||
      callArgument(ownerRuntime, /^ReadRuntimeLive\.pipe\(/u) !==
        'Layer.provide(readRuntimeDependenciesLive)'
    ) {
      return false;
    }
  } else if (
    !isWholeCallExpression(runtime, /^GovernedReadRuntimeLive\.pipe\(/u) ||
    callArgument(runtime, /^GovernedReadRuntimeLive\.pipe\(/u) !==
      'GovernedReadLayer.provide(governedReadRuntimeDependenciesLive)'
  ) {
    return false;
  }
  return effectBffDefinition(source) !== undefined;
};

// eslint-disable-next-line complexity -- Composition validation binds every generated slot to the exported Effect BFF root.
export const hasValidGovernedHttpCompositionRoot = (
  sharedApi: string,
  handlerRoot: string,
): boolean => {
  const sharedRoot = governedSharedApiRoot(sharedApi);
  const governed = assignedExpression(sharedApi, /export const governedHttpApi\s*=\s*/u);
  const expectedApi = governed?.startsWith(HTTP_API_MAKE) === true ? 'governedHttpApi' : governed;
  const sharedImports = generatedSlotRange(
    sharedApi,
    '// <generated-governed-http-api-imports>',
    '// </generated-governed-http-api-imports>',
  );
  const handlerImports = generatedSlotRange(
    handlerRoot,
    '// <generated-governed-http-handler-imports>',
    '// </generated-governed-http-handler-imports>',
  );
  const supportImportStart = '// <generated-governed-http-handler-support-imports>';
  const supportLayerStart = '// <generated-governed-http-handler-support-layers>';
  const supportImports = handlerRoot.includes(supportImportStart)
    ? generatedSlotRange(
        handlerRoot,
        supportImportStart,
        '// </generated-governed-http-handler-support-imports>',
      )
    : null;
  const supportLayers = handlerRoot.includes(supportLayerStart)
    ? generatedSlotRange(
        handlerRoot,
        supportLayerStart,
        '// </generated-governed-http-handler-support-layers>',
      )
    : null;
  const generatedHandlers = assignedExpressionRange(
    handlerRoot,
    /export const governedReadApiHandlersLive\s*=\s*/u,
  );
  const mounted =
    expectedApi !== undefined &&
    slotIsInsideMountedLayer(
      handlerRoot,
      GOVERNED_HANDLER_LAYER_SLOT_START,
      GOVERNED_HANDLER_LAYER_SLOT_END,
      expectedApi,
    );
  return (
    sharedRoot !== undefined &&
    expectedApi !== undefined &&
    hasGovernedHandlerRoot(handlerRoot) &&
    sharedImports?.depth === 0 &&
    handlerImports?.depth === 0 &&
    (supportImports === null || supportImports?.depth === 0) &&
    (supportLayers === null ||
      (generatedHandlers !== undefined &&
        supportLayers !== undefined &&
        supportLayers.markerStart > generatedHandlers.start &&
        supportLayers.markerEnd < generatedHandlers.end)) &&
    mounted
  );
};

const governedReadContribution = (
  contractStem: string,
  source: string,
): GovernedReadContribution | undefined => {
  if (source.startsWith(MODULE_API_HEADER)) {
    return { contractStem, kind: MODULE_API_KIND, name: contractStem };
  }
  const candidateKind = /^\/\/ @ontos-contribution-kind (?<kind>report|search-provider)$/mu.exec(
    source,
  )?.groups?.kind;
  if (!source.startsWith(GOVERNED_CONTRIBUTION_HEADER) || !isGovernedReadKind(candidateKind)) {
    return undefined;
  }
  const kind = candidateKind;
  const suffix = kind === REPORT_KIND ? '-report' : '-search';
  if (!contractStem.endsWith(suffix)) {
    return undefined;
  }
  return {
    contractStem,
    kind,
    name: contractStem.slice(0, -suffix.length),
  };
};

const generatedHeader = (kind: GovernedReadKind): string =>
  kind === MODULE_API_KIND
    ? MODULE_API_HEADER
    : `${GOVERNED_CONTRIBUTION_HEADER}// @ontos-contribution-kind ${kind}\n`;

const contributionRole = (kind: GovernedReadKind): string => {
  if (kind === MODULE_API_KIND) {
    return 'api';
  }
  return kind === REPORT_KIND ? 'report' : 'search';
};

const contributionTypeSuffix = (kind: GovernedReadKind): string => {
  if (kind === MODULE_API_KIND) {
    return '';
  }
  return kind === REPORT_KIND ? 'Report' : 'Search';
};

const contributionGroup = (kind: GovernedReadKind, name: string): string =>
  `${toCamelCase(name)}${contributionTypeSuffix(kind)}`;

const contributionApiValue = (kind: GovernedReadKind, name: string): string =>
  `${toPascalCase(name)}${contributionTypeSuffix(kind)}Api`;

const contributionReadDirectory = (kind: GovernedReadKind): string => {
  if (kind === MODULE_API_KIND) {
    return 'api';
  }
  return kind === REPORT_KIND ? 'reports' : 'search';
};

// eslint-disable-next-line complexity -- Read validation binds the complete generated descriptor and owner identity.
const hasReadContract = (
  source: string,
  contribution: GovernedReadContribution,
  moduleId: string,
): boolean => {
  const camel = toCamelCase(contribution.name);
  const type = toPascalCase(contribution.name);
  const escapedCamel = escapeRegExp(camel);
  const role = contributionRole(contribution.kind);
  const allowedAccessKinds =
    contribution.kind === MODULE_API_KIND
      ? new Set(["'detail'", "'list'"])
      : new Set([contribution.kind === REPORT_KIND ? "'report'" : "'search'"]);
  const contributionKey = `${moduleId}.${role}.${contribution.name}`;
  const entrypointExpression = assignedExpression(
    source,
    new RegExp(`export const ${escapedCamel}Entrypoint\\s*=\\s*`, 'u'),
  );
  const readExpression = assignedExpression(
    source,
    new RegExp(`export const ${escapedCamel}Read\\s*=\\s*`, 'u'),
  );
  const entrypoint =
    entrypointExpression === undefined
      ? undefined
      : objectArgument(entrypointExpression, /^defineTenantModuleEntrypoint\(/u);
  const read =
    readExpression === undefined ? undefined : objectArgument(readExpression, /^defineRead\(/u);
  const inputSchema = `${type}${contribution.kind === MODULE_API_KIND ? '' : 'Provider'}RequestSchema`;
  const resultSchema = `${type}${contribution.kind === MODULE_API_KIND ? '' : 'Provider'}ResponseSchema`;
  const handler = callArgument(readExpression ?? '', /^defineRead\(/u, 1);
  const services = callArgument(readExpression ?? '', /^defineRead\(/u, 2);
  const permissionTarget = callArgument(readExpression ?? '', /^defineRead\(/u, 3);
  const resultTargets = callArgument(readExpression ?? '', /^defineRead\(/u, 4);
  const entrypointAccess = objectProperty(entrypoint ?? '', 'access');
  const policies = objectProperty(read ?? '', 'policies');
  return (
    entrypoint !== undefined &&
    read !== undefined &&
    entrypointExpression !== undefined &&
    readExpression !== undefined &&
    isWholeCallExpression(entrypointExpression, /^defineTenantModuleEntrypoint\(/u) &&
    isWholeCallExpression(readExpression, /^defineRead\(/u) &&
    !entrypoint.includes('...') &&
    !read.includes('...') &&
    hasExactValueImport(source, 'defineRead', '@app/core-runtime') &&
    hasExactValueImport(source, 'defineTenantModuleEntrypoint', '@app/core-runtime') &&
    (entrypointAccess === "'read'" || entrypointAccess === "'historical_read'") &&
    objectProperty(entrypoint, 'entrypointKey') === `'${contributionKey}'` &&
    objectProperty(entrypoint, 'moduleKey') === `'${moduleId}'` &&
    objectProperty(entrypoint, 'role') === `'${role}'` &&
    allowedAccessKinds.has(objectProperty(read, 'accessKind') ?? '') &&
    objectProperty(read, 'entrypoint') === `${camel}Entrypoint` &&
    objectProperty(read, 'inputSchema') === inputSchema &&
    objectProperty(read, 'resultSchema') === resultSchema &&
    matches(objectProperty(read, 'legalEntityScope'), /^'(?:required|optional|forbidden)'$/u) &&
    objectProperty(read, 'owningModuleKey') === `'${moduleId}'` &&
    matches(
      objectProperty(read, 'permissionTarget'),
      /^'(?:legal_entity|module|resource|tenant)'$/u,
    ) &&
    policies !== undefined &&
    policies.startsWith('[') &&
    matchingDelimiterEnd(policies, 0, '[', ']') === policies.length - 1 &&
    objectProperty(read, 'readKey') === `'${contributionKey}'` &&
    isReadHandlerCallback(handler, source) &&
    isExecutableCallback(services, source) &&
    isExecutableCallback(permissionTarget, source) &&
    (contribution.kind !== SEARCH_PROVIDER_KIND || isExecutableCallback(resultTargets, source))
  );
};

// eslint-disable-next-line complexity -- Client validation supports both generated clients and the migrated owner transport boundary.
const hasClientContract = (
  source: string,
  contribution: GovernedReadContribution,
  escapedGroup: string,
  apiValue: string,
): boolean => {
  const camel = toCamelCase(contribution.name);
  const type = toPascalCase(contribution.name);
  const authorizedName =
    contribution.kind === MODULE_API_KIND
      ? `execute${type}WithAuthorization`
      : `load${type}ClientWithAuthorization`;
  const publicName = contribution.kind === MODULE_API_KIND ? `execute${type}` : `load${type}Client`;
  const authorized = assignedExpression(
    source,
    new RegExp(`export const ${authorizedName}\\s*=\\s*`, 'u'),
  );
  const publicClient = assignedExpression(
    source,
    new RegExp(`export const ${publicName}\\s*=\\s*`, 'u'),
  );
  const authorizedCode = authorized === undefined ? undefined : maskNonCode(authorized, true);
  const publicCode = publicClient === undefined ? undefined : maskNonCode(publicClient, true);
  const publicResultCode =
    publicClient === undefined
      ? undefined
      : maskNonCode(callbackReturnedExpression(publicClient) ?? '', true);
  const requestAuthentication = /\b(?<name>authenticate[A-Z][A-Za-z]+HttpRequest)\(/u.exec(
    authorizedCode ?? '',
  )?.groups?.name;
  const correlationHeader =
    requestAuthentication === undefined
      ? undefined
      : callArgument(
          authorized ?? '',
          new RegExp(`\\b${escapeRegExp(requestAuthentication)}\\(`, 'u'),
          3,
        );
  const authenticatedCorrelation =
    requestAuthentication !== undefined &&
    callArgument(
      authorized ?? '',
      new RegExp(`\\b${escapeRegExp(requestAuthentication)}\\(`, 'u'),
      2,
    ) === 'requestCorrelation' &&
    (correlationHeader === undefined ||
      correlationHeader === '' ||
      ["'x-correlation-id'", '"x-correlation-id"'].includes(correlationHeader));
  const generatedClient = assignedExpression(
    source,
    new RegExp(`const ${escapeRegExp(camel)}Client\\s*=\\s*`, 'u'),
  );
  const transformedHeaders =
    generatedClient === undefined
      ? undefined
      : objectArgument(generatedClient, /\bHttpClientRequest\.setHeaders\(/u);
  const executeOptions = objectArgument(
    authorized ?? '',
    new RegExp(`\\bclient\\.${escapedGroup}\\.execute\\(`, 'u'),
  );
  const executeHeaders =
    executeOptions === undefined ? undefined : objectProperty(executeOptions, 'headers');
  const hasGeneratedCorrelation = [transformedHeaders, executeHeaders].some((headers) =>
    (topLevelObjectEntries(headers ?? '') ?? []).some((entry) =>
      /^(?:'x-correlation-id'|"x-correlation-id"):\s*(?:correlationId|'required'|"required")$/u.test(
        entry,
      ),
    ),
  );
  const invokeImport =
    /^\s*import\s*\{(?<values>[^}]*)\}\s*from\s*'(?<module>\.\/[^']+-http-client\.ts)';/gmu;
  const ownerInvoker = [...source.matchAll(invokeImport)]
    .filter(
      (candidate) =>
        candidate.index !== undefined && isTopLevelCodePosition(source, candidate.index),
    )
    .flatMap((candidate) =>
      (candidate.groups?.values ?? '')
        .split(',')
        .map((value) => value.trim())
        .filter((value) => /^invoke[A-Z][A-Za-z]+HttpClient$/u.test(value))
        .map((value) => ({ module: candidate.groups?.module ?? '', value })),
    );
  let transportName: string | undefined;
  let transportBound = false;
  if (generatedClient !== undefined) {
    transportName = `${camel}Client`;
    const options = objectArgument(generatedClient, /^makeEffectHttpApiClient\(/u, 1);
    transportBound =
      hasExactValueImport(
        source,
        'makeEffectHttpApiClient',
        '@modern-js/plugin-bff/effect-client',
      ) &&
      hasExactValueImport(source, apiValue, `../../shared/apis/${contribution.contractStem}.ts`) &&
      isWholeCallExpression(generatedClient, /^makeEffectHttpApiClient\(/u) &&
      callArgument(generatedClient, /^makeEffectHttpApiClient\(/u) === apiValue &&
      options !== undefined &&
      !options.includes('...');
  } else if (ownerInvoker.length === 1) {
    const [{ module, value }] = ownerInvoker;
    const boundary = assignedExpression(source, /const makeEffectHttpApiClientBoundary\s*=\s*/u);
    transportName = boundary === undefined ? value : 'makeEffectHttpApiClientBoundary';
    transportBound =
      module !== undefined &&
      value !== undefined &&
      hasExactValueImport(source, value, module) &&
      (boundary === undefined || boundary === value);
  }
  return (
    authorized !== undefined &&
    publicClient !== undefined &&
    hasExactValueImport(source, 'operationGateway', './action-gateway.ts') &&
    transportBound &&
    transportName !== undefined &&
    matches(authorizedCode, new RegExp(`\\b${escapeRegExp(transportName)}(?:\\.pipe)?\\(`, 'u')) &&
    matches(authorizedCode, new RegExp(`\\bclient\\.${escapedGroup}\\.execute\\(`, 'u')) &&
    (generatedClient === undefined ? authenticatedCorrelation : hasGeneratedCorrelation) &&
    matches(publicCode, /[=]>|function/u) &&
    matches(publicResultCode, /\boperationGateway\.invoke\(/u) &&
    matches(publicResultCode, new RegExp(`\\b${authorizedName}\\(`, 'u'))
  );
};

const hasProblemSet = (source: string, schemaStem: string, contractImport: string): boolean => {
  const expression = assignedExpression(source, /const problems\s*=\s*/u);
  if (
    expression === undefined ||
    !expression.startsWith('{') ||
    matchingDelimiterEnd(expression, 0, '{', '}') !== expression.length - 1 ||
    expression.includes('...') ||
    !hasExactValueImport(source, 'governedReadHttpStatus', '@app/core-runtime/http/governed-read')
  ) {
    return false;
  }
  const constructors = {
    authentication: 'AuthenticationProblemSchema',
    forbidden: 'ForbiddenProblemSchema',
    internal: 'InternalProblemSchema',
    invalid: 'InvalidProblemSchema',
    notFound: 'NotFoundProblemSchema',
    policyConflict: 'PolicyConflictProblemSchema',
    policyIneligible: 'PolicyProblemSchema',
    unavailable: 'UnavailableProblemSchema',
  } as const;
  const entries = topLevelObjectEntries(expression);
  return (
    entries !== undefined &&
    entries.length === Object.keys(constructors).length &&
    Object.entries(constructors).every(([key, suffix]) => {
      const entry = entries.find((candidate) => new RegExp(`^${key}:`, 'u').test(candidate));
      const prefix = new RegExp(
        `^${key}:\\s*\\(\\)\\s*=>\\s*(?<factory>${schemaStem}${suffix}\\.make\\([\\s\\S]*)$`,
        'u',
      ).exec(entry ?? '');
      const factory = prefix?.groups?.factory;
      const problem =
        factory === undefined
          ? undefined
          : objectArgument(factory, new RegExp(`^${schemaStem}${suffix}\\.make\\(`, 'u'));
      return (
        factory !== undefined &&
        problem !== undefined &&
        isWholeCallExpression(factory, new RegExp(`^${schemaStem}${suffix}\\.make\\(`, 'u')) &&
        !problem.includes('...') &&
        hasExactValueImport(source, `${schemaStem}${suffix}`, contractImport) &&
        objectProperty(problem, 'status') === `governedReadHttpStatus.${key}` &&
        (key !== 'unavailable' || objectProperty(problem, 'retryable') === 'true')
      );
    })
  );
};

// eslint-disable-next-line complexity -- Server validation binds the exported group, execute handler, helper options, and every trusted import.
const hasServerContract = (
  source: string,
  escapedCamel: string,
  escapedGroup: string,
  readImport: string,
  schemaStem: string,
  contractImport: string,
): boolean => {
  const code = maskComments(source);
  const layerExpression = assignedExpression(
    code,
    new RegExp(`export const ${escapedCamel}ReadApiLive\\s*=\\s*`, 'u'),
  );
  const groupApi =
    layerExpression === undefined
      ? undefined
      : callArgument(layerExpression, /^HttpApiBuilder\.group\(/u);
  const groupName =
    layerExpression === undefined
      ? undefined
      : callArgument(layerExpression, /^HttpApiBuilder\.group\(/u, 1);
  const groupCallback =
    layerExpression === undefined
      ? undefined
      : callArgument(layerExpression, /^HttpApiBuilder\.group\(/u, 2);
  const callbackPrefix = /^\(\s*handlers\s*\)\s*=>\s*/u.exec(groupCallback ?? '');
  const handlerRegistration =
    groupCallback === undefined || callbackPrefix === null
      ? undefined
      : groupCallback.slice(callbackPrefix[0].length).trim();
  const operation =
    handlerRegistration === undefined
      ? undefined
      : callArgument(handlerRegistration, /^handlers\.handle\(/u);
  const handler =
    handlerRegistration === undefined
      ? undefined
      : callArgument(handlerRegistration, /^handlers\.handle\(/u, 1);
  const options =
    handler === undefined ? undefined : objectArgument(handler, /^makeGovernedReadHttpHandler\(/u);
  return (
    groupApi === 'governedHttpApi' &&
    groupName === `'${escapedGroup}'` &&
    layerExpression !== undefined &&
    isWholeCallExpression(layerExpression, /^HttpApiBuilder\.group\(/u) &&
    handlerRegistration !== undefined &&
    isWholeCallExpression(handlerRegistration, /^handlers\.handle\(/u) &&
    operation === "'execute'" &&
    handler !== undefined &&
    isWholeCallExpression(handler, /^makeGovernedReadHttpHandler\(/u) &&
    options !== undefined &&
    !options.includes('...') &&
    hasExactValueImport(
      source,
      'makeGovernedReadHttpHandler',
      '@app/core-runtime/http/governed-read',
    ) &&
    hasExactValueImport(source, 'authenticateOperationPrincipal', './auth/action-principal.ts') &&
    hasExactValueImport(source, 'governedHttpApi', '../shared/api.ts') &&
    hasExactValueImport(source, 'HttpApiBuilder', '@modern-js/plugin-bff/effect-edge') &&
    hasExactValueImport(source, `${escapedCamel}Read`, readImport) &&
    hasProblemSet(source, schemaStem, contractImport) &&
    hasExactlyOne(code, /HttpApiBuilder\.group\(/gu) &&
    hasExactlyOne(code, /makeGovernedReadHttpHandler\(/gu) &&
    hasExactlyOne(groupCallback, /handlers\.handle\(/gu) &&
    hasExactlyOne(options, /\bauthenticatePrincipal:\s*authenticateOperationPrincipal\b/gu) &&
    hasExactlyOne(options, /(?:\{|,)\s*problems\s*(?::\s*problems)?\s*(?:,|\})/gu) &&
    hasExactlyOne(options, new RegExp(`\\bregistration:\\s*${escapedCamel}Read\\b`, 'gu'))
  );
};

const hasProblemSchemaContract = (
  source: string,
  schema: string,
  status: number,
  retryable: boolean,
): boolean => {
  const expression = assignedExpression(
    source,
    new RegExp(`export const ${escapeRegExp(schema)}\\s*=\\s*`, 'u'),
  );
  const factory = retryable ? 'makeRetryableProblemDetailsSchema' : 'makeProblemDetailsSchema';
  const call = new RegExp(`^${factory}\\(`, 'u');
  return (
    expression !== undefined &&
    hasExactValueImport(source, factory, '@app/shared-contracts/problem-details') &&
    isWholeCallExpression(expression, call) &&
    callArgument(expression, call) === `'${schema.replace(/Schema$/u, '')}'` &&
    callArgument(expression, call, 1) === String(status) &&
    ['', undefined].includes(callArgument(expression, call, 2)) &&
    callArgument(expression, call, 3) === undefined
  );
};

// eslint-disable-next-line complexity -- Contract validation follows the complete exported API/group/endpoint chain and every governed schema binding.
const hasHttpContract = (
  source: string,
  apiValue: string,
  group: string,
  schemaStem: string,
  endpointPath: string,
): boolean => {
  const escapedApiValue = escapeRegExp(apiValue);
  const expression = assignedExpression(
    source,
    new RegExp(`export const ${escapedApiValue}\\s*=\\s*`, 'u'),
  );
  const apiMakeOpening = expression?.indexOf('(') ?? -1;
  const apiMakeClosing =
    expression === undefined || apiMakeOpening === -1
      ? undefined
      : matchingDelimiterEnd(expression, apiMakeOpening, '(', ')');
  const apiAddition =
    expression === undefined || apiMakeClosing === undefined
      ? undefined
      : expression.slice(apiMakeClosing + 1).trim();
  if (
    expression === undefined ||
    !expression.startsWith(HTTP_API_MAKE) ||
    callArgument(expression, /^HttpApi\.make\(/u) !== `'${apiValue}'` ||
    apiAddition === undefined ||
    !apiAddition.startsWith('.add(') ||
    !isWholeCallExpression(apiAddition, /^\.add\(/u)
  ) {
    return false;
  }
  const groupExpression = callArgument(apiAddition, /^\.add\(/u);
  const groupMakeOpening = groupExpression?.indexOf('(') ?? -1;
  const groupMakeClosing =
    groupExpression === undefined || groupMakeOpening === -1
      ? undefined
      : matchingDelimiterEnd(groupExpression, groupMakeOpening, '(', ')');
  const groupAddition =
    groupExpression === undefined || groupMakeClosing === undefined
      ? undefined
      : groupExpression.slice(groupMakeClosing + 1).trim();
  if (
    groupExpression === undefined ||
    !groupExpression.startsWith('HttpApiGroup.make(') ||
    callArgument(groupExpression, /^HttpApiGroup\.make\(/u) !== `'${group}'` ||
    groupAddition === undefined ||
    !groupAddition.startsWith('.add(') ||
    !isWholeCallExpression(groupAddition, /^\.add\(/u)
  ) {
    return false;
  }
  const endpointExpression = callArgument(groupAddition, /^\.add\(/u);
  if (
    endpointExpression === undefined ||
    !isWholeCallExpression(endpointExpression, /^HttpApiEndpoint\.post\(/u) ||
    callArgument(endpointExpression, /^HttpApiEndpoint\.post\(/u) !== "'execute'" ||
    callArgument(endpointExpression, /^HttpApiEndpoint\.post\(/u, 1) !== `'${endpointPath}'`
  ) {
    return false;
  }
  const options = objectArgument(endpointExpression, /^HttpApiEndpoint\.post\(/u, 2);
  const problems = [
    `${schemaStem}InvalidProblemSchema`,
    `${schemaStem}AuthenticationProblemSchema`,
    `${schemaStem}ForbiddenProblemSchema`,
    `${schemaStem}NotFoundProblemSchema`,
    `${schemaStem}PolicyConflictProblemSchema`,
    `${schemaStem}PolicyProblemSchema`,
    `${schemaStem}UnavailableProblemSchema`,
    `${schemaStem}InternalProblemSchema`,
  ];
  const problemStatuses = [400, 401, 403, 404, 409, 422, 503, 500] as const;
  const problemSequence = problems.map(escapeRegExp).join(String.raw`\s*,\s*`);
  const error = objectProperty(options ?? '', 'error');
  return (
    options !== undefined &&
    !options.includes('...') &&
    hasExactValueImport(source, 'HttpApi', HTTP_API_CONTRACT_MODULE) &&
    hasExactValueImport(source, 'HttpApiEndpoint', HTTP_API_CONTRACT_MODULE) &&
    hasExactValueImport(source, 'HttpApiGroup', HTTP_API_CONTRACT_MODULE) &&
    problems.every((problem, index) =>
      hasProblemSchemaContract(source, problem, problemStatuses[index] ?? -1, index === 6),
    ) &&
    objectProperty(options, 'payload') === `${schemaStem}RequestSchema` &&
    objectProperty(options, 'success') === `${schemaStem}ResponseSchema` &&
    matches(error, new RegExp(`^\\[\\s*${problemSequence}\\s*,?\\s*\\]$`, 'u'))
  );
};

const hasManifestContract = (
  manifest: string,
  contribution: GovernedReadContribution,
  moduleId: string,
  escapedContractStem: string,
  escapedApiValue: string,
): boolean => {
  const allOwnerManifestEntries = entriesAcrossSlots(manifest, [
    ['// <generated-module-manifest-apis>', '// </generated-module-manifest-apis>'],
    ['// <generated-module-manifest-reports>', '// </generated-module-manifest-reports>'],
    ['// <generated-module-manifest-search>', '// </generated-module-manifest-search>'],
  ]);
  if (contribution.kind === MODULE_API_KIND) {
    const apiEntries = generatedSlotEntries(
      manifest,
      '// <generated-module-manifest-apis>',
      '// </generated-module-manifest-apis>',
    );
    return (
      slotHasExactlyOneCodeMatch(
        manifest,
        '// <generated-module-manifest-imports>',
        '// </generated-module-manifest-imports>',
        new RegExp(
          `import \\{ ${escapedApiValue} \\} from './shared/apis/${escapedContractStem}\\.ts';`,
          'gu',
        ),
      ) &&
      apiEntries?.filter(
        (entry) =>
          entry ===
          `'${contribution.contractStem}': ${contributionApiValue(contribution.kind, contribution.name)}`,
      ).length === 1 &&
      allOwnerManifestEntries?.filter(
        (entry) =>
          entry ===
          `'${contribution.contractStem}': ${contributionApiValue(contribution.kind, contribution.name)}`,
      ).length === 1
    );
  }
  const role = contributionRole(contribution.kind);
  const manifestSection = contribution.kind === REPORT_KIND ? 'reports' : role;
  const manifestEntries = generatedSlotEntries(
    manifest,
    `// <generated-module-manifest-${manifestSection}>`,
    `// </generated-module-manifest-${manifestSection}>`,
  );
  const shellEntries = generatedSlotEntries(
    manifest,
    `// <generated-module-shell-${manifestSection}>`,
    `// </generated-module-shell-${manifestSection}>`,
  );
  const manifestKey = `${moduleId}.${contribution.name}`;
  const entrypointKey = `${moduleId}.${role}.${contribution.name}`;
  const published = manifestEntries?.filter(
    (entry) => objectProperty(entry, 'key') === `'${manifestKey}'`,
  );
  const allPublished = allOwnerManifestEntries?.filter(
    (entry) => objectProperty(entry, 'key') === `'${manifestKey}'`,
  );
  const shellFunction =
    contribution.kind === REPORT_KIND ? 'reportContribution' : 'searchContribution';
  const shell = shellEntries?.filter((entry) => {
    const shellObject = objectArgument(entry, new RegExp(`^${shellFunction}\\(`, 'u'));
    const entrypoint =
      shellObject === undefined ? undefined : objectProperty(shellObject, 'entrypoint');
    return (
      shellObject !== undefined &&
      isWholeCallExpression(entry, new RegExp(`^${shellFunction}\\(`, 'u')) &&
      objectProperty(shellObject, 'contributionKey') === `'${entrypointKey}'` &&
      entrypoint !== undefined &&
      objectProperty(entrypoint, 'entrypointKey') === `'${entrypointKey}'` &&
      objectProperty(entrypoint, 'role') === `'${role}'`
    );
  });
  return published?.length === 1 && allPublished?.length === 1 && shell?.length === 1;
};

// eslint-disable-next-line complexity -- Publication validation binds API, manifest, registration, and mounted handler category identities.
const hasPublishedContract = (
  sharedApi: string,
  manifest: string,
  registration: string,
  handlerRoot: string,
  contribution: GovernedReadContribution,
  moduleId: string,
): boolean => {
  const governed = assignedExpression(sharedApi, /export const governedHttpApi\s*=\s*/u);
  const expectedApi = governed?.startsWith(HTTP_API_MAKE) === true ? 'governedHttpApi' : governed;
  const apiValue = contributionApiValue(contribution.kind, contribution.name);
  const camel = toCamelCase(contribution.name);
  const serverStem =
    contribution.kind === MODULE_API_KIND ? `${contribution.name}-read` : contribution.contractStem;
  const escapedContractStem = escapeRegExp(contribution.contractStem);
  const escapedApiValue = escapeRegExp(apiValue);
  const escapedCamel = escapeRegExp(camel);
  const escapedName = escapeRegExp(contribution.name);
  const escapedServerStem = escapeRegExp(serverStem);
  let registrationSection = 'search';
  if (contribution.kind === MODULE_API_KIND) {
    registrationSection = 'apis';
  } else if (contribution.kind === REPORT_KIND) {
    registrationSection = 'reports';
  }
  const registrationCategory = contribution.kind === MODULE_API_KIND ? 'api' : registrationSection;
  const registrationEntries = generatedSlotEntries(
    registration,
    `// <generated-module-registration-${registrationSection}>`,
    `// </generated-module-registration-${registrationSection}>`,
  );
  const allRegistrationEntries = entriesAcrossSlots(registration, [
    ['// <generated-module-registration-apis>', '// </generated-module-registration-apis>'],
    ['// <generated-module-registration-reports>', '// </generated-module-registration-reports>'],
    ['// <generated-module-registration-search>', '// </generated-module-registration-search>'],
  ]);
  const handlerLayers = generatedSlotEntries(
    handlerRoot,
    GOVERNED_HANDLER_LAYER_SLOT_START,
    GOVERNED_HANDLER_LAYER_SLOT_END,
  );
  const registrationPattern = new RegExp(
    `^(?:'${escapedName}'|${escapedName})\\s*:\\s*\\(\\s*\\)\\s*=>\\s*import\\(\\s*'./src/api/${escapedContractStem}-client\\.ts'\\s*\\)$`,
    'u',
  );
  const canonicalRegistrationPattern =
    /^(?:'(?<quoted>[a-z][a-z0-9]*(?:-[a-z0-9]+)*)'|(?<bare>[a-z][a-z0-9]*(?:-[a-z0-9]+)*))\s*:\s*\(\s*\)\s*=>\s*import\(\s*'\.\/src\/api\/(?<file>[a-z][a-z0-9]*(?:-[a-z0-9]+)*)-client\.ts'\s*\)$/u;
  const expectedLayer = `${camel}ReadApiLive`;
  const isExpectedHandlerLayer = (entry: string): boolean => {
    if (!isWholeCallExpression(entry, new RegExp(`^${escapedCamel}ReadApiLive\\.pipe\\(`, 'u'))) {
      return false;
    }
    const first = callArgument(entry, new RegExp(`^${escapedCamel}ReadApiLive\\.pipe\\(`, 'u'));
    if (first !== 'GovernedReadLayer.provide(governedReadRuntimeLive)') {
      return false;
    }
    let index = 1;
    let argument = callArgument(
      entry,
      new RegExp(`^${escapedCamel}ReadApiLive\\.pipe\\(`, 'u'),
      index,
    );
    while (argument !== undefined) {
      if (argument === '') {
        return (
          callArgument(
            entry,
            new RegExp(`^${escapedCamel}ReadApiLive\\.pipe\\(`, 'u'),
            index + 1,
          ) === undefined
        );
      }
      if (!/^Layer\.provide\([A-Za-z][A-Za-z0-9]*\)$/u.test(argument)) {
        return false;
      }
      index += 1;
      argument = callArgument(
        entry,
        new RegExp(`^${escapedCamel}ReadApiLive\\.pipe\\(`, 'u'),
        index,
      );
    }
    return entry.startsWith(`${expectedLayer}.pipe(`);
  };
  return (
    expectedApi !== undefined &&
    hasGovernedSharedApiRoot(sharedApi) &&
    hasGovernedHandlerRoot(handlerRoot) &&
    slotHasExactlyOneCodeMatch(
      sharedApi,
      '// <generated-governed-http-api-imports>',
      '// </generated-governed-http-api-imports>',
      new RegExp(
        `import \\{ ${escapedApiValue} \\} from './apis/${escapedContractStem}\\.ts';`,
        'gu',
      ),
    ) &&
    slotHasExactlyOneCodeMatch(
      sharedApi,
      '// <generated-governed-http-api-additions>',
      '// </generated-governed-http-api-additions>',
      new RegExp(`\\.addHttpApi\\(${escapedApiValue}\\)`, 'gu'),
    ) &&
    hasManifestContract(manifest, contribution, moduleId, escapedContractStem, escapedApiValue) &&
    registrationEntries?.filter((entry) => registrationPattern.test(entry)).length === 1 &&
    allRegistrationEntries?.every((entry) => {
      const match = canonicalRegistrationPattern.exec(entry);
      const name = match?.groups?.quoted ?? match?.groups?.bare;
      const file = match?.groups?.file;
      return (
        name !== undefined &&
        file !== undefined &&
        (file === name || file === `${name}-report` || file === `${name}-search`)
      );
    }) === true &&
    allRegistrationEntries?.filter((entry) => objectEntryKey(entry) === contribution.name)
      .length === 1 &&
    slotIsInsideObjectProperty(
      registration,
      registrationCategory,
      `// <generated-module-registration-${registrationSection}>`,
      `// </generated-module-registration-${registrationSection}>`,
    ) &&
    slotHasExactlyOneCodeMatch(
      handlerRoot,
      '// <generated-governed-http-handler-imports>',
      '// </generated-governed-http-handler-imports>',
      new RegExp(
        `import \\{ ${escapedCamel}ReadApiLive \\} from './${escapedServerStem}-server\\.ts';`,
        'gu',
      ),
    ) &&
    handlerLayers?.filter(isExpectedHandlerLayer).length === 1 &&
    slotIsInsideMountedLayer(
      handlerRoot,
      GOVERNED_HANDLER_LAYER_SLOT_START,
      GOVERNED_HANDLER_LAYER_SLOT_END,
      expectedApi,
    )
  );
};

/**
 * Recognizes every complete semantic governed-read seam emitted by the generators.
 * File presence alone is intentionally insufficient: each contract must remain
 * owner-published, privately registered, authenticated, gated, and contract-derived.
 */
// eslint-disable-next-line complexity -- Complete-seam recognition intentionally fails closed across every generated owner boundary.
export const hasCompleteGeneratedModuleApiSeam = (
  sources: ReadonlyMap<string, string>,
  sharedApiFile: string,
): boolean => {
  const verticalPath = sharedApiFile.slice(0, -'/shared/api.ts'.length);
  const sharedApi = sources.get(sharedApiFile);
  const manifest = sources.get(`${verticalPath}/vertical.manifest.ts`);
  const registration = sources.get(`${verticalPath}/vertical.registration.ts`);
  const handlerRoot = sources.get(`${verticalPath}/api/index.ts`);
  const principal = sources.get(`${verticalPath}/api/auth/action-principal.ts`);
  const gateway = sources.get(`${verticalPath}/src/api/action-gateway.ts`);
  const moduleId = /^\/\/ @ontos-module-id (?<moduleId>[^\s]+)$/mu.exec(manifest ?? '')?.groups
    ?.moduleId;
  const principalAuthentication =
    principal === undefined
      ? undefined
      : assignedExpression(principal, /export const authenticateOperationPrincipal\s*=\s*/u);
  const operationGateway =
    gateway === undefined
      ? undefined
      : assignedExpression(gateway, /export const operationGateway\s*=\s*/u);
  if (
    sharedApi === undefined ||
    manifest === undefined ||
    registration === undefined ||
    handlerRoot === undefined ||
    principal === undefined ||
    gateway === undefined ||
    moduleId === undefined ||
    !principal.startsWith('// @generated by OntOS Codesmith MicroVertical Action Boundary v1\n') ||
    principalAuthentication === undefined ||
    !isWholeCallExpression(
      principalAuthentication,
      /^makeMicroverticalHttpPrincipalAuthentication\(/u,
    ) ||
    !hasExactValueImport(
      principal,
      'makeMicroverticalHttpPrincipalAuthentication',
      '@app/core-runtime/http/principal-authentication',
    ) ||
    !gateway.startsWith('// @generated by OntOS Codesmith MicroVertical Action Boundary v1\n') ||
    operationGateway !== 'makeOperationGateway()'
  ) {
    return false;
  }

  const contractPrefix = `${verticalPath}/shared/apis/`;
  const generatedContracts = [...sources.entries()].filter(
    ([candidate, source]) =>
      candidate.startsWith(contractPrefix) &&
      candidate.endsWith('.ts') &&
      !candidate.slice(contractPrefix.length).includes('/') &&
      (source.startsWith(MODULE_API_HEADER) || source.startsWith(GOVERNED_CONTRIBUTION_HEADER)),
  );
  const contributions = generatedContracts.map(
    ([candidate, source]) =>
      [
        candidate,
        source,
        governedReadContribution(path.posix.basename(candidate, '.ts'), source),
      ] as const,
  );
  if (contributions.length === 0 || contributions.some((entry) => entry[2] === undefined)) {
    return false;
  }

  return contributions.every(([, contractSource, contribution]) => {
    if (contribution === undefined) {
      return false;
    }
    const camel = toCamelCase(contribution.name);
    const group = contributionGroup(contribution.kind, contribution.name);
    const apiValue = contributionApiValue(contribution.kind, contribution.name);
    const readDirectory = contributionReadDirectory(contribution.kind);
    const readSuffix = contribution.kind === MODULE_API_KIND ? '.read' : '.provider';
    const serverStem =
      contribution.kind === MODULE_API_KIND
        ? `${contribution.name}-read`
        : contribution.contractStem;
    const readSource = sources.get(
      `${verticalPath}/src/${readDirectory}/${contribution.name}${readSuffix}.ts`,
    );
    const clientSource = sources.get(
      `${verticalPath}/src/api/${contribution.contractStem}-client.ts`,
    );
    const serverSource = sources.get(`${verticalPath}/api/${serverStem}-server.ts`);
    const header = generatedHeader(contribution.kind);
    if (
      readSource === undefined ||
      clientSource === undefined ||
      serverSource === undefined ||
      !contractSource.startsWith(header) ||
      !readSource.startsWith(header) ||
      !clientSource.startsWith(header) ||
      !serverSource.startsWith(header)
    ) {
      return false;
    }

    const escapedCamel = escapeRegExp(camel);
    const escapedGroup = escapeRegExp(group);
    const type = toPascalCase(contribution.name);
    const schemaStem = `${type}${contribution.kind === MODULE_API_KIND ? '' : 'Provider'}`;
    const endpointPath =
      contribution.kind === MODULE_API_KIND
        ? `/reads/${contribution.name}`
        : `/${moduleId}/${contribution.kind === REPORT_KIND ? 'reports' : 'search'}/${contribution.name}`;
    const checks = {
      client: hasClientContract(clientSource, contribution, escapedGroup, apiValue),
      contract: hasHttpContract(contractSource, apiValue, group, schemaStem, endpointPath),
      published: hasPublishedContract(
        sharedApi,
        manifest,
        registration,
        handlerRoot,
        contribution,
        moduleId,
      ),
      read: hasReadContract(readSource, contribution, moduleId),
      server: hasServerContract(
        serverSource,
        escapedCamel,
        escapedGroup,
        `../src/${readDirectory}/${contribution.name}${readSuffix}.ts`,
        schemaStem,
        `../shared/apis/${contribution.contractStem}.ts`,
      ),
    };
    return Object.values(checks).every(Boolean);
  });
};
