// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.customer-context
// @ontos-action-http-slug assign-counterparty-price-group
import { Effect, HttpApiBuilder, Layer } from '@modern-js/bff-effect/effect-edge';
import type { HttpServerRequest } from 'effect/unstable/http';
import { Redacted, Schema } from 'effect';
import { commerceCustomerContextApi } from '../shared/api.ts';
import { assignCounterpartyPriceGroupAction } from '../src/actions/assign-counterparty-price-group.action.ts';
import { bindActionHttpRunner } from './action-http-runner.ts';
import {
  assignCounterpartyPriceGroupActionProblem,
  assignCounterpartyPriceGroupActionSchemaErrorLive,
  mapAssignCounterpartyPriceGroupActionProblem,
} from './assign-counterparty-price-group-action-problems.ts';

const runActionHttp = bindActionHttpRunner({
  authentication: assignCounterpartyPriceGroupActionProblem.authentication,
  unavailable: () => assignCounterpartyPriceGroupActionProblem.unavailable('operation_context_unavailable'),
});

const execute = Effect.fn('AssignCounterpartyPriceGroupActionServer.execute')(
  function* executeAssignCounterpartyPriceGroup(
    payload: typeof assignCounterpartyPriceGroupAction.descriptor.payloadSchema.Encoded,
    idempotencyKey: string | undefined,
    request: HttpServerRequest.HttpServerRequest,
  ) {
    const correlationId = request.headers['x-correlation-id'];
    if (correlationId !== undefined && correlationId.length > 200) {
      return yield* Effect.fail(assignCounterpartyPriceGroupActionProblem.invalid());
    }
    const decoded = yield* Schema.decodeEffect(assignCounterpartyPriceGroupAction.descriptor.payloadSchema)(
      payload,
    ).pipe(Effect.mapError(assignCounterpartyPriceGroupActionProblem.invalid));
    return yield* runActionHttp({
      endpointHeaders: { idempotencyKey, traceId: request.headers['x-trace-id'] },
      internalProblem: assignCounterpartyPriceGroupActionProblem.internal,
      invalidCorrelationProblem: assignCounterpartyPriceGroupActionProblem.invalid,
      mapError: mapAssignCounterpartyPriceGroupActionProblem,
      payload: decoded,
      registration: assignCounterpartyPriceGroupAction,
      requestHeaders: {
        authorization: Redacted.make(request.headers['authorization']),
        'x-correlation-id': correlationId,
      },
    });
  },
);

export const assignCounterpartyPriceGroupActionApiLive = HttpApiBuilder.group(
  commerceCustomerContextApi,
  'assignCounterpartyPriceGroupAction',
  (handlers) =>
    handlers.handle('execute', ({ headers, payload, request }) =>
      execute(payload, headers['idempotency-key'], request),
    ),
).pipe(Layer.provide(assignCounterpartyPriceGroupActionSchemaErrorLive));
