// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.customer-context
// @ontos-action-http-slug create-purchase-proposal-revision
// oxlint-disable sonarjs/function-name -- Effect Match.tags requires owner-declared tag keys; remove-when: sonarjs accepts discriminant-map properties.
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  CreatePurchaseProposalRevisionActionAlreadyCommittedProblemSchema,
  CreatePurchaseProposalRevisionActionAuthenticationProblemSchema,
  CreatePurchaseProposalRevisionActionCommitIndeterminateProblemSchema,
  CreatePurchaseProposalRevisionActionConflictProblemSchema,
  CreatePurchaseProposalRevisionActionForbiddenProblemSchema,
  CreatePurchaseProposalRevisionActionIneligibleProblemSchema,
  CreatePurchaseProposalRevisionActionInternalProblemSchema,
  CreatePurchaseProposalRevisionActionInvalidProblemSchema,
  CreatePurchaseProposalRevisionActionNotFoundProblemSchema,
  CreatePurchaseProposalRevisionActionPreconditionProblemSchema,
  CreatePurchaseProposalRevisionActionSchemaErrorMiddleware,
  CreatePurchaseProposalRevisionActionUnavailableProblemSchema,
} from '../shared/apis/create-purchase-proposal-revision-action.ts';
import type { CreatePurchaseProposalRevisionActionProblem } from '../shared/apis/create-purchase-proposal-revision-action.ts';
import { createPurchaseProposalRevisionAction } from '../src/actions/create-purchase-proposal-revision.action.ts';
/* oxlint-disable anti-slop-effect/no-service-constructor-imports -- These pure helpers construct problem values rather than Effect services. */
import {
  actionProblemStatus as problemStatus,
  makeAuthenticationProblem,
  makeConflictProblem,
  makeForbiddenProblem,
  makeIneligibleProblem,
  makeInternalProblem,
  makeInvalidProblem,
  makeNotFoundProblem,
  makePreconditionProblem,
  makeUnavailableProblem,
  purchasingApprovalRejectedProblemByCode,
} from './action-problem-support.ts';
/* oxlint-enable anti-slop-effect/no-service-constructor-imports */
import type { PurchasingApprovalDomainProblemIdentity } from './action-problem-support.ts';

type DomainError = typeof createPurchaseProposalRevisionAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends CreatePurchaseProposalRevisionActionProblem['_tag']> = Extract<
  CreatePurchaseProposalRevisionActionProblem,
  { readonly _tag: Tag }
>;
export const createPurchaseProposalRevisionActionProblem = {
  authentication: makeAuthenticationProblem<ProblemOf<'CreatePurchaseProposalRevisionActionAuthenticationProblem'>>(
    (input) => CreatePurchaseProposalRevisionActionAuthenticationProblemSchema.make(input),
  ),
  conflict: makeConflictProblem<
    ProblemOf<'CreatePurchaseProposalRevisionActionConflictProblem'>['code'],
    ProblemOf<'CreatePurchaseProposalRevisionActionConflictProblem'>
  >((input) => CreatePurchaseProposalRevisionActionConflictProblemSchema.make(input)),
  forbidden: makeForbiddenProblem<
    ProblemOf<'CreatePurchaseProposalRevisionActionForbiddenProblem'>['code'],
    ProblemOf<'CreatePurchaseProposalRevisionActionForbiddenProblem'>
  >((input) => CreatePurchaseProposalRevisionActionForbiddenProblemSchema.make(input)),
  ineligible: makeIneligibleProblem<
    ProblemOf<'CreatePurchaseProposalRevisionActionIneligibleProblem'>['code'],
    ProblemOf<'CreatePurchaseProposalRevisionActionIneligibleProblem'>
  >((input) => CreatePurchaseProposalRevisionActionIneligibleProblemSchema.make(input)),
  internal: makeInternalProblem<ProblemOf<'CreatePurchaseProposalRevisionActionInternalProblem'>>((input) =>
    CreatePurchaseProposalRevisionActionInternalProblemSchema.make(input),
  ),
  invalid: makeInvalidProblem<ProblemOf<'CreatePurchaseProposalRevisionActionInvalidProblem'>>(
    (input) => CreatePurchaseProposalRevisionActionInvalidProblemSchema.make(input),
    'create-purchase-proposal-revision',
  ),
  notFound: makeNotFoundProblem<
    ProblemOf<'CreatePurchaseProposalRevisionActionNotFoundProblem'>['code'],
    ProblemOf<'CreatePurchaseProposalRevisionActionNotFoundProblem'>
  >((input) => CreatePurchaseProposalRevisionActionNotFoundProblemSchema.make(input)),
  precondition: makePreconditionProblem<ProblemOf<'CreatePurchaseProposalRevisionActionPreconditionProblem'>>((input) =>
    CreatePurchaseProposalRevisionActionPreconditionProblemSchema.make(input),
  ),
  unavailable: makeUnavailableProblem<
    ProblemOf<'CreatePurchaseProposalRevisionActionUnavailableProblem'>['code'],
    ProblemOf<'CreatePurchaseProposalRevisionActionUnavailableProblem'>
  >((input) => CreatePurchaseProposalRevisionActionUnavailableProblemSchema.make(input)),
} as const;

const mapDomainIdentity = (
  identity: PurchasingApprovalDomainProblemIdentity,
): CreatePurchaseProposalRevisionActionProblem =>
  Match.value(identity).pipe(
    Match.when({ kind: 'conflict' as const }, (matched) =>
      createPurchaseProposalRevisionActionProblem.conflict(matched.code),
    ),
    Match.when({ kind: 'forbidden' as const }, (matched) =>
      createPurchaseProposalRevisionActionProblem.forbidden(matched.code),
    ),
    Match.when({ kind: 'ineligible' as const }, (matched) =>
      createPurchaseProposalRevisionActionProblem.ineligible(matched.code),
    ),
    Match.when({ kind: 'notFound' as const }, (matched) =>
      createPurchaseProposalRevisionActionProblem.notFound(matched.code),
    ),
    Match.when({ kind: 'unavailable' as const }, (matched) =>
      createPurchaseProposalRevisionActionProblem.unavailable(matched.code),
    ),
    Match.exhaustive,
  );

const mapDomainProblem = (error: DomainError): CreatePurchaseProposalRevisionActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      PurchasingApprovalRejected: (failure) => mapDomainIdentity(purchasingApprovalRejectedProblemByCode[failure.code]),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): CreatePurchaseProposalRevisionActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        CreatePurchaseProposalRevisionActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: createPurchaseProposalRevisionActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        CreatePurchaseProposalRevisionActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: createPurchaseProposalRevisionActionProblem.internal,
      ActionIdempotencyKeyRequired: createPurchaseProposalRevisionActionProblem.precondition,
      ActionInvocationNotFound: (failure) => createPurchaseProposalRevisionActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) =>
        createPurchaseProposalRevisionActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => createPurchaseProposalRevisionActionProblem.conflict(failure.code),
      ActionPayloadValidationError: createPurchaseProposalRevisionActionProblem.invalid,
      ActionPermissionCheckError: (failure) => createPurchaseProposalRevisionActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => createPurchaseProposalRevisionActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => createPurchaseProposalRevisionActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => createPurchaseProposalRevisionActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => createPurchaseProposalRevisionActionProblem.conflict(failure.code),
      ActionResultValidationError: createPurchaseProposalRevisionActionProblem.internal,
      ActionTransactionError: (failure) => createPurchaseProposalRevisionActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: createPurchaseProposalRevisionActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) =>
        createPurchaseProposalRevisionActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => createPurchaseProposalRevisionActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: createPurchaseProposalRevisionActionProblem.authentication,
      OperationContextDenied: (failure) => createPurchaseProposalRevisionActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => createPurchaseProposalRevisionActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => createPurchaseProposalRevisionActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(createPurchaseProposalRevisionAction.descriptor.domainErrorSchema);
export const mapCreatePurchaseProposalRevisionActionProblem = (
  error: ActionCoreError | DomainError,
): CreatePurchaseProposalRevisionActionProblem =>
  isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error);

export const createPurchaseProposalRevisionActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  CreatePurchaseProposalRevisionActionSchemaErrorMiddleware,
  () => Effect.fail(createPurchaseProposalRevisionActionProblem.invalid()),
);
