// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/plugin-bff/effect-edge';
import { commerceCustomerContextApi } from '../shared/api.ts';
import {
  CustomerCurrencyPreferenceReadAuthenticationProblemSchema,
  CustomerCurrencyPreferenceReadForbiddenProblemSchema,
  CustomerCurrencyPreferenceReadInternalProblemSchema,
  CustomerCurrencyPreferenceReadInvalidProblemSchema,
  CustomerCurrencyPreferenceReadNotFoundProblemSchema,
  CustomerCurrencyPreferenceReadPolicyConflictProblemSchema,
  CustomerCurrencyPreferenceReadPolicyProblemSchema,
  CustomerCurrencyPreferenceReadUnavailableProblemSchema,
} from '../shared/apis/customer-currency-preference-read.ts';
import { customerCurrencyPreferenceReadRead } from '../src/api/customer-currency-preference-read.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: CustomerCurrencyPreferenceReadAuthenticationProblemSchema,
  forbidden: CustomerCurrencyPreferenceReadForbiddenProblemSchema,
  internal: CustomerCurrencyPreferenceReadInternalProblemSchema,
  invalid: CustomerCurrencyPreferenceReadInvalidProblemSchema,
  notFound: CustomerCurrencyPreferenceReadNotFoundProblemSchema,
  policyConflict: CustomerCurrencyPreferenceReadPolicyConflictProblemSchema,
  policyIneligible: CustomerCurrencyPreferenceReadPolicyProblemSchema,
  unavailable: CustomerCurrencyPreferenceReadUnavailableProblemSchema,
});

export const customerCurrencyPreferenceReadReadApiLive = HttpApiBuilder.group(
  commerceCustomerContextApi,
  'customerCurrencyPreferenceRead',
  (handlers) =>
    handlers.handle(
      'execute',
      makeGovernedReadHttpHandler({
        authenticatePrincipal: authenticateOperationPrincipal,
        problems,
        registration: customerCurrencyPreferenceReadRead,
      }),
    ),
);
