// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { commerceCustomerContextApi } from '../shared/api.ts';
import {
  MarketBootstrapResolutionAuthenticationProblemSchema,
  MarketBootstrapResolutionForbiddenProblemSchema,
  MarketBootstrapResolutionInternalProblemSchema,
  MarketBootstrapResolutionInvalidProblemSchema,
  MarketBootstrapResolutionNotFoundProblemSchema,
  MarketBootstrapResolutionPolicyConflictProblemSchema,
  MarketBootstrapResolutionPolicyProblemSchema,
  MarketBootstrapResolutionUnavailableProblemSchema,
} from '../shared/apis/market-bootstrap-resolution.ts';
import { marketBootstrapResolutionRead } from '../src/api/market-bootstrap-resolution.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: MarketBootstrapResolutionAuthenticationProblemSchema,
  forbidden: MarketBootstrapResolutionForbiddenProblemSchema,
  internal: MarketBootstrapResolutionInternalProblemSchema,
  invalid: MarketBootstrapResolutionInvalidProblemSchema,
  notFound: MarketBootstrapResolutionNotFoundProblemSchema,
  policyConflict: MarketBootstrapResolutionPolicyConflictProblemSchema,
  policyIneligible: MarketBootstrapResolutionPolicyProblemSchema,
  unavailable: MarketBootstrapResolutionUnavailableProblemSchema,
});

export const marketBootstrapResolutionReadApiLive = HttpApiBuilder.group(
  commerceCustomerContextApi,
  'marketBootstrapResolution',
  (handlers) =>
    handlers.handle(
      'execute',
      makeGovernedReadHttpHandler({
        authenticatePrincipal: authenticateOperationPrincipal,
        problems,
        registration: marketBootstrapResolutionRead,
      }),
    ),
);
