// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { commerceCustomerContextApi } from '../shared/api.ts';
import {
  ProfileReconciliationReadAuthenticationProblemSchema,
  ProfileReconciliationReadForbiddenProblemSchema,
  ProfileReconciliationReadInternalProblemSchema,
  ProfileReconciliationReadInvalidProblemSchema,
  ProfileReconciliationReadNotFoundProblemSchema,
  ProfileReconciliationReadPolicyConflictProblemSchema,
  ProfileReconciliationReadPolicyProblemSchema,
  ProfileReconciliationReadUnavailableProblemSchema,
} from '../shared/apis/profile-reconciliation-read.ts';
import { profileReconciliationReadRead } from '../src/api/profile-reconciliation-read.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: ProfileReconciliationReadAuthenticationProblemSchema,
  forbidden: ProfileReconciliationReadForbiddenProblemSchema,
  internal: ProfileReconciliationReadInternalProblemSchema,
  invalid: ProfileReconciliationReadInvalidProblemSchema,
  notFound: ProfileReconciliationReadNotFoundProblemSchema,
  policyConflict: ProfileReconciliationReadPolicyConflictProblemSchema,
  policyIneligible: ProfileReconciliationReadPolicyProblemSchema,
  unavailable: ProfileReconciliationReadUnavailableProblemSchema,
});

export const profileReconciliationReadReadApiLive = HttpApiBuilder.group(
  commerceCustomerContextApi,
  'profileReconciliationRead',
  (handlers) =>
    handlers.handle(
      'execute',
      makeGovernedReadHttpHandler({
        authenticatePrincipal: authenticateOperationPrincipal,
        problems,
        registration: profileReconciliationReadRead,
      }),
    ),
);
