// @generated by OntOS Codesmith module-api v1
import { makeGovernedReadHttpHandler } from '@app/core-runtime/http/governed-read';
import { makeGovernedReadProblems } from '@app/shared-contracts/server/effect-bff-runtime';
import { HttpApiBuilder } from '@modern-js/bff-effect/effect-edge';
import { commerceCustomerContextApi } from '../shared/api.ts';
import {
  RetailPortalProfileBindingReadAuthenticationProblemSchema,
  RetailPortalProfileBindingReadForbiddenProblemSchema,
  RetailPortalProfileBindingReadInternalProblemSchema,
  RetailPortalProfileBindingReadInvalidProblemSchema,
  RetailPortalProfileBindingReadNotFoundProblemSchema,
  RetailPortalProfileBindingReadPolicyConflictProblemSchema,
  RetailPortalProfileBindingReadPolicyProblemSchema,
  RetailPortalProfileBindingReadUnavailableProblemSchema,
} from '../shared/apis/retail-portal-profile-binding-read.ts';
import { retailPortalProfileBindingReadRead } from '../src/api/retail-portal-profile-binding-read.read.ts';
import { authenticateOperationPrincipal } from './auth/action-principal.ts';

const problems = makeGovernedReadProblems({
  authentication: RetailPortalProfileBindingReadAuthenticationProblemSchema,
  forbidden: RetailPortalProfileBindingReadForbiddenProblemSchema,
  internal: RetailPortalProfileBindingReadInternalProblemSchema,
  invalid: RetailPortalProfileBindingReadInvalidProblemSchema,
  notFound: RetailPortalProfileBindingReadNotFoundProblemSchema,
  policyConflict: RetailPortalProfileBindingReadPolicyConflictProblemSchema,
  policyIneligible: RetailPortalProfileBindingReadPolicyProblemSchema,
  unavailable: RetailPortalProfileBindingReadUnavailableProblemSchema,
});

export const retailPortalProfileBindingReadReadApiLive = HttpApiBuilder.group(
  commerceCustomerContextApi,
  'retailPortalProfileBindingRead',
  (handlers) =>
    handlers.handle(
      'execute',
      makeGovernedReadHttpHandler({
        authenticatePrincipal: authenticateOperationPrincipal,
        problems,
        registration: retailPortalProfileBindingReadRead,
      }),
    ),
);
