// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.customer-context
// @ontos-action-http-slug revoke-counterparty-access-invitation
// oxlint-disable sonarjs/function-name -- Effect Match.tags requires owner-declared tag keys; remove-when: sonarjs accepts discriminant-map properties.
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/plugin-bff/effect-edge';
import { Match, Schema } from 'effect';
import {
  RevokeCounterpartyAccessInvitationActionAlreadyCommittedProblemSchema,
  RevokeCounterpartyAccessInvitationActionAuthenticationProblemSchema,
  RevokeCounterpartyAccessInvitationActionCommitIndeterminateProblemSchema,
  RevokeCounterpartyAccessInvitationActionConflictProblemSchema,
  RevokeCounterpartyAccessInvitationActionForbiddenProblemSchema,
  RevokeCounterpartyAccessInvitationActionIneligibleProblemSchema,
  RevokeCounterpartyAccessInvitationActionInternalProblemSchema,
  RevokeCounterpartyAccessInvitationActionInvalidProblemSchema,
  RevokeCounterpartyAccessInvitationActionNotFoundProblemSchema,
  RevokeCounterpartyAccessInvitationActionPreconditionProblemSchema,
  RevokeCounterpartyAccessInvitationActionRateLimitedProblemSchema,
  RevokeCounterpartyAccessInvitationActionSchemaErrorMiddleware,
  RevokeCounterpartyAccessInvitationActionUnavailableProblemSchema,
} from '../shared/apis/revoke-counterparty-access-invitation-action.ts';
import type { RevokeCounterpartyAccessInvitationActionProblem } from '../shared/apis/revoke-counterparty-access-invitation-action.ts';
import { revokeCounterpartyAccessInvitationAction } from '../src/actions/revoke-counterparty-access-invitation.action.ts';

type DomainError =
  typeof revokeCounterpartyAccessInvitationAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends RevokeCounterpartyAccessInvitationActionProblem['_tag']> = Extract<
  RevokeCounterpartyAccessInvitationActionProblem,
  { readonly _tag: Tag }
>;
type DomainProblemIdentity =
  | { readonly code: 'invitation_revision_conflict'; readonly kind: 'conflict' }
  | {
      readonly code: 'counterparty_scope_mismatch' | 'principal_scope_mismatch';
      readonly kind: 'forbidden';
    }
  | {
      readonly code:
        | 'administrative_scope_exceeded'
        | 'bootstrap_required'
        | 'grantor_not_authorized'
        | 'invitation_claim_proof_consumed'
        | 'invitation_claim_proof_invalid'
        | 'invitation_claimant_mismatch'
        | 'invitation_expired'
        | 'invitation_invalid'
        | 'inviter_authority_denied'
        | 'permission_not_delegable'
        | 'permission_scope_not_allowed'
        | 'principal_not_eligible'
        | 'reason_required';
      readonly kind: 'ineligible';
    }
  | { readonly code: 'invitation_rate_limited'; readonly kind: 'rateLimited' }
  | { readonly code: 'counterparty_access_unavailable'; readonly kind: 'unavailable' };

const problemStatus = {
  authentication: 401,
  conflict: 409,
  forbidden: 403,
  ineligible: 422,
  internal: 500,
  invalid: 400,
  notFound: 404,
  precondition: 428,
  rateLimited: 429,
  timeout: 504,
  unavailable: 503,
} as const;

const counterpartyAccessContractViolationProblemByCode = {
  administrative_scope_exceeded: { code: 'administrative_scope_exceeded', kind: 'ineligible' },
  bootstrap_required: { code: 'bootstrap_required', kind: 'ineligible' },
  counterparty_scope_mismatch: { code: 'counterparty_scope_mismatch', kind: 'forbidden' },
  grantor_not_authorized: { code: 'grantor_not_authorized', kind: 'ineligible' },
  invitation_claim_proof_consumed: { code: 'invitation_claim_proof_consumed', kind: 'ineligible' },
  invitation_claim_proof_invalid: { code: 'invitation_claim_proof_invalid', kind: 'ineligible' },
  invitation_claimant_mismatch: { code: 'invitation_claimant_mismatch', kind: 'ineligible' },
  invitation_expired: { code: 'invitation_expired', kind: 'ineligible' },
  invitation_invalid: { code: 'invitation_invalid', kind: 'ineligible' },
  invitation_rate_limited: { code: 'invitation_rate_limited', kind: 'rateLimited' },
  invitation_revision_conflict: { code: 'invitation_revision_conflict', kind: 'conflict' },
  inviter_authority_denied: { code: 'inviter_authority_denied', kind: 'ineligible' },
  permission_not_delegable: { code: 'permission_not_delegable', kind: 'ineligible' },
  permission_scope_not_allowed: { code: 'permission_scope_not_allowed', kind: 'ineligible' },
  principal_not_eligible: { code: 'principal_not_eligible', kind: 'ineligible' },
  principal_scope_mismatch: { code: 'principal_scope_mismatch', kind: 'forbidden' },
  reason_required: { code: 'reason_required', kind: 'ineligible' },
} as const satisfies Record<
  Extract<DomainError, { readonly _tag: 'CounterpartyAccessContractViolation' }>['code'],
  DomainProblemIdentity
>;

export const revokeCounterpartyAccessInvitationActionProblem = {
  authentication: (): ProblemOf<'RevokeCounterpartyAccessInvitationActionAuthenticationProblem'> =>
    RevokeCounterpartyAccessInvitationActionAuthenticationProblemSchema.make({
      detail: 'A valid audience-scoped Bearer assertion is required.',
      status: problemStatus.authentication,
      title: 'Authentication required',
      type: 'https://ontos.dev/problems/operation-authentication-required',
    }),
  conflict: (
    code: ProblemOf<'RevokeCounterpartyAccessInvitationActionConflictProblem'>['code'],
  ): ProblemOf<'RevokeCounterpartyAccessInvitationActionConflictProblem'> =>
    RevokeCounterpartyAccessInvitationActionConflictProblemSchema.make({
      code,
      detail: 'The Action conflicts with current state.',
      status: problemStatus.conflict,
      title: 'Action conflict',
      type: 'https://ontos.dev/problems/action-conflict',
    }),
  forbidden: (
    code: ProblemOf<'RevokeCounterpartyAccessInvitationActionForbiddenProblem'>['code'],
  ): ProblemOf<'RevokeCounterpartyAccessInvitationActionForbiddenProblem'> =>
    RevokeCounterpartyAccessInvitationActionForbiddenProblemSchema.make({
      code,
      detail: 'The principal is not permitted to perform this Action.',
      status: problemStatus.forbidden,
      title: 'Action forbidden',
      type: 'https://ontos.dev/problems/action-forbidden',
    }),
  ineligible: (
    code: ProblemOf<'RevokeCounterpartyAccessInvitationActionIneligibleProblem'>['code'],
  ): ProblemOf<'RevokeCounterpartyAccessInvitationActionIneligibleProblem'> =>
    RevokeCounterpartyAccessInvitationActionIneligibleProblemSchema.make({
      code,
      detail: 'The request is not eligible for this Action.',
      status: problemStatus.ineligible,
      title: 'Action ineligible',
      type: 'https://ontos.dev/problems/action-ineligible',
    }),
  internal: (): ProblemOf<'RevokeCounterpartyAccessInvitationActionInternalProblem'> =>
    RevokeCounterpartyAccessInvitationActionInternalProblemSchema.make({
      detail: 'The Action could not be completed.',
      status: problemStatus.internal,
      title: 'Action failed',
      type: 'https://ontos.dev/problems/action-failed',
    }),
  invalid: (): ProblemOf<'RevokeCounterpartyAccessInvitationActionInvalidProblem'> =>
    RevokeCounterpartyAccessInvitationActionInvalidProblemSchema.make({
      detail: 'The revoke-counterparty-access-invitation Action request is invalid.',
      status: problemStatus.invalid,
      title: 'Invalid Action request',
      type: 'https://ontos.dev/problems/action-invalid',
    }),
  notFound: (
    code: ProblemOf<'RevokeCounterpartyAccessInvitationActionNotFoundProblem'>['code'],
  ): ProblemOf<'RevokeCounterpartyAccessInvitationActionNotFoundProblem'> =>
    RevokeCounterpartyAccessInvitationActionNotFoundProblemSchema.make({
      code,
      detail: 'The requested resource was not found.',
      status: problemStatus.notFound,
      title: 'Resource not found',
      type: 'https://ontos.dev/problems/action-resource-not-found',
    }),
  precondition: (): ProblemOf<'RevokeCounterpartyAccessInvitationActionPreconditionProblem'> =>
    RevokeCounterpartyAccessInvitationActionPreconditionProblemSchema.make({
      detail: 'An Idempotency-Key header is required.',
      status: problemStatus.precondition,
      title: 'Idempotency key required',
      type: 'https://ontos.dev/problems/idempotency-key-required',
    }),
  rateLimited: (
    code: Extract<
      ProblemOf<'RevokeCounterpartyAccessInvitationActionRateLimitedProblem'>,
      { readonly code: string }
    >['code'],
  ): ProblemOf<'RevokeCounterpartyAccessInvitationActionRateLimitedProblem'> =>
    RevokeCounterpartyAccessInvitationActionRateLimitedProblemSchema.make({
      code,
      detail: 'The Action rate limit has been exceeded.',
      status: problemStatus.rateLimited,
      title: 'Action rate limited',
      type: 'https://ontos.dev/problems/action-rate-limited',
    }),
  unavailable: (
    code: ProblemOf<'RevokeCounterpartyAccessInvitationActionUnavailableProblem'>['code'],
  ): ProblemOf<'RevokeCounterpartyAccessInvitationActionUnavailableProblem'> =>
    RevokeCounterpartyAccessInvitationActionUnavailableProblemSchema.make({
      code,
      detail: 'The Action capability is temporarily unavailable.',
      retryable: true,
      status: problemStatus.unavailable,
      title: 'Action unavailable',
      type: 'https://ontos.dev/problems/action-unavailable',
    }),
} as const;

const mapDomainIdentity = (
  identity: DomainProblemIdentity,
): RevokeCounterpartyAccessInvitationActionProblem =>
  Match.value(identity).pipe(
    Match.when({ kind: 'conflict' as const }, (matched) =>
      revokeCounterpartyAccessInvitationActionProblem.conflict(matched.code),
    ),
    Match.when({ kind: 'forbidden' as const }, (matched) =>
      revokeCounterpartyAccessInvitationActionProblem.forbidden(matched.code),
    ),
    Match.when({ kind: 'ineligible' as const }, (matched) =>
      revokeCounterpartyAccessInvitationActionProblem.ineligible(matched.code),
    ),
    Match.when({ kind: 'rateLimited' as const }, (matched) =>
      revokeCounterpartyAccessInvitationActionProblem.rateLimited(matched.code),
    ),
    Match.when({ kind: 'unavailable' as const }, (matched) =>
      revokeCounterpartyAccessInvitationActionProblem.unavailable(matched.code),
    ),
    Match.exhaustive,
  );

const mapDomainProblem = (error: DomainError): RevokeCounterpartyAccessInvitationActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      CounterpartyAccessContractViolation: (failure) =>
        mapDomainIdentity(counterpartyAccessContractViolationProblemByCode[failure.code]),
      CounterpartyAccessUnavailable: () =>
        revokeCounterpartyAccessInvitationActionProblem.unavailable(
          'counterparty_access_unavailable',
        ),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): RevokeCounterpartyAccessInvitationActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        RevokeCounterpartyAccessInvitationActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: revokeCounterpartyAccessInvitationActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        RevokeCounterpartyAccessInvitationActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: revokeCounterpartyAccessInvitationActionProblem.internal,
      ActionIdempotencyKeyRequired: revokeCounterpartyAccessInvitationActionProblem.precondition,
      ActionInvocationNotFound: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.conflict(failure.code),
      ActionPayloadValidationError: revokeCounterpartyAccessInvitationActionProblem.invalid,
      ActionPermissionCheckError: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.conflict(failure.code),
      ActionResultValidationError: revokeCounterpartyAccessInvitationActionProblem.internal,
      ActionTransactionError: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError:
        revokeCounterpartyAccessInvitationActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired:
        revokeCounterpartyAccessInvitationActionProblem.authentication,
      OperationContextDenied: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) =>
        revokeCounterpartyAccessInvitationActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(
  revokeCounterpartyAccessInvitationAction.descriptor.domainErrorSchema,
);
export const mapRevokeCounterpartyAccessInvitationActionProblem = (
  error: ActionCoreError | DomainError,
): RevokeCounterpartyAccessInvitationActionProblem =>
  isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error);

export const revokeCounterpartyAccessInvitationActionSchemaErrorLive =
  HttpApiMiddleware.layerSchemaErrorTransform(
    RevokeCounterpartyAccessInvitationActionSchemaErrorMiddleware,
    () => Effect.fail(revokeCounterpartyAccessInvitationActionProblem.invalid()),
  );
