// @generated by OntOS Codesmith Action HTTP v1
// @ontos-action-http-owner commerce.customer-context
// @ontos-action-http-slug submit-purchase-approval-request
// oxlint-disable sonarjs/function-name -- Effect Match.tags requires owner-declared tag keys; remove-when: sonarjs accepts discriminant-map properties.
import type { ActionCoreError } from '@app/core-runtime';
import { Effect, HttpApiMiddleware } from '@modern-js/bff-effect/effect-edge';
import { Match, Schema } from 'effect';
import {
  SubmitPurchaseApprovalRequestActionAlreadyCommittedProblemSchema,
  SubmitPurchaseApprovalRequestActionAuthenticationProblemSchema,
  SubmitPurchaseApprovalRequestActionCommitIndeterminateProblemSchema,
  SubmitPurchaseApprovalRequestActionConflictProblemSchema,
  SubmitPurchaseApprovalRequestActionForbiddenProblemSchema,
  SubmitPurchaseApprovalRequestActionIneligibleProblemSchema,
  SubmitPurchaseApprovalRequestActionInternalProblemSchema,
  SubmitPurchaseApprovalRequestActionInvalidProblemSchema,
  SubmitPurchaseApprovalRequestActionNotFoundProblemSchema,
  SubmitPurchaseApprovalRequestActionPreconditionProblemSchema,
  SubmitPurchaseApprovalRequestActionSchemaErrorMiddleware,
  SubmitPurchaseApprovalRequestActionUnavailableProblemSchema,
} from '../shared/apis/submit-purchase-approval-request-action.ts';
import type { SubmitPurchaseApprovalRequestActionProblem } from '../shared/apis/submit-purchase-approval-request-action.ts';
import { submitPurchaseApprovalRequestAction } from '../src/actions/submit-purchase-approval-request.action.ts';
/* oxlint-disable anti-slop-effect/no-service-constructor-imports -- These pure helpers construct problem values rather than Effect services. */
import {
  actionProblemStatus as problemStatus,
  makeAuthenticationProblem,
  makeConflictProblem,
  makeForbiddenProblem,
  makeIneligibleProblem,
  makeInternalProblem,
  makeInvalidProblem,
  makeNotFoundProblem,
  makePreconditionProblem,
  makeUnavailableProblem,
  purchasingApprovalRejectedProblemByCode,
} from './action-problem-support.ts';
/* oxlint-enable anti-slop-effect/no-service-constructor-imports */
import type { PurchasingApprovalDomainProblemIdentity } from './action-problem-support.ts';

type DomainError = typeof submitPurchaseApprovalRequestAction.descriptor.domainErrorSchema.Type;
type ProblemOf<Tag extends SubmitPurchaseApprovalRequestActionProblem['_tag']> = Extract<
  SubmitPurchaseApprovalRequestActionProblem,
  { readonly _tag: Tag }
>;
export const submitPurchaseApprovalRequestActionProblem = {
  authentication: makeAuthenticationProblem<ProblemOf<'SubmitPurchaseApprovalRequestActionAuthenticationProblem'>>(
    (input) => SubmitPurchaseApprovalRequestActionAuthenticationProblemSchema.make(input),
  ),
  conflict: makeConflictProblem<
    ProblemOf<'SubmitPurchaseApprovalRequestActionConflictProblem'>['code'],
    ProblemOf<'SubmitPurchaseApprovalRequestActionConflictProblem'>
  >((input) => SubmitPurchaseApprovalRequestActionConflictProblemSchema.make(input)),
  forbidden: makeForbiddenProblem<
    ProblemOf<'SubmitPurchaseApprovalRequestActionForbiddenProblem'>['code'],
    ProblemOf<'SubmitPurchaseApprovalRequestActionForbiddenProblem'>
  >((input) => SubmitPurchaseApprovalRequestActionForbiddenProblemSchema.make(input)),
  ineligible: makeIneligibleProblem<
    ProblemOf<'SubmitPurchaseApprovalRequestActionIneligibleProblem'>['code'],
    ProblemOf<'SubmitPurchaseApprovalRequestActionIneligibleProblem'>
  >((input) => SubmitPurchaseApprovalRequestActionIneligibleProblemSchema.make(input)),
  internal: makeInternalProblem<ProblemOf<'SubmitPurchaseApprovalRequestActionInternalProblem'>>((input) =>
    SubmitPurchaseApprovalRequestActionInternalProblemSchema.make(input),
  ),
  invalid: makeInvalidProblem<ProblemOf<'SubmitPurchaseApprovalRequestActionInvalidProblem'>>(
    (input) => SubmitPurchaseApprovalRequestActionInvalidProblemSchema.make(input),
    'submit-purchase-approval-request',
  ),
  notFound: makeNotFoundProblem<
    ProblemOf<'SubmitPurchaseApprovalRequestActionNotFoundProblem'>['code'],
    ProblemOf<'SubmitPurchaseApprovalRequestActionNotFoundProblem'>
  >((input) => SubmitPurchaseApprovalRequestActionNotFoundProblemSchema.make(input)),
  precondition: makePreconditionProblem<ProblemOf<'SubmitPurchaseApprovalRequestActionPreconditionProblem'>>((input) =>
    SubmitPurchaseApprovalRequestActionPreconditionProblemSchema.make(input),
  ),
  unavailable: makeUnavailableProblem<
    ProblemOf<'SubmitPurchaseApprovalRequestActionUnavailableProblem'>['code'],
    ProblemOf<'SubmitPurchaseApprovalRequestActionUnavailableProblem'>
  >((input) => SubmitPurchaseApprovalRequestActionUnavailableProblemSchema.make(input)),
} as const;

const mapDomainIdentity = (
  identity: PurchasingApprovalDomainProblemIdentity,
): SubmitPurchaseApprovalRequestActionProblem =>
  Match.value(identity).pipe(
    Match.when({ kind: 'conflict' as const }, (matched) =>
      submitPurchaseApprovalRequestActionProblem.conflict(matched.code),
    ),
    Match.when({ kind: 'forbidden' as const }, (matched) =>
      submitPurchaseApprovalRequestActionProblem.forbidden(matched.code),
    ),
    Match.when({ kind: 'ineligible' as const }, (matched) =>
      submitPurchaseApprovalRequestActionProblem.ineligible(matched.code),
    ),
    Match.when({ kind: 'notFound' as const }, (matched) =>
      submitPurchaseApprovalRequestActionProblem.notFound(matched.code),
    ),
    Match.when({ kind: 'unavailable' as const }, (matched) =>
      submitPurchaseApprovalRequestActionProblem.unavailable(matched.code),
    ),
    Match.exhaustive,
  );

const mapDomainProblem = (error: DomainError): SubmitPurchaseApprovalRequestActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      PurchasingApprovalRejected: (failure) => mapDomainIdentity(purchasingApprovalRejectedProblemByCode[failure.code]),
    }),
    Match.exhaustive,
  );

const mapCoreProblem = (error: ActionCoreError): SubmitPurchaseApprovalRequestActionProblem =>
  Match.value(error).pipe(
    Match.tags({
      ActionAlreadyCommitted: (failure) =>
        SubmitPurchaseApprovalRequestActionAlreadyCommittedProblemSchema.make({
          code: failure.code,
          detail: 'This Action is already committed. Refresh governed reads.',
          invocationId: failure.invocationId,
          resolution: 'REFRESH_GOVERNED_READS',
          retryCommand: false,
          status: problemStatus.conflict,
          title: 'Action already committed',
          type: 'https://ontos.dev/problems/action-already-committed',
        }),
      ActionCollectorError: submitPurchaseApprovalRequestActionProblem.internal,
      ActionCommitIndeterminate: (failure) =>
        SubmitPurchaseApprovalRequestActionCommitIndeterminateProblemSchema.make({
          detail: 'The Action commit is uncertain. Resolve this invocation before another attempt.',
          invocationId: failure.invocationId,
          resolution: 'RESOLVE_COMMIT',
          retryCommand: false,
          status: problemStatus.unavailable,
          title: 'Action commit uncertain',
          type: 'https://ontos.dev/problems/action-commit-indeterminate',
        }),
      ActionHandlerExecutionError: submitPurchaseApprovalRequestActionProblem.internal,
      ActionIdempotencyKeyRequired: submitPurchaseApprovalRequestActionProblem.precondition,
      ActionInvocationNotFound: (failure) => submitPurchaseApprovalRequestActionProblem.notFound(failure.code),
      ActionInvocationPersistenceError: (failure) =>
        submitPurchaseApprovalRequestActionProblem.unavailable(failure.code),
      ActionInvocationStateError: (failure) => submitPurchaseApprovalRequestActionProblem.conflict(failure.code),
      ActionPayloadValidationError: submitPurchaseApprovalRequestActionProblem.invalid,
      ActionPermissionCheckError: (failure) => submitPurchaseApprovalRequestActionProblem.unavailable(failure.code),
      ActionPermissionDenied: (failure) => submitPurchaseApprovalRequestActionProblem.forbidden(failure.code),
      ActionPolicyDenied: (failure) => submitPurchaseApprovalRequestActionProblem.ineligible(failure.code),
      ActionPolicyEvaluationError: (failure) => submitPurchaseApprovalRequestActionProblem.unavailable(failure.code),
      ActionRequestHashConflict: (failure) => submitPurchaseApprovalRequestActionProblem.conflict(failure.code),
      ActionResultValidationError: submitPurchaseApprovalRequestActionProblem.internal,
      ActionTransactionError: (failure) => submitPurchaseApprovalRequestActionProblem.unavailable(failure.code),
      ActionTrustedContextValidationError: submitPurchaseApprovalRequestActionProblem.authentication,
      ModuleStateCheckUnavailableError: (failure) =>
        submitPurchaseApprovalRequestActionProblem.unavailable(failure.code),
      ModuleStateDeniedError: (failure) => submitPurchaseApprovalRequestActionProblem.forbidden(failure.code),
      OperationAuthenticationRequired: submitPurchaseApprovalRequestActionProblem.authentication,
      OperationContextDenied: (failure) => submitPurchaseApprovalRequestActionProblem.forbidden(failure.code),
      OperationContextInvalid: (failure) => submitPurchaseApprovalRequestActionProblem.forbidden(failure.code),
      OperationContextUnavailable: (failure) => submitPurchaseApprovalRequestActionProblem.unavailable(failure.code),
    }),
    Match.exhaustive,
  );

const isDomainError = Schema.is(submitPurchaseApprovalRequestAction.descriptor.domainErrorSchema);
export const mapSubmitPurchaseApprovalRequestActionProblem = (
  error: ActionCoreError | DomainError,
): SubmitPurchaseApprovalRequestActionProblem =>
  isDomainError(error) ? mapDomainProblem(error) : mapCoreProblem(error);

export const submitPurchaseApprovalRequestActionSchemaErrorLive = HttpApiMiddleware.layerSchemaErrorTransform(
  SubmitPurchaseApprovalRequestActionSchemaErrorMiddleware,
  () => Effect.fail(submitPurchaseApprovalRequestActionProblem.invalid()),
);
